In [1]:
import pandas as pd
import os
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2026"
quarter = "1"
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-02-15 10:06:48

### Restart and Run All

In [4]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [6]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()
format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%'
              }

In [14]:
sql = """
SELECT * 
FROM epss 
WHERE name = 'AOT' AND year = %s AND quarter = %s
"""
sql = sql % (year, quarter)
print(sql)

df_tmp = pd.read_sql(sql, conlt)
df_tmp.style.format(format_dict)

SELECT *
FROM epss
WHERE name = 'AOT' AND year = 2026 AND quarter = 1

In [16]:
today = date(2026, 1, 1)
select_date = today.strftime("%Y-%m-%d")
select_date

'2026-01-01'

In [18]:
sql = """
SELECT * 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
ORDER BY name
"""
sql = sql % (year, quarter, select_date)
print(sql)

df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.style.format(format_dict)

SELECT *
FROM epss
WHERE year = 2026 AND quarter = 1
AND publish_date >= '2026-01-01'
ORDER BY name

In [20]:
df_epss_inp["yoy_gain"] = df_epss_inp["q_amt"] - df_epss_inp["y_amt"]
df_epss_inp["yoy_pct"]  = round(df_epss_inp["yoy_gain"] / abs(df_epss_inp["y_amt"]) * 100,2)
df_epss_inp["acc_gain"] = df_epss_inp["aq_amt"] - df_epss_inp["ay_amt"]
df_epss_inp["acc_pct"] = round(df_epss_inp["acc_gain"] / abs(df_epss_inp["ay_amt"]) * 100,2)
df_aggr = df_epss_inp[
    [
        "name",
        "year",
        "quarter",
        "q_amt",
        "y_amt",
        "yoy_gain",
        "yoy_pct",
        "aq_amt",
        "ay_amt",
        "acc_gain",
        "acc_pct",
    ]
]
df_aggr.sample().style.format(format_dict)

In [22]:
criteria_1 = df_aggr.q_amt > 110_000
df_aggr.loc[criteria_1,cols].style.format(format_dict)

In [24]:
criteria_2 = df_aggr.y_amt > 100_000
df_aggr.loc[criteria_2, cols].style.format(format_dict)

In [26]:
criteria_3 = df_aggr.yoy_pct > 10.00
df_aggr.loc[criteria_3, cols].style.format(format_dict)

In [28]:
df_aggr_criteria = criteria_1 & criteria_2 & criteria_3
#df_aggr_criteria = criteria_1 & criteria_2 
df_aggr.loc[df_aggr_criteria, cols].style.format(format_dict)

In [30]:
df_aggr[df_aggr_criteria].sort_values(by=["yoy_pct"], ascending=[False]).style.format(format_dict)

In [32]:
df_aggr[df_aggr_criteria].sort_values(by=["name"], ascending=[True]).style.format(format_dict)

### If new records pass filter criteria then proceed to create quarterly profits process.

In [35]:
names = df_epss_inp['name']
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'AOT', 'GVREIT', 'TFFIF'"

In [37]:
sql = """
SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name 
WHERE E.name IN (%s)
ORDER BY E.name, year DESC, quarter DESC 
"""
sql = sql % (in_p)
print(sql)

epss_stocks = pd.read_sql(sql, conlt)
epss_stocks.shape

SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name
WHERE E.name IN ('AOT', 'GVREIT', 'TFFIF')
ORDER BY E.name, year DESC, quarter DESC

(124, 11)

### Delete from profits of older profit stocks

In [40]:
sqlDel = text("""
    DELETE FROM profits 
    WHERE name IN ({})
    AND quarter < :quarter
""".format(in_p))
print(sqlDel)
# Execute with parameters
rp = conlt.execute(sqlDel, {'quarter': quarter})
rp.rowcount

    DELETE FROM profits
    WHERE name IN ('AOT', 'GVREIT', 'TFFIF')
    AND quarter < :quarter

0

In [42]:
rp = conmy.execute(sqlDel, {'quarter': quarter})
rp.rowcount

OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
    DELETE FROM profits
    WHERE name IN ('AOT', 'GVREIT', 'TFFIF')
    AND quarter < ?
]
[parameters: ('1',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
rp = conpg.execute(sqlDel, {'quarter': quarter})
rp.rowcount

In [ ]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
lt_profits = pd.read_sql(sql, conlt)
lt_profits.set_index("name", inplace=True)
lt_profits.index

In [ ]:
my_profits = pd.read_sql(sql, conmy)
my_profits.set_index("name", inplace=True)
my_profits.index

In [ ]:
pg_profits = pd.read_sql(sql, conpg)
pg_profits.set_index("name", inplace=True)
pg_profits.index

### Portfolio that publish today

In [49]:
sql = """
SELECT * 
FROM tickers
WHERE name IN (%s)
ORDER BY name"""
sql = sql % in_p
print(sql)

pg_tickers = pd.read_sql(sql, conpg)
pg_tickers[['name','id']].sort_values(by=[ "name"], ascending=[True])

SELECT *
FROM tickers
WHERE name IN ('AOT', 'GVREIT', 'TFFIF')
ORDER BY name

     name   id
0     AOT   28
1  GVREIT  209
2   TFFIF  655

In [51]:
sql = """
SELECT name 
FROM buy
"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(29, 1)

In [53]:
df_merge = pd.merge(pg_tickers, df_buy, on='name', how='inner')
df_merge

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,209,GVREIT,GOLDEN VENTURES LEASEHOLD REAL ESTATE INVESTME...,Property & Construction,Property Fund & REITs,SET,www.gvreit.com,2018-04-22 04:29:37.417731,2018-04-22 04:29:37.417731
1,655,TFFIF,THAILAND FUTURE FUND,Services,Transportation & Logistics,SET,www.tffif.com,2019-03-03 03:45:02.485777,2019-03-03 03:45:02.485777

In [55]:
# To check if the DataFrame is empty
if not df_merge.empty:
    file_name = 'pub_stock.xlsx'
    output_file = os.path.join(dat_path, file_name)
    print(f"Output file : {output_file}") 

    df_merge[['id','name','sector','market']].to_excel(output_file, index=False)

Output file : C:\Users\PC1\OneDrive\A4\Data\pub_stock.xlsx

### Portfolio that already published

In [58]:
sql = """
SELECT * 
FROM buy"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(29, 10)

In [60]:
names = df_buy["name"].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'STA', 'SINGER', 'PTG', 'PTT', 'MCS', 'DIF', 'JMT', 'WHART', 'BCH', 'SENA', 'TFFIF', '3BBIF', 'CPF', 'IVL', 'PTTGC', 'WHAIR', 'ORI', 'AH', 'GVREIT', 'NER', 'AIMIRT', 'TOA', 'AWC', 'SYNEX', 'SCC', 'RCL', 'JMART', 'CPNREIT', 'TVO'"

In [62]:
sql = """
SELECT *
FROM epss
WHERE publish_date >= '%s'
AND name IN (%s)
ORDER BY publish_date, name"""
sql = sql % (select_date, in_p)
df_tmp = pd.read_sql(sql, conlt)
df_tmp.style.format(format_dict)

In [64]:
#const.close()
#conpg.commit()
#conpg.close()
#conmy.commit()
#conmy.close()
conlt.commit()
conlt.close()