In [1]:
import pandas as pd
import os
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2026"
quarter = "1"
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-05-15 22:21:00

In [2]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [3]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [4]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()
format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%'
              }

In [5]:
sql = """
SELECT * 
FROM epss 
WHERE name = 'AOT' AND year = %s AND quarter = %s
"""
sql = sql % (year, quarter)
print(sql)

df_tmp = pd.read_sql(sql, conlt)
df_tmp.style.format(format_dict)

SELECT *
FROM epss
WHERE name = 'AOT' AND year = 2026 AND quarter = 1

In [6]:
today = date(2026, 5, 14)
select_date = today.strftime("%Y-%m-%d")
select_date

'2026-05-14'

### Restart and Run All

In [8]:
sql = """
SELECT * 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
ORDER BY name
"""
sql = sql % (year, quarter, select_date)
print(sql)

df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.style.format(format_dict)

SELECT *
FROM epss
WHERE year = 2026 AND quarter = 1
AND publish_date >= '2026-05-14'
ORDER BY name

In [9]:
df_epss_inp["yoy_gain"] = df_epss_inp["q_amt"] - df_epss_inp["y_amt"]
df_epss_inp["yoy_pct"]  = round(df_epss_inp["yoy_gain"] / abs(df_epss_inp["y_amt"]) * 100,2)
df_epss_inp["acc_gain"] = df_epss_inp["aq_amt"] - df_epss_inp["ay_amt"]
df_epss_inp["acc_pct"] = round(df_epss_inp["acc_gain"] / abs(df_epss_inp["ay_amt"]) * 100,2)
df_aggr = df_epss_inp[
    [
        "name",
        "year",
        "quarter",
        "q_amt",
        "y_amt",
        "yoy_gain",
        "yoy_pct",
        "aq_amt",
        "ay_amt",
        "acc_gain",
        "acc_pct",
    ]
]
df_aggr.style.format(format_dict)

In [10]:
criteria_1 = df_aggr.q_amt > 110_000
df_aggr.loc[criteria_1,cols].style.format(format_dict)

In [11]:
criteria_2 = df_aggr.y_amt > 100_000
df_aggr.loc[criteria_2, cols].style.format(format_dict)

In [12]:
criteria_3 = df_aggr.yoy_pct > 10.00
df_aggr.loc[criteria_3, cols].style.format(format_dict)

In [13]:
df_aggr_criteria = criteria_1 & criteria_2 & criteria_3
#df_aggr_criteria = criteria_1 & criteria_2 
df_aggr.loc[df_aggr_criteria, cols].style.format(format_dict)

In [14]:
df_aggr[df_aggr_criteria].sort_values(by=["yoy_pct"], ascending=[False]).style.format(format_dict)

In [15]:
df_aggr[df_aggr_criteria].sort_values(by=["name"], ascending=[True]).style.format(format_dict)

### If new records pass filter criteria then proceed to create quarterly profits process.

In [17]:
stock_list = df_epss_inp['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

AH','AIE','ANAN','AP','BCH','BCP','BEM','CHG','CPF','CPNREIT','DIF','EA','FSMART','GFPT','HANA','HTC','IVL','JMART','JMT','LH','LPN','MCS','ORI','PLANB','PREB','PRM','PTT','SAPPE','SAT','SC','SGP','SINGER','SJWD','SPRC','TKN','TOA','VNG

In [18]:
sql = f"""
SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name 
WHERE E.name IN ('{stock_list_str}')
ORDER BY E.name, year DESC, quarter DESC 
"""
print(sql)

epss_stocks = pd.read_sql(sql, conlt)
epss_stocks.shape

SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name
WHERE E.name IN ('AH','AIE','ANAN','AP','BCH','BCP','BEM','CHG','CPF','CPNREIT','DIF','EA','FSMART','GFPT','HANA','HTC','IVL','JMART','JMT','LH','LPN','MCS','ORI','PLANB','PREB','PRM','PTT','SAPPE','SAT','SC','SGP','SINGER','SJWD','SPRC','TKN','TOA','VNG')
ORDER BY E.name, year DESC, quarter DESC

(1804, 11)

### Delete from profits of older profit stocks

In [20]:
sqlDel = text("""
    DELETE FROM profits 
    WHERE name IN ('{stock_list_str}')
    AND quarter < :quarter
""")
print(sqlDel)
# Execute with parameters
rp = conlt.execute(sqlDel, {'quarter': quarter})
rp.rowcount

    DELETE FROM profits
    WHERE name IN ('{stock_list_str}')
    AND quarter < :quarter

0

In [21]:
rp = conmy.execute(sqlDel, {'quarter': quarter})
rp.rowcount

0

In [22]:
rp = conpg.execute(sqlDel, {'quarter': quarter})
rp.rowcount

0

In [23]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
lt_profits = pd.read_sql(sql, conlt)
lt_profits.set_index("name", inplace=True)
lt_profits.index

Index(['3BBIF', 'ADVANC', 'ADVANC', 'BCP', 'CENTEL', 'COM7', 'CPALL',
       'CPNREIT', 'DELTA', 'DIF', 'FPT', 'GPSC', 'GULF', 'GUNKUL', 'KKP',
       'KKP', 'KTB', 'MTC', 'NER', 'SCC', 'SCGP', 'SCGP', 'SIS', 'THANI',
       'THANI', 'TIDLOR', 'TOA', 'TPIPL', 'TVO', 'VIBHA', 'WHA', 'WHART'],
      dtype='object', name='name')

In [24]:
my_profits = pd.read_sql(sql, conmy)
my_profits.set_index("name", inplace=True)
my_profits.index

Index(['2842', '2843', '2844', '2845', '2846', '2847', '2848', '2849', '2850',
       '2851', '2851', '2852', '2853', '2854', '2855', '2856', '3BBIF',
       'ADVANC', 'ADVANC', 'BCP', 'CENTEL', 'COM7', 'CPALL', 'CPNREIT',
       'DELTA', 'DIF', 'FPT', 'GPSC', 'GULF', 'GUNKUL', 'KKP', 'KKP', 'KTB',
       'MTC', 'NER', 'SCC', 'SCGP', 'SCGP', 'SIS', 'THANI', 'THANI', 'TIDLOR',
       'TOA', 'TPIPL', 'TVO', 'VIBHA', 'WHA', 'WHART'],
      dtype='object', name='name')

In [25]:
pg_profits = pd.read_sql(sql, conpg)
pg_profits.set_index("name", inplace=True)
pg_profits.index

Index(['3BBIF', 'ADVANC', 'ADVANC', 'BCP', 'DELTA', 'FPT', 'GPSC', 'GUNKUL',
       'KKP', 'KKP', 'KTB', 'SCC', 'SCGP', 'SCGP', 'THANI', 'TIDLOR', 'TPIPL',
       'TVO', 'WHART'],
      dtype='object', name='name')

### Portfolio that publish today

In [27]:
sql = f"""
SELECT * 
FROM tickers
WHERE name IN ('{stock_list_str}')
ORDER BY name"""
print(sql)

pg_tickers = pd.read_sql(sql, conpg)
pg_tickers[['name','id']].sort_values(by=[ "name"], ascending=[True])

SELECT *
FROM tickers
WHERE name IN ('AH','AIE','ANAN','AP','BCH','BCP','BEM','CHG','CPF','CPNREIT','DIF','EA','FSMART','GFPT','HANA','HTC','IVL','JMART','JMT','LH','LPN','MCS','ORI','PLANB','PREB','PRM','PTT','SAPPE','SAT','SC','SGP','SINGER','SJWD','SPRC','TKN','TOA','VNG')
ORDER BY name

       name   id
0        AH   11
1       AIE  691
2      ANAN   27
3        AP   29
4       BCH   55
5       BCP   56
6       BEM   61
7       CHG  101
8       CPF  121
9   CPNREIT  127
10      DIF  146
11       EA  153
12   FSMART  183
13     GFPT  192
14     HANA  211
15      HTC  218
16      IVL  238
17    JMART  244
18      JMT  245
19       LH  275
20      LPN  284
21      MCS  301
22      ORI  347
23    PLANB  366
24     PREB  377
25      PRM  382
26      PTT  389
27    SAPPE  426
28      SAT  427
29       SC  431
30      SGP  447
31   SINGER  452
32     SJWD  250
33     SPRC  478
34      TKN  542
35      TOA  562
36      VNG  703

In [28]:
sql = """
SELECT name 
FROM buy
"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(27, 1)

In [29]:
df_merge = pd.merge(pg_tickers, df_buy, on='name', how='inner')
df_merge

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,11,AH,AAPICO HITECH PUBLIC COMPANY LIMITED,Industrials,Automotive,sSET / SETTHSI,www.aapico.com,2018-04-22 04:29:36.134601,2021-07-07 03:33:38.806441
1,55,BCH,BANGKOK CHAIN HOSPITAL PUBLIC COMPANY LIMITED,Services,Health Care Services,SET100 / SETWB,www.bangkokchainhospital.com,2018-04-22 04:29:36.442067,2019-11-19 07:13:52.520896
2,121,CPF,CHAROEN POKPHAND FOODS PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET50 / SETCLMV / SETHD / SETTHSI / SETWB,www.cpfworldwide.com,2018-04-22 04:29:36.867977,2021-07-07 03:33:38.893396
3,127,CPNREIT,CPN RETAIL GROWTH LEASEHOLD REIT,Property & Construction,Property Fund & REITs,SET,www.cpnreit.com,2018-04-22 04:29:36.900508,2018-04-22 04:29:36.900508
4,146,DIF,DIGITAL TELECOMMUNICATIONS INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.digital-tif.com,2018-04-22 04:29:37.030748,2018-04-22 04:29:37.030748
5,238,IVL,INDORAMA VENTURES PUBLIC COMPANY LIMITED,Industrials,Petrochemicals & Chemicals,SET50 / SETTHSI,www.indoramaventures.com,2018-04-22 04:29:37.583373,2021-07-07 03:33:38.986666
6,245,JMT,JMT NETWORK SERVICES PUBLIC COMPANY LIMITED,Financials,Finance & Securities,SET50,www.jmtnetwork.co.th,2018-04-22 04:29:37.621811,2020-07-06 13:23:59.311892
7,301,MCS,M.C.S.STEEL PUBLIC COMPANY LIMITED,Industrials,Steel and Metal Products,sSET,www.mcssteel.com,2018-04-22 04:29:37.957104,2021-08-22 18:22:07.463483
8,347,ORI,ORIGIN PROPERTY PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SET100 / SETHD / SETTHSI,www.origin.co.th,2018-04-22 04:29:38.228072,2022-01-15 03:54:48.440923
9,389,PTT,PTT PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET50 / SETCLMV / SETHD / SETTHSI,www.pttplc.com,2018-04-22 04:29:38.484745,2019-11-19 07:13:53.785316
10,452,SINGER,SINGER THAILAND PUBLIC COMPANY LIMITED,Services,Commerce,SET100,www.singerthai.co.th,2018-04-22 04:29:38.875668,2021-07-07 03:33:39.150064
11,562,TOA,TOA PAINT (THAILAND) PUBLIC COMPANY LIMITED,Property & Construction,Construction Materials,SETTHSI,www.toagroup.com,2018-04-22 04:29:39.494571,2021-07-07 03:33:39.241053

In [30]:
# To check if the DataFrame is empty
if not df_merge.empty:
    file_name = 'pub_stock.xlsx'
    output_file = os.path.join(dat_path, file_name)
    print(f"Output file : {output_file}") 

    df_merge[['id','name','sector','market']].to_excel(output_file, index=False)

Output file : C:\Users\PC1\OneDrive\A4\Data\pub_stock.xlsx

### Portfolio that already published

In [32]:
sql = """
SELECT * 
FROM buy"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(27, 10)

In [33]:
stock_list = df_buy['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

STA','SINGER','PTG','PTT','MCS','DIF','ADVANC','JMT','WHART','BCH','SENA','TFFIF','3BBIF','CPF','IVL','PTTGC','WHAIR','ORI','AH','GVREIT','NER','TOA','AWC','SYNEX','RCL','CPNREIT','TVO

In [34]:
select_date = '2026-01-01'

In [35]:
sql = f"""
SELECT *
FROM epss
WHERE name IN ('{stock_list_str}')
AND publish_date >= '2026-04-01'
ORDER BY name, year DESC, quarter DESC"""
df_tmp = pd.read_sql(sql, conlt)
df_tmp.shape

(27, 14)

In [36]:
# Get unique rows based on 'name' column
result = df_tmp.drop_duplicates(subset=['name'])
result.sort_values(by=["name"], ascending=[True]).style.format(format_dict)

In [37]:
conlt.commit()
conlt.close()