In [1]:
import pandas as pd
import os
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2026"
quarter = "1"
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-05-17 14:49:39

In [2]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [3]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [4]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()
format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%'
              }

In [5]:
today = date(2026, 4, 1)
select_date = today.strftime("%Y-%m-%d")
select_date

'2026-04-01'

### Restart and Run All

### Portfolio that already published

In [8]:
sql = """
SELECT name 
FROM buy
"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(27, 1)

In [9]:
stock_list = df_buy['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

3BBIF','ADVANC','AH','AWC','BCH','CPF','CPNREIT','DIF','GVREIT','IVL','JMT','MCS','NER','ORI','PTG','PTT','PTTGC','RCL','SENA','SINGER','STA','SYNEX','TFFIF','TOA','TVO','WHAIR','WHART

In [10]:
sql = f"""
SELECT * 
FROM tickers
WHERE name IN ('{stock_list_str}')
ORDER BY name"""
print(sql)

pg_tickers = pd.read_sql(sql, conpg)
pg_tickers[['name','id']].sort_values(by=[ "name"], ascending=[True])

SELECT *
FROM tickers
WHERE name IN ('3BBIF','ADVANC','AH','AWC','BCH','CPF','CPNREIT','DIF','GVREIT','IVL','JMT','MCS','NER','ORI','PTG','PTT','PTTGC','RCL','SENA','SINGER','STA','SYNEX','TFFIF','TOA','TVO','WHAIR','WHART')
ORDER BY name

       name   id
0     3BBIF  241
1    ADVANC    8
2        AH   11
3       AWC  668
4       BCH   55
5       CPF  121
6   CPNREIT  127
7       DIF  146
8    GVREIT  209
9       IVL  238
10      JMT  245
11      MCS  301
12      NER  649
13      ORI  347
14      PTG  387
15      PTT  389
16    PTTGC  391
17      RCL  401
18     SENA  443
19   SINGER  452
20      STA  489
21    SYNEX  504
22    TFFIF  655
23      TOA  562
24      TVO  594
25    WHAIR  217
26    WHART  630

In [11]:
df_merge = pd.merge(pg_tickers, df_buy, on='name', how='inner')
df_merge

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,241,3BBIF,JASMINE BROADBAND INTERNET INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.jas-if.com,2018-04-22 04:29:37.600684,2019-03-03 03:45:01.621634
1,8,ADVANC,ADVANCED INFO SERVICE PUBLIC COMPANY LIMITED,Technology,Information & Communication Technology,SET50 / SETHD / SETTHSI,investor.ais.co.th,2018-04-22 04:29:36.118727,2021-07-07 03:33:38.798595
2,11,AH,AAPICO HITECH PUBLIC COMPANY LIMITED,Industrials,Automotive,sSET / SETTHSI,www.aapico.com,2018-04-22 04:29:36.134601,2021-07-07 03:33:38.806441
3,668,AWC,ASSET WORLD CORP PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SET50 / SETTHSI,https://www.assetworldcorp-th.com,2019-11-19 07:13:52.454317,2022-01-15 03:54:48.241937
4,55,BCH,BANGKOK CHAIN HOSPITAL PUBLIC COMPANY LIMITED,Services,Health Care Services,SET100 / SETWB,www.bangkokchainhospital.com,2018-04-22 04:29:36.442067,2019-11-19 07:13:52.520896
5,121,CPF,CHAROEN POKPHAND FOODS PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET50 / SETCLMV / SETHD / SETTHSI / SETWB,www.cpfworldwide.com,2018-04-22 04:29:36.867977,2021-07-07 03:33:38.893396
6,127,CPNREIT,CPN RETAIL GROWTH LEASEHOLD REIT,Property & Construction,Property Fund & REITs,SET,www.cpnreit.com,2018-04-22 04:29:36.900508,2018-04-22 04:29:36.900508
7,146,DIF,DIGITAL TELECOMMUNICATIONS INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.digital-tif.com,2018-04-22 04:29:37.030748,2018-04-22 04:29:37.030748
8,209,GVREIT,GOLDEN VENTURES LEASEHOLD REAL ESTATE INVESTME...,Property & Construction,Property Fund & REITs,SET,www.gvreit.com,2018-04-22 04:29:37.417731,2018-04-22 04:29:37.417731
9,238,IVL,INDORAMA VENTURES PUBLIC COMPANY LIMITED,Industrials,Petrochemicals & Chemicals,SET50 / SETTHSI,www.indoramaventures.com,2018-04-22 04:29:37.583373,2021-07-07 03:33:38.986666
10,245,JMT,JMT NETWORK SERVICES PUBLIC COMPANY LIMITED,Financials,Finance & Securities,SET50,www.jmtnetwork.co.th,2018-04-22 04:29:37.621811,2020-07-06 13:23:59.311892
11,301,MCS,M.C.S.STEEL PUBLIC COMPANY LIMITED,Industrials,Steel and Metal Products,sSET,www.mcssteel.com,2018-04-22 04:29:37.957104,2021-08-22 18:22:07.463483
12,649,NER,NORTH EAST RUBBER PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,sSET,www.nerubber.com,2019-03-03 03:45:01.837764,2019-11-19 07:13:53.611284
13,347,ORI,ORIGIN PROPERTY PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SET100 / SETHD / SETTHSI,www.origin.co.th,2018-04-22 04:29:38.228072,2022-01-15 03:54:48.440923
14,387,PTG,PTG ENERGY PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET100 / SETHD / SETTHSI,www.ptgenergy.co.th,2018-04-22 04:29:38.474708,2022-01-15 03:54:48.464340
15,389,PTT,PTT PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET50 / SETCLMV / SETHD / SETTHSI,www.pttplc.com,2018-04-22 04:29:38.484745,2019-11-19 07:13:53.785316
16,391,PTTGC,PTT GLOBAL CHEMICAL PUBLIC COMPANY LIMITED,Industrials,Petrochemicals & Chemicals,SET50 / SETCLMV / SETTHSI,www.pttgcgroup.com,2018-04-22 04:29:38.496779,2021-07-07 03:33:39.100623
17,401,RCL,REGIONAL CONTAINER LINES PUBLIC COMPANY LIMITED,Services,Transportation & Logistics,SET100 / SETCLMV,www.rclgroup.com,2018-04-22 04:29:38.554599,2022-01-15 03:54:48.472788
18,443,SENA,SENADEVELOPMENT PUBLIC COMPANY LIMITED,Property & Construction,Property Development,sSET,www.sena.co.th,2018-04-22 04:29:38.825191,2018-04-22 04:29:38.825191
19,452,SINGER,SINGER THAILAND PUBLIC COMPANY LIMITED,Services,Commerce,SET100,www.singerthai.co.th,2018-04-22 04:29:38.875668,2021-07-07 03:33:39.150064
20,489,STA,SRI TRANG AGRO-INDUSTRY PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,SET100 / SETTHSI / SETWB,www.sritranggroup.com,2018-04-22 04:29:39.085589,2022-01-15 03:54:48.525517
21,504,SYNEX,SYNNEX (THAILAND) PUBLIC COMPANY LIMITED,Technology,Information & Communication Technology,SET100 / SETTHSI,www.synnex.co.th,2018-04-22 04:29:39.170664,2021-07-07 03:33:39.202279
22,655,TFFIF,THAILAND FUTURE FUND,Services,Transportation & Logistics,SET,www.tffif.com,2019-03-03 03:45:02.485777,2019-03-03 03:45:02.485777
23,562,TOA,TOA PAINT (THAILAND) PUBLIC COMPANY LIMITED,Property & Construction,Construction Materials,SETTHSI,www.toagroup.com,2018-04-22 04:29:39.494571,2021-07-07 03:33:39.241053
24,594,TVO,THAI VEGETABLE OIL PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET / SETTHSI / SETWB,www.tvothai.com,2018-04-22 04:29:39.677962,2019-11-19 07:13:54.470342
25,217,WHAIR,HEMARAJ LEASEHOLD REAL ESTATE INVESTMENT TRUST,Property & Construction,Property Fund & REITs,SET,www.hemarajreit.com,2018-04-22 04:29:37.460955,2018-04-22 04:29:37.460955
26,630,WHART,WHA PREMIUM GROWTH FREEHOLD AND LEASEHOLD REAL...,Property & Construction,Property Fund & REITs,SET,www.whareit.com,2018-04-22 04:29:39.879467,2018-04-22 04:29:39.879467

In [12]:
sql = f"""
SELECT *
FROM epss
WHERE name IN ('{stock_list_str}')
AND publish_date >= '2026-04-01'
ORDER BY name, year DESC, quarter DESC"""
df_tmp = pd.read_sql(sql, conlt)
df_tmp.shape

(27, 14)

In [13]:
df_tmp["yoy_gain"] = df_tmp["q_amt"] - df_tmp["y_amt"]
df_tmp["yoy_pct"]  = round(df_tmp["yoy_gain"] / abs(df_tmp["y_amt"]) * 100,2)
df_tmp["acc_gain"] = df_tmp["aq_amt"] - df_tmp["ay_amt"]
df_tmp["acc_pct"] = round(df_tmp["acc_gain"] / abs(df_tmp["ay_amt"]) * 100,2)
df_aggr = df_tmp[
    [
        "name",
        "year",
        "quarter",
        "q_amt",
        "y_amt",
        "yoy_gain",
        "yoy_pct",
        "aq_amt",
        "ay_amt",
        "acc_gain",
        "acc_pct",
    ]
]

In [14]:
# Get unique rows based on 'name' column
result = df_tmp.drop_duplicates(subset=['name'])
result.sort_values(by=["name"], ascending=[True]).style.format(format_dict)

In [15]:
result.drop('ticker_id', axis=1, inplace=True)
result.columns

Index(['id', 'name', 'year', 'quarter', 'q_amt', 'y_amt', 'aq_amt', 'ay_amt',
       'q_eps', 'y_eps', 'aq_eps', 'ay_eps', 'publish_date', 'yoy_gain',
       'yoy_pct', 'acc_gain', 'acc_pct'],
      dtype='object')

In [16]:
pg_tickers.columns

Index(['id', 'name', 'full_name', 'sector', 'subsector', 'market', 'website',
       'created_at', 'updated_at'],
      dtype='object')

In [17]:
pg_tickers.drop(['full_name','website','created_at','updated_at'], axis=1, inplace=True)
pg_tickers.columns

Index(['id', 'name', 'sector', 'subsector', 'market'], dtype='object')

In [18]:
df_merge = pd.merge(pg_tickers, result, on='name', how='inner')
df_merge

,id_x,name,sector,subsector,market,id_y,year,quarter,q_amt,y_amt,...,ay_amt,q_eps,y_eps,aq_eps,ay_eps,publish_date,yoy_gain,yoy_pct,acc_gain,acc_pct
0,241,3BBIF,Technology,Information & Communication Technology,SET,25119,2026,1,-2689000,1307258,...,1307258,0.0000,0.0000,0.0000,0.0000,2026-05-07,-3996258,-305.70,-3996258,-305.70
1,8,ADVANC,Technology,Information & Communication Technology,SET50 / SETHD / SETTHSI,25120,2026,1,13495505,10583526,...,10583526,4.5400,3.5600,4.5400,3.5600,2026-05-07,2911979,27.51,2911979,27.51
2,11,AH,Industrials,Automotive,sSET / SETTHSI,25205,2026,1,314360,306182,...,306182,0.9400,0.9100,0.9400,0.9100,2026-05-14,8178,2.67,8178,2.67
3,668,AWC,Property & Construction,Property Development,SET50 / SETTHSI,25164,2026,1,1986471,1969327,...,1969327,0.0620,0.0615,0.0620,0.0615,2026-05-11,17144,0.87,17144,0.87
4,55,BCH,Services,Health Care Services,SET100 / SETWB,25238,2026,1,267555,321312,...,321312,0.1100,0.1300,0.1100,0.1300,2026-05-15,-53757,-16.73,-53757,-16.73
5,121,CPF,Agro & Food Industry,Food & Beverage,SET50 / SETCLMV / SETHD / SETTHSI / SETWB,25206,2026,1,4874798,8549183,...,8549183,0.6000,1.0700,0.6000,1.0700,2026-05-14,-3674385,-42.98,-3674385,-42.98
6,127,CPNREIT,Property & Construction,Property Fund & REITs,SET,25232,2026,1,809381,907578,...,907578,0.0000,0.0000,0.0000,0.0000,2026-05-14,-98197,-10.82,-98197,-10.82
7,146,DIF,Technology,Information & Communication Technology,SET,25207,2026,1,2767480,2731943,...,2731943,0.0000,0.0000,0.0000,0.0000,2026-05-14,35537,1.30,35537,1.30
8,209,GVREIT,Property & Construction,Property Fund & REITs,SET,25181,2026,2,194332,200096,...,403948,0.0000,0.0000,0.0000,0.0000,2026-05-13,-5764,-2.88,-39538,-9.79
9,238,IVL,Industrials,Petrochemicals & Chemicals,SET50 / SETTHSI,25239,2026,1,-2816451,-1312080,...,-1312080,-0.5400,-0.2700,-0.5400,-0.2700,2026-05-15,-1504371,-114.66,-1504371,-114.66
10,245,JMT,Financials,Finance & Securities,SET50,25210,2026,1,252201,330029,...,330029,0.1700,0.2300,0.1700,0.2300,2026-05-14,-77828,-23.58,-77828,-23.58
11,301,MCS,Industrials,Steel and Metal Products,sSET,25237,2026,1,97448,220194,...,220194,0.2000,0.4600,0.2000,0.4600,2026-05-14,-122746,-55.74,-122746,-55.74
12,649,NER,Agro & Food Industry,Agribusiness,sSET,25124,2026,1,254369,608836,...,608836,0.1377,0.3295,0.1377,0.3295,2026-05-06,-354467,-58.22,-354467,-58.22
13,347,ORI,Property & Construction,Property Development,SET100 / SETHD / SETTHSI,25240,2026,1,103473,111613,...,111613,0.0422,0.0455,0.0422,0.0455,2026-05-15,-8140,-7.29,-8140,-7.29
14,387,PTG,Resources,Energy & Utilities,SET100 / SETHD / SETTHSI,25175,2026,1,-205373,190045,...,190045,-0.1200,0.1100,-0.1200,0.1100,2026-05-12,-395418,-208.07,-395418,-208.07
15,389,PTT,Resources,Energy & Utilities,SET50 / SETCLMV / SETHD / SETTHSI,25204,2026,1,25738299,23315489,...,23315489,0.9100,0.8100,0.9100,0.8100,2026-05-14,2422810,10.39,2422810,10.39
16,391,PTTGC,Industrials,Petrochemicals & Chemicals,SET50 / SETCLMV / SETTHSI,25122,2026,1,3231758,-2567193,...,-2567193,0.5100,-0.6100,0.5100,-0.6100,2026-05-05,5798951,225.89,5798951,225.89
17,401,RCL,Services,Transportation & Logistics,SET100 / SETCLMV,25116,2026,1,1671086,2058085,...,2058085,2.0200,2.4800,2.0200,2.4800,2026-05-08,-386999,-18.80,-386999,-18.80
18,443,SENA,Property & Construction,Property Development,sSET,25182,2026,1,50596,111373,...,111373,0.0351,0.0772,0.0351,0.0772,2026-05-13,-60777,-54.57,-60777,-54.57
19,452,SINGER,Services,Commerce,SET100,25209,2026,1,142942,-946,...,-946,0.1750,-0.0010,0.1750,-0.0010,2026-05-14,143888,15210.15,143888,15210.15
20,489,STA,Agro & Food Industry,Agribusiness,SET100 / SETTHSI / SETWB,25118,2026,1,645434,688689,...,688689,0.4200,0.4500,0.4200,0.4500,2026-05-08,-43255,-6.28,-43255,-6.28
21,504,SYNEX,Technology,Information & Communication Technology,SET100 / SETTHSI,25151,2026,1,221377,188217,...,188217,0.2600,0.2200,0.2600,0.2200,2026-05-11,33160,17.62,33160,17.62
22,655,TFFIF,Services,Transportation & Logistics,SET,25180,2026,2,549895,537321,...,1080788,0.0000,0.0000,0.0000,0.0000,2026-05-12,12574,2.34,26506,2.45
23,562,TOA,Property & Construction,Construction Materials,SETTHSI,25241,2026,1,953247,733099,...,733099,0.4900,0.3700,0.4900,0.3700,2026-05-15,220148,30.03,220148,30.03
24,594,TVO,Agro & Food Industry,Food & Beverage,SET / SETTHSI / SETWB,25117,2026,1,708925,533615,...,533615,0.8000,0.6000,0.8000,0.6000,2026-05-08,175310,32.85,175310,32.85
25,217,WHAIR,Property & Construction,Property Fund & REITs,SET,25163,2026,1,178532,245718,...,245718,0.0000,0.0000,0.0000,0.0000,2026-05-11,-67186,-27.34,-67186,-27.34
26,630,WHART,Property & Construction,Property Fund & REITs,SET,25121,2026,1,674906,665907,...,665907,0.0000,0.0000,0.0000,0.0000,2026-05-07,8999,1.35,8999,1.35

In [19]:
conlt.commit()
conlt.close()