In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()

year = 2026
quarter = 1
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-05-17 14:57:15

### Insert Profits from PortLt to PortMy

In [4]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

lt_profits = pd.read_sql(sql, conlt)
lt_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 1

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,q_amt_c,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct
0,2860,ADVANC,2026,1,1,50797881,35075357,15722524,44.82,50797881,...,13495505,10583526,2911979,27.514261,10583526,2911979,27.514261,6,26.482131,15.860380
1,2861,DELTA,2026,1,1,28407374,18938580,9468794,50.00,28407374,...,9081176,5488126,3593050,65.469525,5488126,3593050,65.469525,138,48.854762,24.048815
2,2862,GPSC,2026,1,1,6978315,4062379,2915936,71.78,6978315,...,1719348,1140036,579312,50.815237,1140036,579312,50.815237,197,45.615119,26.303938
3,2863,GUNKUL,2026,1,1,1857507,1660831,196676,11.84,1857507,...,455763,366965,88798,24.197948,366965,88798,24.197948,202,16.313974,9.519881
4,2864,KKP,2026,1,1,6806788,4985068,1821720,36.54,6806788,...,1955494,1061619,893875,84.199228,1061619,893875,84.199228,255,55.014614,34.815585
5,2865,KTB,2026,1,1,48952081,43855657,5096424,11.62,48952081,...,12437176,11713698,723478,6.176342,11713698,723478,6.176342,258,6.368171,4.137406
6,2866,SCC,2026,1,1,19199135,6341638,12857497,202.75,19199135,...,6222963,1098848,5124115,466.316997,1098848,5124115,466.316997,427,292.948499,211.393033
7,2867,SCGP,2026,1,1,4735791,3699083,1036708,28.03,4735791,...,1566168,899872,666296,74.043420,899872,666296,74.043420,713,48.121710,30.307963
8,2868,THANI,2026,1,1,1234581,800211,434370,54.28,1234581,...,340348,253604,86744,34.204508,253604,86744,34.204508,522,32.562254,19.167396
9,2869,TIDLOR,2026,1,1,5248767,4230480,1018287,24.07,5248767,...,1613744,1197815,415929,34.723977,-12882,1626626,12627.123118,751,3182.706774,6296.283312
10,2870,TPIPL,2026,1,1,2107706,1442498,665208,46.12,2107706,...,832438,723236,109202,15.099082,723236,109202,15.099082,559,20.444541,17.709823
11,2871,TVO,2026,1,1,2364101,2103105,260996,12.41,2364101,...,708925,533615,175310,32.853274,533615,175310,32.853274,585,21.531637,13.195932
12,2872,WHART,2026,1,1,2358805,1920946,437859,22.79,2358805,...,674906,665907,8999,1.351390,665907,8999,1.351390,622,6.468195,10.890834
13,2873,AMATA,2026,1,1,3697994,2482899,1215095,48.94,3697994,...,1378517,829181,549336,66.250433,829181,549336,66.250433,21,49.722716,23.010662
14,2874,BCP,2026,1,1,6908168,2184088,4724080,216.30,6908168,...,6143762,2115295,4028467,190.444690,2115295,4028467,190.444690,52,184.269845,31.998744
15,2875,BGRIM,2026,1,1,1742731,1556871,185860,11.94,1742731,...,721178,653934,67244,10.282995,653934,67244,10.282995,59,9.128997,3.500918
16,2876,BKIH,2026,1,1,3634595,3014794,619801,20.56,3634595,...,1129143,558499,570644,102.174579,558499,570644,102.174579,68,60.882289,47.686806
17,2877,BLA,2026,1,1,7384829,4317070,3067759,71.06,7384829,...,1605539,1250525,355014,28.389197,1189085,416454,35.023064,70,35.113065,26.994667
18,2878,BPP,2026,1,1,8329005,1746321,6582684,376.95,8329005,...,5877083,574355,5302728,923.249210,574355,5302728,923.249210,74,599.667105,382.609031
19,2879,CENTEL,2026,1,1,3387598,1752985,1634613,93.25,3387598,...,2142542,747845,1394697,186.495464,747845,1394697,186.495464,92,134.055232,61.293442
20,2880,CK,2026,1,1,3375096,1445903,1929193,133.42,3375096,...,329116,282243,46873,16.607321,282243,46873,16.607321,106,42.011160,61.358891
21,2881,CKP,2026,1,1,2890971,1344536,1546435,115.02,2890971,...,179611,70465,109146,154.893919,70465,109146,154.893919,107,107.181959,71.361356
22,2882,COM7,2026,1,1,4309060,3307162,1001898,30.29,4309060,...,1226182,980654,245528,25.037169,980654,245528,25.037169,114,21.601085,10.665489
23,2883,CPALL,2026,1,1,29738684,25345841,4392843,17.33,29738684,...,9117822,7585238,1532584,20.204824,7585238,1532584,20.204824,116,15.792412,7.039946
24,2884,CPN,2026,1,1,19584844,16729046,2855798,17.07,19584844,...,4970796,4227207,743589,17.590551,4227207,743589,17.590551,121,14.050275,6.737987
25,2885,DIF,2026,1,1,13891180,656288,13234892,2016.63,13891180,...,2767480,2731943,35537,1.300796,2731943,35537,1.300796,140,504.872898,1007.838187
26,2886,KGI,2026,1,1,987326,864737,122589,14.18,987326,...,318590,197666,120924,61.175923,197666,120924,61.175923,252,37.622962,27.196766
27,2887,MINT,2026,1,1,9241257,7750222,1491035,19.24,9241257,...,648780,416865,231915,55.633119,416865,231915,55.633119,301,33.269059,26.705487
28,2888,MTC,2026,1,1,6975094,5867308,1107786,18.88,6975094,...,1823034,1571215,251819,16.027024,1571215,251819,16.027024,315,13.671012,6.749361
29,2889,ONEE,2026,1,1,527725,421017,106708,25.35,527725,...,53720,-23533,77253,328.275188,-23533,77253,328.275188,741,174.762594,177.292683
30,2890,SIS,2026,1,1,932467,697604,234863,33.67,932467,...,258003,201954,56049,27.753350,201954,56049,27.753350,449,23.894175,11.991655
31,2891,SPRC,2026,1,1,9222759,2234886,6987873,312.67,9222759,...,7366927,713522,6653405,932.473701,713522,6653405,932.473701,470,609.141850,373.995036
32,2892,SYNEX,2026,1,1,802946,627721,175225,27.91,802946,...,221377,188217,33160,17.617962,188217,33160,17.617962,495,16.863981,9.673916
33,2893,TCAP,2026,1,1,8163458,6646024,1517434,22.83,8163458,...,2123240,1709616,413624,24.193971,1709616,413624,24.193971,503,19.139486,9.222099
34,2894,TFG,2026,1,1,7451307,3166564,4284743,135.31,7451307,...,2047091,2036621,10470,0.514087,2036621,10470,0.514087,513,34.119543,67.460535
35,2895,TOA,2026,1,1,3137161,1919604,1217557,63.43,3137161,...,953247,733099,220148,30.029778,733099,220148,30.029778,645,32.759889,23.029700
36,2896,TOP,2026,1,1,30561848,9958628,20603220,206.89,30561848,...,19481157,3503510,15977647,456.046850,3503510,15977647,456.046850,555,307.133425,176.482644
37,2897,TTW,2026,1,1,3270342,2790939,479403,17.18,3270342,...,672938,668684,4254,0.636175,668684,4254,0.636175,581,4.645587,8.359681
38,2898,VIBHA,2026,1,1,1805630,698606,1107024,158.46,1805630,...,136719,25983,110736,426.186353,25983,110736,426.186353,610,254.340676,207.898299

In [6]:
lt_profits = lt_profits.drop(columns=['id'])
lt_profits.shape

(39, 22)

In [8]:
sql = """
SELECT * 
FROM profits 
WHERE  year = %s AND quarter = %s"""
sql = sql % (year, quarter)
print(sql)

my_profits = pd.read_sql(sql, conmy)
my_profits

SELECT *
FROM profits
WHERE  year = 2026 AND quarter = 1

,id,name,year,quarter,kind,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,latest_amt_q,...,q_amt_c,y_amt,inc_amt_py,inc_pct_py,q_amt_p,inc_amt_pq,inc_pct_pq,ticker_id,mean_pct,std_pct
0,369,ADVANC,2026,1,1,50797881,35075357,15722524,44.82,50797881,...,13495505,10583526,2911979,27.514261,10583526,2911979,27.514261,6,26.482131,15.860380
1,370,DELTA,2026,1,1,28407374,18938580,9468794,50.00,28407374,...,9081176,5488126,3593050,65.469525,5488126,3593050,65.469525,138,48.854762,24.048815
2,371,GPSC,2026,1,1,6978315,4062379,2915936,71.78,6978315,...,1719348,1140036,579312,50.815237,1140036,579312,50.815237,197,45.615119,26.303938
3,372,GUNKUL,2026,1,1,1857507,1660831,196676,11.84,1857507,...,455763,366965,88798,24.197948,366965,88798,24.197948,202,16.313974,9.519881
4,373,KKP,2026,1,1,6806788,4985068,1821720,36.54,6806788,...,1955494,1061619,893875,84.199228,1061619,893875,84.199228,255,55.014614,34.815585
5,374,KTB,2026,1,1,48952081,43855657,5096424,11.62,48952081,...,12437176,11713698,723478,6.176342,11713698,723478,6.176342,258,6.368171,4.137406
6,375,SCC,2026,1,1,19199135,6341638,12857497,202.75,19199135,...,6222963,1098848,5124115,466.316997,1098848,5124115,466.316997,427,292.948499,211.393033
7,376,SCGP,2026,1,1,4735791,3699083,1036708,28.03,4735791,...,1566168,899872,666296,74.043420,899872,666296,74.043420,713,48.121710,30.307963
8,377,THANI,2026,1,1,1234581,800211,434370,54.28,1234581,...,340348,253604,86744,34.204508,253604,86744,34.204508,522,32.562254,19.167396
9,378,TIDLOR,2026,1,1,5248767,4230480,1018287,24.07,5248767,...,1613744,1197815,415929,34.723977,-12882,1626626,12627.123118,751,3182.706774,6296.283312
10,379,TPIPL,2026,1,1,2107706,1442498,665208,46.12,2107706,...,832438,723236,109202,15.099082,723236,109202,15.099082,559,20.444541,17.709823
11,380,TVO,2026,1,1,2364101,2103105,260996,12.41,2364101,...,708925,533615,175310,32.853274,533615,175310,32.853274,585,21.531637,13.195932
12,381,WHART,2026,1,1,2358805,1920946,437859,22.79,2358805,...,674906,665907,8999,1.351390,665907,8999,1.351390,622,6.468195,10.890834

In [10]:
sqlDel = text("DELETE FROM profits WHERE year = :year AND quarter = :quarter")
print(sqlDel)  # Shows the uncompiled SQL with placeholders

# Execute and get the result
result = conmy.execute(sqlDel, {"year": year, "quarter": quarter})
rows_deleted = result.rowcount  # Get the number of rows deleted
conmy.commit()  # Commit the transaction

print(f"Number of rows deleted: {rows_deleted}")

DELETE FROM profits WHERE year = :year AND quarter = :quarter

OperationalError: (sqlite3.OperationalError) database is locked
[SQL: DELETE FROM profits WHERE year = ? AND quarter = ?]
[parameters: (2026, 1)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [14]:
# Define SQL statement using named placeholders
sqlIns = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")
print(sqlIns)

INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)

In [16]:
rcds = lt_profits.values.tolist()
print(f"Number of rows to insert: {len(rcds)}")

Number of rows to insert: 39

In [47]:
sql = f"""SELECT name, year, quarter, publish_date FROM epss WHERE year = {year} AND quarter = {quarter} AND name IN ('{stock_list_str}')"""
print(sql)
df_epss_profits = pd.read_sql(sql, conlt)
df_epss_profits

SELECT name, year, quarter, publish_date FROM epss WHERE year = 2026 AND quarter = 1 AND name IN ('ADVANC','DELTA','GPSC','GUNKUL','KKP','KTB','SCC','SCGP','THANI','TIDLOR','TPIPL','TVO','WHART')

      name  year  quarter publish_date
0   ADVANC  2026        1   2026-05-07
1    DELTA  2026        1   2026-04-27
2     GPSC  2026        1   2026-05-07
3   GUNKUL  2026        1   2026-05-08
4      KKP  2026        1   2026-04-20
5      KTB  2026        1   2026-04-21
6      SCC  2026        1   2026-04-29
7     SCGP  2026        1   2026-04-28
8    THANI  2026        1   2026-05-08
9   TIDLOR  2026        1   2026-05-07
10   TPIPL  2026        1   2026-05-08
11     TVO  2026        1   2026-05-08
12   WHART  2026        1   2026-05-07