In [1]:
import os
import pandas as pd
from datetime import date, datetime, timedelta
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2026"
quarter = "2"

current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-08-22 11:15:49

In [3]:
select_date = date(2026, 7, 1)
select_date = select_date.strftime("%Y-%m-%d")
select_date

'2026-07-01'

### Tables in the process

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [8]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [10]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()
format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%'
              }

In [12]:
sql = '''
SELECT * 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= "%s"
ORDER BY name'''
sql = sql % (year, quarter, select_date)
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.tail().style.format(format_dict)

SELECT *
FROM epss
WHERE year = 2026 AND quarter = 2
AND publish_date >= "2026-07-01"
ORDER BY name

In [14]:
df_epss_inp.shape

(174, 14)

In [16]:
df_epss_inp["yoy_gain"] = df_epss_inp["q_amt"] - df_epss_inp["y_amt"]
df_epss_inp["yoy_pct"]  = round(df_epss_inp["yoy_gain"] / abs(df_epss_inp["y_amt"]) * 100,2)
df_epss_inp["acc_gain"] = df_epss_inp["aq_amt"] - df_epss_inp["ay_amt"]
df_epss_inp["acc_pct"] = round(df_epss_inp["acc_gain"] / abs(df_epss_inp["ay_amt"]) * 100,2)
df_aggr = df_epss_inp[
    [
        "name",
        "year",
        "quarter",
        "q_amt",
        "y_amt",
        "yoy_gain",
        "yoy_pct",
        "aq_amt",
        "ay_amt",
        "acc_gain",
        "acc_pct",
    ]
]
df_aggr.tail().style.format(format_dict)

In [18]:
df_aggr.query('name == "PTT"')

,name,year,quarter,q_amt,y_amt,yoy_gain,yoy_pct,aq_amt,ay_amt,acc_gain,acc_pct
106,PTT,2026,2,52524592,21532882,30991710,143.93,78262891,44848371,33414520,74.51

In [20]:
criteria_1 = df_aggr.q_amt > 110_000
df_aggr.loc[criteria_1,cols].style.format(format_dict)

In [22]:
criteria_2 = df_aggr.y_amt > 100_000
df_aggr.loc[criteria_2, cols].style.format(format_dict)

In [24]:
criteria_3 = df_aggr.yoy_pct > 10
df_aggr.loc[criteria_3, cols].style.format(format_dict)

In [26]:
criteria_4 = (df_aggr.q_amt > df_aggr.y_amt)
df_aggr.loc[criteria_4, cols].style.format(format_dict)

In [28]:
df_aggr_criteria = criteria_1 & criteria_2 & criteria_3 & criteria_4
df_aggr.loc[df_aggr_criteria, cols].sort_values(['name'],ascending=[True]).style.format(format_dict)

In [30]:
df_aggr[df_aggr_criteria].sort_values(by=["yoy_pct"], ascending=[False]).style.format(format_dict)

In [32]:
df_aggr[df_aggr_criteria].sort_values(by=["name"], ascending=[True]).style.format(format_dict)

In [34]:
names = df_epss_inp['name']
portfolio = ", ".join(map(lambda name: "'%s'" % name, names))
portfolio

"'3BBIF', 'ACE', 'ADVANC', 'AH', 'AIE', 'AIMIRT', 'AIT', 'AMATA', 'ANAN', 'AP', 'ASIAN', 'ASK', 'ASP', 'ASW', 'AWC', 'BA', 'BAM', 'BBL', 'BCH', 'BCP', 'BCPG', 'BDMS', 'BEAUTY', 'BEC', 'BEM', 'BGC', 'BGRIM', 'BH', 'BJC', 'BKIH', 'BLA', 'CBG', 'CENTEL', 'CHG', 'CK', 'CKP', 'COM7', 'CPALL', 'CPAXT', 'CPF', 'CPN', 'CPNCG', 'CPNREIT', 'CRC', 'DCC', 'DCON', 'DELTA', 'DIF', 'DOHOME', 'EA', 'EGATIF', 'EGCO', 'FSMART', 'GC', 'GFPT', 'GLOBAL', 'GPSC', 'GULF', 'GUNKUL', 'HANA', 'HFT', 'HMPRO', 'HTC', 'ICHI', 'III', 'ILM', 'IMH', 'IP', 'IRPC', 'IVL', 'JMART', 'JMT', 'KBANK', 'KCE', 'KKP', 'KTB', 'KTC', 'LALIN', 'LANNA', 'LH', 'LIT', 'LPN', 'M', 'MAJOR', 'MBAX', 'MCS', 'MEGA', 'MINT', 'MST', 'MTC', 'NER', 'NOBLE', 'ONEE', 'OR', 'ORI', 'OSP', 'PCSGH', 'PDG', 'PLANB', 'POPF', 'PREB', 'PRM', 'PROSPECT', 'PSH', 'PSL', 'PTG', 'PTT', 'PTTEP', 'PTTGC', 'QH', 'RATCH', 'RBF', 'RCL', 'RJH', 'ROJNA', 'SAPPE', 'SAT', 'SAWAD', 'SC', 'SCB', 'SCC', 'SCCC', 'SCGP', 'SENA', 'SGP', 'SINGER', 'SIRI', 'SIS', 'SJWD', 'SMPC', 'SNC', 'SPALI', 'SPCG', 'SPRC', 'SSP', 'STA', 'STGT', 'SUPER', 'SUPEREIF', 'SYNEX', 'TASCO', 'TCAP', 'TFG', 'THANI', 'THG', 'TIDLOR', 'TIPH', 'TISCO', 'TKN', 'TKS', 'TMT', 'TOA', 'TOP', 'TPIPL', 'TPIPP', 'TQM', 'TRUE', 'TSE', 'TTA', 'TTB', 'TTLPF', 'TTW', 'TU', 'TVO', 'TYCN', 'UTP', 'VIBHA', 'VNG', 'WHA', 'WHAIR', 'WHART', 'WHAUP', 'WICE', 'WORK'"

### If new records pass filter criteria then proceed to create quarterly profits process.

In [37]:
sql = """
    SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, daily_volume, beta, publish_date
    FROM epss E JOIN stocks S ON E.name = S.name 
    WHERE E.name IN ({})
    ORDER BY E.name, year DESC, quarter DESC 
""".format(portfolio)
print(sql)

epss_stocks = pd.read_sql(sql, conlt)
epss_stocks.shape

    SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, daily_volume, beta, publish_date
    FROM epss E JOIN stocks S ON E.name = S.name
    WHERE E.name IN ('3BBIF', 'ACE', 'ADVANC', 'AH', 'AIE', 'AIMIRT', 'AIT', 'AMATA', 'ANAN', 'AP', 'ASIAN', 'ASK', 'ASP', 'ASW', 'AWC', 'BA', 'BAM', 'BBL', 'BCH', 'BCP', 'BCPG', 'BDMS', 'BEAUTY', 'BEC', 'BEM', 'BGC', 'BGRIM', 'BH', 'BJC', 'BKIH', 'BLA', 'CBG', 'CENTEL', 'CHG', 'CK', 'CKP', 'COM7', 'CPALL', 'CPAXT', 'CPF', 'CPN', 'CPNCG', 'CPNREIT', 'CRC', 'DCC', 'DCON', 'DELTA', 'DIF', 'DOHOME', 'EA', 'EGATIF', 'EGCO', 'FSMART', 'GC', 'GFPT', 'GLOBAL', 'GPSC', 'GULF', 'GUNKUL', 'HANA', 'HFT', 'HMPRO', 'HTC', 'ICHI', 'III', 'ILM', 'IMH', 'IP', 'IRPC', 'IVL', 'JMART', 'JMT', 'KBANK', 'KCE', 'KKP', 'KTB', 'KTC', 'LALIN', 'LANNA', 'LH', 'LIT', 'LPN', 'M', 'MAJOR', 'MBAX', 'MCS', 'MEGA', 'MINT', 'MST', 'MTC', 'NER', 'NOBLE', 'ONEE', 'OR', 'ORI', 'OSP', 'PCSGH', 'PDG', 'PLANB', 'POPF', 'PREB', 'PRM', 'PROSPECT', 'PSH', 'PSL', 'PTG', 'PTT', 'PTTEP', 'PTTGC', 'QH', 'RATCH', 'RBF', 'RCL', 'RJH', 'ROJNA', 'SAPPE', 'SAT', 'SAWAD', 'SC', 'SCB', 'SCC', 'SCCC', 'SCGP', 'SENA', 'SGP', 'SINGER', 'SIRI', 'SIS', 'SJWD', 'SMPC', 'SNC', 'SPALI', 'SPCG', 'SPRC', 'SSP', 'STA', 'STGT', 'SUPER', 'SUPEREIF', 'SYNEX', 'TASCO', 'TCAP', 'TFG', 'THANI', 'THG', 'TIDLOR', 'TIPH', 'TISCO', 'TKN', 'TKS', 'TMT', 'TOA', 'TOP', 'TPIPL', 'TPIPP', 'TQM', 'TRUE', 'TSE', 'TTA', 'TTB', 'TTLPF', 'TTW', 'TU', 'TVO', 'TYCN', 'UTP', 'VIBHA', 'VNG', 'WHA', 'WHAIR', 'WHART', 'WHAUP', 'WICE', 'WORK')
    ORDER BY E.name, year DESC, quarter DESC

(8392, 10)

### Delete from profits of older profit stocks

In [40]:
sqlDel = text("""
    DELETE FROM profits 
    WHERE name IN ({})
    AND quarter < :quarter
""".format(portfolio))
print(sqlDel)
# Execute with parameters
result = conlt.execute(sqlDel, {'quarter': quarter})
result.rowcount

    DELETE FROM profits
    WHERE name IN ('3BBIF', 'ACE', 'ADVANC', 'AH', 'AIE', 'AIMIRT', 'AIT', 'AMATA', 'ANAN', 'AP', 'ASIAN', 'ASK', 'ASP', 'ASW', 'AWC', 'BA', 'BAM', 'BBL', 'BCH', 'BCP', 'BCPG', 'BDMS', 'BEAUTY', 'BEC', 'BEM', 'BGC', 'BGRIM', 'BH', 'BJC', 'BKIH', 'BLA', 'CBG', 'CENTEL', 'CHG', 'CK', 'CKP', 'COM7', 'CPALL', 'CPAXT', 'CPF', 'CPN', 'CPNCG', 'CPNREIT', 'CRC', 'DCC', 'DCON', 'DELTA', 'DIF', 'DOHOME', 'EA', 'EGATIF', 'EGCO', 'FSMART', 'GC', 'GFPT', 'GLOBAL', 'GPSC', 'GULF', 'GUNKUL', 'HANA', 'HFT', 'HMPRO', 'HTC', 'ICHI', 'III', 'ILM', 'IMH', 'IP', 'IRPC', 'IVL', 'JMART', 'JMT', 'KBANK', 'KCE', 'KKP', 'KTB', 'KTC', 'LALIN', 'LANNA', 'LH', 'LIT', 'LPN', 'M', 'MAJOR', 'MBAX', 'MCS', 'MEGA', 'MINT', 'MST', 'MTC', 'NER', 'NOBLE', 'ONEE', 'OR', 'ORI', 'OSP', 'PCSGH', 'PDG', 'PLANB', 'POPF', 'PREB', 'PRM', 'PROSPECT', 'PSH', 'PSL', 'PTG', 'PTT', 'PTTEP', 'PTTGC', 'QH', 'RATCH', 'RBF', 'RCL', 'RJH', 'ROJNA', 'SAPPE', 'SAT', 'SAWAD', 'SC', 'SCB', 'SCC', 'SCCC', 'SCGP', 'SENA', 'SGP', 'SINGER', 'SIRI', 'SIS', 'SJWD', 'SMPC', 'SNC', 'SPALI', 'SPCG', 'SPRC', 'SSP', 'STA', 'STGT', 'SUPER', 'SUPEREIF', 'SYNEX', 'TASCO', 'TCAP', 'TFG', 'THANI', 'THG', 'TIDLOR', 'TIPH', 'TISCO', 'TKN', 'TKS', 'TMT', 'TOA', 'TOP', 'TPIPL', 'TPIPP', 'TQM', 'TRUE', 'TSE', 'TTA', 'TTB', 'TTLPF', 'TTW', 'TU', 'TVO', 'TYCN', 'UTP', 'VIBHA', 'VNG', 'WHA', 'WHAIR', 'WHART', 'WHAUP', 'WICE', 'WORK')
    AND quarter < :quarter

5

In [42]:
result = conmy.execute(sqlDel, {'quarter': quarter})
result.rowcount

1

In [44]:
result = conpg.execute(sqlDel, {'quarter': quarter})
result.rowcount

5

In [46]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
lt_profits = pd.read_sql(sql, conlt)
lt_profits.set_index("name", inplace=True)
lt_profits.index

Index(['3BBIF', '3BBIF', 'ADVANC', 'ADVANC', 'BCP', 'BCP', 'BPP', 'CENTEL',
       'COM7', 'COM7', 'CPALL', 'CPNREIT', 'DIF', 'DOHOME', 'FPT', 'GLOBAL',
       'GULF', 'KGI', 'KKP', 'KKP', 'KTC', 'MINT', 'MTC', 'MTC', 'NER', 'PSL',
       'SCGP', 'SCGP', 'SGP', 'SIS', 'SIS', 'SYNEX', 'TCAP', 'THANI', 'THANI',
       'TOA', 'VIBHA', 'WHA', 'WHART', 'WHAUP'],
      dtype='object', name='name')

In [48]:
my_profits = pd.read_sql(sql, conmy)
my_profits.set_index("name", inplace=True)
my_profits.index

Index(['2842', '2843', '2844', '2845', '2846', '2847', '2848', '2849', '2850',
       '2851', '2851', '2852', '2853', '2854', '2855', '2856', '3BBIF',
       '3BBIF', 'ADVANC', 'ADVANC', 'BCP', 'BCP', 'CENTEL', 'COM7', 'COM7',
       'CPALL', 'CPNREIT', 'DIF', 'DOHOME', 'FPT', 'GLOBAL', 'GULF', 'KKP',
       'KKP', 'KTC', 'MINT', 'MTC', 'MTC', 'NER', 'PSL', 'SCGP', 'SCGP', 'SGP',
       'SIS', 'SIS', 'SYNEX', 'TCAP', 'THANI', 'THANI', 'TOA', 'VIBHA', 'WHA',
       'WHART', 'WHAUP'],
      dtype='object', name='name')

In [50]:
pg_profits = pd.read_sql(sql, conpg)
pg_profits.set_index("name", inplace=True)
pg_profits.index

Index(['3BBIF', '3BBIF', 'ADVANC', 'ADVANC', 'BCP', 'BCP', 'BPP', 'CENTEL',
       'COM7', 'COM7', 'CPALL', 'CPNREIT', 'DIF', 'DOHOME', 'FPT', 'GLOBAL',
       'KGI', 'KKP', 'KKP', 'KTC', 'MINT', 'MTC', 'MTC', 'NER', 'PSL', 'SCGP',
       'SCGP', 'SGP', 'SIS', 'SIS', 'SYNEX', 'TCAP', 'THANI', 'THANI', 'TOA',
       'VIBHA', 'WHA', 'WHART', 'WHAUP'],
      dtype='object', name='name')

### Portfolio that publish today

In [53]:
sql = """
    SELECT * 
    FROM tickers
    WHERE name IN ({})
    ORDER BY name
""".format(portfolio)
print(sql)

pg_tickers = pd.read_sql(sql, conpg)
pg_tickers[['name','id']].sort_values(by=[ "name"], ascending=[True])

    SELECT *
    FROM tickers
    WHERE name IN ('3BBIF', 'ACE', 'ADVANC', 'AH', 'AIE', 'AIMIRT', 'AIT', 'AMATA', 'ANAN', 'AP', 'ASIAN', 'ASK', 'ASP', 'ASW', 'AWC', 'BA', 'BAM', 'BBL', 'BCH', 'BCP', 'BCPG', 'BDMS', 'BEAUTY', 'BEC', 'BEM', 'BGC', 'BGRIM', 'BH', 'BJC', 'BKIH', 'BLA', 'CBG', 'CENTEL', 'CHG', 'CK', 'CKP', 'COM7', 'CPALL', 'CPAXT', 'CPF', 'CPN', 'CPNCG', 'CPNREIT', 'CRC', 'DCC', 'DCON', 'DELTA', 'DIF', 'DOHOME', 'EA', 'EGATIF', 'EGCO', 'FSMART', 'GC', 'GFPT', 'GLOBAL', 'GPSC', 'GULF', 'GUNKUL', 'HANA', 'HFT', 'HMPRO', 'HTC', 'ICHI', 'III', 'ILM', 'IMH', 'IP', 'IRPC', 'IVL', 'JMART', 'JMT', 'KBANK', 'KCE', 'KKP', 'KTB', 'KTC', 'LALIN', 'LANNA', 'LH', 'LIT', 'LPN', 'M', 'MAJOR', 'MBAX', 'MCS', 'MEGA', 'MINT', 'MST', 'MTC', 'NER', 'NOBLE', 'ONEE', 'OR', 'ORI', 'OSP', 'PCSGH', 'PDG', 'PLANB', 'POPF', 'PREB', 'PRM', 'PROSPECT', 'PSH', 'PSL', 'PTG', 'PTT', 'PTTEP', 'PTTGC', 'QH', 'RATCH', 'RBF', 'RCL', 'RJH', 'ROJNA', 'SAPPE', 'SAT', 'SAWAD', 'SC', 'SCB', 'SCC', 'SCCC', 'SCGP', 'SENA', 'SGP', 'SINGER', 'SIRI', 'SIS', 'SJWD', 'SMPC', 'SNC', 'SPALI', 'SPCG', 'SPRC', 'SSP', 'STA', 'STGT', 'SUPER', 'SUPEREIF', 'SYNEX', 'TASCO', 'TCAP', 'TFG', 'THANI', 'THG', 'TIDLOR', 'TIPH', 'TISCO', 'TKN', 'TKS', 'TMT', 'TOA', 'TOP', 'TPIPL', 'TPIPP', 'TQM', 'TRUE', 'TSE', 'TTA', 'TTB', 'TTLPF', 'TTW', 'TU', 'TVO', 'TYCN', 'UTP', 'VIBHA', 'VNG', 'WHA', 'WHAIR', 'WHART', 'WHAUP', 'WICE', 'WORK')
    ORDER BY name

       name   id
0     3BBIF  241
1       ACE  667
2    ADVANC    8
3        AH   11
4       AIE  691
..      ...  ...
169   WHAIR  217
170   WHART  630
171   WHAUP  631
172    WICE  632
173    WORK  636

[174 rows x 2 columns]

In [55]:
sql = """
    SELECT name 
    FROM buy
"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(29, 1)

In [57]:
df_merge = pd.merge(pg_tickers, df_buy, on='name', how='inner')
df_merge

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,241,3BBIF,JASMINE BROADBAND INTERNET INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.jas-if.com,2018-04-22 04:29:37.600684,2019-03-03 03:45:01.621634
1,8,ADVANC,ADVANCED INFO SERVICE PUBLIC COMPANY LIMITED,Technology,Information & Communication Technology,SET50 / SETHD / SETTHSI,investor.ais.co.th,2018-04-22 04:29:36.118727,2021-07-07 03:33:38.798595
2,11,AH,AAPICO HITECH PUBLIC COMPANY LIMITED,Industrials,Automotive,sSET / SETTHSI,www.aapico.com,2018-04-22 04:29:36.134601,2021-07-07 03:33:38.806441
3,13,AIMIRT,AIM INDUSTRIAL GROWTH FREEHOLD AND LEASEHOLD R...,Property & Construction,Property Fund & REITs,SET,www.aimreit.com,2018-04-22 04:29:36.146073,2018-04-22 04:29:36.146073
4,668,AWC,ASSET WORLD CORP PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SET50 / SETTHSI,https://www.assetworldcorp-th.com,2019-11-19 07:13:52.454317,2022-01-15 03:54:48.241937
5,55,BCH,BANGKOK CHAIN HOSPITAL PUBLIC COMPANY LIMITED,Services,Health Care Services,SET100 / SETWB,www.bangkokchainhospital.com,2018-04-22 04:29:36.442067,2019-11-19 07:13:52.520896
6,121,CPF,CHAROEN POKPHAND FOODS PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET50 / SETCLMV / SETHD / SETTHSI / SETWB,www.cpfworldwide.com,2018-04-22 04:29:36.867977,2021-07-07 03:33:38.893396
7,127,CPNREIT,CPN RETAIL GROWTH LEASEHOLD REIT,Property & Construction,Property Fund & REITs,SET,www.cpnreit.com,2018-04-22 04:29:36.900508,2018-04-22 04:29:36.900508
8,146,DIF,DIGITAL TELECOMMUNICATIONS INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.digital-tif.com,2018-04-22 04:29:37.030748,2018-04-22 04:29:37.030748
9,238,IVL,INDORAMA VENTURES PUBLIC COMPANY LIMITED,Industrials,Petrochemicals & Chemicals,SET50 / SETTHSI,www.indoramaventures.com,2018-04-22 04:29:37.583373,2021-07-07 03:33:38.986666
10,245,JMT,JMT NETWORK SERVICES PUBLIC COMPANY LIMITED,Financials,Finance & Securities,SET50,www.jmtnetwork.co.th,2018-04-22 04:29:37.621811,2020-07-06 13:23:59.311892
11,301,MCS,M.C.S.STEEL PUBLIC COMPANY LIMITED,Industrials,Steel and Metal Products,sSET,www.mcssteel.com,2018-04-22 04:29:37.957104,2021-08-22 18:22:07.463483
12,649,NER,NORTH EAST RUBBER PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,sSET,www.nerubber.com,2019-03-03 03:45:01.837764,2019-11-19 07:13:53.611284
13,347,ORI,ORIGIN PROPERTY PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SET100 / SETHD / SETTHSI,www.origin.co.th,2018-04-22 04:29:38.228072,2022-01-15 03:54:48.440923
14,750,PROSPECT,PROSPECT LOGISTICS AND INDUSTRIAL FREEHOLD AND...,Property & Construction,Property Fund & REITs,SET,http://www.prospectreit.com/,2026-08-12 07:18:35.336565,2026-08-12 07:18:35.336565
15,387,PTG,PTG ENERGY PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET100 / SETHD / SETTHSI,www.ptgenergy.co.th,2018-04-22 04:29:38.474708,2022-01-15 03:54:48.464340
16,389,PTT,PTT PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET50 / SETCLMV / SETHD / SETTHSI,www.pttplc.com,2018-04-22 04:29:38.484745,2019-11-19 07:13:53.785316
17,391,PTTGC,PTT GLOBAL CHEMICAL PUBLIC COMPANY LIMITED,Industrials,Petrochemicals & Chemicals,SET50 / SETCLMV / SETTHSI,www.pttgcgroup.com,2018-04-22 04:29:38.496779,2021-07-07 03:33:39.100623
18,401,RCL,REGIONAL CONTAINER LINES PUBLIC COMPANY LIMITED,Services,Transportation & Logistics,SET100 / SETCLMV,www.rclgroup.com,2018-04-22 04:29:38.554599,2022-01-15 03:54:48.472788
19,443,SENA,SENADEVELOPMENT PUBLIC COMPANY LIMITED,Property & Construction,Property Development,sSET,www.sena.co.th,2018-04-22 04:29:38.825191,2018-04-22 04:29:38.825191
20,452,SINGER,SINGER THAILAND PUBLIC COMPANY LIMITED,Services,Commerce,SET100,www.singerthai.co.th,2018-04-22 04:29:38.875668,2021-07-07 03:33:39.150064
21,489,STA,SRI TRANG AGRO-INDUSTRY PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,SET100 / SETTHSI / SETWB,www.sritranggroup.com,2018-04-22 04:29:39.085589,2022-01-15 03:54:48.525517
22,504,SYNEX,SYNNEX (THAILAND) PUBLIC COMPANY LIMITED,Technology,Information & Communication Technology,SET100 / SETTHSI,www.synnex.co.th,2018-04-22 04:29:39.170664,2021-07-07 03:33:39.202279
23,562,TOA,TOA PAINT (THAILAND) PUBLIC COMPANY LIMITED,Property & Construction,Construction Materials,SETTHSI,www.toagroup.com,2018-04-22 04:29:39.494571,2021-07-07 03:33:39.241053
24,594,TVO,THAI VEGETABLE OIL PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET / SETTHSI / SETWB,www.tvothai.com,2018-04-22 04:29:39.677962,2019-11-19 07:13:54.470342
25,217,WHAIR,HEMARAJ LEASEHOLD REAL ESTATE INVESTMENT TRUST,Property & Construction,Property Fund & REITs,SET,www.hemarajreit.com,2018-04-22 04:29:37.460955,2018-04-22 04:29:37.460955
26,630,WHART,WHA PREMIUM GROWTH FREEHOLD AND LEASEHOLD REAL...,Property & Construction,Property Fund & REITs,SET,www.whareit.com,2018-04-22 04:29:39.879467,2018-04-22 04:29:39.879467

In [59]:
file_name = 'pub_stock.xlsx'
output_file = os.path.join(dat_path, file_name)
print(f"Output file : {output_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\pub_stock.xlsx

In [61]:
df_merge[['id','name','sector','market']].to_excel(output_file, index=False)

### Update ticker_id from table tickers in PortPg

In [64]:
sql = """
SELECT name FROM buy WHERE active = 1 ORDER BY name"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(29, 1)

In [66]:
sql = '''
SELECT * 
FROM epss 
WHERE publish_date >= '%s' 
'''
sql = sql % (select_date)
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.shape

SELECT *
FROM epss
WHERE publish_date >= '2026-07-01'

(177, 14)

In [68]:
sql = """
SELECT *
FROM tickers"""
pg_tickers = pd.read_sql(sql, conpg)
pg_tickers.shape

(391, 9)

In [70]:
df_epss_buy = df_epss_inp.merge(df_buy, on='name', how='inner')
df_epss_buy = df_epss_buy.drop(columns=['ticker_id'])

df_epss_buy_tickers = df_epss_buy.merge(pg_tickers, on='name', how='inner')
df_epss_buy_tickers = df_epss_buy_tickers.rename(columns={'id_y': 'ticker_id'})
                                                  
columns = 'name ticker_id publish_date year quarter'.split()
df_epss_buy_tickers[columns].sort_values(by='name')

        name  ticker_id publish_date  year  quarter
0      3BBIF        241   2026-08-05  2026        2
1     ADVANC          8   2026-08-07  2026        2
2         AH         11   2026-08-11  2026        2
3     AIMIRT         13   2026-08-10  2026        2
23       AWC        668   2026-08-14  2026        2
22       BCH         55   2026-08-14  2026        2
25       CPF        121   2026-08-14  2026        2
21   CPNREIT        127   2026-08-13  2026        2
16       DIF        146   2026-08-13  2026        2
14    GVREIT        209   2026-08-13  2026        3
4        IVL        238   2026-08-11  2026        2
5        JMT        245   2026-08-11  2026        2
6        MCS        301   2026-08-10  2026        2
7        NER        649   2026-08-05  2026        2
28       ORI        347   2026-08-14  2026        2
13  PROSPECT        750   2026-08-10  2026        2
20       PTG        387   2026-08-13  2026        2
17       PTT        389   2026-08-13  2026        2
8      PTTGC        391   2026-08-07  2026        2
9        RCL        401   2026-08-07  2026        2
27      SENA        443   2026-08-14  2026        2
10    SINGER        452   2026-08-11  2026        2
26       STA        489   2026-08-14  2026        2
11     SYNEX        504   2026-08-05  2026        2
18     TFFIF        655   2026-08-13  2026        3
19       TOA        562   2026-08-13  2026        2
24       TVO        594   2026-08-14  2026        2
15     WHAIR        217   2026-08-13  2026        2
12     WHART        630   2026-08-07  2026        2

In [72]:
df_epss_buy_tickers.shape

(29, 21)

In [74]:
conlt.commit()
conlt.close()
conmy.commit()
conmy.close()
conpg.commit()
conpg.close()

In [76]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-08-22 11:16:52