In [1]:
import os
import pandas as pd
from datetime import date, datetime, timedelta
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2026"
quarter = "2"

current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-06-08 14:48:58

In [3]:
select_date = date(2026, 4, 1)
select_date = select_date.strftime("%Y-%m-%d")
select_date

'2026-04-01'

### Tables in the process

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [8]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [10]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()
format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%'
              }

In [12]:
sql = '''
SELECT * 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= "%s"
ORDER BY name'''
sql = sql % (year, quarter, select_date)

df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.tail().style.format(format_dict)

In [14]:
df_epss_inp.shape

(4, 14)

In [16]:
df_epss_inp["yoy_gain"] = df_epss_inp["q_amt"] - df_epss_inp["y_amt"]
df_epss_inp["yoy_pct"]  = round(df_epss_inp["yoy_gain"] / abs(df_epss_inp["y_amt"]) * 100,2)
df_epss_inp["acc_gain"] = df_epss_inp["aq_amt"] - df_epss_inp["ay_amt"]
df_epss_inp["acc_pct"] = round(df_epss_inp["acc_gain"] / abs(df_epss_inp["ay_amt"]) * 100,2)
df_aggr = df_epss_inp[
    [
        "name",
        "year",
        "quarter",
        "q_amt",
        "y_amt",
        "yoy_gain",
        "yoy_pct",
        "aq_amt",
        "ay_amt",
        "acc_gain",
        "acc_pct",
    ]
]
df_aggr.tail().style.format(format_dict)

In [18]:
criteria_1 = df_aggr.q_amt > 110000
df_aggr.loc[criteria_1,cols].style.format(format_dict)

In [20]:
criteria_2 = df_aggr.y_amt > 100000
df_aggr.loc[criteria_2, cols].style.format(format_dict)

In [22]:
criteria_3 = df_aggr.yoy_pct > 10
df_aggr.loc[criteria_3, cols].style.format(format_dict)

In [24]:
criteria_4 = (df_aggr.q_amt > df_aggr.y_amt)
df_aggr.loc[criteria_4, cols].style.format(format_dict)

In [26]:
df_aggr_criteria = criteria_1 & criteria_2 & criteria_3 & criteria_4
df_aggr.loc[df_aggr_criteria, cols].sort_values(['name'],ascending=[True]).style.format(format_dict)

In [28]:
df_aggr[df_aggr_criteria].sort_values(by=["yoy_pct"], ascending=[False]).style.format(format_dict)

In [30]:
df_aggr[df_aggr_criteria].sort_values(by=["name"], ascending=[True]).style.format(format_dict)

In [32]:
names = df_epss_inp['name']
portfolio = ", ".join(map(lambda name: "'%s'" % name, names))
portfolio

"'AOT', 'FPT', 'GVREIT', 'TFFIF'"

### If new records pass filter criteria then proceed to create quarterly profits process.

In [35]:
sql = """
    SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, daily_volume, beta, publish_date
    FROM epss E JOIN stocks S ON E.name = S.name 
    WHERE E.name IN ({})
    ORDER BY E.name, year DESC, quarter DESC 
""".format(portfolio)
print(sql)

epss_stocks = pd.read_sql(sql, conlt)
epss_stocks.shape

    SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, daily_volume, beta, publish_date
    FROM epss E JOIN stocks S ON E.name = S.name
    WHERE E.name IN ('AOT', 'FPT', 'GVREIT', 'TFFIF')
    ORDER BY E.name, year DESC, quarter DESC

(151, 10)

### Delete from profits of older profit stocks

In [38]:
sqlDel = text("""
    DELETE FROM profits 
    WHERE name IN ({})
    AND quarter < :quarter
""".format(portfolio))
print(sqlDel)
# Execute with parameters
result = conlt.execute(sqlDel, {'quarter': quarter})
result.rowcount

    DELETE FROM profits
    WHERE name IN ('AOT', 'FPT', 'GVREIT', 'TFFIF')
    AND quarter < :quarter

0

In [40]:
result = conmy.execute(sqlDel, {'quarter': quarter})
result.rowcount

0

In [42]:
result = conpg.execute(sqlDel, {'quarter': quarter})
result.rowcount

0

In [44]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
lt_profits = pd.read_sql(sql, conlt)
lt_profits.set_index("name", inplace=True)
lt_profits.index

Index(['3BBIF', 'ADVANC', 'ADVANC', 'AMATA', 'BCP', 'BCP', 'BGRIM', 'BKIH',
       'BLA', 'BPP', 'CENTEL', 'CENTEL', 'CK', 'CKP', 'COM7', 'COM7', 'CPALL',
       'CPALL', 'CPN', 'CPNREIT', 'DELTA', 'DIF', 'DIF', 'FPT', 'GPSC', 'GULF',
       'GUNKUL', 'KGI', 'KKP', 'KKP', 'KTB', 'MINT', 'MTC', 'MTC', 'NER',
       'ONEE', 'SCC', 'SCGP', 'SCGP', 'SIS', 'SIS', 'SPRC', 'SYNEX', 'TCAP',
       'TFG', 'THANI', 'THANI', 'TIDLOR', 'TOA', 'TOA', 'TOP', 'TPIPL', 'TTW',
       'TVO', 'VIBHA', 'VIBHA', 'WHA', 'WHART'],
      dtype='object', name='name')

In [46]:
my_profits = pd.read_sql(sql, conmy)
my_profits.set_index("name", inplace=True)
my_profits.index

Index(['2842', '2843', '2844', '2845', '2846', '2847', '2848', '2849', '2850',
       '2851', '2851', '2852', '2853', '2854', '2855', '2856', '3BBIF',
       'ADVANC', 'ADVANC', 'BCP', 'CENTEL', 'COM7', 'CPALL', 'CPNREIT',
       'DELTA', 'DIF', 'FPT', 'GPSC', 'GULF', 'GUNKUL', 'KKP', 'KKP', 'KTB',
       'MTC', 'NER', 'SCC', 'SCGP', 'SCGP', 'SIS', 'THANI', 'THANI', 'TIDLOR',
       'TOA', 'TPIPL', 'TVO', 'VIBHA', 'WHA', 'WHART'],
      dtype='object', name='name')

In [48]:
pg_profits = pd.read_sql(sql, conpg)
pg_profits.set_index("name", inplace=True)
pg_profits.index

Index(['3BBIF', 'ADVANC', 'ADVANC', 'AMATA', 'BCP', 'BCP', 'BGRIM', 'BKIH',
       'BLA', 'BPP', 'CENTEL', 'CENTEL', 'CK', 'CKP', 'COM7', 'COM7', 'CPALL',
       'CPALL', 'CPN', 'CPNREIT', 'DELTA', 'DIF', 'DIF', 'FPT', 'GPSC',
       'GUNKUL', 'KGI', 'KKP', 'KKP', 'KTB', 'MINT', 'MTC', 'MTC', 'NER',
       'ONEE', 'SCC', 'SCGP', 'SCGP', 'SIS', 'SIS', 'SPRC', 'SYNEX', 'TCAP',
       'TFG', 'THANI', 'THANI', 'TIDLOR', 'TOA', 'TOA', 'TOP', 'TPIPL', 'TTW',
       'TVO', 'VIBHA', 'VIBHA', 'WHA', 'WHART'],
      dtype='object', name='name')

### Portfolio that publish today

In [51]:
sql = """
    SELECT * 
    FROM tickers
    WHERE name IN ({})
    ORDER BY name
""".format(portfolio)
print(sql)

pg_tickers = pd.read_sql(sql, conpg)
pg_tickers[['name','id']].sort_values(by=[ "name"], ascending=[True])

    SELECT *
    FROM tickers
    WHERE name IN ('AOT', 'FPT', 'GVREIT', 'TFFIF')
    ORDER BY name

     name   id
0     AOT   28
1     FPT  722
2  GVREIT  209
3   TFFIF  655

In [53]:
sql = """
    SELECT name 
    FROM buy
"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(28, 1)

In [55]:
df_merge = pd.merge(pg_tickers, df_buy, on='name', how='inner')
df_merge

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,209,GVREIT,GOLDEN VENTURES LEASEHOLD REAL ESTATE INVESTME...,Property & Construction,Property Fund & REITs,SET,www.gvreit.com,2018-04-22 04:29:37.417731,2018-04-22 04:29:37.417731
1,655,TFFIF,THAILAND FUTURE FUND,Services,Transportation & Logistics,SET,www.tffif.com,2019-03-03 03:45:02.485777,2019-03-03 03:45:02.485777

In [57]:
file_name = 'pub_stock.xlsx'
output_file = os.path.join(dat_path, file_name)
print(f"Output file : {output_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\pub_stock.xlsx

In [59]:
df_merge[['id','name','sector','market']].to_excel(output_file, index=False)

### Update ticker_id from table tickers in PortPg

In [62]:
sql = """
SELECT name FROM buy WHERE active = 1 ORDER BY name"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(28, 1)

In [64]:
sql = '''
SELECT * 
FROM epss 
WHERE publish_date >= '%s' 
'''
sql = sql % (select_date)
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.shape

SELECT *
FROM epss
WHERE publish_date >= '2026-04-01'

(190, 14)

In [66]:
sql = """
SELECT *
FROM tickers"""
pg_tickers = pd.read_sql(sql, conpg)
pg_tickers.shape

(390, 9)

In [68]:
df_epss_buy = df_epss_inp.merge(df_buy, on='name', how='inner')
df_epss_buy = df_epss_buy.drop(columns=['ticker_id'])

df_epss_buy_tickers = df_epss_buy.merge(pg_tickers, on='name', how='inner')
df_epss_buy_tickers = df_epss_buy_tickers.rename(columns={'id_y': 'ticker_id'})
                                                  
columns = 'name ticker_id publish_date'.split()
df_epss_buy_tickers[columns].sort_values(by='name')

       name  ticker_id publish_date
3     3BBIF        241   2026-05-07
4    ADVANC          8   2026-05-07
17       AH         11   2026-05-14
9    AIMIRT         13   2026-05-11
11      AWC        668   2026-05-11
24      BCH         55   2026-05-15
18      CPF        121   2026-05-14
22  CPNREIT        127   2026-05-14
19      DIF        146   2026-05-14
14   GVREIT        209   2026-05-13
25      IVL        238   2026-05-15
21      JMT        245   2026-05-14
23      MCS        301   2026-05-14
7       NER        649   2026-05-06
26      ORI        347   2026-05-15
12      PTG        387   2026-05-12
16      PTT        389   2026-05-14
6     PTTGC        391   2026-05-05
0       RCL        401   2026-05-08
15     SENA        443   2026-05-13
20   SINGER        452   2026-05-14
2       STA        489   2026-05-08
8     SYNEX        504   2026-05-11
13    TFFIF        655   2026-05-12
27      TOA        562   2026-05-15
1       TVO        594   2026-05-08
10    WHAIR        217   2026-05-11
5     WHART        630   2026-05-07

In [70]:
conlt.commit()
conlt.close()
conmy.commit()
conmy.close()
conpg.commit()
conpg.close()

In [72]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-06-08 14:51:44