In [1]:
import os
import pandas as pd
from datetime import date, datetime, timedelta
from sqlalchemy import create_engine, text
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2026"
quarter = "2"

today = date.today()
print(today)

2026-08-16

In [2]:
# If run after actual work day
#today = today - timedelta(days=2)
#print(today)

In [3]:
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
print(today, yesterday)

2026-08-16 2026-08-14

### Tables in the process

In [5]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [6]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [7]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()
format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}','qty':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%','unit_cost':'{:.2f}%'
              }

In [8]:
select_date = date(2026, 7, 1)
select_date = select_date.strftime("%Y-%m-%d")
select_date

'2026-07-01'

In [9]:
sql = '''
SELECT * 
FROM epss 
WHERE year = %s AND quarter >= %s
AND publish_date >= "%s"
ORDER BY name'''
sql = sql % (year, quarter, select_date)
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.tail().style.format(format_dict)

SELECT *
FROM epss
WHERE year = 2026 AND quarter >= 2
AND publish_date >= "2026-07-01"
ORDER BY name

In [10]:
df_epss_inp.shape

(151, 14)

In [11]:
df_epss_inp["yoy_gain"] = df_epss_inp["q_amt"] - df_epss_inp["y_amt"]
df_epss_inp["yoy_pct"]  = round(df_epss_inp["yoy_gain"] / abs(df_epss_inp["y_amt"]) * 100,2)
df_epss_inp["acc_gain"] = df_epss_inp["aq_amt"] - df_epss_inp["ay_amt"]
df_epss_inp["acc_pct"] = round(df_epss_inp["acc_gain"] / abs(df_epss_inp["ay_amt"]) * 100,2)
df_aggr = df_epss_inp[
    [
        "name",
        "year",
        "quarter",
        "q_amt",
        "y_amt",
        "yoy_gain",
        "yoy_pct",
        "aq_amt",
        "ay_amt",
        "acc_gain",
        "acc_pct",
    ]
]
df_aggr.tail().style.format(format_dict)

In [12]:
df_aggr.shape

(151, 11)

In [13]:
names = df_epss_inp['name']
portfolio = ", ".join(map(lambda name: "'%s'" % name, names))
portfolio

"'3BBIF', 'ACE', 'ADVANC', 'AH', 'AIE', 'AIMIRT', 'AIT', 'AMATA', 'ANAN', 'AP', 'ASIAN', 'ASK', 'ASP', 'ASW', 'AWC', 'BA', 'BBL', 'BCH', 'BCP', 'BCPG', 'BDMS', 'BEAUTY', 'BEC', 'BGC', 'BGRIM', 'BH', 'BJC', 'BLA', 'CBG', 'CENTEL', 'CHG', 'CK', 'CKP', 'COM7', 'CPALL', 'CPAXT', 'CPF', 'CPN', 'CPNCG', 'CPNREIT', 'DCC', 'DELTA', 'DIF', 'DOHOME', 'EA', 'EGATIF', 'EGCO', 'FSMART', 'GC', 'GFPT', 'GLOBAL', 'GPSC', 'GULF', 'GVREIT', 'HANA', 'HMPRO', 'ICHI', 'ILM', 'IRPC', 'IVL', 'JMART', 'JMT', 'KCE', 'KKP', 'KTB', 'KTC', 'LANNA', 'LH', 'LIT', 'LPN', 'M', 'MAJOR', 'MBAX', 'MCS', 'MEGA', 'MINT', 'MST', 'MTC', 'NER', 'NOBLE', 'OR', 'ORI', 'OSP', 'PCSGH', 'PDG', 'PLANB', 'POPF', 'PREB', 'PRM', 'PROSPECT', 'PSH', 'PSL', 'PTG', 'PTT', 'PTTEP', 'PTTGC', 'QH', 'RATCH', 'RCL', 'RJH', 'ROJNA', 'SAPPE', 'SAT', 'SC', 'SCB', 'SCC', 'SCCC', 'SCGP', 'SENA', 'SGP', 'SINGER', 'SIS', 'SJWD', 'SMPC', 'SNC', 'SPALI', 'SPCG', 'STA', 'STGT', 'SUPEREIF', 'SYNEX', 'TASCO', 'TCAP', 'TFFIF', 'TFG', 'THANI', 'THG', 'TIDLOR', 'TIPH', 'TISCO', 'TKN', 'TKS', 'TMT', 'TOA', 'TOP', 'TPIPL', 'TPIPP', 'TQM', 'TRUE', 'TTA', 'TTB', 'TTLPF', 'TTW', 'TU', 'TVO', 'VNG', 'WHA', 'WHAIR', 'WHART', 'WHAUP', 'WORK'"

### Portfolio that publish today

In [15]:
sql = """
    SELECT name, id AS ticker_id
    FROM tickers
    WHERE name IN ({})
    ORDER BY name
""".format(portfolio)
print(sql)

pg_tickers = pd.read_sql(sql, conpg)
pg_tickers[['name','ticker_id']].sort_values(by=[ "name"], ascending=[True])

    SELECT name, id AS ticker_id
    FROM tickers
    WHERE name IN ('3BBIF', 'ACE', 'ADVANC', 'AH', 'AIE', 'AIMIRT', 'AIT', 'AMATA', 'ANAN', 'AP', 'ASIAN', 'ASK', 'ASP', 'ASW', 'AWC', 'BA', 'BBL', 'BCH', 'BCP', 'BCPG', 'BDMS', 'BEAUTY', 'BEC', 'BGC', 'BGRIM', 'BH', 'BJC', 'BLA', 'CBG', 'CENTEL', 'CHG', 'CK', 'CKP', 'COM7', 'CPALL', 'CPAXT', 'CPF', 'CPN', 'CPNCG', 'CPNREIT', 'DCC', 'DELTA', 'DIF', 'DOHOME', 'EA', 'EGATIF', 'EGCO', 'FSMART', 'GC', 'GFPT', 'GLOBAL', 'GPSC', 'GULF', 'GVREIT', 'HANA', 'HMPRO', 'ICHI', 'ILM', 'IRPC', 'IVL', 'JMART', 'JMT', 'KCE', 'KKP', 'KTB', 'KTC', 'LANNA', 'LH', 'LIT', 'LPN', 'M', 'MAJOR', 'MBAX', 'MCS', 'MEGA', 'MINT', 'MST', 'MTC', 'NER', 'NOBLE', 'OR', 'ORI', 'OSP', 'PCSGH', 'PDG', 'PLANB', 'POPF', 'PREB', 'PRM', 'PROSPECT', 'PSH', 'PSL', 'PTG', 'PTT', 'PTTEP', 'PTTGC', 'QH', 'RATCH', 'RCL', 'RJH', 'ROJNA', 'SAPPE', 'SAT', 'SC', 'SCB', 'SCC', 'SCCC', 'SCGP', 'SENA', 'SGP', 'SINGER', 'SIS', 'SJWD', 'SMPC', 'SNC', 'SPALI', 'SPCG', 'STA', 'STGT', 'SUPEREIF', 'SYNEX', 'TASCO', 'TCAP', 'TFFIF', 'TFG', 'THANI', 'THG', 'TIDLOR', 'TIPH', 'TISCO', 'TKN', 'TKS', 'TMT', 'TOA', 'TOP', 'TPIPL', 'TPIPP', 'TQM', 'TRUE', 'TTA', 'TTB', 'TTLPF', 'TTW', 'TU', 'TVO', 'VNG', 'WHA', 'WHAIR', 'WHART', 'WHAUP', 'WORK')
    ORDER BY name

       name  ticker_id
0     3BBIF        241
1       ACE        667
2    ADVANC          8
3        AH         11
4       AIE        691
..      ...        ...
146     WHA        628
147   WHAIR        217
148   WHART        630
149   WHAUP        631
150    WORK        636

[151 rows x 2 columns]

In [16]:
sql = """
    SELECT name, date AS pur_date, volbuy AS qty, price AS unit_cost, dividend, period, grade
    FROM buy
"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(29, 7)

In [17]:
df_buy.dtypes

name          object
pur_date      object
qty          float64
unit_cost    float64
dividend     float64
period        object
grade         object
dtype: object

In [18]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()
format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}','qty':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%','unit_cost':'{:.2f}','dividend':'{:.4f}'
              }

In [19]:
sqlPrice = """SELECT * FROM price LIMIT 1"""
df_price = pd.read_sql(sqlPrice, const)
df_price

    name        date  price  maxp  minp      qty  opnp
0  JMART  2019-04-01    8.1   8.3  8.05  2971120  8.05

In [20]:
sql = """SELECT buy.name AS name, buy.date AS date, volbuy,
				buy.price AS buy_price, price.price AS mkt_price,
                volbuy * buy.price AS amtcst, 
				volbuy * price.price AS amtmkt, 
				(price.price - buy.price) * volbuy AS amtpol,
				(price.price - buy.price)*volbuy/(volbuy*buy.price)*100 AS percent, period, grade
          FROM buy INNER JOIN price ON buy.name = price.name
          WHERE price.date = '%s'
          ORDER BY period, name"""
sql = sql % (yesterday)
print(sql)

SELECT buy.name AS name, buy.date AS date, volbuy,
				buy.price AS buy_price, price.price AS mkt_price,
                volbuy * buy.price AS amtcst,
				volbuy * price.price AS amtmkt,
				(price.price - buy.price) * volbuy AS amtpol,
				(price.price - buy.price)*volbuy/(volbuy*buy.price)*100 AS percent, period, grade
          FROM buy INNER JOIN price ON buy.name = price.name
          WHERE price.date = '2026-08-14'
          ORDER BY period, name

In [21]:
df_buy = pd.read_sql(sql, const)
df_buy

,name,date,volbuy,buy_price,mkt_price,amtcst,amtmkt,amtpol,percent,period,grade
0,PTTGC,2021-03-17,6000.0,64.75,38.25,388500.0,229500.0,-159000.0,-40.926641,1,A1
1,SINGER,2023-01-19,6000.0,24.80,11.20,148800.0,67200.0,-81600.0,-54.838710,1,A4
2,STA,2021-06-15,10000.0,30.00,18.60,300000.0,186000.0,-114000.0,-38.000000,1,C3
3,3BBIF,2018-05-17,120000.0,10.10,6.65,1212000.0,798000.0,-414000.0,-34.158416,2,A4
4,AIMIRT,2026-05-21,10000.0,11.30,12.40,113000.0,124000.0,11000.0,9.734513,2,B1
5,CPNREIT,2022-08-16,55000.0,18.00,13.60,990000.0,748000.0,-242000.0,-24.444444,2,A4
6,DIF,2020-08-01,45000.0,12.70,10.20,571500.0,459000.0,-112500.0,-19.685039,2,A4
7,GVREIT,2022-08-24,69000.0,7.75,8.30,534750.0,572700.0,37950.0,7.096774,2,C4
8,MCS,2016-09-20,75000.0,15.30,7.90,1147500.0,592500.0,-555000.0,-48.366013,2,A4
9,NER,2021-09-01,27000.0,7.45,4.54,201150.0,122580.0,-78570.0,-39.060403,2,A1
10,PROSPECT,2026-06-10,20000.0,9.40,10.30,188000.0,206000.0,18000.0,9.574468,2,B1
11,PTT,2025-08-08,7500.0,32.00,39.75,240000.0,298125.0,58125.0,24.218750,2,B4
12,SENA,2022-03-29,105000.0,4.48,1.77,470400.0,185850.0,-284550.0,-60.491071,2,C1
13,TFFIF,2023-07-06,25000.0,7.30,7.10,182500.0,177500.0,-5000.0,-2.739726,2,A4
14,WHAIR,2021-10-11,50000.0,8.70,8.45,435000.0,422500.0,-12500.0,-2.873563,2,A1
15,WHART,2022-01-05,20000.0,12.30,11.20,246000.0,224000.0,-22000.0,-8.943089,2,A3
16,ADVANC,2026-02-27,400.0,355.00,371.00,142000.0,148400.0,6400.0,4.507042,3,A1
17,AH,2023-06-08,1200.0,37.00,16.10,44400.0,19320.0,-25080.0,-56.486486,3,B1
18,AWC,2023-06-15,9000.0,4.96,3.02,44640.0,27180.0,-17460.0,-39.112903,3,B1
19,BCH,2021-09-07,4000.0,21.70,11.00,86800.0,44000.0,-42800.0,-49.308756,3,B2
20,CPF,2025-08-21,10000.0,23.40,21.80,234000.0,218000.0,-16000.0,-6.837607,3,A2
21,PTG,2023-07-12,3600.0,11.40,7.30,41040.0,26280.0,-14760.0,-35.964912,3,B4
22,RCL,2021-11-08,27000.0,38.78,41.00,1047060.0,1107000.0,59940.0,5.724600,3,B3
23,SYNEX,2022-01-07,17500.0,26.40,9.40,462000.0,164500.0,-297500.0,-64.393939,3,A3
24,TOA,2023-09-06,1000.0,26.00,15.10,26000.0,15100.0,-10900.0,-41.923077,3,A4
25,TVO,2024-11-06,4000.0,24.90,27.50,99600.0,110000.0,10400.0,10.441767,3,B2
26,IVL,2022-08-29,7200.0,40.00,21.20,288000.0,152640.0,-135360.0,-47.000000,4,C3
27,JMT,2023-01-26,7000.0,37.70,11.40,263900.0,79800.0,-184100.0,-69.761273,4,C4
28,ORI,2022-04-07,50000.0,9.00,1.96,450000.0,98000.0,-352000.0,-78.222222,4,C2

In [22]:
df_merge1 = pd.merge(df_aggr, df_buy, on='name', how='inner')
df_merge1.style.format(format_dict)

In [23]:
df_merge1.shape

(29, 21)

In [24]:
df_merge2 = pd.merge(df_merge1, pg_tickers, on='name', how='inner')
df_merge2.style.format(format_dict)

In [25]:
df_merge2.shape

(29, 22)

In [26]:
file_name = 'stocks-in-port.xlsx'
output_file = os.path.join(dat_path, file_name)
print(f"Output file : {output_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\stocks-in-port.xlsx

In [27]:
df_merge2.to_excel(output_file, index=False)

In [28]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-08-16 17:42:25