In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2026
quarter = 2

current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-08-22 11:18:11

In [3]:
# Must modify select date to latest unprocessed date
select_date = date(2026, 7, 1)
select_date = select_date.strftime("%Y-%m-%d")
select_date

'2026-07-01'

In [5]:
cols = "name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y".split()
colt = "year quarter q_amt y_amt aq_amt ay_amt".split()
colu = 'name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt q_amt_p'.split() 
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
colw = 'name year quarter kind_x latest_amt_y_x previous_amt_y_x inc_amt_y_x inc_pct_y_x \
        latest_amt_q_x previous_amt_q_x inc_amt_q_x inc_pct_q_x q_amt_c_x y_amt_x \
        inc_amt_py_x inc_pct_py_x q_amt_p_x inc_amt_pq_x inc_pct_pq_x \
        ticker_id_x mean_pct_x std_pct_x'.split()
format_dict = {
    'q_amt': '{:,}',
    'y_amt': '{:,}',
    'yoy_gain': '{:,}',
    'q_amt_c': '{:,}',
    'q_amt_p': '{:,}',
    'aq_amt': '{:,}',
    'ay_amt': '{:,}',
    'acc_gain': '{:,}',
    'latest_amt': '{:,}',
    'previous_amt': '{:,}',
    'inc_amt': '{:,}',
    'inc_amt_pq': '{:,}',
    'inc_amt_py': '{:,}',    
    'latest_amt_q': '{:,}',
    'previous_amt_q': '{:,}',
    'inc_amt_q': '{:,}',
    'latest_amt_y': '{:,}',
    'previous_amt_y': '{:,}',
    'inc_amt_y': '{:,}',
    'kind_x': '{:,}',
    'inc_pct': '{:.2f}%',
    'inc_pct_q': '{:.2f}%',
    'inc_pct_y': '{:.2f}%',
    'inc_pct_pq': '{:.2f}%',
    'inc_pct_py': '{:.2f}%',   
    'mean_pct': '{:.2f}%',
    'std_pct': '{:.2f}%',      
}

### Process for specified stocks

In [5]:
names = """
IP
""".split()
names

['IP']

In [6]:
stock_list = names
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

"'IP'"

In [7]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = {year} AND quarter = {quarter}
AND name IN ('{stock_list_str}')
"""
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.style.format(format_dict)

### End of Process for specified stocks

In [11]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
"""
sql = sql % (year, quarter, select_date)
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
#df_epss_inp.style.format(format_dict)
df_epss_inp.shape

SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt
FROM epss
WHERE year = 2026 AND quarter = 2
AND publish_date >= '2026-07-01'

(174, 7)

### End of Normal Process

In [13]:
sql = """
    SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
    FROM qt_profits 
    WHERE year = :year AND quarter = :quarter
"""
params = (year, f"Q{quarter}")
print(sql)
df_qt_profits = pd.read_sql(sql, con=conlt, params=params)
df_qt_profits.shape

    SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
    FROM qt_profits
    WHERE year = :year AND quarter = :quarter

(179, 7)

In [15]:
epss_inp_qt_profits = pd.merge(df_epss_inp, df_qt_profits, on=["name"], suffixes=(["_e", "_q"]), how="inner")
epss_inp_qt_profits.tail().style.format(format_dict)

### Delete duplicated year and quarter

In [18]:
columns = ['year_q','quarter_q']
epss_inp_qt_profits = epss_inp_qt_profits.drop(columns, axis='columns')
epss_inp_qt_profits.tail().style.format(format_dict)

In [20]:
sql = '''
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM yr_profits 
WHERE year = %s AND quarter = "Q%s"'''
sql = sql % (year, quarter)
print(sql)
df_yr_profits = pd.read_sql(sql, conlt)
df_yr_profits.tail().sort_values(['inc_pct'],ascending=[False]).style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM yr_profits
WHERE year = 2026 AND quarter = "Q2"

In [22]:
df_merge2 = pd.merge(epss_inp_qt_profits, df_yr_profits, on=['name'], suffixes=(['_q','_y']), how='inner')
df_merge2.tail().style.format(format_dict)

### Delete duplicated year and quarter

In [25]:
columns = ['year_e','quarter_e']
df_aggr = df_merge2.drop(columns, axis='columns')
df_aggr.tail().style.format(format_dict)

### Profits criteria
1. Current yearly profit amount > 440 millions
2. Previous yearly profit amount > 400 millions
3. Yearly gain percent >= 10 percent

In [28]:
df_aggr[df_aggr['name'] == 'M'].style.format(format_dict)

In [30]:
criteria_1 = df_aggr.latest_amt_y > 440_000
df_aggr.loc[criteria_1, cols].tail().sort_values(by=["name"], ascending=True).style.format(format_dict)

In [32]:
criteria_2 = df_aggr.previous_amt_y >= 400_000
df_aggr.loc[criteria_2, cols].tail().sort_values(by=["name"], ascending=True).style.format(format_dict)

In [34]:
criteria_3 = df_aggr.inc_pct_y >= 10.00
df_aggr.loc[criteria_3, cols].tail().style.format(format_dict)

In [36]:
criteria_4 = (df_aggr.q_amt > df_aggr.y_amt)
colt = 'name q_amt y_amt inc_amt_q inc_pct_q'.split()
df_aggr.loc[criteria_4,colt].tail().sort_values(['inc_pct_q'],ascending=[False]).style.format(format_dict)

In [38]:
profits_criteria = criteria_1 & criteria_2 & criteria_3 & criteria_4
filter = df_aggr.loc[profits_criteria]
filter.sort_values('name').style.format(format_dict)

In [40]:
columns = 'year quarter q_amt y_amt aq_amt ay_amt'.split()
pre_final = filter.drop(columns, axis=1)
pre_final.sort_values(['name'],ascending=[True]).style.format(format_dict)

In [42]:
final = pre_final.copy()
final.style.format(format_dict)

In [44]:
final.sort_values(['name'], ascending=True).style.format(format_dict)

In [46]:
sql = '''
SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p 
FROM epss A JOIN epss B ON a.name = B.name 
WHERE A.year = %s AND A.quarter = %s 
AND B.year = %s AND B.quarter = (%s-1)'''
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p
FROM epss A JOIN epss B ON a.name = B.name
WHERE A.year = 2026 AND A.quarter = 2
AND B.year = 2026 AND B.quarter = (2-1)

In [48]:
epss2 = pd.read_sql(sql, conlt)
epss2.shape

(179, 6)

In [50]:
df_merge3 = pd.merge(final, epss2, on=['name'], suffixes=(['_f','_e']), how='inner')
df_merge3.style.format(format_dict)

### The fifth criteria, added on 2022q1

In [53]:
mask = (df_merge3.q_amt_c > df_merge3.q_amt_p)
df_merge3 = df_merge3[mask]
df_merge3.style.format(format_dict)

In [55]:
final2 = df_merge3[['name','year','quarter',\
'latest_amt_y','previous_amt_y','inc_amt_y','inc_pct_y',\
'latest_amt_q','previous_amt_q','inc_amt_q','inc_pct_q',\
'q_amt_c', 'y_amt', 'q_amt_p']].copy()               
final2.style.format(format_dict)

### If there is no record in the above statement, no need to further process

In [58]:
def better(vals):
    current, previous = vals
    if current > previous:
        return 1
    else:
        return 0

In [60]:
final2.loc[:, 'kind'] = final2[['q_amt_c', 'q_amt_p']].apply(better, axis=1)

In [62]:
final2.kind.value_counts()

kind
1    30
Name: count, dtype: int64

In [64]:
final2.loc[:, 'inc_amt_py'] = final2['q_amt_c'] - final2['y_amt']
final2.loc[:, 'inc_pct_py'] = (final2['inc_amt_py'] / abs(final2['y_amt'])) * 100

final2.loc[:, 'inc_amt_pq'] = final2['q_amt_c'] - final2['q_amt_p']
final2.loc[:, 'inc_pct_pq'] = (final2['inc_amt_pq'] / abs(final2['q_amt_p'])) * 100

In [66]:
final2.loc[:, 'inc_pct_py'] = final2['inc_pct_py'].replace('inf', np.nan)

In [68]:
final2.loc[:, 'mean_pct'] = final2[['inc_pct_y', 'inc_pct_q', 'inc_pct_py', 'inc_pct_pq']].mean(axis=1, skipna=True)

In [70]:
final2[['name','mean_pct']].sample().sort_values(['mean_pct'], ascending=False)

     name    mean_pct
31  AMATA  291.640772

In [72]:
# First ensure it's a copy
final3 = final2.copy()
# Then perform operations
final3['std_pct'] = final3[['inc_pct_y', 'inc_pct_q', 'inc_pct_py', 'inc_pct_pq']].std(axis=1)

In [74]:
final3[['name','std_pct']].tail().sort_values(['std_pct'], ascending=True)

      name     std_pct
43   SAWAD    4.035281
41  GUNKUL    9.026396
40    BKIH   14.118320
42     RBF   25.574763
45   VIBHA  142.432464

In [76]:
sql = "SELECT name, id, market FROM tickers"
lt_tickers = pd.read_sql(sql, conlt)
lt_tickers.tail().style.format(format_dict)

In [78]:
df_merge4 = pd.merge(final3, lt_tickers, on="name", how="inner")
df_merge4.rename(columns={"id": "ticker_id"}, inplace=True)

final4 = df_merge4[colv].copy()
final4.tail().style.format(format_dict)

In [80]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)

SELECT *
FROM profits
WHERE year = 2026 AND quarter = 2
ORDER BY name

In [82]:
lt_profits = pd.read_sql(sql, conlt)
lt_profits.style.format(format_dict)

In [84]:
df_merge = pd.merge(
    final4, lt_profits, on=["name", "year", "quarter"], how="outer", indicator=True
)
df_merge.sample(5).style.format(format_dict)

In [86]:
final5 = df_merge[df_merge["_merge"] == "left_only"]
final5

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,y_amt_y,inc_amt_py_y,inc_pct_py_y,q_amt_p_y,inc_amt_pq_y,inc_pct_pq_y,ticker_id_y,mean_pct_y,std_pct_y,_merge
2,AMATA,2026,2,1,5141635,2848499,2293136,80.50,5141635,3697994,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,BJC,2026,2,1,5868866,4664809,1204057,25.81,5868866,3977310,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,BKIH,2026,2,1,3923235,2883605,1039630,36.05,3923235,3634595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7,CPNREIT,2026,2,1,3438241,1718245,1719996,100.10,3438241,3362779,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
10,GUNKUL,2026,2,1,1947973,1728234,219739,12.71,1947973,1857507,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
16,PTT,2026,2,1,123580894,84420012,39160882,46.39,123580894,92589184,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
17,RBF,2026,2,1,532012,446692,85320,19.10,532012,467717,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
18,SAWAD,2026,2,1,5393842,4890951,502891,10.28,5393842,5263124,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
25,TPIPL,2026,2,1,2521083,1423631,1097452,77.09,2521083,2107706,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
26,TVO,2026,2,1,2593590,2328245,265345,11.40,2593590,2364101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
27,VIBHA,2026,2,1,1846836,448818,1398018,311.49,1846836,1805630,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [88]:
final6 = final5[colw].copy()
final6.sort_values('name')

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,q_amt_c_x,y_amt_x,inc_amt_py_x,inc_pct_py_x,q_amt_p_x,inc_amt_pq_x,inc_pct_pq_x,ticker_id_x,mean_pct_x,std_pct_x
2,AMATA,2026,2,1,5141635,2848499,2293136,80.50,5141635,3697994,...,1583508,139867,1443641,1032.152688,1378517,204991,14.870401,21,291.640772,494.417945
4,BJC,2026,2,1,5868866,4664809,1204057,25.81,5868866,3977310,...,2881532,989976,1891556,191.070895,1057374,1824158,172.517766,65,109.239665,84.587939
5,BKIH,2026,2,1,3923235,2883605,1039630,36.05,3923235,3634595,...,1244466,955826,288640,30.197965,1129143,115323,10.213321,68,21.100321,14.118320
7,CPNREIT,2026,2,1,3438241,1718245,1719996,100.10,3438241,3362779,...,893491,818029,75462,9.224856,809381,84110,10.391892,647,30.489187,46.546589
10,GUNKUL,2026,2,1,1947973,1728234,219739,12.71,1947973,1857507,...,574990,484524,90466,18.671108,455763,119227,26.159868,202,15.602744,9.026396
16,PTT,2026,2,1,123580894,84420012,39160882,46.39,123580894,92589184,...,52524592,21532882,30991710,143.927367,25738299,26786293,104.071730,383,81.964774,51.463217
17,RBF,2026,2,1,532012,446692,85320,19.10,532012,467717,...,161180,96885,64295,66.362182,141930,19250,13.563024,703,28.193801,25.574763
18,SAWAD,2026,2,1,5393842,4890951,502891,10.28,5393842,5263124,...,1400758,1270040,130718,10.292432,1342077,58681,4.372402,423,6.856208,4.035281
25,TPIPL,2026,2,1,2521083,1423631,1097452,77.09,2521083,2107706,...,974626,561249,413377,73.653049,832438,142188,17.080912,559,46.858490,32.970072
26,TVO,2026,2,1,2593590,2328245,265345,11.40,2593590,2364101,...,877107,647618,229489,35.435859,708925,168182,23.723525,585,20.067346,11.999394
27,VIBHA,2026,2,1,1846836,448818,1398018,311.49,1846836,1805630,...,256778,215572,41206,19.114727,136719,120059,87.814422,610,105.174787,142.432464

In [90]:
rcds = final6.values.tolist()
len(rcds)

11

In [92]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)
lt_profits = pd.read_sql(sql, conlt)
lt_profits.style.format(format_dict)

SELECT *
FROM profits
WHERE year = 2026 AND quarter = 2
ORDER BY name

In [94]:
# 1. First replace inf in the DataFrame
lt_profits['inc_pct_py'] = lt_profits['inc_pct_py'].replace([np.inf, -np.inf], 999.99)
lt_profits['mean_pct'] = lt_profits['mean_pct'].replace([np.inf, -np.inf], 999.99)

# Now when you print rcds, you'll see 999.99 instead of inf
lt_profits.style.format(format_dict)

In [96]:
# Define SQL statement using named placeholders
sql = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]

records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]

# Check for empty records before attempting insertion
if not rcds:
    print("No records to insert - skipping database operation")
    # In notebook/script context, just proceed to next cell instead of 'return'
else:
    try:
        # Convert list data to dictionaries for named parameters
#        records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]
        conlt.execute(sql, records_dicts)
        conlt.commit()
        print(f"Successfully inserted {len(records_dicts)} records")
    except Exception as e:
        conlt.rollback()
        print("Insert failed:", e)
    finally:
        conlt.commit()

Successfully inserted 11 records

In [98]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
lt_profits = pd.read_sql(sql, conlt)
lt_profits.style.format(format_dict)

### End of Create Data

In [101]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y:%m:%d %H:%M:%S")
print(formatted_time)

2026:08:22 11:23:57