In [3]:
import pandas as pd
from sqlalchemy import create_engine
from glob import glob

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

output_path = "../excel/"
csv_path = "\\Users\\User\\iCloudDrive\\"
one_path = "\\Users\\User\\OneDrive\\Documents\\Data\\"
osd_path = "\\Users\\User\\OneDrive\\Documents\\obsidian-git-sync\\Data\\"

data_path = "../data/"
irreg_path = "../data/irreg/"

In [5]:
year = 2026
quarter = 2
year, quarter

(2026, 2)

### Begin of Irregular quarter

### Irregular Quarter Plus 1

In [9]:
file_name = 'P1-Stocks.csv'
input_file = irreg_path + file_name
# Read with header=0 (default) to use first row as column names
df_P1 = pd.read_csv(input_file)
# Now data_ins will have the actual column name (probably 'name' or something else)
df_P1

      name
0      AOT
1     CITY
2      FPT
3   GVREIT
4      IRC
5     KTIS
6       MC
7    OISHI
8     PICO
9      SSC
10   TFFIF
11      UV

In [11]:
sql = "SELECT * FROM exempts"
df_exempts = pd.read_sql(sql, conlt)
df_exempts.shape

(427, 2)

In [13]:
df_exempts.dtypes

id       int64
name    object
dtype: object

In [17]:
df_merge = pd.merge(df_P1,df_exempts,on='name',how='inner')
df_merge

   name   id
0  CITY  576
1   IRC  646
2  KTIS  668
3  PICO  727
4   SSC  808
5    UV  894

### Irregular Quarter Minus 1

In [22]:
file_name   = 'M1-Stocks.csv'
input_file = irreg_path + file_name
# Read with header=0 (default) to use first row as column names
df_M1 = pd.read_csv(input_file)
df_M1

      name
0   AEONTS
1      BCT
2    BLAND
3      BTS
4   BTSGIF
5      EPG
6   IMPACT
7      KYE
8      LHK
9      LPF
10    MACO
11     PTL
12     SFP
13  STANLY
14    TIF1
15    TLGF
16     TMW
17      TR
18    TSTH
19     VGI

In [24]:
df_merge2 = pd.merge(df_M1,df_exempts,on='name',how='inner')
df_merge2

     name   id
0     BCT  919
1     KYE  923
2     LHK  925
3     SFP  783
4  STANLY  932
5    TIF1  843
6     TMW  935

# END OF PROCESS