## Restart and Run All

In [2]:
import pandas as pd
import os
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2025"
quarter = "3"
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-02-15 10:01:31

In [4]:
sql = """
SELECT * 
FROM epss 
WHERE year = %s AND quarter = %s
ORDER BY publish_date DESC LIMIT 2
"""
sql = sql % (year, quarter)
print(sql)

df_tmp = pd.read_sql(sql, conlt)
df_tmp

SELECT *
FROM epss
WHERE year = 2025 AND quarter = 3
ORDER BY publish_date DESC LIMIT 2

,id,name,year,quarter,q_amt,y_amt,aq_amt,ay_amt,q_eps,y_eps,aq_eps,ay_eps,ticker_id,publish_date
0,24919,TR,2025,3,-800652,622431,-1641424,18792,-3.97,3.09,-8.14,0.09,564,2026-02-13
1,24921,BTSGIF,2025,3,-58825,491903,31515,1173557,0.00,0.00,0.00,0.00,84,2026-02-13

In [6]:
today = date(2026, 1, 1)
select_date = today.strftime("%Y-%m-%d")
select_date

'2026-01-01'

### Tables in the process

In [9]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")
#C:\Users\PC1\OneDrive\A5\Excel
xsl_path = os.path.join(base_path, "Excel")

In [11]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Excel path (xsl_path): {xsl_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Excel path (xsl_path): C:\Users\PC1\OneDrive\A4\Excel
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [13]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()

format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:,.2f}%','acc_pct':'{:,.2f}%'
              }

In [15]:
sql = """
SELECT * 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
ORDER BY id DESC
"""
sql = sql % (year, quarter, select_date)
print(sql)

df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.tail().style.format(format_dict)

SELECT *
FROM epss
WHERE year = 2025 AND quarter = 3
AND publish_date >= '2026-01-01'
ORDER BY id DESC

In [17]:
df_epss_inp["yoy_gain"] = df_epss_inp["q_amt"] - df_epss_inp["y_amt"]
df_epss_inp["yoy_pct"] = round(df_epss_inp["yoy_gain"] / abs(df_epss_inp["y_amt"]) * 100, 2)
df_epss_inp["acc_gain"] = df_epss_inp["aq_amt"] - df_epss_inp["ay_amt"]
df_epss_inp["acc_pct"] = round(df_epss_inp["acc_gain"] / abs(df_epss_inp["ay_amt"]) * 100,2)

df_aggr = df_epss_inp[colt]
df_aggr.tail().style.format(format_dict)

In [19]:
criteria_1 = df_aggr.q_amt > 110_000
df_aggr.loc[criteria_1,cols].style.format(format_dict)

In [21]:
criteria_2 = df_aggr.y_amt > 100_000
df_aggr.loc[criteria_2, cols].style.format(format_dict)

In [23]:
criteria_3 = df_aggr.yoy_pct > 10.00
df_aggr.loc[criteria_3, cols].style.format(format_dict)

In [25]:
df_aggr_criteria = criteria_1 & criteria_2 & criteria_3
#df_aggr_criteria = criteria_1 & criteria_3 
df_aggr.loc[df_aggr_criteria, cols].style.format(format_dict)

In [27]:
df_aggr[df_aggr_criteria].sort_values(by=["name"], ascending=[True]).style.format(format_dict)

In [29]:
names = df_epss_inp['name']
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'TMW', 'BTSGIF', 'TR', 'LHK', 'BLAND', 'KYE', 'IMPACT', 'PTL', 'VGI', 'EPG', 'TSTH', 'STANLY'"

### If new records pass filter criteria then proceed to create quarterly profits process.

In [32]:
sql = """
SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name 
WHERE E.name IN (%s)
ORDER BY E.name, year DESC, quarter DESC 
LIMIT 12
"""
sql = sql % (in_p)
print(sql)

epss_stocks = pd.read_sql(sql, conlt)
epss_stocks.style.format(format_dict)

SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name
WHERE E.name IN ('TMW', 'BTSGIF', 'TR', 'LHK', 'BLAND', 'KYE', 'IMPACT', 'PTL', 'VGI', 'EPG', 'TSTH', 'STANLY')
ORDER BY E.name, year DESC, quarter DESC
LIMIT 12

### Delete from profits of older profit stocks

In [35]:
in_p

"'TMW', 'BTSGIF', 'TR', 'LHK', 'BLAND', 'KYE', 'IMPACT', 'PTL', 'VGI', 'EPG', 'TSTH', 'STANLY'"

In [37]:
sqlDel = text("""
    DELETE FROM profits 
    WHERE name IN ({})
    AND quarter < :quarter
""".format(in_p))

# Execute with parameters
rp = conlt.execute(sqlDel, {'quarter': quarter})
rp.rowcount

0

In [39]:
rp = conmy.execute(sqlDel, {'quarter': quarter})
rp.rowcount

0

In [41]:
rp = conpg.execute(sqlDel, {'quarter': quarter})
rp.rowcount

0

In [43]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
lt_profits = pd.read_sql(sql, conlt)
lt_profits.set_index("name", inplace=True)
lt_profits.index

Index(['3BBIF', 'ACE', 'ADVANC', 'AMATA', 'BA', 'BCP', 'BGRIM', 'BKIH', 'BLA',
       'CENTEL', 'CK', 'CKP', 'FPT', 'GFPT', 'KKP', 'MTC', 'PCSGH', 'RCL',
       'SCGP', 'SSP', 'SYNEX', 'THANI', 'TOA', 'TTA', 'TTW'],
      dtype='object', name='name')

In [45]:
my_profits = pd.read_sql(sql, conmy)
my_profits.set_index("name", inplace=True)
my_profits.index

Index(['2842', '2843', '2844', '2845', '2846', 'BAM', 'BLA', 'CBG', 'CK',
       'CKP', 'CKP', 'COM7', 'FPT', 'GFPT', 'GULF', 'GUNKUL', 'MTC', 'RCL',
       'SYNEX', 'TTW', 'TVO'],
      dtype='object', name='name')

In [47]:
pg_profits = pd.read_sql(sql, conpg)
pg_profits.set_index("name", inplace=True)
pg_profits.index

Index(['ACE', 'AMATA', 'BA', 'BGRIM', 'BKIH', 'BLA', 'CENTEL', 'CK', 'CKP',
       'FPT', 'GFPT', 'MTC', 'PCSGH', 'RCL', 'SSP', 'SYNEX', 'THANI', 'TOA',
       'TTA', 'TTW'],
      dtype='object', name='name')

### Portfolio that publish today

In [50]:
sql = """
SELECT * 
FROM tickers
WHERE name IN (%s)
ORDER BY name"""
sql = sql % in_p
print(sql)

pg_tickers = pd.read_sql(sql, conpg)
pg_tickers[['name','id']].sort_values(by=[ "name"], ascending=[True])

SELECT *
FROM tickers
WHERE name IN ('TMW', 'BTSGIF', 'TR', 'LHK', 'BLAND', 'KYE', 'IMPACT', 'PTL', 'VGI', 'EPG', 'TSTH', 'STANLY')
ORDER BY name

      name   id
0    BLAND   74
1   BTSGIF   87
2      EPG  166
3   IMPACT  228
4      KYE  270
5      LHK  278
6      PTL  388
7   STANLY  490
8      TMW  554
9       TR  573
10    TSTH  587
11     VGI  618

In [52]:
sql = """
SELECT name 
FROM buy
"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(29, 1)

In [54]:
df_merge = pd.merge(pg_tickers, df_buy, on='name', how='inner')
df_merge

Empty DataFrame
Columns: [id, name, full_name, sector, subsector, market, website, created_at, updated_at]
Index: []

In [56]:
file_name = 'pub_stock.xlsx'
xsl_file = xsl_path + '\\' + file_name
df_merge[['id','name','sector','market']].to_excel(xsl_file, index=False)

### Portfolio that already published

In [59]:
	names = df_buy["name"].values.tolist()
	in_p = ", ".join(map(lambda name: "'%s'" % name, names))
	in_p

"'3BBIF', 'AH', 'AIMIRT', 'AWC', 'BCH', 'CPF', 'CPNREIT', 'DIF', 'GVREIT', 'IVL', 'JMART', 'JMT', 'MCS', 'NER', 'ORI', 'PTG', 'PTT', 'PTTGC', 'RCL', 'SCC', 'SENA', 'SINGER', 'STA', 'SYNEX', 'TFFIF', 'TOA', 'TVO', 'WHAIR', 'WHART'"

In [61]:
sql = """
SELECT *
FROM epss
WHERE publish_date >= '%s'
AND name IN (%s)
ORDER BY publish_date DESC, name"""
sql = sql % (select_date, in_p)
df_tmp = pd.read_sql(sql, conlt)
df_tmp.style.format(format_dict)

In [63]:
conlt.commit()
conlt.close()