In [1]:
import os
import pandas as pd
from datetime import date, datetime, timedelta
from sqlalchemy import create_engine, text
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2026"
quarter = "3"

today = date.today()
print(today)

2026-10-24

In [5]:
# If run after actual work day
today = today - timedelta(days=2)
print(today)

2026-10-22

In [7]:
num_business_days = BDay(1)
yesterday = today - num_business_days
yesterday = yesterday.date()
print(today, yesterday)

2026-10-22 2026-10-21

### Tables in the process

In [11]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [13]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [15]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()
format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}','qty':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%','unit_cost':'{:.2f}%'
              }

In [18]:
select_date = date(2026, 10, 14)
select_date = select_date.strftime("%Y-%m-%d")
select_date

'2026-10-14'

In [20]:
sql = '''
SELECT * 
FROM epss 
WHERE year = %s AND quarter >= %s
AND publish_date >= "%s"
ORDER BY name'''
sql = sql % (year, quarter, select_date)
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.tail().style.format(format_dict)

SELECT *
FROM epss
WHERE year = 2026 AND quarter >= 3
AND publish_date >= "2026-10-14"
ORDER BY name

In [22]:
df_epss_inp.shape

(8, 14)

In [24]:
df_epss_inp["yoy_gain"] = df_epss_inp["q_amt"] - df_epss_inp["y_amt"]
df_epss_inp["yoy_pct"]  = round(df_epss_inp["yoy_gain"] / abs(df_epss_inp["y_amt"]) * 100,2)
df_epss_inp["acc_gain"] = df_epss_inp["aq_amt"] - df_epss_inp["ay_amt"]
df_epss_inp["acc_pct"] = round(df_epss_inp["acc_gain"] / abs(df_epss_inp["ay_amt"]) * 100,2)
df_aggr = df_epss_inp[
    [
        "name",
        "year",
        "quarter",
        "q_amt",
        "y_amt",
        "yoy_gain",
        "yoy_pct",
        "aq_amt",
        "ay_amt",
        "acc_gain",
        "acc_pct",
    ]
]
df_aggr.tail().style.format(format_dict)

In [26]:
df_aggr.shape

(8, 11)

In [28]:
names = df_epss_inp['name']
portfolio = ", ".join(map(lambda name: "'%s'" % name, names))
portfolio

"'BBL', 'KBANK', 'KKP', 'KTB', 'KTC', 'SCB', 'TISCO', 'TTB'"

### Portfolio that publish today

In [31]:
sql = """
    SELECT name, id AS ticker_id
    FROM tickers
    WHERE name IN ({})
    ORDER BY name
""".format(portfolio)
print(sql)

pg_tickers = pd.read_sql(sql, conpg)
pg_tickers[['name','ticker_id']].sort_values(by=[ "name"], ascending=[True])

    SELECT name, id AS ticker_id
    FROM tickers
    WHERE name IN ('BBL', 'KBANK', 'KKP', 'KTB', 'KTC', 'SCB', 'TISCO', 'TTB')
    ORDER BY name

    name  ticker_id
0    BBL         54
1  KBANK        253
2    KKP        262
3    KTB        265
4    KTC        266
5    SCB        432
6  TISCO        539
7    TTB        549

In [33]:
df_merge1 = pd.merge(df_aggr, pg_tickers, on='name', how='inner')
df_merge1.head().style.format(format_dict)

In [35]:
df_merge1.dtypes

name          object
year           int64
quarter        int64
q_amt          int64
y_amt          int64
yoy_gain       int64
yoy_pct      float64
aq_amt         int64
ay_amt         int64
acc_gain       int64
acc_pct      float64
ticker_id      int64
dtype: object

In [37]:
sql = """
    SELECT name, date AS pur_date, volbuy AS qty, price AS unit_cost, dividend, period, grade
    FROM buy
"""
df_buy = pd.read_sql(sql, const)
df_buy.shape

(29, 7)

In [39]:
df_buy.dtypes

name          object
pur_date      object
qty          float64
unit_cost    float64
dividend     float64
period        object
grade         object
dtype: object

In [41]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()
format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}',
                'qty':'{:,}','volbuy':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%','percent':'{:.2f}%','yield':'{:.2f}%',
                'unit_cost':'{:.2f}','buy_price':'{:.2f}','mkt_price':'{:.2f}','amtcst':'{:,.2f}','amtmkt':'{:,.2f}','amtpol':'{:,.2f}'
              }

In [43]:
sqlPrice = """SELECT name, date, price, maxp, minp, opnp, qty AS volume FROM price LIMIT 1"""
df_price = pd.read_sql(sqlPrice, const)
df_price

    name        date  price  maxp  minp  opnp   volume
0  JMART  2019-04-01    8.1   8.3  8.05  8.05  2971120

In [45]:
sql = """SELECT buy.name AS name, buy.date AS date, volbuy AS qty,
				buy.price AS buy_price, price.price AS mkt_price,
                volbuy * buy.price AS amtcst, 
				volbuy * price.price AS amtmkt, 
				(price.price - buy.price) * volbuy AS amtpol,
				(price.price - buy.price)*volbuy/(volbuy*buy.price)*100 AS percent, dividend, 
                dividend*qty/(qty*price.price)*100 AS yield,
                period, grade
          FROM buy INNER JOIN price ON buy.name = price.name
          WHERE price.date = '%s'
          ORDER BY period, name"""
sql = sql % (yesterday)
print(sql)

SELECT buy.name AS name, buy.date AS date, volbuy AS qty,
				buy.price AS buy_price, price.price AS mkt_price,
                volbuy * buy.price AS amtcst,
				volbuy * price.price AS amtmkt,
				(price.price - buy.price) * volbuy AS amtpol,
				(price.price - buy.price)*volbuy/(volbuy*buy.price)*100 AS percent, dividend,
                dividend*qty/(qty*price.price)*100 AS yield,
                period, grade
          FROM buy INNER JOIN price ON buy.name = price.name
          WHERE price.date = '2026-10-21'
          ORDER BY period, name

In [47]:
df_buy = pd.read_sql(sql, const)
# Convert all columns that should be integers
int_columns = ['qty','period']  # Add other columns like 'period' if needed
df_buy[int_columns] = df_buy[int_columns].astype(int)

In [49]:
df_buy.dtypes

name          object
date          object
qty            int32
buy_price    float64
mkt_price    float64
amtcst       float64
amtmkt       float64
amtpol       float64
percent      float64
dividend     float64
yield        float64
period         int32
grade         object
dtype: object

In [51]:
df_buy.head().style.format(format_dict)

In [53]:
df_merge1 = pd.merge(df_aggr, df_buy, on='name', how='inner')
df_merge1.head().style.format(format_dict)

In [55]:
df_merge1.dtypes

name          object
year           int64
quarter        int64
q_amt          int64
y_amt          int64
yoy_gain       int64
yoy_pct      float64
aq_amt         int64
ay_amt         int64
acc_gain       int64
acc_pct      float64
date          object
qty            int32
buy_price    float64
mkt_price    float64
amtcst       float64
amtmkt       float64
amtpol       float64
percent      float64
dividend     float64
yield        float64
period         int32
grade         object
dtype: object

In [57]:
df_merge2 = pd.merge(df_merge1, pg_tickers, on='name', how='inner')
df_merge2.style.format(format_dict)

In [59]:
df_merge2.dtypes

name          object
year           int64
quarter        int64
q_amt          int64
y_amt          int64
yoy_gain       int64
yoy_pct      float64
aq_amt         int64
ay_amt         int64
acc_gain       int64
acc_pct      float64
date          object
qty            int32
buy_price    float64
mkt_price    float64
amtcst       float64
amtmkt       float64
amtpol       float64
percent      float64
dividend     float64
yield        float64
period         int32
grade         object
ticker_id      int64
dtype: object

In [61]:
file_name = 'stocks-in-port.xlsx'
output_file = os.path.join(dat_path, file_name)
print(f"Output file : {output_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\stocks-in-port.xlsx

In [63]:
df_merge2.to_excel(output_file, index=False)

In [65]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2026-10-24 20:32:23