In [3]:
sql = """
SELECT * 
FROM epss 
WHERE year = %s AND quarter = %s
ORDER BY publish_date ASC LIMIT 2
"""
sql = sql % (year, quarter)
print(sql)

df_tmp = pd.read_sql(sql, conlt)
df_tmp

SELECT *
FROM epss
WHERE year = 2025 AND quarter = 3
ORDER BY publish_date ASC LIMIT 2

,id,name,year,quarter,q_amt,y_amt,aq_amt,ay_amt,q_eps,y_eps,aq_eps,ay_eps,ticker_id,publish_date
0,24354,MC,2025,3,188485,164658,625659,576728,0.24,0.21,0.79,0.73,291,2025-05-14
1,24533,AOT,2025,3,3864797,4562722,14262366,14910347,0.27,0.32,1.00,1.04,24,2025-08-13

In [1]:
import numpy as np
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text
engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

year = 2025
quarter = 3
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time )

2025-11-30 11:27:37

In [5]:
# Must modify select date to latest unprocess date
select_date = date(2025, 10, 24)
select_date = select_date.strftime("%Y-%m-%d")
select_date

'2025-10-24'

In [7]:
cols = "name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y".split()
colt = "year quarter q_amt y_amt aq_amt ay_amt".split()
colu = 'name year quarter latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt q_amt_p'.split() 
colv = 'name year quarter kind latest_amt_y previous_amt_y inc_amt_y inc_pct_y \
        latest_amt_q previous_amt_q inc_amt_q inc_pct_q q_amt_c y_amt \
        inc_amt_py inc_pct_py q_amt_p inc_amt_pq inc_pct_pq \
        ticker_id mean_pct std_pct'.split()
colw = 'name year quarter kind_x latest_amt_y_x previous_amt_y_x inc_amt_y_x inc_pct_y_x \
        latest_amt_q_x previous_amt_q_x inc_amt_q_x inc_pct_q_x q_amt_c_x y_amt_x \
        inc_amt_py_x inc_pct_py_x q_amt_p_x inc_amt_pq_x inc_pct_pq_x \
        ticker_id_x mean_pct_x std_pct_x'.split()

format_dict = {
    "q_amt": "{:,}",
    "y_amt": "{:,}",
    "yoy_gain": "{:,}",
    "q_amt_c": "{:,}",
    "q_amt_p": "{:,}",
    "aq_amt": "{:,}",
    "ay_amt": "{:,}",
    "acc_gain": "{:,}",
    "latest_amt": "{:,}",
    "previous_amt": "{:,}",
    "inc_amt": "{:,}",
    "inc_amt_pq": "{:,}",
    "inc_amt_py": "{:,}",    
    "latest_amt_q": "{:,}",
    "previous_amt_q": "{:,}",
    "inc_amt_q": "{:,}",
    "latest_amt_y": "{:,}",
    "previous_amt_y": "{:,}",
    "inc_amt_y": "{:,}",
    "kind_x": "{:,}",
    "inc_pct": "{:.2f}%",
    "inc_pct_q": "{:.2f}%",
    "inc_pct_y": "{:.2f}%",
    "inc_pct_pq": "{:.2f}%",
    "inc_pct_py": "{:.2f}%",   
    "mean_pct": "{:.2f}%",
    "std_pct": "{:.2f}%",      
}

### Process for specified stocks

In [1]:
names = """
SINGER
""".split()
names

['SINGER']

In [3]:
stock_list = names
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

SINGER

In [8]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = {year} AND quarter = {quarter}
AND name IN ('{stock_list_str}')
"""
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.style.format(format_dict)

### End of Process for specified stocks

In [9]:
sql = """
SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
"""
sql = sql % (year, quarter, select_date)
print(sql)
df_epss_inp = pd.read_sql(sql, conlt)
df_epss_inp.tail().style.format(format_dict)

SELECT name,year,quarter,q_amt,y_amt,aq_amt,ay_amt
FROM epss
WHERE year = 2025 AND quarter = 3
AND publish_date >= '2025-10-24'

### End of Normal Process

In [12]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM qt_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
df_qt_profits = pd.read_sql(sql, conlt)
df_qt_profits.tail().style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM qt_profits
WHERE year = 2025 AND quarter = 'Q3'

In [14]:
df_merge = pd.merge(df_epss_inp, df_qt_profits, on=["name"], suffixes=(["_e", "_q"]), how="inner")
df_merge.head().style.format(format_dict)

### Delete duplicated year and quarter

In [16]:
columns = ["year_q", "quarter_q"]
epss_inp_qt_profits = df_merge.drop(columns, axis=1)
epss_inp_qt_profits.tail().style.format(format_dict)

In [18]:
sql = """
SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct 
FROM yr_profits 
WHERE year = %s AND quarter = 'Q%s'
"""
sql = sql % (year, quarter)
print(sql)
df_yr_profits = pd.read_sql(sql, conlt)
df_yr_profits.tail().style.format(format_dict)

SELECT name, year, quarter, latest_amt, previous_amt, inc_amt, inc_pct
FROM yr_profits
WHERE year = 2025 AND quarter = 'Q3'

In [20]:
df_merge2 = pd.merge(
    epss_inp_qt_profits, df_yr_profits, on=["name"], suffixes=(["_q", "_y"]), how="inner"
)
df_merge2.head(7).style.format(format_dict)

### Delete duplicated year and quarter

In [23]:
columns = ["year_e", "quarter_e"]
df_aggr = df_merge2.drop(columns, axis=1)
df_aggr.head().style.format(format_dict)

### profits criteria
1. Yearly profit amount > 440 millions
2. Previous yearly gain amount > 400 millions
3. Yearly gain percent >= 10 percent

### Must manually select interested stock name

In [27]:
df_aggr[df_aggr["name"] == "MCS"].style.format(format_dict)

In [29]:
criteria_1 = df_aggr.latest_amt_y > 440_000
df_aggr.loc[criteria_1, cols].sort_values(by=["name"], ascending=True).tail().style.format(format_dict)

In [31]:
criteria_2 = df_aggr.previous_amt_y >= 400_000
df_aggr.loc[criteria_2, cols].sort_values(by=["name"], ascending=True).tail().style.format(format_dict)

In [33]:
criteria_3 = df_aggr.inc_pct_y >= 10.00
df_aggr.loc[criteria_3, cols].tail().style.format(format_dict)

In [35]:
df_aggr_criteria = criteria_1 & criteria_2 & criteria_3
#df_aggr_criteria = criteria_1 & criteria_2 
filter = df_aggr.loc[df_aggr_criteria]
filter.sort_values('name').tail().style.format(format_dict)

### If there is no record, not necessary to run the rest

In [38]:
final = filter.drop(colt, axis=1)
final.tail().style.format(format_dict)

In [40]:
final.sort_values(by=["name"], ascending=True).tail().style.format(format_dict)

In [42]:
sql = """
SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p 
FROM epss A JOIN epss B ON a.name = B.name 
WHERE A.year = %s AND A.quarter = %s 
AND B.year = %s AND B.quarter = (%s-1)"""
sql = sql % (year, quarter, year, quarter)
print(sql)

SELECT A.name,A.year,A.quarter,A.q_amt AS q_amt_c,A.y_amt,B.q_amt AS q_amt_p
FROM epss A JOIN epss B ON a.name = B.name
WHERE A.year = 2025 AND A.quarter = 3
AND B.year = 2025 AND B.quarter = (3-1)

In [44]:
epss2 = pd.read_sql(sql, conlt)
epss2.head().tail().style.format(format_dict)

In [46]:
df_merge3 = pd.merge(final, epss2, on=["name"], suffixes=(["_f", "_e"]), how="inner")
df_merge3.tail().style.format(format_dict)

### The fifth criteria, added on 2022q1

In [49]:
mask = (df_merge3.q_amt_c > df_merge3.q_amt_p)
df_merge3 = df_merge3[mask]
df_merge3

,name,latest_amt_q,previous_amt_q,inc_amt_q,inc_pct_q,latest_amt_y,previous_amt_y,inc_amt_y,inc_pct_y,year,quarter,q_amt_c,y_amt,q_amt_p
4,RCL,9681980,11472607,-1790627,-15.61,9681980,5280406,4401574,83.36,2025,3,2300555,4091182,2004879
6,CKP,2491436,2412207,79229,3.28,2491436,1346529,1144907,85.03,2025,3,1270148,1190919,610152
9,MTC,6484813,6251924,232889,3.73,6484813,5675828,808985,14.25,2025,3,1723953,1491064,1647011
11,AMATA,3130606,2757200,373406,13.54,3130606,2142951,987655,46.09,2025,3,1138536,765130,139867
12,TTW,3190977,3130292,60685,1.94,3190977,2857325,333652,11.68,2025,3,976211,915526,796563
13,GFPT,2378968,2205364,173604,7.87,2378968,2001260,377708,18.87,2025,3,715408,541804,642113
14,BA,3648593,3278894,369699,11.28,3648593,2910875,737718,25.34,2025,3,1040922,671223,401749
18,BLA,7271185,5579492,1691693,30.32,7271185,3027476,4243709,140.17,2025,3,2305941,1497610,2128385
21,TOA,2523302,2023474,499828,24.70,2523302,2013648,509654,25.31,2025,3,687726,187898,651794
22,SYNEX,723427,694197,29230,4.21,723427,628765,94662,15.06,2025,3,198138,168908,190158
25,TTA,2303219,711450,1591769,223.74,2303219,462798,1840421,397.67,2025,3,502910,1088859,90105
29,PCSGH,680862,623891,56971,9.13,680862,495395,185467,37.44,2025,3,132602,75631,116942
32,CK,2712981,1981824,731157,36.89,2712981,1773101,939880,53.01,2025,3,1738865,1007708,862763
33,CENTEL,1685602,1688337,-2735,-0.16,1685602,1510544,175058,11.59,2025,3,160361,163096,110343
34,BGRIM,1968731,1610483,358248,22.24,1968731,1233128,735603,59.65,2025,3,520997,162749,6846
35,ACE,839069,738812,100257,13.57,839069,750207,88862,11.84,2025,3,210777,110520,148794
36,ADVANC,42863183,39612451,3250732,8.21,42863183,32818977,10044206,30.60,2025,3,12038861,8788129,10981885
37,BKIH,3386810,3001468,385342,12.84,3386810,2761710,625100,22.63,2025,3,1121712,1144725,955826
40,OR,12224912,8001908,4223004,52.77,12224912,4843875,7381037,152.38,2025,3,2614259,-1608745,2231799
41,SSP,650095,652019,-1924,-0.30,650095,566446,83649,14.77,2025,3,111736,113660,-13732
42,THANI,955604,734770,220834,30.05,955604,838723,116881,13.94,2025,3,300620,79786,278679

In [51]:
final2 = df_merge3[colu].copy()
final2.style.format(format_dict)

### If there is no record in the above statement, no need to further process

In [54]:
def better(vals):
    current, previous = vals
    if current > previous:
        return 1
    else:
        return 0

In [56]:
final2.loc[:, "kind"] = final2[["q_amt_c", "q_amt_p"]].apply(better, axis=1)

In [58]:
final2.kind.value_counts()

kind
1    21
Name: count, dtype: int64

In [60]:
final2.loc[:, "inc_amt_py"] = final2["q_amt_c"] - final2["y_amt"]
final2.loc[:, "inc_pct_py"] = final2["inc_amt_py"] / abs(final2["y_amt"]) * 100

final2.loc[:, "inc_amt_pq"] = final2["q_amt_c"] - final2["q_amt_p"]
final2.loc[:, "inc_pct_pq"] = final2["inc_amt_pq"] / abs(final2["q_amt_p"]) * 100

In [62]:
final2.loc[:, 'inc_pct_py'] = final2['inc_pct_py'].replace('inf', np.nan)

In [64]:
final2.loc[:, 'mean_pct'] = final2[['inc_pct_y', 'inc_pct_q', 'inc_pct_py', 'inc_pct_pq']].mean(axis=1, skipna=True)

In [66]:
final2[['name','mean_pct']].sample().sort_values(['mean_pct'], ascending=False)

     name   mean_pct
22  SYNEX  10.192947

In [68]:
# First ensure it's a copy
final3 = final2.copy()
# Then perform operations
final3['std_pct'] = final3[['inc_pct_y', 'inc_pct_q', 'inc_pct_py', 'inc_pct_pq']].std(axis=1)

In [70]:
final3[['name','std_pct']].sample().sort_values(['std_pct'], ascending=True)

      name    std_pct
36  ADVANC  14.609526

In [72]:
sql = "SELECT name, id FROM tickers"
lt_tickers = pd.read_sql(sql, conlt)
lt_tickers.head().style.format(format_dict)

In [74]:
df_merge4 = pd.merge(final3, lt_tickers, on="name", how="inner")
df_merge4.rename(columns={"id": "ticker_id"}, inplace=True)

final4 = df_merge4[colv].copy()
final4.style.format(format_dict)

In [76]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)

SELECT *
FROM profits
WHERE year = 2025 AND quarter = 3
ORDER BY name

In [78]:
lt_profits = pd.read_sql(sql, conlt)
lt_profits.style.format(format_dict)

In [80]:
df_merge = pd.merge(
    final4, lt_profits, on=["name", "year", "quarter"], how="outer", indicator=True
)
df_merge.head().style.format(format_dict)

In [82]:
final5 = df_merge[df_merge["_merge"] == "left_only"]
final5

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,y_amt_y,inc_amt_py_y,inc_pct_py_y,q_amt_p_y,inc_amt_pq_y,inc_pct_pq_y,ticker_id_y,mean_pct_y,std_pct_y,_merge
0,ACE,2025,3,1.0,839069.0,750207.0,88862.0,11.84,839069.0,738812.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,ADVANC,2025,3,1.0,42863183.0,32818977.0,10044206.0,30.60,42863183.0,39612451.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,AMATA,2025,3,1.0,3130606.0,2142951.0,987655.0,46.09,3130606.0,2757200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,BA,2025,3,1.0,3648593.0,2910875.0,737718.0,25.34,3648593.0,3278894.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,BGRIM,2025,3,1.0,1968731.0,1233128.0,735603.0,59.65,1968731.0,1610483.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,BKIH,2025,3,1.0,3386810.0,2761710.0,625100.0,22.63,3386810.0,3001468.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
6,BLA,2025,3,1.0,7271185.0,3027476.0,4243709.0,140.17,7271185.0,5579492.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7,CENTEL,2025,3,1.0,1685602.0,1510544.0,175058.0,11.59,1685602.0,1688337.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
8,CK,2025,3,1.0,2712981.0,1773101.0,939880.0,53.01,2712981.0,1981824.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
11,GFPT,2025,3,1.0,2378968.0,2001260.0,377708.0,18.87,2378968.0,2205364.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,MTC,2025,3,1.0,6484813.0,5675828.0,808985.0,14.25,6484813.0,6251924.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
13,OR,2025,3,1.0,12224912.0,4843875.0,7381037.0,152.38,12224912.0,8001908.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
14,PCSGH,2025,3,1.0,680862.0,495395.0,185467.0,37.44,680862.0,623891.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
16,SSP,2025,3,1.0,650095.0,566446.0,83649.0,14.77,650095.0,652019.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
17,SYNEX,2025,3,1.0,723427.0,628765.0,94662.0,15.06,723427.0,694197.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
18,THANI,2025,3,1.0,955604.0,838723.0,116881.0,13.94,955604.0,734770.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
19,TOA,2025,3,1.0,2523302.0,2013648.0,509654.0,25.31,2523302.0,2023474.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
20,TTA,2025,3,1.0,2303219.0,462798.0,1840421.0,397.67,2303219.0,711450.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
21,TTW,2025,3,1.0,3190977.0,2857325.0,333652.0,11.68,3190977.0,3130292.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [84]:
final6 = final5[colw].copy()
final6.sort_values('name')

,name,year,quarter,kind_x,latest_amt_y_x,previous_amt_y_x,inc_amt_y_x,inc_pct_y_x,latest_amt_q_x,previous_amt_q_x,...,q_amt_c_x,y_amt_x,inc_amt_py_x,inc_pct_py_x,q_amt_p_x,inc_amt_pq_x,inc_pct_pq_x,ticker_id_x,mean_pct_x,std_pct_x
0,ACE,2025,3,1.0,839069.0,750207.0,88862.0,11.84,839069.0,738812.0,...,210777.0,110520.0,100257.0,90.713898,148794.0,61983.0,41.656922,698.0,39.445205,36.810072
1,ADVANC,2025,3,1.0,42863183.0,32818977.0,10044206.0,30.60,42863183.0,39612451.0,...,12038861.0,8788129.0,3250732.0,36.990035,10981885.0,1056976.0,9.624723,6.0,21.356189,14.609526
2,AMATA,2025,3,1.0,3130606.0,2142951.0,987655.0,46.09,3130606.0,2757200.0,...,1138536.0,765130.0,373406.0,48.802949,139867.0,998669.0,714.013313,21.0,205.611565,339.312980
3,BA,2025,3,1.0,3648593.0,2910875.0,737718.0,25.34,3648593.0,3278894.0,...,1040922.0,671223.0,369699.0,55.078417,401749.0,639173.0,159.097596,45.0,62.699003,66.809109
4,BGRIM,2025,3,1.0,1968731.0,1233128.0,735603.0,59.65,1968731.0,1610483.0,...,520997.0,162749.0,358248.0,220.123012,6846.0,514151.0,7510.239556,59.0,1953.063142,3705.778484
5,BKIH,2025,3,1.0,3386810.0,2761710.0,625100.0,22.63,3386810.0,3001468.0,...,1121712.0,1144725.0,-23013.0,-2.010352,955826.0,165886.0,17.355251,68.0,12.703725,10.593870
6,BLA,2025,3,1.0,7271185.0,3027476.0,4243709.0,140.17,7271185.0,5579492.0,...,2305941.0,1497610.0,808331.0,53.974733,2128385.0,177556.0,8.342288,70.0,58.201755,57.735084
7,CENTEL,2025,3,1.0,1685602.0,1510544.0,175058.0,11.59,1685602.0,1688337.0,...,160361.0,163096.0,-2735.0,-1.676926,110343.0,50018.0,45.329563,92.0,13.770659,21.858720
8,CK,2025,3,1.0,2712981.0,1773101.0,939880.0,53.01,2712981.0,1981824.0,...,1738865.0,1007708.0,731157.0,72.556435,862763.0,876102.0,101.546079,106.0,66.000629,27.824706
11,GFPT,2025,3,1.0,2378968.0,2001260.0,377708.0,18.87,2378968.0,2205364.0,...,715408.0,541804.0,173604.0,32.041845,642113.0,73295.0,11.414658,187.0,17.549126,10.694248
12,MTC,2025,3,1.0,6484813.0,5675828.0,808985.0,14.25,6484813.0,6251924.0,...,1723953.0,1491064.0,232889.0,15.618981,1647011.0,76942.0,4.671614,315.0,9.567649,6.234109
13,OR,2025,3,1.0,12224912.0,4843875.0,7381037.0,152.38,12224912.0,8001908.0,...,2614259.0,-1608745.0,4223004.0,262.503007,2231799.0,382460.0,17.136848,715.0,121.197464,110.227850
14,PCSGH,2025,3,1.0,680862.0,495395.0,185467.0,37.44,680862.0,623891.0,...,132602.0,75631.0,56971.0,75.327577,116942.0,15660.0,13.391254,346.0,33.822208,30.347505
16,SSP,2025,3,1.0,650095.0,566446.0,83649.0,14.77,650095.0,652019.0,...,111736.0,113660.0,-1924.0,-1.692768,-13732.0,125468.0,913.690650,643.0,231.616970,454.776878
17,SYNEX,2025,3,1.0,723427.0,628765.0,94662.0,15.06,723427.0,694197.0,...,198138.0,168908.0,29230.0,17.305279,190158.0,7980.0,4.196510,495.0,10.192947,6.976780
18,THANI,2025,3,1.0,955604.0,838723.0,116881.0,13.94,955604.0,734770.0,...,300620.0,79786.0,220834.0,276.782894,278679.0,21941.0,7.873216,522.0,82.161528,130.084611
19,TOA,2025,3,1.0,2523302.0,2013648.0,509654.0,25.31,2523302.0,2023474.0,...,687726.0,187898.0,499828.0,266.010282,651794.0,35932.0,5.512785,645.0,80.383267,124.092263
20,TTA,2025,3,1.0,2303219.0,462798.0,1840421.0,397.67,2303219.0,711450.0,...,502910.0,1088859.0,-585949.0,-53.813120,90105.0,412805.0,458.137728,579.0,256.433652,229.458910
21,TTW,2025,3,1.0,3190977.0,2857325.0,333652.0,11.68,3190977.0,3130292.0,...,976211.0,915526.0,60685.0,6.628430,796563.0,179648.0,22.552893,581.0,10.700331,8.846219

In [86]:
rcds = final6.values.tolist()
len(rcds)

19

In [88]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
print(sql)
lt_profits = pd.read_sql(sql, conlt)
lt_profits.head().style.format(format_dict)

SELECT *
FROM profits
WHERE year = 2025 AND quarter = 3
ORDER BY name

In [90]:
# 1. First replace inf in the DataFrame
lt_profits['inc_pct_py'] = lt_profits['inc_pct_py'].replace([np.inf, -np.inf], 999.99)
lt_profits['mean_pct'] = lt_profits['mean_pct'].replace([np.inf, -np.inf], 999.99)

# Now when you print rcds, you'll see 999.99 instead of inf
lt_profits.style.format(format_dict)

In [92]:
# Define SQL statement using named placeholders
sql = text("""
INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)
""")

# Convert list data to dictionaries for named parameters
columns = [
    "name", "year", "quarter", "kind",
    "latest_amt_y", "previous_amt_y", "inc_amt_y", "inc_pct_y",
    "latest_amt_q", "previous_amt_q", "inc_amt_q", "inc_pct_q",
    "q_amt_c", "y_amt", "inc_amt_py", "inc_pct_py",
    "q_amt_p", "inc_amt_pq", "inc_pct_pq",
    "ticker_id", "mean_pct", "std_pct"
]
print(sql)

INSERT INTO profits (name, year, quarter, kind,
latest_amt_y, previous_amt_y, inc_amt_y, inc_pct_y,
latest_amt_q, previous_amt_q, inc_amt_q, inc_pct_q,
q_amt_c, y_amt, inc_amt_py, inc_pct_py,
q_amt_p, inc_amt_pq, inc_pct_pq,
ticker_id, mean_pct, std_pct)
VALUES (:name, :year, :quarter, :kind,
:latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y,
:latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q,
:q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py,
:q_amt_p, :inc_amt_pq, :inc_pct_pq,
:ticker_id, :mean_pct, :std_pct)

In [94]:
records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]

# Check for empty records before attempting insertion
if not rcds:
    print("No records to insert - skipping database operation")
    # In notebook/script context, just proceed to next cell instead of 'return'
else:
    try:
        # Convert list data to dictionaries for named parameters
#        records_dicts = [dict(zip(columns, rcd)) for rcd in rcds]
        conlt.execute(sql, records_dicts)
        conlt.commit()
        print(f"Successfully inserted {len(records_dicts)} records")
    except Exception as e:
        conlt.rollback()
        print("Insert failed:", e)
    finally:
        conlt.commit()

Successfully inserted 19 records

In [96]:
sql = """
SELECT *
FROM profits
WHERE year = %s AND quarter = %s
ORDER BY name"""
sql = sql % (year, quarter)
lt_profits = pd.read_sql(sql, conlt)
lt_profits.style.format(format_dict)

### End of Create Data

In [99]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y:%m:%d %H:%M:%S")
print(formatted_time)

2025:11:30 11:33:28