In [1]:
import pandas as pd
import os
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2025"
quarter = "4"
select_date = date.today()
select_date = select_date.strftime("%Y-%m-%d")
print(select_date)

2026-03-02

In [2]:
select_date = date(2026, 2, 24)
select_date = select_date.strftime("%Y-%m-%d")
print(select_date)

2026-02-24

In [3]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")
#C:\Users\PC1\OneDrive\A5\Excel
xsl_path = os.path.join(base_path, "Excel")

In [4]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Excel path (xsl_path): {xsl_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Excel path (xsl_path): C:\Users\PC1\OneDrive\A4\Excel
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

### Restart and Run All

In [6]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()

format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%'
              }

In [7]:
pd.read_sql_query('SELECT * FROM EPSS ORDER BY id DESC LIMIT 5', conlt).style.format(format_dict)

In [8]:
sql = """
SELECT * 
FROM epss 
WHERE year = %s AND quarter = %s
AND publish_date >= '%s'
"""
sql = sql % (year, quarter, select_date)
print(sql)

epss = pd.read_sql(sql, conlt)
epss.head().style.format(format_dict)

SELECT *
FROM epss
WHERE year = 2025 AND quarter = 4
AND publish_date >= '2026-02-24'

In [9]:
epss["yoy_gain"] = epss["q_amt"] - epss["y_amt"]
epss["yoy_pct"] = round(epss["yoy_gain"] / abs(epss["y_amt"]) * 100, 2)
epss["acc_gain"] = epss["aq_amt"] - epss["ay_amt"]
epss["acc_pct"] = round(epss["acc_gain"] / abs(epss["ay_amt"]) * 100,2)

df_pct = epss[colt]
df_pct.head().style.format(format_dict)

In [10]:
criteria_1 = df_pct.q_amt > 110_000
df_pct.loc[criteria_1,cols].style.format(format_dict)

In [11]:
criteria_2 = df_pct.y_amt > 100_000
df_pct.loc[criteria_2, cols].style.format(format_dict)

In [12]:
criteria_3 = df_pct.yoy_pct > 10.00
df_pct.loc[criteria_3, cols].style.format(format_dict)

In [13]:
df_pct_criteria = criteria_1 & criteria_2 & criteria_3
#df_pct_criteria = criteria_1 & criteria_2 
df_pct.loc[df_pct_criteria, cols].style.format(format_dict)

In [14]:
df_pct[df_pct_criteria].sort_values(by=["yoy_pct"], ascending=[False]).style.format(format_dict)

In [15]:
df_pct[df_pct_criteria].sort_values(by=["name"], ascending=[True]).style.format(format_dict)

In [16]:
names = epss['name']
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'SYNEX', 'SJWD', 'HMPRO', 'TKS', 'QH', 'COM7', 'BJC', 'SPCG', 'SC', 'CENTEL', 'DCON', 'SPALI', 'BGRIM', 'MEGA', 'TTW', 'TKN', 'PTG', 'CPNREIT', 'RJH', 'SGP', 'BDMS', 'WHAUP', 'OSP', 'TK', 'BEM', 'PAP', 'CPALL', 'CPF', 'AWC', 'AH', 'BCH', 'CK', 'BAM', 'TTA', 'RATCH', 'PRM', 'M', 'ILM', 'BA', 'ASP', 'LPN', 'AP', 'WICE', 'BEAUTY', 'FSMART', 'EASTW', 'WHA', 'BPP', 'BANPU', 'VNG', 'SAPPE', 'III', 'SENA', 'TOA', 'TVO', 'ORI', 'IVL'"

### If new records pass filter criteria then proceed to create quarterly profits process.

In [18]:
sql = """
SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name 
WHERE E.name IN (%s)
ORDER BY E.name, year DESC, quarter DESC 
"""
sql = sql % (in_p)
print(sql)

epss = pd.read_sql(sql, conlt)
epss.shape

SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name
WHERE E.name IN ('SYNEX', 'SJWD', 'HMPRO', 'TKS', 'QH', 'COM7', 'BJC', 'SPCG', 'SC', 'CENTEL', 'DCON', 'SPALI', 'BGRIM', 'MEGA', 'TTW', 'TKN', 'PTG', 'CPNREIT', 'RJH', 'SGP', 'BDMS', 'WHAUP', 'OSP', 'TK', 'BEM', 'PAP', 'CPALL', 'CPF', 'AWC', 'AH', 'BCH', 'CK', 'BAM', 'TTA', 'RATCH', 'PRM', 'M', 'ILM', 'BA', 'ASP', 'LPN', 'AP', 'WICE', 'BEAUTY', 'FSMART', 'EASTW', 'WHA', 'BPP', 'BANPU', 'VNG', 'SAPPE', 'III', 'SENA', 'TOA', 'TVO', 'ORI', 'IVL')
ORDER BY E.name, year DESC, quarter DESC

(2741, 11)

### Delete from profits of older profit stocks

In [20]:
in_p

"'SYNEX', 'SJWD', 'HMPRO', 'TKS', 'QH', 'COM7', 'BJC', 'SPCG', 'SC', 'CENTEL', 'DCON', 'SPALI', 'BGRIM', 'MEGA', 'TTW', 'TKN', 'PTG', 'CPNREIT', 'RJH', 'SGP', 'BDMS', 'WHAUP', 'OSP', 'TK', 'BEM', 'PAP', 'CPALL', 'CPF', 'AWC', 'AH', 'BCH', 'CK', 'BAM', 'TTA', 'RATCH', 'PRM', 'M', 'ILM', 'BA', 'ASP', 'LPN', 'AP', 'WICE', 'BEAUTY', 'FSMART', 'EASTW', 'WHA', 'BPP', 'BANPU', 'VNG', 'SAPPE', 'III', 'SENA', 'TOA', 'TVO', 'ORI', 'IVL'"

In [21]:
sqlDel = text("""
    DELETE FROM profits 
    WHERE name IN ({})
    AND quarter < :quarter
""".format(in_p))
print(sqlDel)
# Execute with parameters
rp = conlt.execute(sqlDel, {'quarter': quarter})
rp.rowcount

    DELETE FROM profits
    WHERE name IN ('SYNEX', 'SJWD', 'HMPRO', 'TKS', 'QH', 'COM7', 'BJC', 'SPCG', 'SC', 'CENTEL', 'DCON', 'SPALI', 'BGRIM', 'MEGA', 'TTW', 'TKN', 'PTG', 'CPNREIT', 'RJH', 'SGP', 'BDMS', 'WHAUP', 'OSP', 'TK', 'BEM', 'PAP', 'CPALL', 'CPF', 'AWC', 'AH', 'BCH', 'CK', 'BAM', 'TTA', 'RATCH', 'PRM', 'M', 'ILM', 'BA', 'ASP', 'LPN', 'AP', 'WICE', 'BEAUTY', 'FSMART', 'EASTW', 'WHA', 'BPP', 'BANPU', 'VNG', 'SAPPE', 'III', 'SENA', 'TOA', 'TVO', 'ORI', 'IVL')
    AND quarter < :quarter

0

In [22]:
rp = conmy.execute(sqlDel, {'quarter': quarter})
rp.rowcount

0

In [23]:
rp = conpg.execute(sqlDel, {'quarter': quarter})
rp.rowcount

0

In [24]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
lt_profits = pd.read_sql(sql, conlt)
lt_profits.set_index("name", inplace=True)
lt_profits.index

Index(['3BBIF', 'ACE', 'ADVANC', 'AMATA', 'BCP', 'BKIH', 'DIF', 'FPT', 'GFPT',
       'GULF', 'KKP', 'MTC', 'NER', 'SCGP', 'SSP', 'THANI'],
      dtype='object', name='name')

In [25]:
my_profits = pd.read_sql(sql, conmy)
my_profits.set_index("name", inplace=True)
my_profits.index

Index(['2842', '2843', '2844', '2845', '2846', '2847', '2848', '2849', '2850',
       '2851', '2851', '2852', '2853', '2854', '2855', '2856', '3BBIF',
       'ADVANC', 'BCP', 'DIF', 'FPT', 'GFPT', 'GULF', 'GUNKUL', 'KKP', 'MTC',
       'NER', 'SCGP'],
      dtype='object', name='name')

In [26]:
pg_profits = pd.read_sql(sql, conpg)
pg_profits.set_index("name", inplace=True)
pg_profits.index

Index(['3BBIF', 'ACE', 'ADVANC', 'AMATA', 'BCP', 'BKIH', 'FPT', 'GFPT', 'KKP',
       'SCGP', 'SSP', 'THANI'],
      dtype='object', name='name')

### Portfolio that publish today

In [28]:
sql = """
SELECT * 
FROM tickers
WHERE name IN (%s)
ORDER BY name"""
sql = sql % in_p
print(sql)

SELECT *
FROM tickers
WHERE name IN ('SYNEX', 'SJWD', 'HMPRO', 'TKS', 'QH', 'COM7', 'BJC', 'SPCG', 'SC', 'CENTEL', 'DCON', 'SPALI', 'BGRIM', 'MEGA', 'TTW', 'TKN', 'PTG', 'CPNREIT', 'RJH', 'SGP', 'BDMS', 'WHAUP', 'OSP', 'TK', 'BEM', 'PAP', 'CPALL', 'CPF', 'AWC', 'AH', 'BCH', 'CK', 'BAM', 'TTA', 'RATCH', 'PRM', 'M', 'ILM', 'BA', 'ASP', 'LPN', 'AP', 'WICE', 'BEAUTY', 'FSMART', 'EASTW', 'WHA', 'BPP', 'BANPU', 'VNG', 'SAPPE', 'III', 'SENA', 'TOA', 'TVO', 'ORI', 'IVL')
ORDER BY name

In [29]:
tickers = pd.read_sql(sql, conpg)
tickers[['name','id']].sort_values(by=[ "name"], ascending=[True])

       name   id
0        AH   11
1        AP   29
2       ASP   44
3       AWC  668
4        BA   49
5       BAM  680
6     BANPU   51
7       BCH   55
8      BDMS   58
9    BEAUTY   59
10      BEM   61
11    BGRIM   63
12      BJC   68
13      BPP   78
14   CENTEL   94
15       CK  109
16     COM7  118
17    CPALL  120
18      CPF  121
19  CPNREIT  127
20     DCON  141
21    EASTW  155
22   FSMART  183
23    HMPRO  214
24      III  226
25      ILM  702
26      IVL  238
27      LPN  284
28        M  287
29     MEGA  303
30      ORI  347
31      OSP  650
32      PAP  350
33      PRM  382
34      PTG  387
35       QH  394
36    RATCH  399
37      RJH  404
38    SAPPE  426
39       SC  431
40     SENA  443
41      SGP  447
42     SJWD  250
43    SPALI  470
44     SPCG  472
45    SYNEX  504
46       TK  541
47      TKN  542
48      TKS  543
49      TOA  562
50      TTA  588
51      TTW  590
52      TVO  594
53      VNG  703
54      WHA  628
55    WHAUP  631
56     WICE  632

In [30]:
sql = """
SELECT name 
FROM buy
"""
buys = pd.read_sql(sql, const)
buys.shape

(30, 1)

In [31]:
df_merge = pd.merge(tickers, buys, on='name', how='inner')
df_merge

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,11,AH,AAPICO HITECH PUBLIC COMPANY LIMITED,Industrials,Automotive,sSET / SETTHSI,www.aapico.com,2018-04-22 04:29:36.134601,2021-07-07 03:33:38.806441
1,668,AWC,ASSET WORLD CORP PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SET50 / SETTHSI,https://www.assetworldcorp-th.com,2019-11-19 07:13:52.454317,2022-01-15 03:54:48.241937
2,55,BCH,BANGKOK CHAIN HOSPITAL PUBLIC COMPANY LIMITED,Services,Health Care Services,SET100 / SETWB,www.bangkokchainhospital.com,2018-04-22 04:29:36.442067,2019-11-19 07:13:52.520896
3,121,CPF,CHAROEN POKPHAND FOODS PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET50 / SETCLMV / SETHD / SETTHSI / SETWB,www.cpfworldwide.com,2018-04-22 04:29:36.867977,2021-07-07 03:33:38.893396
4,127,CPNREIT,CPN RETAIL GROWTH LEASEHOLD REIT,Property & Construction,Property Fund & REITs,SET,www.cpnreit.com,2018-04-22 04:29:36.900508,2018-04-22 04:29:36.900508
5,238,IVL,INDORAMA VENTURES PUBLIC COMPANY LIMITED,Industrials,Petrochemicals & Chemicals,SET50 / SETTHSI,www.indoramaventures.com,2018-04-22 04:29:37.583373,2021-07-07 03:33:38.986666
6,347,ORI,ORIGIN PROPERTY PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SET100 / SETHD / SETTHSI,www.origin.co.th,2018-04-22 04:29:38.228072,2022-01-15 03:54:48.440923
7,387,PTG,PTG ENERGY PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET100 / SETHD / SETTHSI,www.ptgenergy.co.th,2018-04-22 04:29:38.474708,2022-01-15 03:54:48.464340
8,443,SENA,SENADEVELOPMENT PUBLIC COMPANY LIMITED,Property & Construction,Property Development,sSET,www.sena.co.th,2018-04-22 04:29:38.825191,2018-04-22 04:29:38.825191
9,504,SYNEX,SYNNEX (THAILAND) PUBLIC COMPANY LIMITED,Technology,Information & Communication Technology,SET100 / SETTHSI,www.synnex.co.th,2018-04-22 04:29:39.170664,2021-07-07 03:33:39.202279
10,562,TOA,TOA PAINT (THAILAND) PUBLIC COMPANY LIMITED,Property & Construction,Construction Materials,SETTHSI,www.toagroup.com,2018-04-22 04:29:39.494571,2021-07-07 03:33:39.241053
11,594,TVO,THAI VEGETABLE OIL PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET / SETTHSI / SETWB,www.tvothai.com,2018-04-22 04:29:39.677962,2019-11-19 07:13:54.470342

In [32]:
file_name = 'pub_stock.xlsx'
output_file = os.path.join(dat_path, file_name)
print(f"Output file : {output_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\pub_stock.xlsx

In [33]:
df_merge[['id','name','sector','market']].to_excel(output_file, index=False)

### Portfolio that already published

In [35]:
sql = """
SELECT * 
FROM buy"""
buys = pd.read_sql(sql, const)
buys.shape

(30, 10)

In [36]:
names = buys["name"].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'STA', 'SINGER', 'PTG', 'PTT', 'MCS', 'DIF', 'ADVANC', 'JMT', 'WHART', 'BCH', 'SENA', 'TFFIF', '3BBIF', 'CPF', 'IVL', 'PTTGC', 'WHAIR', 'ORI', 'AH', 'GVREIT', 'NER', 'AIMIRT', 'TOA', 'AWC', 'SYNEX', 'SCC', 'RCL', 'JMART', 'CPNREIT', 'TVO'"

In [37]:
sql = """
SELECT *
FROM epss
WHERE publish_date >= '%s'
AND name IN (%s)
ORDER BY publish_date, name"""
sql = sql % (select_date, in_p)
df_tmp = pd.read_sql(sql, conlt)
df_tmp.style.format(format_dict)

In [38]:
df_tmp.shape

(12, 14)

### Not yet published

In [40]:
sql = """
SELECT name
FROM epss
WHERE publish_date >= '2026-01-01'
"""
epss = pd.read_sql(sql, conlt)
epss.shape

(150, 1)

In [41]:
names = epss["name"].values.tolist()
in_p = ", ".join(map(lambda name: "'%s'" % name, names))
in_p

"'SCGP', 'SCC', 'MST', 'KBANK', 'SCB', 'KTB', 'TTB', 'BBL', 'KKP', 'STANLY', 'TSTH', 'DCC', 'KCE', 'MBAX', 'OR', 'GGC', 'PTTGC', 'PTTEP', '3BBIF', 'ADVANC', 'EPG', 'BCP', 'BCPG', 'VGI', 'SPRC', 'PLANB', 'PTL', 'TOP', 'IMPACT', 'TFFIF', 'KYE', 'BLAND', 'AOT', 'DRT', 'SINGER', 'JMART', 'JMT', 'SVI', 'LHK', 'GPSC', 'INOX', 'SMPC', 'ASK', 'DELTA', 'PSL', 'EGATIF', 'TTLPF', 'TR', 'GVREIT', 'BTSGIF', 'MINT', 'TMW', 'MC', 'LANNA', 'BTS', 'DIF', 'STA', 'PTT', 'NER', 'RCL', 'BLA', 'AIMIRT', 'CBG', 'DOHOME', 'MAJOR', 'TMT', 'WORK', 'TPIPL', 'SCCC', 'TIPCO', 'LIT', 'PDG', 'ASIAN', 'BEC', 'TCAP', 'PREB', 'ASW', 'STGT', 'TASCO', 'TPIPP', 'MTC', 'IRPC', 'GULF', 'SUPEREIF', 'MCS', 'SYNEX', 'WHAIR', 'WHART', 'THG', 'SIS', 'CKP', 'CPN', 'CPAXT', 'PCSGH', 'SJWD', 'HMPRO', 'TKS', 'QH', 'COM7', 'BJC', 'SPCG', 'SC', 'CENTEL', 'DCON', 'SPALI', 'BGRIM', 'MEGA', 'TTW', 'TKN', 'PTG', 'CPNREIT', 'RJH', 'SGP', 'BDMS', 'WHAUP', 'OSP', 'TK', 'BEM', 'PAP', 'CPALL', 'CPF', 'AWC', 'AH', 'BCH', 'CK', 'BAM', 'TTA', 'RATCH', 'PRM', 'M', 'ILM', 'BA', 'ASP', 'LPN', 'AP', 'WICE', 'BEAUTY', 'FSMART', 'EASTW', 'WHA', 'BPP', 'BANPU', 'VNG', 'SAPPE', 'III', 'SENA', 'TOA', 'TVO', 'ORI', 'IVL'"

In [42]:
sql = """
SELECT *
FROM buy
WHERE name NOT IN (%s)
ORDER BY name
"""
sql = sql % in_p
df_tmp = pd.read_sql(sql, const)
df_tmp

Empty DataFrame
Columns: [name, date, volbuy, price, volsell, volbal, active, dividend, period, grade]
Index: []

In [43]:
df_tmp.shape

(0, 10)

### Comparison check between EPS and Buy

In [45]:
sql = """
SELECT name FROM buy WHERE active = 1 ORDER BY name"""
buy = pd.read_sql(sql, const)
buy.shape

(30, 1)

In [46]:
sql = '''
SELECT * 
FROM epss 
WHERE publish_date >= '%s' 
AND quarter = %s
'''
sql = sql % (select_date, quarter)
print(sql)
tdy_df = pd.read_sql(sql, conlt)
tdy_df.shape

SELECT *
FROM epss
WHERE publish_date >= '2026-02-24'
AND quarter = 4

(57, 14)

In [47]:
tdy_buy_df = tdy_df.merge(buy, on='name', how='inner')
tdy_buy_df.sort_values(by='name')

,id,name,year,quarter,q_amt,y_amt,aq_amt,ay_amt,q_eps,y_eps,aq_eps,ay_eps,ticker_id,publish_date
5,24994,AH,2025,4,105562,119895,731428,746961,0.32000,0.3700,2.1800,2.1500,9,2026-02-27
4,24993,AWC,2025,4,1866088,1859770,6388002,5850295,0.05820,0.0580,0.1995,0.1827,699,2026-02-26
6,24995,BCH,2025,4,259498,233040,1316360,1282371,0.11000,0.0900,0.5300,0.5100,51,2026-02-27
3,24992,CPF,2025,4,1085272,4172528,25197488,19558133,0.11000,0.5100,3.1200,2.3900,117,2026-02-26
2,24982,CPNREIT,2025,4,1484839,357438,3460976,1696069,0.00000,0.0000,0.0000,0.0000,647,2026-02-26
11,25021,IVL,2025,4,-4697188,1095694,-7348393,-19262126,-0.88000,0.1200,-1.4700,-3.6500,231,2026-03-02
10,25020,ORI,2025,4,105152,-266145,719936,1051790,0.04280,-0.1084,0.2933,0.4286,339,2026-02-27
1,24981,PTG,2025,4,314288,228393,1021441,1021805,0.19000,0.1300,0.6100,0.6100,381,2026-02-25
7,25017,SENA,2025,4,35749,97807,323614,399608,0.02480,0.0678,0.2244,0.2771,437,2026-02-27
0,24957,SYNEX,2025,4,193273,146914,769786,627721,0.23000,0.1700,0.9100,0.7400,495,2026-02-24
8,25018,TOA,2025,4,844394,450683,2917013,1919604,0.43719,0.2318,1.5000,0.9600,645,2026-02-27
9,25019,TVO,2025,4,521643,807667,2188791,2103105,0.59000,0.9000,2.4600,2.3600,585,2026-02-27

In [48]:
sql = """
SELECT * 
FROM tickers
ORDER BY name"""
print(sql)
tickers = pd.read_sql(sql, conpg)
tickers[['name','id','market']].shape

SELECT *
FROM tickers
ORDER BY name

(396, 3)

In [49]:
tmp_df = tdy_buy_df.merge(tickers, on='name', how='inner')
tmp_df.shape

(12, 22)

In [50]:
tmp_df[['name','id_y','market']].sort_values(by='name')

       name  id_y                                     market
5        AH    11                             sSET / SETTHSI
4       AWC   668                            SET50 / SETTHSI
6       BCH    55                             SET100 / SETWB
3       CPF   121  SET50 / SETCLMV / SETHD / SETTHSI / SETWB
2   CPNREIT   127                                        SET
11      IVL   238                            SET50 / SETTHSI
10      ORI   347                   SET100 / SETHD / SETTHSI
1       PTG   387                   SET100 / SETHD / SETTHSI
7      SENA   443                                       sSET
0     SYNEX   504                           SET100 / SETTHSI
8       TOA   562                                    SETTHSI
9       TVO   594                      SET / SETTHSI / SETWB

In [51]:
const.close()
conpg.commit()
conpg.close()
conmy.commit()
conmy.close()
conlt.commit()
conlt.close()

In [52]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y:%m:%d %H:%M:%S")
print(formatted_time)

2026:03:02 10:38:05