In [4]:
import pandas as pd
import os
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

year = "2025"
quarter = "4"
select_date = date.today()
select_date = select_date.strftime("%Y-%m-%d")
print(select_date)

2026-03-12

In [6]:
select_date = date(2026, 1, 1)
select_date = select_date.strftime("%Y-%m-%d")
print(select_date)

2026-01-01

In [8]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")
#C:\Users\PC1\OneDrive\A5\Excel
xsl_path = os.path.join(base_path, "Excel")

In [10]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Excel path (xsl_path): {xsl_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Quarterly
Base path: C:\Users\PC1\OneDrive\A4
Data path (dat_path): C:\Users\PC1\OneDrive\A4\Data
Excel path (xsl_path): C:\Users\PC1\OneDrive\A4\Excel
Google Drive path (god_path): C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\PC1\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

### Restart and Run All

In [13]:
cols = 'name year quarter q_amt y_amt yoy_gain yoy_pct'.split()
colt = 'name year quarter q_amt y_amt yoy_gain yoy_pct aq_amt ay_amt acc_gain acc_pct'.split()

format_dict = {
                'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}',
                'yoy_gain':'{:,}','acc_gain':'{:,}',    
                'q_eps':'{:.4f}','y_eps':'{:.4f}','aq_eps':'{:.4f}','ay_eps':'{:.4f}',
                'yoy_pct':'{:.2f}%','acc_pct':'{:.2f}%'
              }

In [15]:
pd.read_sql_query('SELECT * FROM EPSS ORDER BY id DESC LIMIT 5', conlt).style.format(format_dict)

In [17]:
sql = f"""
SELECT * 
FROM epss 
WHERE year = {year} AND quarter = {quarter}
AND publish_date >= '{select_date}'
"""
print(sql)

epss = pd.read_sql(sql, conlt)
epss.tail().style.format(format_dict)

SELECT *
FROM epss
WHERE year = 2025 AND quarter = 4
AND publish_date >= '2026-01-01'

In [19]:
epss["yoy_gain"] = epss["q_amt"] - epss["y_amt"]
epss["yoy_pct"] = round(epss["yoy_gain"] / abs(epss["y_amt"]) * 100, 2)
epss["acc_gain"] = epss["aq_amt"] - epss["ay_amt"]
epss["acc_pct"] = round(epss["acc_gain"] / abs(epss["ay_amt"]) * 100,2)

df_pct = epss[colt]
df_pct.tail().style.format(format_dict)

In [21]:
criteria_1 = df_pct.q_amt > 110_000
df_pct.loc[criteria_1,cols].style.format(format_dict)

In [23]:
criteria_2 = df_pct.y_amt > 100_000
df_pct.loc[criteria_2, cols].style.format(format_dict)

In [25]:
criteria_3 = df_pct.yoy_pct > 10.00
df_pct.loc[criteria_3, cols].style.format(format_dict)

In [27]:
df_pct_criteria = criteria_1 & criteria_2 & criteria_3
#df_pct_criteria = criteria_1 & criteria_2 
df_pct.loc[df_pct_criteria, cols].style.format(format_dict)

In [29]:
df_pct[df_pct_criteria].sort_values(by=["yoy_pct"], ascending=[False]).style.format(format_dict)

In [31]:
df_pct[df_pct_criteria].sort_values(by=["name"], ascending=[True]).style.format(format_dict)

In [33]:
stock_list = epss['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

SCGP','SCC','MST','KBANK','SCB','KTB','TTB','BBL','KKP','DCC','KCE','MBAX','OR','GGC','PTTGC','PTTEP','3BBIF','ADVANC','BCP','BCPG','SPRC','PLANB','TOP','DRT','SINGER','JMART','JMT','SVI','GPSC','INOX','SMPC','ASK','DELTA','PSL','EGATIF','TTLPF','MINT','LANNA','DIF','STA','PTT','NER','RCL','BLA','AIMIRT','CBG','DOHOME','MAJOR','TMT','WORK','TPIPL','SCCC','TIPCO','LIT','PDG','ASIAN','BEC','TCAP','PREB','ASW','STGT','TASCO','TPIPP','MTC','IRPC','GULF','SUPEREIF','MCS','SYNEX','WHAIR','WHART','THG','SIS','CKP','CPN','CPAXT','PCSGH','SJWD','HMPRO','TKS','QH','COM7','BJC','SPCG','SC','CENTEL','DCON','SPALI','BGRIM','MEGA','TTW','TKN','PTG','CPNREIT','RJH','SGP','BDMS','WHAUP','OSP','TK','BEM','PAP','CPALL','CPF','AWC','AH','BCH','CK','BAM','TTA','RATCH','PRM','M','ILM','BA','ASP','LPN','AP','WICE','BEAUTY','FSMART','EASTW','WHA','BPP','BANPU','VNG','SAPPE','III','SENA','TOA','TVO','ORI','IVL','ACE','AIE','AIT','AJ','AMATA','ANAN','BAY','BE8','BGC','BH','BKIH','CHG','CPNCG','CRC','EA','EGCO','FORTH','GC','GFPT','GLOBAL','GRAMMY','RS','S11','SAT','GUNKUL','HANA','HFT','HTC','ICHI','IMH','IP','KGI','LALIN','LH','LPH','NOBLE','ONEE','POPF','PSH','RBF','ROJNA','SAWAD','SIRI','SKN','SKR','SNC','SPC','SPRIME','SSP','SUPER','TFG','THANI','TIDLOR','TIPH','TQM','TRUE','TSE','TU','TYCN','UTP','VIBHA

### If new records pass filter criteria then proceed to create quarterly profits process.

In [36]:
sql = f"""
SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name 
WHERE E.name IN ('{stock_list_str}')
ORDER BY E.name, year DESC, quarter DESC 
"""
print(sql)

epss = pd.read_sql(sql, conlt)
epss.shape

SELECT E.name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, q_eps, y_eps, aq_eps, ay_eps
FROM epss E JOIN stocks S ON E.name = S.name
WHERE E.name IN ('SCGP','SCC','MST','KBANK','SCB','KTB','TTB','BBL','KKP','DCC','KCE','MBAX','OR','GGC','PTTGC','PTTEP','3BBIF','ADVANC','BCP','BCPG','SPRC','PLANB','TOP','DRT','SINGER','JMART','JMT','SVI','GPSC','INOX','SMPC','ASK','DELTA','PSL','EGATIF','TTLPF','MINT','LANNA','DIF','STA','PTT','NER','RCL','BLA','AIMIRT','CBG','DOHOME','MAJOR','TMT','WORK','TPIPL','SCCC','TIPCO','LIT','PDG','ASIAN','BEC','TCAP','PREB','ASW','STGT','TASCO','TPIPP','MTC','IRPC','GULF','SUPEREIF','MCS','SYNEX','WHAIR','WHART','THG','SIS','CKP','CPN','CPAXT','PCSGH','SJWD','HMPRO','TKS','QH','COM7','BJC','SPCG','SC','CENTEL','DCON','SPALI','BGRIM','MEGA','TTW','TKN','PTG','CPNREIT','RJH','SGP','BDMS','WHAUP','OSP','TK','BEM','PAP','CPALL','CPF','AWC','AH','BCH','CK','BAM','TTA','RATCH','PRM','M','ILM','BA','ASP','LPN','AP','WICE','BEAUTY','FSMART','EASTW','WHA','BPP','BANPU','VNG','SAPPE','III','SENA','TOA','TVO','ORI','IVL','ACE','AIE','AIT','AJ','AMATA','ANAN','BAY','BE8','BGC','BH','BKIH','CHG','CPNCG','CRC','EA','EGCO','FORTH','GC','GFPT','GLOBAL','GRAMMY','RS','S11','SAT','GUNKUL','HANA','HFT','HTC','ICHI','IMH','IP','KGI','LALIN','LH','LPH','NOBLE','ONEE','POPF','PSH','RBF','ROJNA','SAWAD','SIRI','SKN','SKR','SNC','SPC','SPRIME','SSP','SUPER','TFG','THANI','TIDLOR','TIPH','TQM','TRUE','TSE','TU','TYCN','UTP','VIBHA')
ORDER BY E.name, year DESC, quarter DESC

(8951, 11)

### Delete from profits of older profit stocks

In [39]:
print(stock_list_str)

SCGP','SCC','MST','KBANK','SCB','KTB','TTB','BBL','KKP','DCC','KCE','MBAX','OR','GGC','PTTGC','PTTEP','3BBIF','ADVANC','BCP','BCPG','SPRC','PLANB','TOP','DRT','SINGER','JMART','JMT','SVI','GPSC','INOX','SMPC','ASK','DELTA','PSL','EGATIF','TTLPF','MINT','LANNA','DIF','STA','PTT','NER','RCL','BLA','AIMIRT','CBG','DOHOME','MAJOR','TMT','WORK','TPIPL','SCCC','TIPCO','LIT','PDG','ASIAN','BEC','TCAP','PREB','ASW','STGT','TASCO','TPIPP','MTC','IRPC','GULF','SUPEREIF','MCS','SYNEX','WHAIR','WHART','THG','SIS','CKP','CPN','CPAXT','PCSGH','SJWD','HMPRO','TKS','QH','COM7','BJC','SPCG','SC','CENTEL','DCON','SPALI','BGRIM','MEGA','TTW','TKN','PTG','CPNREIT','RJH','SGP','BDMS','WHAUP','OSP','TK','BEM','PAP','CPALL','CPF','AWC','AH','BCH','CK','BAM','TTA','RATCH','PRM','M','ILM','BA','ASP','LPN','AP','WICE','BEAUTY','FSMART','EASTW','WHA','BPP','BANPU','VNG','SAPPE','III','SENA','TOA','TVO','ORI','IVL','ACE','AIE','AIT','AJ','AMATA','ANAN','BAY','BE8','BGC','BH','BKIH','CHG','CPNCG','CRC','EA','EGCO','FORTH','GC','GFPT','GLOBAL','GRAMMY','RS','S11','SAT','GUNKUL','HANA','HFT','HTC','ICHI','IMH','IP','KGI','LALIN','LH','LPH','NOBLE','ONEE','POPF','PSH','RBF','ROJNA','SAWAD','SIRI','SKN','SKR','SNC','SPC','SPRIME','SSP','SUPER','TFG','THANI','TIDLOR','TIPH','TQM','TRUE','TSE','TU','TYCN','UTP','VIBHA

In [41]:
sqlDel = f"""
    DELETE FROM profits 
    WHERE name IN ('{stock_list_str}')
    AND quarter < {quarter}
"""
print(sqlDel)
# Execute with parameters
rp = conlt.execute(text(sqlDel))
rp.rowcount

    DELETE FROM profits
    WHERE name IN ('SCGP','SCC','MST','KBANK','SCB','KTB','TTB','BBL','KKP','DCC','KCE','MBAX','OR','GGC','PTTGC','PTTEP','3BBIF','ADVANC','BCP','BCPG','SPRC','PLANB','TOP','DRT','SINGER','JMART','JMT','SVI','GPSC','INOX','SMPC','ASK','DELTA','PSL','EGATIF','TTLPF','MINT','LANNA','DIF','STA','PTT','NER','RCL','BLA','AIMIRT','CBG','DOHOME','MAJOR','TMT','WORK','TPIPL','SCCC','TIPCO','LIT','PDG','ASIAN','BEC','TCAP','PREB','ASW','STGT','TASCO','TPIPP','MTC','IRPC','GULF','SUPEREIF','MCS','SYNEX','WHAIR','WHART','THG','SIS','CKP','CPN','CPAXT','PCSGH','SJWD','HMPRO','TKS','QH','COM7','BJC','SPCG','SC','CENTEL','DCON','SPALI','BGRIM','MEGA','TTW','TKN','PTG','CPNREIT','RJH','SGP','BDMS','WHAUP','OSP','TK','BEM','PAP','CPALL','CPF','AWC','AH','BCH','CK','BAM','TTA','RATCH','PRM','M','ILM','BA','ASP','LPN','AP','WICE','BEAUTY','FSMART','EASTW','WHA','BPP','BANPU','VNG','SAPPE','III','SENA','TOA','TVO','ORI','IVL','ACE','AIE','AIT','AJ','AMATA','ANAN','BAY','BE8','BGC','BH','BKIH','CHG','CPNCG','CRC','EA','EGCO','FORTH','GC','GFPT','GLOBAL','GRAMMY','RS','S11','SAT','GUNKUL','HANA','HFT','HTC','ICHI','IMH','IP','KGI','LALIN','LH','LPH','NOBLE','ONEE','POPF','PSH','RBF','ROJNA','SAWAD','SIRI','SKN','SKR','SNC','SPC','SPRIME','SSP','SUPER','TFG','THANI','TIDLOR','TIPH','TQM','TRUE','TSE','TU','TYCN','UTP','VIBHA')
    AND quarter < 4

6

In [45]:
rp = conmy.execute(text(sqlDel))
rp.rowcount

2

In [49]:
rp = conpg.execute(text(sqlDel))
rp.rowcount

6

In [51]:
sql = """
SELECT name, year, quarter 
FROM profits
ORDER BY name
"""
lt_profits = pd.read_sql(sql, conlt)
lt_profits.set_index("name", inplace=True)
lt_profits.index

Index(['3BBIF', 'ADVANC', 'BCP', 'DIF', 'FPT', 'GULF', 'KKP', 'MTC', 'NER',
       'SCGP'],
      dtype='object', name='name')

In [53]:
my_profits = pd.read_sql(sql, conmy)
my_profits.set_index("name", inplace=True)
my_profits.index

Index(['2842', '2843', '2844', '2845', '2846', '2847', '2848', '2849', '2850',
       '2851', '2851', '2852', '2853', '2854', '2855', '2856', '3BBIF',
       'ADVANC', 'BCP', 'DIF', 'FPT', 'GULF', 'KKP', 'MTC', 'NER', 'SCGP'],
      dtype='object', name='name')

In [55]:
pg_profits = pd.read_sql(sql, conpg)
pg_profits.set_index("name", inplace=True)
pg_profits.index

Index(['3BBIF', 'ADVANC', 'BCP', 'FPT', 'KKP', 'SCGP'], dtype='object', name='name')

### Portfolio that publish today

In [60]:
sql = f"""
SELECT * 
FROM tickers
WHERE name IN ('{stock_list_str}')
ORDER BY name"""
print(sql)

SELECT *
FROM tickers
WHERE name IN ('SCGP','SCC','MST','KBANK','SCB','KTB','TTB','BBL','KKP','DCC','KCE','MBAX','OR','GGC','PTTGC','PTTEP','3BBIF','ADVANC','BCP','BCPG','SPRC','PLANB','TOP','DRT','SINGER','JMART','JMT','SVI','GPSC','INOX','SMPC','ASK','DELTA','PSL','EGATIF','TTLPF','MINT','LANNA','DIF','STA','PTT','NER','RCL','BLA','AIMIRT','CBG','DOHOME','MAJOR','TMT','WORK','TPIPL','SCCC','TIPCO','LIT','PDG','ASIAN','BEC','TCAP','PREB','ASW','STGT','TASCO','TPIPP','MTC','IRPC','GULF','SUPEREIF','MCS','SYNEX','WHAIR','WHART','THG','SIS','CKP','CPN','CPAXT','PCSGH','SJWD','HMPRO','TKS','QH','COM7','BJC','SPCG','SC','CENTEL','DCON','SPALI','BGRIM','MEGA','TTW','TKN','PTG','CPNREIT','RJH','SGP','BDMS','WHAUP','OSP','TK','BEM','PAP','CPALL','CPF','AWC','AH','BCH','CK','BAM','TTA','RATCH','PRM','M','ILM','BA','ASP','LPN','AP','WICE','BEAUTY','FSMART','EASTW','WHA','BPP','BANPU','VNG','SAPPE','III','SENA','TOA','TVO','ORI','IVL','ACE','AIE','AIT','AJ','AMATA','ANAN','BAY','BE8','BGC','BH','BKIH','CHG','CPNCG','CRC','EA','EGCO','FORTH','GC','GFPT','GLOBAL','GRAMMY','RS','S11','SAT','GUNKUL','HANA','HFT','HTC','ICHI','IMH','IP','KGI','LALIN','LH','LPH','NOBLE','ONEE','POPF','PSH','RBF','ROJNA','SAWAD','SIRI','SKN','SKR','SNC','SPC','SPRIME','SSP','SUPER','TFG','THANI','TIDLOR','TIPH','TQM','TRUE','TSE','TU','TYCN','UTP','VIBHA')
ORDER BY name

In [62]:
tickers = pd.read_sql(sql, conpg)
tickers[['name','id']].sort_values(by=[ "name"], ascending=[True])

       name   id
0     3BBIF  241
1       ACE  667
2    ADVANC    8
3        AH   11
4       AIE  691
..      ...  ...
189   WHAIR  217
190   WHART  630
191   WHAUP  631
192    WICE  632
193    WORK  636

[194 rows x 2 columns]

In [64]:
sql = """
SELECT name 
FROM buy
"""
buys = pd.read_sql(sql, const)
buys.shape

(27, 1)

In [66]:
df_merge = pd.merge(tickers, buys, on='name', how='inner')
df_merge

,id,name,full_name,sector,subsector,market,website,created_at,updated_at
0,241,3BBIF,JASMINE BROADBAND INTERNET INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.jas-if.com,2018-04-22 04:29:37.600684,2019-03-03 03:45:01.621634
1,8,ADVANC,ADVANCED INFO SERVICE PUBLIC COMPANY LIMITED,Technology,Information & Communication Technology,SET50 / SETHD / SETTHSI,investor.ais.co.th,2018-04-22 04:29:36.118727,2021-07-07 03:33:38.798595
2,11,AH,AAPICO HITECH PUBLIC COMPANY LIMITED,Industrials,Automotive,sSET / SETTHSI,www.aapico.com,2018-04-22 04:29:36.134601,2021-07-07 03:33:38.806441
3,668,AWC,ASSET WORLD CORP PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SET50 / SETTHSI,https://www.assetworldcorp-th.com,2019-11-19 07:13:52.454317,2022-01-15 03:54:48.241937
4,55,BCH,BANGKOK CHAIN HOSPITAL PUBLIC COMPANY LIMITED,Services,Health Care Services,SET100 / SETWB,www.bangkokchainhospital.com,2018-04-22 04:29:36.442067,2019-11-19 07:13:52.520896
5,121,CPF,CHAROEN POKPHAND FOODS PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET50 / SETCLMV / SETHD / SETTHSI / SETWB,www.cpfworldwide.com,2018-04-22 04:29:36.867977,2021-07-07 03:33:38.893396
6,127,CPNREIT,CPN RETAIL GROWTH LEASEHOLD REIT,Property & Construction,Property Fund & REITs,SET,www.cpnreit.com,2018-04-22 04:29:36.900508,2018-04-22 04:29:36.900508
7,146,DIF,DIGITAL TELECOMMUNICATIONS INFRASTRUCTURE FUND,Technology,Information & Communication Technology,SET,www.digital-tif.com,2018-04-22 04:29:37.030748,2018-04-22 04:29:37.030748
8,238,IVL,INDORAMA VENTURES PUBLIC COMPANY LIMITED,Industrials,Petrochemicals & Chemicals,SET50 / SETTHSI,www.indoramaventures.com,2018-04-22 04:29:37.583373,2021-07-07 03:33:38.986666
9,245,JMT,JMT NETWORK SERVICES PUBLIC COMPANY LIMITED,Financials,Finance & Securities,SET50,www.jmtnetwork.co.th,2018-04-22 04:29:37.621811,2020-07-06 13:23:59.311892
10,301,MCS,M.C.S.STEEL PUBLIC COMPANY LIMITED,Industrials,Steel and Metal Products,sSET,www.mcssteel.com,2018-04-22 04:29:37.957104,2021-08-22 18:22:07.463483
11,649,NER,NORTH EAST RUBBER PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,sSET,www.nerubber.com,2019-03-03 03:45:01.837764,2019-11-19 07:13:53.611284
12,347,ORI,ORIGIN PROPERTY PUBLIC COMPANY LIMITED,Property & Construction,Property Development,SET100 / SETHD / SETTHSI,www.origin.co.th,2018-04-22 04:29:38.228072,2022-01-15 03:54:48.440923
13,387,PTG,PTG ENERGY PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET100 / SETHD / SETTHSI,www.ptgenergy.co.th,2018-04-22 04:29:38.474708,2022-01-15 03:54:48.464340
14,389,PTT,PTT PUBLIC COMPANY LIMITED,Resources,Energy & Utilities,SET50 / SETCLMV / SETHD / SETTHSI,www.pttplc.com,2018-04-22 04:29:38.484745,2019-11-19 07:13:53.785316
15,391,PTTGC,PTT GLOBAL CHEMICAL PUBLIC COMPANY LIMITED,Industrials,Petrochemicals & Chemicals,SET50 / SETCLMV / SETTHSI,www.pttgcgroup.com,2018-04-22 04:29:38.496779,2021-07-07 03:33:39.100623
16,401,RCL,REGIONAL CONTAINER LINES PUBLIC COMPANY LIMITED,Services,Transportation & Logistics,SET100 / SETCLMV,www.rclgroup.com,2018-04-22 04:29:38.554599,2022-01-15 03:54:48.472788
17,443,SENA,SENADEVELOPMENT PUBLIC COMPANY LIMITED,Property & Construction,Property Development,sSET,www.sena.co.th,2018-04-22 04:29:38.825191,2018-04-22 04:29:38.825191
18,452,SINGER,SINGER THAILAND PUBLIC COMPANY LIMITED,Services,Commerce,SET100,www.singerthai.co.th,2018-04-22 04:29:38.875668,2021-07-07 03:33:39.150064
19,489,STA,SRI TRANG AGRO-INDUSTRY PUBLIC COMPANY LIMITED,Agro & Food Industry,Agribusiness,SET100 / SETTHSI / SETWB,www.sritranggroup.com,2018-04-22 04:29:39.085589,2022-01-15 03:54:48.525517
20,504,SYNEX,SYNNEX (THAILAND) PUBLIC COMPANY LIMITED,Technology,Information & Communication Technology,SET100 / SETTHSI,www.synnex.co.th,2018-04-22 04:29:39.170664,2021-07-07 03:33:39.202279
21,562,TOA,TOA PAINT (THAILAND) PUBLIC COMPANY LIMITED,Property & Construction,Construction Materials,SETTHSI,www.toagroup.com,2018-04-22 04:29:39.494571,2021-07-07 03:33:39.241053
22,594,TVO,THAI VEGETABLE OIL PUBLIC COMPANY LIMITED,Agro & Food Industry,Food & Beverage,SET / SETTHSI / SETWB,www.tvothai.com,2018-04-22 04:29:39.677962,2019-11-19 07:13:54.470342
23,217,WHAIR,HEMARAJ LEASEHOLD REAL ESTATE INVESTMENT TRUST,Property & Construction,Property Fund & REITs,SET,www.hemarajreit.com,2018-04-22 04:29:37.460955,2018-04-22 04:29:37.460955
24,630,WHART,WHA PREMIUM GROWTH FREEHOLD AND LEASEHOLD REAL...,Property & Construction,Property Fund & REITs,SET,www.whareit.com,2018-04-22 04:29:39.879467,2018-04-22 04:29:39.879467

In [68]:
file_name = 'pub_stock.xlsx'
output_file = os.path.join(dat_path, file_name)
print(f"Output file : {output_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\pub_stock.xlsx

In [70]:
df_merge[['id','name','sector','market']].to_excel(output_file, index=False)

### Portfolio that already published

In [73]:
sql = """
SELECT * 
FROM buy"""
buys = pd.read_sql(sql, const)
buys.shape

(27, 10)

In [75]:
stock_list = buys['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

STA','SINGER','PTG','PTT','MCS','DIF','ADVANC','JMT','WHART','BCH','SENA','TFFIF','3BBIF','CPF','IVL','PTTGC','WHAIR','ORI','AH','GVREIT','NER','TOA','AWC','SYNEX','RCL','CPNREIT','TVO

In [77]:
sql = f"""
SELECT *
FROM epss
WHERE publish_date >= '{select_date}'
AND name IN ('{stock_list_str}')
ORDER BY publish_date, name"""
print(sql)
df_tmp = pd.read_sql(sql, conlt)
df_tmp.style.format(format_dict)

SELECT *
FROM epss
WHERE publish_date >= '2026-01-01'
AND name IN ('STA','SINGER','PTG','PTT','MCS','DIF','ADVANC','JMT','WHART','BCH','SENA','TFFIF','3BBIF','CPF','IVL','PTTGC','WHAIR','ORI','AH','GVREIT','NER','TOA','AWC','SYNEX','RCL','CPNREIT','TVO')
ORDER BY publish_date, name

In [79]:
df_tmp.shape

(27, 14)

### Not yet published

In [82]:
sql = f"""
SELECT name
FROM epss
WHERE publish_date >= '{select_date}'
"""
print(sql)
epss = pd.read_sql(sql, conlt)
epss.shape

SELECT name
FROM epss
WHERE publish_date >= '2026-01-01'

(211, 1)

In [84]:
stock_list = epss['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

SCGP','SCC','MST','KBANK','SCB','KTB','TTB','BBL','KKP','STANLY','TSTH','DCC','KCE','MBAX','OR','GGC','PTTGC','PTTEP','3BBIF','ADVANC','EPG','BCP','BCPG','VGI','SPRC','PLANB','PTL','TOP','IMPACT','TFFIF','KYE','BLAND','AOT','DRT','SINGER','JMART','JMT','SVI','LHK','GPSC','INOX','SMPC','ASK','DELTA','PSL','EGATIF','TTLPF','TR','GVREIT','BTSGIF','MINT','TMW','MC','LANNA','BTS','DIF','STA','PTT','NER','RCL','BLA','AIMIRT','CBG','DOHOME','MAJOR','TMT','WORK','TPIPL','SCCC','TIPCO','LIT','PDG','ASIAN','BEC','TCAP','PREB','ASW','STGT','TASCO','TPIPP','MTC','IRPC','GULF','SUPEREIF','MCS','SYNEX','WHAIR','WHART','THG','SIS','CKP','CPN','CPAXT','PCSGH','SJWD','HMPRO','TKS','QH','COM7','BJC','SPCG','SC','CENTEL','DCON','SPALI','BGRIM','MEGA','TTW','TKN','PTG','CPNREIT','RJH','SGP','BDMS','WHAUP','OSP','TK','BEM','PAP','CPALL','CPF','AWC','AH','BCH','CK','BAM','TTA','RATCH','PRM','M','ILM','BA','ASP','LPN','AP','WICE','BEAUTY','FSMART','EASTW','WHA','BPP','BANPU','VNG','SAPPE','III','SENA','TOA','TVO','ORI','IVL','ACE','AIE','AIT','AJ','AMATA','ANAN','BAY','BE8','BGC','BH','BKIH','CHG','CPNCG','CRC','EA','EGCO','FORTH','GC','GFPT','GLOBAL','GRAMMY','RS','S11','SAT','GUNKUL','HANA','HFT','HTC','ICHI','IMH','IP','KGI','LALIN','LH','LPH','NOBLE','ONEE','POPF','PSH','RBF','ROJNA','SAWAD','SIRI','SKN','SKR','SNC','SPC','SPRIME','SSP','SUPER','TFG','THANI','TIDLOR','TIPH','TQM','TRUE','TSE','TU','TYCN','UTP','VIBHA

In [86]:
sql = f"""
SELECT *
FROM buy
WHERE name NOT IN ('{stock_list_str}')
ORDER BY name
"""
print(sql)
df_tmp = pd.read_sql(sql, const)
df_tmp

SELECT *
FROM buy
WHERE name NOT IN ('SCGP','SCC','MST','KBANK','SCB','KTB','TTB','BBL','KKP','STANLY','TSTH','DCC','KCE','MBAX','OR','GGC','PTTGC','PTTEP','3BBIF','ADVANC','EPG','BCP','BCPG','VGI','SPRC','PLANB','PTL','TOP','IMPACT','TFFIF','KYE','BLAND','AOT','DRT','SINGER','JMART','JMT','SVI','LHK','GPSC','INOX','SMPC','ASK','DELTA','PSL','EGATIF','TTLPF','TR','GVREIT','BTSGIF','MINT','TMW','MC','LANNA','BTS','DIF','STA','PTT','NER','RCL','BLA','AIMIRT','CBG','DOHOME','MAJOR','TMT','WORK','TPIPL','SCCC','TIPCO','LIT','PDG','ASIAN','BEC','TCAP','PREB','ASW','STGT','TASCO','TPIPP','MTC','IRPC','GULF','SUPEREIF','MCS','SYNEX','WHAIR','WHART','THG','SIS','CKP','CPN','CPAXT','PCSGH','SJWD','HMPRO','TKS','QH','COM7','BJC','SPCG','SC','CENTEL','DCON','SPALI','BGRIM','MEGA','TTW','TKN','PTG','CPNREIT','RJH','SGP','BDMS','WHAUP','OSP','TK','BEM','PAP','CPALL','CPF','AWC','AH','BCH','CK','BAM','TTA','RATCH','PRM','M','ILM','BA','ASP','LPN','AP','WICE','BEAUTY','FSMART','EASTW','WHA','BPP','BANPU','VNG','SAPPE','III','SENA','TOA','TVO','ORI','IVL','ACE','AIE','AIT','AJ','AMATA','ANAN','BAY','BE8','BGC','BH','BKIH','CHG','CPNCG','CRC','EA','EGCO','FORTH','GC','GFPT','GLOBAL','GRAMMY','RS','S11','SAT','GUNKUL','HANA','HFT','HTC','ICHI','IMH','IP','KGI','LALIN','LH','LPH','NOBLE','ONEE','POPF','PSH','RBF','ROJNA','SAWAD','SIRI','SKN','SKR','SNC','SPC','SPRIME','SSP','SUPER','TFG','THANI','TIDLOR','TIPH','TQM','TRUE','TSE','TU','TYCN','UTP','VIBHA')
ORDER BY name

Empty DataFrame
Columns: [name, date, volbuy, price, volsell, volbal, active, dividend, period, grade]
Index: []

In [88]:
df_tmp.shape

(0, 10)

### Comparison check between EPS and Buy

In [91]:
sql = """
SELECT name FROM buy WHERE active = 1 ORDER BY name"""
buy = pd.read_sql(sql, const)
buy.shape

(27, 1)

In [95]:
sql = f'''
SELECT * 
FROM epss 
WHERE publish_date >= '{select_date}' 
AND quarter = {quarter}
'''
print(sql)
tdy_df = pd.read_sql(sql, conlt)
tdy_df.shape

SELECT *
FROM epss
WHERE publish_date >= '2026-01-01'
AND quarter = 4

(194, 14)

In [97]:
tdy_buy_df = tdy_df.merge(buy, on='name', how='inner')
tdy_buy_df.sort_values(by='name')

,id,name,year,quarter,q_amt,y_amt,aq_amt,ay_amt,q_eps,y_eps,aq_eps,ay_eps,ticker_id,publish_date
1,24890,3BBIF,2025,4,6429421,3961184,7044205,5279119,-0.25050,-0.5370,0.0000,0.0000,234,2026-02-03
2,24891,ADVANC,2025,4,14281630,9258911,47885902,35075357,4.80000,3.1100,16.1000,11.7900,6,2026-02-03
18,24994,AH,2025,4,105562,119895,731428,746961,0.32000,0.3700,2.1800,2.1500,9,2026-02-27
17,24993,AWC,2025,4,1866088,1859770,6388002,5850295,0.05820,0.0580,0.1995,0.1827,699,2026-02-26
19,24995,BCH,2025,4,259498,233040,1316360,1282371,0.11000,0.0900,0.5300,0.5100,51,2026-02-27
16,24992,CPF,2025,4,1085272,4172528,25197488,19558133,0.11000,0.5100,3.1200,2.3900,117,2026-02-26
15,24982,CPNREIT,2025,4,1484839,357438,3460976,1696069,0.00000,0.0000,0.0000,0.0000,647,2026-02-26
5,24927,DIF,2025,4,5589388,-7397987,13855643,656288,0.00000,0.0000,0.0000,0.0000,140,2026-02-18
24,25021,IVL,2025,4,-4697188,1095694,-7348393,-19262126,-0.88000,0.1200,-1.4700,-3.6500,231,2026-03-02
4,24908,JMT,2025,4,221722,400174,1029560,1615223,0.16000,0.2800,0.7100,1.1100,237,2026-02-11
10,24956,MCS,2025,4,263400,346777,960010,678604,0.55000,0.7200,2.0100,1.4200,293,2026-02-23
8,24930,NER,2025,4,395108,359321,1884525,1652466,0.21380,0.1945,1.0199,0.8943,680,2026-02-19
23,25020,ORI,2025,4,105152,-266145,719936,1051790,0.04280,-0.1084,0.2933,0.4286,339,2026-02-27
14,24981,PTG,2025,4,314288,228393,1021441,1021805,0.19000,0.1300,0.6100,0.6100,381,2026-02-25
7,24929,PTT,2025,4,25534645,9311516,90166373,90072026,0.89000,0.3200,3.1500,3.1500,383,2026-02-19
0,24888,PTTGC,2025,4,-5501682,-11738129,-14600390,-29810548,-1.41000,-2.6100,-3.6100,-6.6200,385,2026-02-09
9,24931,RCL,2025,4,1803382,3318461,8166901,9170542,2.17000,4.0100,9.8500,11.0700,396,2026-02-20
20,25017,SENA,2025,4,35749,97807,323614,399608,0.02480,0.0678,0.2244,0.2771,437,2026-02-27
3,24906,SINGER,2025,4,59940,-103465,105084,-42960,0.07000,-0.1200,0.1300,-0.0500,446,2026-02-12
6,24928,STA,2025,4,-325739,854339,-1265710,1670375,-0.21000,0.5600,-0.8200,1.0900,481,2026-02-19
11,24957,SYNEX,2025,4,193273,146914,769786,627721,0.23000,0.1700,0.9100,0.7400,495,2026-02-24
21,25018,TOA,2025,4,844394,450683,2917013,1919604,0.43719,0.2318,1.5000,0.9600,645,2026-02-27
22,25019,TVO,2025,4,521643,807667,2188791,2103105,0.59000,0.9000,2.4600,2.3600,585,2026-02-27
12,24958,WHAIR,2025,4,-176793,-116575,413649,316443,0.00000,0.0000,0.0000,0.0000,211,2026-02-23
13,24959,WHART,2025,4,390358,204671,2349806,1920947,0.00000,0.0000,0.0000,0.0000,622,2026-02-23

In [99]:
sql = """
SELECT * 
FROM tickers
ORDER BY name"""
print(sql)
tickers = pd.read_sql(sql, conpg)
tickers[['name','id','market']].shape

SELECT *
FROM tickers
ORDER BY name

(396, 3)

In [101]:
tmp_df = tdy_buy_df.merge(tickers, on='name', how='inner')
tmp_df.shape

(25, 22)

In [103]:
tmp_df[['name','id_y','market']].sort_values(by='name')

       name  id_y                                     market
1     3BBIF   241                                        SET
2    ADVANC     8                    SET50 / SETHD / SETTHSI
18       AH    11                             sSET / SETTHSI
17      AWC   668                            SET50 / SETTHSI
19      BCH    55                             SET100 / SETWB
16      CPF   121  SET50 / SETCLMV / SETHD / SETTHSI / SETWB
15  CPNREIT   127                                        SET
5       DIF   146                                        SET
24      IVL   238                            SET50 / SETTHSI
4       JMT   245                                      SET50
10      MCS   301                                       sSET
8       NER   649                                       sSET
23      ORI   347                   SET100 / SETHD / SETTHSI
14      PTG   387                   SET100 / SETHD / SETTHSI
7       PTT   389          SET50 / SETCLMV / SETHD / SETTHSI
0     PTTGC   391                  SET50 / SETCLMV / SETTHSI
9       RCL   401                           SET100 / SETCLMV
20     SENA   443                                       sSET
3    SINGER   452                                     SET100
6       STA   489                   SET100 / SETTHSI / SETWB
11    SYNEX   504                           SET100 / SETTHSI
21      TOA   562                                    SETTHSI
22      TVO   594                      SET / SETTHSI / SETWB
12    WHAIR   217                                        SET
13    WHART   630                                        SET

In [105]:
const.close()
conpg.commit()
conpg.close()
conmy.commit()
conmy.close()
conlt.commit()
conlt.close()

In [107]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y:%m:%d %H:%M:%S")
print(formatted_time)

2026:03:12 13:26:06