### port_lite database: stocks tables
### portmy database: profits, stocks tables
### portpg database: consensus, tickers tables
### csv files: consensus-ORD.csv

In [2]:
import pandas as pd
import numpy as np
import os

from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text
from pandas.tseries.offsets import BDay

engine = create_engine("sqlite:///c:\\ruby\\portmy\\db\\development.sqlite3")
conmy = engine.connect()
engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()
engine = create_engine('mysql+pymysql://root:@localhost:3306/stock')
const = engine.connect()

# Define a formatting function to format integers with zero decimal places and floats with two decimal places
def format_cell(x):
    if isinstance(x, int):
        return "{:,.0f}".format(x)
    elif isinstance(x, float):
        return "{:.2f}".format(x)
    else:
        return x
pd.options.display.max_rows = 40
#pd.options.display.float_format = '{:.2f}'.format

today = date.today()
print(today)

2026-05-19

In [4]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(1)
yesterday = today - num_business_days
#yesterday = yesterday.date()
print(f'today: {today}')
print(f'yesterday: {yesterday}')

today: 2026-05-19
yesterday: 2026-05-18 00:00:00

In [6]:
# find the beginning of the week for the given yesterday
week_start = yesterday.to_period('W').start_time
week_end = yesterday.to_period('W').end_time
week_start = week_start.date()
week_end = week_end.date()
print(f'week start: {week_start}')
print(f'week end: {week_end}')

week start: 2026-05-18
week end: 2026-05-24

In [8]:
print(week_start, yesterday)

2026-05-18 2026-05-18 00:00:00

### Restart and Run All Cells

In [11]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [13]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path (dat_path): {dat_path}") 
print(f"Google Drive path (god_path): {god_path}")
print(f"iCloudDrive path (icd_path): {icd_path}") 
print(f"Obsidian path (osd_path): {osd_path}")

User path: C:\Users\User
Current path: C:\Users\User\OneDrive\A4\Weekly
Base path: C:\Users\User\OneDrive\A4
Data path (dat_path): C:\Users\User\OneDrive\A4\Data
Google Drive path (god_path): C:\Users\User\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path (icd_path): C:\Users\User\iCloudDrive\Data
Obsidian path (osd_path): C:\Users\User\OneDrive\Documents\obsidian-git-sync\Data

In [15]:
cols = 'quarter price target_price upside buy hold sell yield max_price min_price pe pbv dly_vol beta'.split()
colt = 'name price target_price upside buy hold sell market sector subsector dly_vol beta yield'.split()
colu = 'price target_price upside buy hold sell mrkt yield'.split()

format_dict = {
    'latest_amt_y':'{:,}','previous_amt_y':'{:,}','inc_amt_y':'{:,}',   
    'latest_amt_q':'{:,}','previous_amt_q':'{:,}','inc_amt_q':'{:,}',    
    'q_amt_c':'{:,}','y_amt': '{:,}','inc_amt_py':'{:,}', 
    'q_amt_p': '{:,}','inc_amt_pq':'{:,}', 
    'inc_pct_y': '{:.2f}%','inc_pct_q': '{:.2f}%',
    'inc_pct_py': '{:.2f}%','inc_pct_pq': '{:.2f}%',
    'mean_pct': '{:.2f}%','std_pct': '{:.2f}%','upside': '{:.2f}%', 
    
    'price':'{:.2f}','target_price':'{:.2f}','diff':'{:.2f}',
    'eps_a':'{:.2f}','eps_b':'{:.2f}',                
    'pe':'{:.2f}','pbv':'{:.2f}',
    'yield':'{:.2f}%',
    
    'price':'{:.2f}','max_price':'{:.2f}','min_price':'{:.2f}',   
    'target':'{:.2f}','max':'{:.2f}','min':'{:.2f}',
    'pe':'{:.2f}','pbv':'{:.2f}',
    'paid_up':'{:,.2f}','market_cap':'{:,.2f}',   
    'daily_volume':'{:,.2f}','beta':'{:,.2f}', 
    'dly_vol':'{:,.2f}',    
}

In [17]:
sql = '''
SELECT *
FROM profits
LIMIT 1'''
my_profits = pd.read_sql(sql, conmy)
my_profits.dtypes

id                  int64
name               object
year                int64
quarter             int64
kind                int64
latest_amt_y        int64
previous_amt_y      int64
inc_amt_y           int64
inc_pct_y         float64
latest_amt_q        int64
previous_amt_q      int64
inc_amt_q           int64
inc_pct_q         float64
q_amt_c             int64
y_amt               int64
inc_amt_py          int64
inc_pct_py        float64
q_amt_p             int64
inc_amt_pq          int64
inc_pct_pq        float64
ticker_id           int64
mean_pct          float64
std_pct           float64
dtype: object

In [19]:
sql = '''
SELECT *
FROM stocks
LIMIT 1'''
lite_stocks = pd.read_sql(sql, conlite)
lite_stocks.dtypes

id                 int64
name              object
max_price        float64
min_price        float64
status            object
buy_target       float64
sell_target      float64
volume           float64
beta             float64
cost             float64
qty                int64
buy_spread         int64
sell_spread        int64
available_qty      int64
bl               float64
sh               float64
reason            object
market            object
dtype: object

In [21]:
sql = '''
SELECT *
FROM tickers
LIMIT 1'''
pg_tickers = pd.read_sql(sql, conpg)
pg_tickers.dtypes

id                     int64
name                  object
full_name             object
sector                object
subsector             object
market                object
website               object
created_at    datetime64[ns]
updated_at    datetime64[ns]
dtype: object

In [23]:
sql = '''
SELECT P.name, market
FROM profits P
JOIN tickers T
ON P.ticker_id = T.id 
ORDER BY P.name'''
my_profits = pd.read_sql(sql, conmy)
my_profits

       name                              market
0     3BBIF                                 SET
1    ADVANC             SET50 / SETHD / SETTHSI
2       BCP          SET100 / SETCLMV / SETTHSI
3    CENTEL            SET100 / SETTHSI / SETWB
4      COM7            SET100 / SETTHSI / SETWB
5     CPALL             SET50 / SETTHSI / SETWB
6   CPNREIT                                 SET
7       DIF                                 SET
8       FPT  SET100 / SET100FF / SETESG / SETWB
9      GULF           SET50 / SETCLMV / SETTHSI
10      KKP  SET100 / SETCLMV / SETHD / SETTHSI
11      MTC                     SET50 / SETTHSI
12      NER                                sSET
13     SCGP           SET50 / SETCLMV / SETTHSI
14      SIS                                sSET
15    THANI            SET100 / SETHD / SETTHSI
16      TOA                             SETTHSI
17    VIBHA                               SETWB
18      WHA            SET100 / SETHD / SETTHSI

### Create consensus from name-ttl and https://www.settrade.com/th/equities/quote/BCH/analyst-consensus

In [25]:
%pwd

'C:\\Users\\User\\OneDrive\\A4\\Weekly'

In [27]:
# Derive the base directory (to_dir) by removing the last folder ('Daily')
base_dir = os.path.dirname(base_path)
print(f"Base Directory : {base_path}")

Base Directory : C:\Users\User\OneDrive\A4

In [29]:
os.chdir(base_path)
%pwd

'C:\\Users\\User\\OneDrive\\A4'

In [33]:
!ruby ruby\\crt-consensus.rb

Start at: Tuesday, May 19 03:19 PM
name,target,max,min,buy,hold,sell
ADVANC   396.10 422.00 355.00  9  4  0   1
AEONTS   104.04 136.00  85.00  7  3  2   2
AH        15.71  17.00  14.80  5  2  0   3
AIMIRT    12.20  12.20  12.20  1  0  0   4
AIT        5.35   5.35   5.35  0  0  0   5
AMATA     24.22  35.00  15.40 11  2  1   6
AOT       60.17  80.00  50.00 11  6  1   7
AP         9.91  12.00   8.20 15  2  0   8
ASK       10.47  12.90   7.50  1  1  1   9
ASP        2.10   2.10   2.10  0  0  0  10
ASW        8.32   9.00   7.50  3  0  0  11
AWC        2.62   3.55   2.20  6  4  0  12
BA        18.07  24.30  11.70  7  0  0  13
BAM        7.61   8.90   6.00  6  0  0  14
BANPU      6.41   7.70   5.50  5  4  0  15
BBL      177.66 198.00 134.00 10  6  2  16
BCH       12.13  14.20  10.50 19  1  1  17
BCP       41.39  49.00  38.00 12  2  0  18
BCPG       9.68  12.00   7.60 12  1  0  19
BDMS      24.52  32.00  20.00 18  4  0  20
BEC        1.96   2.34   1.57  1  0  0  21
BEM        8.18  10.86   5.85 12  0  0  22
BGRIM     15.81  20.00  12.00 10  6  0  23
BH       190.08 216.00  25.00 17  2  1  24
BJC       17.81  25.00  14.80 12  3  0  25
BLA       23.70  24.40  23.00  2  0  0  26
BPP       12.30  13.00  11.60  0  0  0  27
BTS        3.60   5.40   2.59  1  5  0  28
BTSGIF     2.38   2.60   2.15  0  0  0  29
CBG       45.46  60.00  38.00  5  8  0  30
CENTEL    40.28  45.00  34.00 16  2  0  31
CHG        1.82   2.02   1.48 14  1  0  32
CK        21.82  25.90  18.50 13  2  0  33
CKP        3.00   3.90   2.00  7  2  1  34
COM7      29.77  32.00  25.00 12  0  0  35
CPALL     61.93  80.00  47.00 19  0  0  36
CPAXT     16.75  19.00  14.20  5 11  1  37
CPF       23.12  25.00  20.40 12  6  0  38
CPN       75.38  83.00  70.00 17  0  0  39
CPNREIT   11.83  12.60  10.60  2  1  0  40
CRC       23.11  27.00  19.00 12  5  0  41
DCC        1.44   1.56   1.36  1  2  0  42
DELTA    295.83 366.00 216.00  6  7  5  43
DIF       10.08  11.00   9.30  1  4  0  44
DOHOME     3.75   4.30   3.06  5  5  2  45
EGCO     129.75 145.00 117.00  5  5  0  46
EPG        4.16   5.00   3.40  5  1  0  47
FSMART    10.50  10.50  10.50  1  0  0  48
GFPT      10.18  13.10   8.00  5 10  2  49
GLOBAL     7.92   9.00   7.30 13  0  0  50
GPSC      44.56  56.00  37.00 13  6  0  51
GULF      72.34  91.00  65.00 17  0  0  52
GUNKUL     3.55   4.00   2.70  5  1  0  53
HANA      27.64  38.00  16.00  8  4  4  54
HMPRO      7.48  10.00   6.00 10  7  0  55
HTC       15.55  15.60  15.50  0  0  0  56
ICHI      13.98  15.50  11.90  5  4  0  57
III        5.19   5.50   4.58  3  0  0  58
ILM       16.31  18.00  15.00  2  1  0  59
IMPACT    12.30  12.60  12.00  1  1  0  60
IRPC       1.76   2.20   1.20  2  8  5  61
IVL       25.97  29.00  21.00 11  4  1  62
3BBIF      7.30   8.70   6.10  1  2  1  63
JMART      8.00   8.00   8.00  0  0  0  64
JMT       10.38  13.00   8.50  1  2  1  65
KBANK    208.86 232.00 190.00 13  2  0  66
KCE       29.60  40.00  17.80  6  1  8  67
KKP       83.20  92.00  71.00  8  8  0  68
KTB       36.94  41.00  34.00 15  2  0  69
KTC       35.60  47.00  26.00  9  3  1  70
LH         3.97   4.50   3.20  2 10  1  71
LPN        1.39   1.65   1.30  0  1  0  72
M         20.04  24.00  17.50  3  3  0  73
MAJOR      9.76  11.00   9.10  7  0  0  74
MC        12.13  13.30  11.10  1  2  0  75
MEGA      40.66  45.00  35.00  5  3  0  76
MINT      31.37  38.00  24.90 15  0  0  77
MST        7.00   7.00   7.00  0  0  0  78
MTC       41.53  55.00  35.80 17  0  0  79
NER        5.02   5.60   4.50  4  5  0  80
ONEE       2.96   3.20   2.40  4  2  1  81
OR        14.82  17.30  11.90 12  6  0  82
ORI        1.87   2.42   1.00  3  4  1  83
OSP       18.32  22.00  13.40 10  9  0  84
PLANB      5.61   6.50   4.70  8  2  0  85
PRM        9.38   9.70   8.45  6  0  0  86
PSH        3.26   3.98   2.78  1  1  5  87
PSL        7.48   8.15   6.80  2  1  0  88
PTG        8.73  11.50   7.10  5  9  0  89
PTT       40.01  45.00  31.00 12  5  0  90
PTTEP    171.85 197.00 159.00 16  4  0  91
PTTGC     38.57  46.00  24.00 10  5  3  92
QH         1.39   1.77   1.10  2  7  2  93
RATCH     32.94  42.00  29.00  7  4  0  94
RBF        3.99   4.40   3.56  0  0  0  95
RCL       34.00  35.00  33.00  1  1  0  96
RJH       14.67  15.50  14.00  2  1  0  97
SAPPE     30.73  33.00  28.00  1  9  0  98
SAT       15.69  17.70  14.20  1  7  1  99
SAWAD     31.10  36.00  21.00 13  2  1 100
SC         2.38   2.75   2.10  9  0  0 101
SCB      143.43 170.00 126.00  4 10  0 102
SCC      231.07 290.00 150.00  6  6  3 103
SCCC     186.33 200.00 174.00  3  0  0 104
SCGP      27.83  33.75  21.00 16  2  0 105
SGP       10.60  10.60  10.60  1  0  0 106
SIRI       1.65   1.80   1.52 14  2  0 107
SIS       24.68  25.35  24.00  1  1  0 108
SJWD      11.48  13.40  10.00  9  0  0 109
SPALI     17.15  21.60  14.50  5  9  2 110
SPRC       8.37  10.30   7.00 12  5  0 111
SSP        4.90   5.00   4.80  2  0  0 112
STA       18.10  22.00  14.80  5  2  0 113
STGT      10.80  14.00   9.00  1  3  0 114
SYNEX     11.57  12.60  10.70  9  0  0 115
TASCO     15.83  18.00  14.20  5  2  0 116
TCAP      60.68  68.00  54.00  3  5  0 117
TFFIF      7.25   7.50   7.00  1  1  0 118
TFG       10.86  15.05   6.20  5  6  0 119
THANI      2.07   2.36   1.70  4  2  0 120
THG       10.30  10.30  10.30  0  0  0 121
TISCO    108.77 117.00  91.50  1 12  2 122
TKN        4.30   4.50   4.10  0  0  0 123
TOA       14.43  16.00  12.70  0  0  0 124
TOP       53.12  73.00  43.00  9 10  1 125
TQM       16.35  18.00  15.00  4  0  0 126
TRUE      16.66  19.00  15.10 12  0  0 127
TTA        5.30   5.30   5.30  1  0  0 128
TTB        2.26   2.60   2.00  3 12  1 129
TTW       10.14  11.00   9.50  2  3  0 130
TU        13.64  15.50  11.50 14  4  0 131
TVO       27.52  30.00  25.00  3  2  0 132
UTP       10.00  10.00  10.00  0  0  0 133
VGI        1.22   1.22   1.22  0  0  0 134
WHA        5.07   5.80   4.70 13  3  0 135
WHAIR      8.27   8.60   7.60  3  0  0 136
WHART     11.30  11.40  11.20  1  1  0 137
WHAUP      5.71   6.10   5.15  6  1  0 138
End at: Tuesday, May 19 03:25 PM

In [35]:
os.chdir(current_path)
%pwd

'C:\\Users\\User\\OneDrive\\A4\\Weekly'

In [37]:
file_name   = 'consensus.csv'
input_file = os.path.join(dat_path, file_name)
print(f"Input file : {input_file}")

Input file : C:\Users\User\OneDrive\A4\Data\consensus.csv

In [39]:
consensus = pd.read_csv(input_file, sep=',', index_col=None)
consensus = consensus.rename(columns=str.lower)
consensus.shape

(138, 7)

In [41]:
consensus.query('buy + hold + sell == 0')

       name  target    max    min  buy  hold  sell
4       AIT    5.35   5.35   5.35    0     0     0
9       ASP    2.10   2.10   2.10    0     0     0
26      BPP   12.30  13.00  11.60    0     0     0
28   BTSGIF    2.38   2.60   2.15    0     0     0
55      HTC   15.55  15.60  15.50    0     0     0
63    JMART    8.00   8.00   8.00    0     0     0
77      MST    7.00   7.00   7.00    0     0     0
94      RBF    3.99   4.40   3.56    0     0     0
120     THG   10.30  10.30  10.30    0     0     0
122     TKN    4.30   4.50   4.10    0     0     0
123     TOA   14.43  16.00  12.70    0     0     0
132     UTP   10.00  10.00  10.00    0     0     0
133     VGI    1.22   1.22   1.22    0     0     0

### End of Process

In [44]:
const.close()
conlite.close()
conpg.close()
conmy.close()

In [46]:
current_time = datetime.now()
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-05-19 15:28:34