In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/wc22_development"
)
wc22 = engine.connect()
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/wc26_development"
)
wc26 = engine.connect()

output_path = "../data/"

In [2]:
sql = """
SELECT *
FROM teams LIMIT 1
"""
wc22_teams = pd.read_sql(sql, wc22)
wc22_teams.dtypes

id          int64
name       object
group      object
ranking     int64
flag       object
year        int64
dtype: object

In [3]:
sql = """
SELECT *
FROM teams LIMIT 1
"""
wc26_teams = pd.read_sql(sql, wc26)
wc26_teams.dtypes

id                        int64
name                     object
group                    object
ranking                   int64
flag                     object
confederation            object
created_at       datetime64[ns]
updated_at       datetime64[ns]
dtype: object

In [4]:
sql = """
SELECT *
FROM fixtures LIMIT 1
"""
wc22_fixtures = pd.read_sql(sql, wc22)
wc22_fixtures.dtypes

id                       int64
round_id                 int64
date                    object
session_id               int64
home_id                  int64
away_id                  int64
channel_id               int64
criterium_id             int64
created_at      datetime64[ns]
updated_at      datetime64[ns]
year                     int64
dtype: object

In [5]:
sql = """
SELECT *
FROM fixtures LIMIT 1
"""
wc26_fixtures = pd.read_sql(sql, wc26)
wc26_fixtures.dtypes

id                       int64
round_id                 int64
date                    object
session_id               int64
home_team_id             int64
away_team_id             int64
channel_id               int64
created_at      datetime64[ns]
updated_at      datetime64[ns]
criterium_id            object
dtype: object

In [6]:
sql = """
SELECT *
FROM criteria LIMIT 1
"""
wc22_criteria = pd.read_sql(sql, wc22)
wc22_criteria.dtypes

id                     int64
show_date             object
created_at    datetime64[ns]
updated_at    datetime64[ns]
dtype: object

In [7]:
sql = """
SELECT *
FROM criteria LIMIT 1
"""
wc26_criteria = pd.read_sql(sql, wc26)
wc26_criteria.dtypes

id                     int64
show_date             object
created_at    datetime64[ns]
updated_at    datetime64[ns]
dtype: object

In [8]:
sql = """
SELECT *
FROM sessions LIMIT 1
"""
wc22_sessions = pd.read_sql(sql, wc22)
wc22_sessions.dtypes

id           int64
sequence     int64
time        object
dtype: object

In [9]:
sql = """
SELECT *
FROM sessions LIMIT 1
"""
wc26_sessions = pd.read_sql(sql, wc26)
wc26_sessions.dtypes

id                     int64
sequence               int64
time                  object
created_at    datetime64[ns]
updated_at    datetime64[ns]
dtype: object

In [10]:
sql = """
SELECT *
FROM sessions ORDER BY sequence
"""
wc26_sessions = pd.read_sql(sql, wc26)
wc26_sessions

,id,sequence,time,created_at,updated_at
0,31,1,00:00:00,2026-06-19 08:46:26.772329,2026-06-19 08:46:26.772329
1,32,2,00:30:00,2026-06-19 08:46:26.773309,2026-06-19 08:46:26.773309
2,33,3,01:00:00,2026-06-19 08:46:26.774298,2026-06-19 08:46:26.774298
3,34,4,01:30:00,2026-06-19 08:46:26.775277,2026-06-19 08:46:26.775277
4,35,5,02:00:00,2026-06-19 08:46:26.776257,2026-06-19 08:46:26.776257
5,36,6,02:30:00,2026-06-19 08:46:26.777242,2026-06-19 08:46:26.777242
6,37,7,03:00:00,2026-06-19 08:46:26.778222,2026-06-19 08:46:26.778222
7,38,8,03:30:00,2026-06-19 08:46:26.779211,2026-06-19 08:46:26.779211
8,39,9,04:00:00,2026-06-19 08:46:26.780194,2026-06-19 08:46:26.780194
9,40,10,04:30:00,2026-06-19 08:46:26.781174,2026-06-19 08:46:26.781174
10,41,11,05:00:00,2026-06-19 08:46:26.782209,2026-06-19 08:46:26.782209
11,42,12,05:30:00,2026-06-19 08:46:26.783202,2026-06-19 08:46:26.783202
12,43,13,06:00:00,2026-06-19 08:46:26.784287,2026-06-19 08:46:26.784287
13,44,14,06:30:00,2026-06-19 08:46:26.785269,2026-06-19 08:46:26.785269
14,45,15,07:00:00,2026-06-19 08:46:26.786251,2026-06-19 08:46:26.786251
15,46,16,07:30:00,2026-06-19 08:46:26.787334,2026-06-19 08:46:26.787334
16,47,17,08:00:00,2026-06-19 08:46:26.788322,2026-06-19 08:46:26.788322
17,48,18,08:30:00,2026-06-19 08:46:26.789312,2026-06-19 08:46:26.789312
18,49,19,09:00:00,2026-06-19 08:46:26.790294,2026-06-19 08:46:26.790294
19,50,20,09:30:00,2026-06-19 08:46:26.791283,2026-06-19 08:46:26.791283
20,51,21,10:00:00,2026-06-19 08:46:26.792265,2026-06-19 08:46:26.792265
21,52,22,10:30:00,2026-06-19 08:46:26.793246,2026-06-19 08:46:26.793246
22,53,23,11:00:00,2026-06-19 08:46:26.794226,2026-06-19 08:46:26.794226
23,54,24,11:30:00,2026-06-19 08:46:26.795246,2026-06-19 08:46:26.795246
24,55,25,12:00:00,2026-06-19 08:46:26.796241,2026-06-19 08:46:26.796241
25,56,26,12:30:00,2026-06-19 08:46:26.797223,2026-06-19 08:46:26.797223
26,57,27,13:00:00,2026-06-19 08:46:26.798205,2026-06-19 08:46:26.798205
27,58,28,13:30:00,2026-06-19 08:46:26.799240,2026-06-19 08:46:26.799240
28,59,29,14:00:00,2026-06-19 08:46:26.800225,2026-06-19 08:46:26.800225
29,60,30,14:30:00,2026-06-19 08:46:26.801217,2026-06-19 08:46:26.801217
30,61,31,15:00:00,2026-06-19 08:46:26.802293,2026-06-19 08:46:26.802293
31,62,32,15:30:00,2026-06-19 08:46:26.803341,2026-06-19 08:46:26.803341
32,63,33,16:00:00,2026-06-19 08:46:26.804331,2026-06-19 08:46:26.804331
33,64,34,16:30:00,2026-06-19 08:46:26.805318,2026-06-19 08:46:26.805318
34,17,35,17:00:00,2026-06-19 08:46:26.736288,2026-06-19 08:46:26.736288
35,18,36,17:30:00,2026-06-19 08:46:26.757429,2026-06-19 08:46:26.757429
36,19,37,18:00:00,2026-06-19 08:46:26.759001,2026-06-19 08:46:26.759001
37,20,38,18:30:00,2026-06-19 08:46:26.760399,2026-06-19 08:46:26.760399
38,21,39,19:00:00,2026-06-19 08:46:26.761740,2026-06-19 08:46:26.761740
39,22,40,19:30:00,2026-06-19 08:46:26.762859,2026-06-19 08:46:26.762859
40,23,41,20:00:00,2026-06-19 08:46:26.763954,2026-06-19 08:46:26.763954
41,24,42,20:30:00,2026-06-19 08:46:26.765160,2026-06-19 08:46:26.765160
42,25,43,21:00:00,2026-06-19 08:46:26.766258,2026-06-19 08:46:26.766258
43,26,44,21:30:00,2026-06-19 08:46:26.767315,2026-06-19 08:46:26.767315
44,27,45,22:00:00,2026-06-19 08:46:26.768303,2026-06-19 08:46:26.768303
45,28,46,22:30:00,2026-06-19 08:46:26.769294,2026-06-19 08:46:26.769294
46,29,47,23:00:00,2026-06-19 08:46:26.770273,2026-06-19 08:46:26.770273
47,30,48,23:30:00,2026-06-19 08:46:26.771338,2026-06-19 08:46:26.771338

In [24]:
sql = """
SELECT F.date, S.id, S.sequence
FROM fixtures F
JOIN sessions S ON F.session_id = S.id
ORDER BY date asc, S.sequence asc
"""
wc26_fixtures = pd.read_sql(sql, wc26)
wc26_fixtures

          date  id  sequence
0   2026-06-12  35         5
1   2026-06-12  49        19
2   2026-06-13  35         5
3   2026-06-13  47        17
4   2026-06-14  35         5
..         ...  ..       ...
67  2026-06-28  37         7
68  2026-06-28  43        13
69  2026-06-28  43        13
70  2026-06-28  49        19
71  2026-06-28  49        19

[72 rows x 3 columns]