In [45]:
import pandas as pd
import numpy as np
import os
from sqlalchemy import create_engine, text
from glob import glob

# Database connections
engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()
engine = create_engine('mysql+pymysql://root:@localhost:3306/portfolio_development')
conpf = engine.connect()
engine = create_engine("postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development")
conpg = engine.connect()
engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.options.display.max_rows = None
data_path = "../data/"
format_dict = {
               'q_amt':'{:,}','y_amt':'{:,}','aq_amt':'{:,}','ay_amt':'{:,}','shares':'{:,}'
}

In [3]:
year = 2025
quarter = 4
print(f"Year: {year}, Quarter: {quarter}")

Year: 2025, Quarter: 4

In [5]:
sql = f"""
SELECT name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, ticker_id
FROM epss
WHERE year = {year} AND quarter = {quarter}
ORDER BY name
"""
print(sql)
epss_df = pd.read_sql(sql, conlt)
epss_df.shape

SELECT name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, ticker_id
FROM epss
WHERE year = 2025 AND quarter = 4
ORDER BY name

(202, 8)

In [7]:
epss_df['grade'] = 0
epss_df.columns

Index(['name', 'year', 'quarter', 'q_amt', 'y_amt', 'aq_amt', 'ay_amt',
       'ticker_id', 'grade'],
      dtype='object')

In [9]:
def grade(vals):
    qc, qp, aqc, aqp = vals
    if aqc >= aqp:
        if qc >= qp:
            return 1
        else:
            return 2
    else:
        if qc < qp:
            return 4
        else:
            return 3

In [11]:
epss_df["grade"] = epss_df[["q_amt", "y_amt","aq_amt", "ay_amt"]].apply(grade, axis=1)
epss_df.shape

(202, 9)

In [15]:
g1 = epss_df[epss_df["grade"] == 1]
g1.shape

(74, 9)

In [17]:
g2 = epss_df[epss_df["grade"] == 2]
g2.shape

(37, 9)

In [19]:
g3 = epss_df[epss_df["grade"] == 3]
g3.shape

(26, 9)

In [21]:
g4 = epss_df[epss_df["grade"] == 4]
g4.shape

(65, 9)

In [23]:
#g4.style.format(format_dict)

In [25]:
#g3.style.format(format_dict)

In [27]:
#g2.style.format(format_dict)

In [29]:
g1.style.format(format_dict)

In [33]:
# Get active stocks in portfolio
sql = '''
SELECT period, name, volbuy AS shares
FROM buy
WHERE active = 1
ORDER BY period, name
'''
df_buy = pd.read_sql(sql, const)
df_buy['shares'] = df_buy['shares'].astype('int64')
print("\nActive stocks:")
print(df_buy)

Active stocks:
   period     name  shares
0       1    PTTGC    6000
1       1   SINGER    6000
2       1      STA   10000
3       2    3BBIF  120000
4       2  CPNREIT   55000
5       2      DIF   45000
6       2   GVREIT   69000
7       2      MCS   75000
8       2      NER   27000
9       2      PTT    7500
10      2     SENA  105000
11      2    TFFIF   25000
12      2    WHAIR   50000
13      2    WHART   20000
14      3   ADVANC     100
15      3       AH    1200
16      3      AWC    9000
17      3      BCH    4000
18      3      CPF   10000
19      3      PTG    3600
20      3      RCL   27000
21      3    SYNEX   17500
22      3      TOA    1000
23      3      TVO    4000
24      4      IVL    7200
25      4      JMT    7000
26      4      ORI   50000

In [47]:
df_merge  = pd.merge(g1, df_buy, on = 'name', how='inner')
df_merge.style.format(format_dict)

In [55]:
df_merge  = pd.merge(g4, df_buy, on = 'name', how='inner')
df_merge.style.format(format_dict)

In [57]:
file_name = '254-worse.csv'
data_file = data_path + file_name
df_merge.to_csv(data_file, index=False, header=True)

### New feature: Exempt SET50 & SET100

In [198]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [200]:
### SET100 b
file_name = "StockQuotation.xlsx"
# Get the user's home directory
user_path = os.path.expanduser('~')
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
#df_S100 = df_S100[df_S100['Total Volume'] != '-']
df_S100[colu].shape

(100, 9)

In [202]:
# --- Delete SET100 stocks from g4 group ---

# Get the list of SET100 symbols from df_S100
set100_symbols = df_S100['Symbol'].tolist()
print(f"SET100 symbols (first 10): {set100_symbols[:10]} ...")

# Find stocks in g4 that are also in SET100
deleted_stocks = g4[g4['name'].isin(set100_symbols)]
print(f"\nNumber of stocks deleted from g4 (in SET100): {len(deleted_stocks)}")
print("Deleted stocks:")
display(deleted_stocks[['name', 'grade']])  # Show only relevant columns, or use print(deleted_stocks)

# Create the remaining g4 group (exclude SET100 stocks)
g4_remaining = g4[~g4['name'].isin(set100_symbols)]
print(f"\nNumber of stocks remaining in g4 after deleting SET100: {len(g4_remaining)}")
print("Remaining stocks:")
display(g4_remaining[['name', 'grade']])   # Or display the full DataFrame

SET100 symbols (first 10): ['AAV', 'ADVANC', 'AEONTS', 'AMATA', 'AOT', 'AP', 'AURA', 'AWC', 'BA', 'BAM'] ...

Number of stocks deleted from g4 (in SET100): 25
Deleted stocks:

       name  grade
10      AOT      4
11       AP      4
17       BA      4
25     BDMS      4
32       BH      4
37      CBG      4
54   DOHOME      4
59     EGCO      4
66   GLOBAL      4
74    HMPRO      4
84    JMART      4
85      JMT      4
86    KBANK      4
87      KCE      4
94       LH      4
99        M      4
104    MEGA      4
125   PTTEP      4
130     RCL      4
153   SPALI      4
159     STA      4
160    STGT      4
165   TASCO      4
174   TISCO      4
190      TU      4

Number of stocks remaining in g4 after deleting SET100: 40
Remaining stocks:

       name  grade
1       ACE      4
3        AH      4
4       AIE      4
5    AIMIRT      4
9      ANAN      4
14      ASP      4
26      BE8      4
44    CPAXT      4
47    CPNCG      4
50      DCC      4
51     DCON      4
57    EASTW      4
65      GGC      4
68   GRAMMY      4
71   GVREIT      4
73      HFT      4
75      HTC      4
77      III      4
80     INOX      4
92    LALIN      4
93    LANNA      4
106     MST      4
115   PCSGH      4
121     PSH      4
129     RBF      4
132   ROJNA      4
133      RS      4
135   SAPPE      4
141    SCCC      4
143    SENA      4
149     SKN      4
155    SPCG      4
158     SSP      4
163     SVI      4
173    TIPH      4
176     TKN      4
182   TPIPP      4
193     UTP      4
195     VNG      4
199   WHAUP      4

In [204]:
g4.shape

(65, 9)

In [206]:
deleted_stocks.shape

(25, 9)

In [208]:
g4_remaining.shape

(40, 9)

### End of New feature

In [210]:
mask41 = g4_remaining.aq_amt < 200_000
g4_remaining[mask41].style.format(format_dict)

In [212]:
g4_remaining[mask41].style.format(format_dict)

In [214]:
mask42 = g4_remaining.q_amt < 100_000
g4_remaining[mask42].style.format(format_dict)

In [216]:
mask43 = g4_remaining.ay_amt < 200_000
g4_remaining[mask43].style.format(format_dict)

In [218]:
filter1 = g4_remaining[mask41 & mask42 & mask43]
filter1.sort_values(by='name',ascending=True).style.format(format_dict)

In [220]:
filter1.shape

(6, 9)

In [222]:
loss = filter1['name']
file_name = 'loss.csv'
data_file = data_path + file_name
loss.to_csv(data_file, index=False, header=False)

In [224]:
sql = '''
SELECT name
FROM exempts
ORDER BY name'''
exempts = pd.read_sql(sql, conlt)
exempts.shape

(408, 1)

In [226]:
file_name = 'exempts-25q4.csv'
data_file = data_path + file_name
data_file

'../data/exempts-25q4.csv'

In [228]:
exempts.to_csv(data_file, index=False, header=False)

In [230]:
exempts.shape

(408, 1)

In [232]:
df_merge = pd.merge(filter1, exempts, on='name', how='outer', indicator=True)
df_merge1 = df_merge[df_merge['_merge'] == 'left_only']
df_merge1

,name,year,quarter,q_amt,y_amt,aq_amt,ay_amt,ticker_id,grade,_merge
92,DCON,2025.0,4.0,15777.0,20349.0,8291.0,59173.0,136.0,4.0,left_only

In [234]:
sql = '''
SELECT DISTINCT name 
FROM buys B
JOIN stocks S
ON B.stock_id = S.id
ORDER BY name'''
buys = pd.read_sql(sql, conpf)
buys.shape

(150, 1)

In [236]:
df_merge1 = df_merge1.drop(columns=['_merge'])
df_merge1.shape

(1, 9)

In [238]:
df_merge2 = pd.merge(df_merge1, buys, on='name', how='outer', indicator=True)
final2 = df_merge2[df_merge2['_merge'] == 'left_only']
final2

Empty DataFrame
Columns: [name, year, quarter, q_amt, y_amt, aq_amt, ay_amt, ticker_id, grade, _merge]
Index: []

In [240]:
sr = final2['name']
file_name = 'loss.csv'
data_file = data_path + file_name
sr.to_csv(data_file, index=False, header=False)

In [242]:
rcds = sr.values.tolist()
rcds

[]

In [244]:
for rcd in rcds:
    print(rcd)

In [246]:
sql = '''
SELECT COUNT(*)
FROM exempts'''
tmp_bf = pd.read_sql(sql, conlt)
tmp_bf

   COUNT(*)
0       408

In [248]:
from sqlalchemy import text

for rcd in rcds:
    conlt.execute(text("INSERT INTO exempts (name) VALUES(:name)"), {"name": rcd})
conlt.commit()

In [250]:
sql = "SELECT COUNT(*) FROM exempts"
tmp_af = pd.read_sql(sql, conlt)
tmp_af

   COUNT(*)
0       408