### Restart and Run All
#### Input file: C:\Users\PC1\OneDrive\A5\Data\price-hilo.csv
#### Update file: C:\Ruby\PortPg\db

In [2]:
import os
import pandas as pd
from datetime import date, timedelta, datetime
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/portpg_development"
)
conpg = engine.connect()

# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-04-10 19:55:03

In [3]:
sql = '''
SELECT *
FROM stocks
'''
stocks = pd.read_sql(sql, conpg)
stocks.sample(5)

,id,name,market,price,max_price,min_price,pe,pbv,paid_up,market_cap,daily_volume,beta,ticker_id,created_at,updated_at
122,926,TPIPP,SETTHSI,1.89,2.44,1.66,9.00,0.94,8400.00,29232.00,11.08,0.54,569,2022-05-17 19:05:48.058568,2026-04-08
100,951,BE8,mai,5.45,12.40,4.10,122.44,10.74,120.32,13573.09,149.36,1.33,721,2022-08-05 10:28:19.003762,2026-03-13
57,759,BTSGIF,SET,2.58,2.84,2.46,999.99,0.58,53533.21,22457.44,25.78,0.43,87,2022-05-17 18:59:06.334996,2026-04-08
173,825,KTC,SET50 / SETTHSI,31.00,47.75,21.80,22.16,4.97,2578.33,147609.63,407.59,0.99,266,2022-05-17 18:59:06.576500,2026-04-08
60,762,CHG,SET100 / SETHD / SETWB,1.43,1.94,1.36,9.71,5.76,1100.00,41800.00,144.55,0.21,101,2022-05-17 18:59:06.345563,2026-04-08

In [4]:
# Get the current working directory
current_path = os.getcwd()
#print(f"Current path: {current_path}") 
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#print(f"Base path (base_path): {base_path}") 
dat_path = os.path.join(base_path, "Data")
#print(f"Data path (dat_path): {dat_path}") 

file_name = 'price-hilo.csv'
input_file = os.path.join(dat_path, file_name )
print(f"Input file : {input_file}")

Input file : C:\Users\PC1\OneDrive\A4\Data\price-hilo.csv

In [5]:
in_df = pd.read_csv(input_file)
in_df.sample(5)

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
66,GUNKUL,2.40,2.40,2.48,1.31,2.58,-3.23,2026-04-09
178,VNG,2.08,2.06,2.14,1.64,2.28,0.00,2026-04-09
23,BDMS,18.80,18.70,19.10,17.40,24.90,-1.57,2026-04-09
133,SGP,7.90,7.90,8.00,5.00,8.25,-1.25,2026-04-09
42,COM7,21.40,21.40,22.10,16.70,28.00,-3.17,2026-04-09

In [6]:
# Logic to update year_low and year_high based on conditions
in_df.loc[in_df['today_low'] < in_df['year_low'], 'year_low'] = in_df['today_low']
in_df.loc[in_df['today_high'] > in_df['year_high'], 'year_high'] = in_df['today_high']

In [7]:
in_df.sample(5)

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
176,VGI,0.88,0.88,0.91,0.77,2.36,-3.30,2026-04-09
118,QH,1.39,1.39,1.40,1.15,1.63,-0.71,2026-04-09
30,BJC,15.10,15.00,15.30,12.80,24.60,-0.66,2026-04-09
119,RATCH,30.25,30.00,30.25,22.70,32.50,-0.82,2026-04-09
145,STGT,10.50,10.40,10.80,5.10,11.40,-2.78,2026-04-09

### Update table Stocks in PortPG Database, columns max_price & min_price with 
### year_high & year_low from price-hilo.csv

In [9]:
for index, row in in_df.iterrows():
    sql = text('''
        UPDATE stocks
        SET price = :price, max_price = :max_price, min_price = :min_price, updated_at = :updated_at 
        WHERE name = :name
    ''')
    
    params = {
        'price': float(row['price']),
        'max_price': float(row['year_high']),
        'min_price': float(row['year_low']),
        'updated_at': row['updated_at'],
        'name': str(row['name'])
    }
    
    conpg.execute(sql, params)

In [10]:
# Commit the changes
conpg.commit()
conpg.close()

In [11]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-04-10 19:55:03