### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
yesterday = today - timedelta(days=1)
print(today, yesterday)

2026-03-16 2026-03-15

In [4]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-16 20:28:10

### Restart & Run All Cells

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\PC1\OneDrive\Downloads\Datasets

In [7]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Datasets path : C:\Users\PC1\OneDrive\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [9]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [11]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
df_S100[colu].shape

(100, 9)

In [12]:
df_S100.query('Symbol == ("ADVANC","BCH","IVL","JMT","PTTGC","RCL","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,ADVANC,-,370.00,7,1.93,365.00,373.00,363.00,-,0.00,7363602,2723427.24,543100,370.00,371.00,23800
12,BCH,-,10.20,0.10,0.99,10.20,10.20,10.00,2000000,20200.00,10179202,103249.89,106000,10.10,10.20,225600
47,IVL,-,20.10,0.40,2.03,20.20,20.20,19.70,-,0.00,23626202,473238.62,419500,20.00,20.10,19700
50,JMT,-,8.65,-0.10,-1.14,8.80,8.90,8.65,-,0.00,12182252,106197.45,27300,8.65,8.70,28400
71,PTTGC,-,28.75,0.50,1.77,28.75,29.25,27.75,-,0.00,30635789,874881.65,1794300,28.75,29.00,1382600
74,RCL,-,30.00,0.50,1.69,29.25,30.25,29.00,-,0.00,3048582,90719.05,82000,29.75,30.00,78600
84,STA,-,16.10,0.60,3.87,15.70,16.30,15.60,-,0.00,20283261,324491.46,682600,16.00,16.10,63300

In [13]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].shape

(100, 9)

In [14]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
2,AH,-,13.30,-,-,13.30,13.30,13.10,-,0,46130,607.95,200,13.20,13.30,39200
39,MCS,-,9.50,-0.05,-0.52,9.60,9.70,9.50,-,0,1042670,10025.47,69400,9.50,9.55,300
50,ORI,-,1.85,-0.05,-2.63,1.90,1.90,1.85,-,0,1427551,2666.25,69800,1.84,1.85,1900
73,SINGER,-,5.45,-0.05,-0.91,5.50,5.65,5.45,-,0,1858422,10254.41,29900,5.45,5.50,34100
83,SYNEX,-,9.55,0.05,0.53,9.50,9.55,9.40,-,0,403899,3834.04,64500,9.50,9.55,107300

In [15]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].shape

(57, 9)

In [16]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,10.20,0.10,0.99,10.20,10.20,10.00,2000000,20200.00,10179202,103249.89,106000,10.10,10.20,225600
24,IVL,-,20.10,0.40,2.03,20.20,20.20,19.70,-,0.00,23626202,473238.62,419500,20.00,20.10,19700
38,PTTGC,-,28.75,0.50,1.77,28.75,29.25,27.75,-,0.00,30635789,874881.65,1794300,28.75,29.00,1382600
41,RCL,-,30.00,0.50,1.69,29.25,30.25,29.00,-,0.00,3048582,90719.05,82000,29.75,30.00,78600
53,TOA,-,12.50,-0.20,-1.57,12.60,13.00,12.40,-,0.00,3752273,47270.02,198500,12.50,12.60,69600

In [17]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].shape

(30, 9)

In [18]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
6,JMT,-,8.65,-0.10,-1.14,8.80,8.90,8.65,-,0.00,12182252,106197.45,27300,8.65,8.70,28400
19,RCL,-,30.00,0.50,1.69,29.25,30.25,29.00,-,0.00,3048582,90719.05,82000,29.75,30.00,78600

In [19]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].shape

(122, 9)

In [20]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMT","NER","ORI","PTTGC","STA","SYNEX","TOA","TVO","VIBHA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.04,-,-,2.04,2.08,2.02,-,0.00,40312326,82857.48,775600,2.04,2.06,1083000
13,BCH,-,10.20,0.10,0.99,10.20,10.20,10.00,2000000,20200.00,10179202,103249.89,106000,10.10,10.20,225600
48,IVL,-,20.10,0.40,2.03,20.20,20.20,19.70,-,0.00,23626202,473238.62,419500,20.00,20.10,19700
50,JMT,-,8.65,-0.10,-1.14,8.80,8.90,8.65,-,0.00,12182252,106197.45,27300,8.65,8.70,28400
66,NER,-,4.68,-0.02,-0.43,4.68,4.72,4.64,-,0.00,6321935,29579.54,505700,4.68,4.70,38400
68,ORI,-,1.85,-0.05,-2.63,1.90,1.90,1.85,-,0.00,1427551,2666.25,69800,1.84,1.85,1900
80,PTTGC,-,28.75,0.50,1.77,28.75,29.25,27.75,-,0.00,30635789,874881.65,1794300,28.75,29.00,1382600
101,STA,-,16.10,0.60,3.87,15.70,16.30,15.60,-,0.00,20283261,324491.46,682600,16.00,16.10,63300
104,SYNEX,-,9.55,0.05,0.53,9.50,9.55,9.40,-,0.00,403899,3834.04,64500,9.50,9.55,107300
112,TOA,-,12.50,-0.20,-1.57,12.60,13.00,12.40,-,0.00,3752273,47270.02,198500,12.50,12.60,69600
119,TVO,XD,24.00,-0.20,-0.83,23.90,24.20,23.90,-,0.00,921488,22180.20,44100,24.00,24.10,8600

In [21]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].shape

(30, 9)

In [22]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO","VIBHA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,BCH,-,10.20,0.10,0.99,10.20,10.20,10.00,2000000,20200.00,10179202,103249.89,106000,10.10,10.20,225600
15,CPF,-,18.70,-0.20,-1.06,18.90,19.00,18.70,-,0.00,30856231,580637.44,940400,18.70,18.80,380200
26,STA,-,16.10,0.60,3.87,15.70,16.30,15.60,-,0.00,20283261,324491.46,682600,16.00,16.10,63300
29,TVO,XD,24.00,-0.20,-0.83,23.90,24.20,23.90,-,0.00,921488,22180.20,44100,24.00,24.10,8600

In [23]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].shape

(56, 9)

In [24]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.04,-,-,2.04,2.08,2.02,-,0,40312326,82857.48,775600,2.04,2.06,1083000
34,ORI,-,1.85,-0.05,-2.63,1.90,1.90,1.85,-,0,1427551,2666.25,69800,1.84,1.85,1900
53,SENA,-,1.87,-,-,1.87,1.87,1.86,-,0,78073,145.37,8500,1.86,1.87,65900

In [25]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].shape

(52, 9)

In [26]:
df_PFREIT.query('Symbol == ("CPNREIT","GVREIT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,11.50,-0.10,-0.86,11.60,11.60,11.50,-,0,1173829,13564.42,1003600,11.50,11.60,291000
17,GVREIT,-,6.40,-,-,6.35,6.40,6.35,-,0,194590,1239.91,161300,6.35,6.40,67400
54,WHAIR,-,6.75,0.10,1.50,6.65,6.75,6.65,-,0,398108,2670.55,510500,6.65,6.75,1200
55,WHART,-,10.30,-,-,10.20,10.40,10.20,-,0,720631,7411.33,841100,10.20,10.30,378100

In [27]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].shape

(27, 9)

In [28]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,30,0.50,1.69,29.25,30.25,29,-,0,3048582,90719.05,82000,29.75,30.00,78600
23,TFFIF,-,6.50,-,-,6.50,6.60,6.50,-,0,2249595,14718.95,2053400,6.50,6.55,6000

In [29]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].shape

(38, 9)

In [30]:
df_ICT.query('Symbol == ("3BBIF","DIF","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.55,-0.05,-0.76,6.55,6.60,6.55,-,0,3312895,21715.00,1532000,6.55,6.60,2721600
7,DIF,-,9.40,-,-,9.40,9.45,9.40,-,0,11374154,107003.79,7467100,9.35,9.40,22700
33,SYNEX,-,9.55,0.05,0.53,9.50,9.55,9.40,-,0,403899,3834.04,64500,9.50,9.55,107300

## Add section ENERG for PTG

In [32]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].shape

(59, 9)

In [33]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
35,PTG,-,7.90,-0.10,-1.25,8.15,8.15,7.90,-,0,6691520,53643.76,530500,7.90,7.95,63300
36,PTT,-,33.50,-0.75,-2.19,34.50,34.50,33.25,-,0,94051617,3160475.86,7913500,33.25,33.50,11001000

### ------------ End of Individual Category

In [35]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(671, 16)

In [102]:
df.query('Symbol == ("CPAXT","GULF")')

,Symbol,Trading-Sign,Last,Change,%Change,Open,High,Low,TR-Volume,TR-Value-(k),Total-Volume,Total-Value-(k),Bid-Size,Bid,Offer,Offer-Size
41,GULF,-,55.75,-0.50,-0.89,55.75,56.75,55.25,180000,10080.00,39465452,2207818.51,344200,55.75,56.00,455300

In [37]:
df.Symbol.nunique()

363

In [38]:
stock_list = df['Symbol'].unique().tolist()
stock_list_str = "','".join(stock_list)
len(stock_list)

363

In [39]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(363, 16)

In [40]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [41]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(363, 9)

In [42]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [43]:
df_ttl = pd.read_csv(input_file, header=None, names=['Symbol'])
df_ttl.shape

(211, 1)

In [44]:
colt = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()

In [45]:
df_out = df[colt]
df_out.shape

(363, 9)

In [46]:
df_merge = pd.merge(df_ttl, df_out, on = 'Symbol', how='inner')
df_merge.shape

(164, 9)

In [47]:
# Select rows in df_ttl where Symbol is NOT in df
df_only_in_ttl = df_ttl[~df_ttl['Symbol'].isin(df['Symbol'])]
print(df_only_in_ttl.shape)

(47, 1)

In [48]:
print(df_only_in_ttl)

     Symbol
7        AJ
14      ASP
20      BAY
25      BCT
27   BEAUTY
30      BGC
34     BKIH
47    CPAXT
53      DCC
54     DCON
58      DRT
65   FSMART
66       GC
80      IMH
82     INOX
83       IP
93      KSL
96      KYE
100    LHFG
101     LHK
102     LIT
103     LPH
107    MBAX
112     MST
120     PAP
121   PCSGH
122     PDG
125    PREB
140     S11
147    SCCC
155     SKN
156     SKR
157    SMPC
158     SNC
160     SPC
166  STANLY
179   TIPCO
181      TK
184     TMT
185     TMW
188   TPIPL
193    TSTH
200    TYCN
201     UTP
203   VIBHA
204     VNG
210    WORK

In [49]:
file_name = '254-candidates.csv'
data_file = os.path.join(dat_path, file_name)
df_only_in_ttl.to_csv(data_file, index=False, header=True)

### End of daily process to export Price to MySql Stock database

In [51]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-16 20:28:10

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes