### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
yesterday = today - timedelta(days=1)
print(today, yesterday)

2026-02-06 2026-02-05

In [4]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-02-06 20:00:16

### Restart & Run All Cells

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\PC1\OneDrive\Downloads\Datasets

In [7]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Datasets path : C:\Users\PC1\OneDrive\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [9]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [11]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
#df_S100[colu].sort_values(['%Change'],ascending=[False])
df_S100[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.20,-0.01,-0.83,1.21,1.22,1.19,111047407,133755.42
1,ADVANC,365.00,-2,-0.54,365.00,373.00,363.00,10824649,3970372.79
2,AEONTS,95.50,-1.25,-1.29,97.00,97.00,95.25,910697,87181.97
3,AMATA,15.50,-0.10,-0.64,15.60,15.70,15.50,5984881,93128.13
4,AOT,53.00,1.25,2.42,52.00,53.25,51.75,33164263,1751949.51

In [12]:
df_S100.query('Symbol == ("BCH","IVL","JMART","JMT","PTTGC","RCL","SCC","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
12,BCH,-,10.10,-,-,10.10,10.40,10.00,-,0.00,18367895,188124.65,570900,10.10,10.20,1092200
47,IVL,-,21.30,0.10,0.47,21.00,21.40,20.90,-,0.00,14457880,306335.83,310000,21.20,21.30,362700
49,JMART,-,7.00,-0.10,-1.41,7.00,7.15,7.00,-,0.00,4951456,34789.10,181300,7.00,7.05,117800
50,JMT,-,8.35,-0.10,-1.18,8.40,8.50,8.25,-,0.00,10271920,85794.53,1900,8.35,8.40,310800
71,PTTGC,-,25.25,-,-,25.25,25.50,25.00,-,0.00,9762786,247006.88,380800,25.25,25.50,864200
74,RCL,-,27.25,-0.25,-0.91,27.50,27.75,27.25,-,0.00,1305454,35797.37,413000,27.25,27.50,143200
77,SCC,-,218.00,6,2.83,211.00,219.00,211.00,-,0.00,6614213,1431658.26,15100,217.00,218.00,78500
84,STA,-,13.00,-0.10,-0.76,13.10,13.20,13.00,-,0.00,1441475,18862.14,218000,13.00,13.10,211300

In [13]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAI,4.30,-0.02,-0.46,4.30,4.32,4.28,1348498,5802.48
1,ADVICE,5.70,-0.05,-0.87,5.75,5.85,5.70,1234285,7094.97
2,AH,13.20,0.10,0.76,13.00,13.30,13.00,180574,2370.13
3,AIT,4.98,0.02,0.40,4.98,5.00,4.96,554772,2763.92
4,ASIAN,7.50,-,-,7.55,7.55,7.45,671875,5059.68

In [14]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
2,AH,-,13.20,0.10,0.76,13.00,13.30,13.00,-,0.00,180574,2370.13,8000,13.10,13.20,4000
39,MCS,-,8.55,-,-,8.55,8.55,8.50,-,0.00,295914,2527.72,68000,8.50,8.55,256500
50,ORI,-,1.76,-0.06,-3.30,1.81,1.84,1.76,-,0.00,4057622,7257.34,216300,1.76,1.77,161900
73,SINGER,-,4.66,-0.14,-2.92,4.76,4.78,4.64,-,0.00,3672125,17254.99,175700,4.66,4.68,500
83,SYNEX,-,10.10,-,-,10.10,10.40,10.10,-,0.00,1934409,19771.26,366800,10.10,10.20,40900

In [15]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.20,-0.01,-0.83,1.21,1.22,1.19,111047407,133755.42
1,AMATA,15.50,-0.10,-0.64,15.60,15.70,15.50,5984881,93128.13
2,BA,15.60,-0.20,-1.27,15.80,16.00,15.50,5747870,90387.60
3,BANPU,5.30,-,-,5.30,5.40,5.25,40985994,217925.87
4,BBL,157.00,-0.50,-0.32,157.00,157.50,156.50,6306587,989798.60

In [16]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","SCC","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,10.10,-,-,10.10,10.40,10.00,-,0.00,18367895,188124.65,570900,10.10,10.20,1092200
24,IVL,-,21.30,0.10,0.47,21.00,21.40,20.90,-,0.00,14457880,306335.83,310000,21.20,21.30,362700
38,PTTGC,-,25.25,-,-,25.25,25.50,25.00,-,0.00,9762786,247006.88,380800,25.25,25.50,864200
41,RCL,-,27.25,-0.25,-0.91,27.50,27.75,27.25,-,0.00,1305454,35797.37,413000,27.25,27.50,143200
46,SCC,-,218.00,6,2.83,211.00,219.00,211.00,-,0.00,6614213,1431658.26,15100,217.00,218.00,78500
53,TOA,-,14.40,0.20,1.41,14.10,14.40,14.10,-,0.00,1318232,18842.64,20000,14.30,14.40,96000

In [17]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AEONTS,95.50,-1.25,-1.29,97.00,97.00,95.25,910697,87181.97
1,AMATA,15.50,-0.10,-0.64,15.60,15.70,15.50,5984881,93128.13
2,AP,8.90,-0.05,-0.56,8.90,8.95,8.85,1801530,16026.31
3,BAM,7.70,-0.05,-0.65,7.75,7.80,7.70,3509250,27154.91
4,BBL,157.00,-0.50,-0.32,157.00,157.50,156.50,6306587,989798.60

In [18]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
6,JMT,-,8.35,-0.10,-1.18,8.40,8.50,8.25,-,0.00,10271920,85794.53,1900,8.35,8.40,310800
19,RCL,-,27.25,-0.25,-0.91,27.50,27.75,27.25,-,0.00,1305454,35797.37,413000,27.25,27.50,143200

In [19]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.20,-0.01,-0.83,1.21,1.22,1.19,111047407,133755.42
1,ADVANC,365.00,-2,-0.54,365.00,373.00,363.00,10824649,3970372.79
2,AEONTS,95.50,-1.25,-1.29,97.00,97.00,95.25,910697,87181.97
3,AMATA,15.50,-0.10,-0.64,15.60,15.70,15.50,5984881,93128.13
4,AOT,53.00,1.25,2.42,52.00,53.25,51.75,33164263,1751949.51

In [20]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMART","JMT","NER","ORI","PTTGC","SCC","STA","SYNEX","TOA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.32,-0.02,-0.85,2.32,2.36,2.30,-,0.00,51511564,119545.31,731900,2.30,2.32,1100000
13,BCH,-,10.10,-,-,10.10,10.40,10.00,-,0.00,18367895,188124.65,570900,10.10,10.20,1092200
48,IVL,-,21.30,0.10,0.47,21.00,21.40,20.90,-,0.00,14457880,306335.83,310000,21.20,21.30,362700
49,JMART,-,7.00,-0.10,-1.41,7.00,7.15,7.00,-,0.00,4951456,34789.10,181300,7.00,7.05,117800
50,JMT,-,8.35,-0.10,-1.18,8.40,8.50,8.25,-,0.00,10271920,85794.53,1900,8.35,8.40,310800
66,NER,-,4.72,-0.06,-1.26,4.78,4.80,4.72,-,0.00,6839815,32526.27,395500,4.72,4.74,30400
68,ORI,-,1.76,-0.06,-3.30,1.81,1.84,1.76,-,0.00,4057622,7257.34,216300,1.76,1.77,161900
80,PTTGC,-,25.25,-,-,25.25,25.50,25.00,-,0.00,9762786,247006.88,380800,25.25,25.50,864200
91,SCC,-,218.00,6,2.83,211.00,219.00,211.00,-,0.00,6614213,1431658.26,15100,217.00,218.00,78500
101,STA,-,13.00,-0.10,-0.76,13.10,13.20,13.00,-,0.00,1441475,18862.14,218000,13.00,13.10,211300
104,SYNEX,-,10.10,-,-,10.10,10.40,10.10,-,0.00,1934409,19771.26,366800,10.10,10.20,40900
112,TOA,-,14.40,0.20,1.41,14.10,14.40,14.10,-,0.00,1318232,18842.64,20000,14.30,14.40,96000
119,TVO,-,23.70,-,-,23.60,23.70,23.50,-,0.00,296116,6998.13,12400,23.60,23.70,25800

In [21]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].head()

  Symbol  Last Change %Change  Open  High   Low  Total Volume  Total Value (k)
0    AOT 53.00   1.25    2.42 52.00 53.25 51.75      33164263       1751949.51
1   AURA 12.40   0.10    0.81 12.40 12.50 12.20       1848609         22832.68
2     BA 15.60  -0.20   -1.27 15.80 16.00 15.50       5747870         90387.60
3    BCH 10.10      -       - 10.10 10.40 10.00      18367895        188124.65
4   BDMS 20.90   0.50    2.45 20.40 20.90 20.40      83359246       1731149.04

In [22]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,BCH,-,10.10,-,-,10.10,10.40,10.00,-,0.00,18367895,188124.65,570900,10.10,10.20,1092200
15,CPF,-,21.00,0.30,1.45,20.80,21.00,20.70,-,0.00,21513744,449326.54,419600,20.90,21.00,1575500
26,STA,-,13.00,-0.10,-0.76,13.10,13.20,13.00,-,0.00,1441475,18862.14,218000,13.00,13.10,211300
29,TVO,-,23.70,-,-,23.60,23.70,23.50,-,0.00,296116,6998.13,12400,23.60,23.70,25800

In [23]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].head()

   Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
1      A5  1.84   0.01    0.55  1.84  1.84  1.84         8802           16.20
2     AKS  0.02      -       -  0.03  0.03  0.02       202257            4.94
3   AMATA 15.50  -0.10   -0.64 15.60 15.70 15.50      5984881        93128.13
4  AMATAV  1.80      -       -  1.81  1.81  1.78        22015           39.51
5    ANAN  0.40      -       -  0.40  0.41  0.40       978230          391.62

In [24]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.32,-0.02,-0.85,2.32,2.36,2.30,-,0,51511564,119545.31,731900,2.30,2.32,1100000
34,ORI,-,1.76,-0.06,-3.30,1.81,1.84,1.76,-,0,4057622,7257.34,216300,1.76,1.77,161900
53,SENA,-,1.71,0.04,2.40,1.67,1.78,1.66,-,0,170475,291.83,500,1.69,1.71,2300

In [25]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].head()

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0    AIMCG  1.64   0.01    0.61  1.63  1.65  1.60       822201         1318.92
1   AIMIRT 10.80      -       - 10.80 10.80 10.70        90762          979.16
2     ALLY  4.46   0.06    1.36  4.40  4.46  4.40       387527         1718.03
3   AMATAR  6.70      -       -  6.70  6.70  6.70        10720           71.82
4  AXTRART    13   0.10    0.78    13    13 12.80       688501         8900.65

In [26]:
df_PFREIT.query('Symbol == ("AIMIRT","CPNREIT","GVREIT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,AIMIRT,-,10.80,-,-,10.80,10.80,10.70,-,0,90762,979.16,224000,10.70,10.80,132500
9,CPNREIT,-,11.30,-0.10,-0.88,11.40,11.40,11.20,-,0,2973212,33464.72,1200800,11.20,11.30,2246200
17,GVREIT,-,6.65,-,-,6.60,6.65,6.55,-,0,438414,2886.78,200,6.60,6.65,89700
54,WHAIR,-,6.40,-,-,6.40,6.40,6.35,-,0,233030,1483.66,14500,6.35,6.40,645000
55,WHART,-,10.70,-,-,10.70,10.70,10.60,-,0,940673,10044.93,841400,10.60,10.70,455100

In [27]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].head()

   Symbol Last Change %Change Open  High   Low Total Volume Total Value (k)
0     AAV 1.20  -0.01   -0.83 1.21  1.22  1.19    111047407       133755.42
1     ANI 2.74      -       - 2.74  2.76  2.74         5700           15.63
2     AOT   53   1.25    2.42   52 53.25 51.75     33164263      1751949.51
3  ASIMAR 1.51      -       - 1.51  1.51  1.50        51600           77.91
4       B 0.04      -       - 0.04  0.04  0.03       151072            5.92

In [28]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,27.25,-0.25,-0.91,27.50,27.75,27.25,-,0,1305454,35797.37,413000,27.25,27.50,143200
23,TFFIF,-,6.65,0.05,0.76,6.60,6.70,6.60,-,0,5598529,37200.43,464800,6.65,6.70,786500

In [29]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].head()

   Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0   3BBIF 6.65      -       - 6.65 6.70 6.65     15795914       105443.93
1  ADVANC  365     -2   -0.54  365  373  363     10824649      3970372.79
2     AIT 4.98   0.02    0.40 4.98    5 4.96       554772         2763.92
3     ALT 1.09  -0.01   -0.91 1.09 1.11 1.08       420510          459.35
4     AMR 0.38      -       - 0.39 0.40 0.38       194217           76.15

In [30]:
df_ICT.query('Symbol == ("3BBIF","DIF","JMART","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.65,-,-,6.65,6.70,6.65,-,0,15795914,105443.93,4652500,6.65,6.70,3407200
7,DIF,-,9.50,0.05,0.53,9.45,9.50,9.45,-,0,7537252,71519.80,6551800,9.45,9.50,4675900
19,JMART,-,7,-0.10,-1.41,7,7.15,7,-,0,4951456,34789.10,181300,7,7.05,117800
33,SYNEX,-,10.10,-,-,10.10,10.40,10.10,-,0,1934409,19771.26,366800,10.10,10.20,40900

## Add section ENERG for PTG

In [32]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].head()

  Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0    ACC 0.38  -0.01   -2.56 0.39 0.39 0.38       985900          382.24
1    ACE 1.29      -       - 1.29 1.30 1.29       524901          677.41
2     AE 0.09      -       - 0.09 0.09 0.08      1358606          117.73
3    AGE 1.25  -0.01   -0.79 1.25 1.26 1.25       438564          548.21
4     AI    3  -0.02   -0.66 3.02 3.02    3        23966           71.97

In [33]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
35,PTG,-,7.80,-,-,7.75,7.85,7.70,-,0,4573241,35529.42,31400,7.75,7.80,343300
36,PTT,-,35.25,-,-,35.25,35.50,35,-,0,58620929,2070236.54,19657000,35.25,35.50,29025100

### ------------ End of Individual Category

In [35]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(675, 16)

In [36]:
df.Symbol.nunique()

367

In [37]:
df.query('Symbol == "CPNREIT"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,11.30,-0.10,-0.88,11.40,11.40,11.20,-,0,2973212,33464.72,1200800,11.20,11.30,2246200

In [38]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(367, 16)

In [39]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [40]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(367, 9)

In [41]:
# Clean Symbol column (remove <XD>)
df['Symbol'] = df['Symbol'].str.replace(r'\s*<.*?>', '', regex=True)

# Then proceed with numeric conversion as above
numeric_cols = df.columns.drop('Symbol')
df[numeric_cols] = (
    df[numeric_cols].replace('-', 0)
    .apply(pd.to_numeric, errors='coerce', downcast=None)  # Disable downcasting
)
df[cols].shape

C:\Users\PC1\AppData\Local\Temp\ipykernel_4212\3393296708.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[numeric_cols].replace('-', 0)

(367, 9)

In [42]:
# If run after actual work day
#today = today - timedelta(days=2)
#today

In [43]:
df.insert(1, 'Date', today)

In [44]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2026-02-06,1.20,-0.01,-0.83,1.21,1.22,1.19,111047407,133755.42
1,ADVANC,2026-02-06,365.00,-2.00,-0.54,365.00,373.00,363.00,10824649,3970372.79
2,AEONTS,2026-02-06,95.50,-1.25,-1.29,97.00,97.00,95.25,910697,87181.97
3,AMATA,2026-02-06,15.50,-0.10,-0.64,15.60,15.70,15.50,5984881,93128.13
4,AOT,2026-02-06,53.00,1.25,2.42,52.00,53.25,51.75,33164263,1751949.51
...,...,...,...,...,...,...,...,...,...,...
53,TGE,2026-02-06,1.33,0.03,2.31,1.30,1.33,1.29,34900,45.21
55,TPIPP,2026-02-06,1.84,0.01,0.55,1.83,1.84,1.82,787495,1441.39
56,TSE,2026-02-06,0.41,0.01,2.50,0.40,0.41,0.40,207997,83.49
58,UBE,2026-02-06,0.44,0.00,0.00,0.44,0.46,0.44,757838,338.85
60,WP,2026-02-06,3.78,0.00,0.00,3.80,3.80,3.76,70366,265.71

In [45]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [46]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(215, 1)

In [47]:
df_out = df[colt]
df_out.shape

(367, 10)

In [48]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(165, 10)

In [49]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [50]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [51]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [52]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price.csv

In [53]:
df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(god_file, header=True, index=False)
df_merge[colp].to_csv(icd_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [55]:
file_name = "Price-Today.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [56]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Today.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Today.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Today.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Today.csv

In [57]:
df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(god_file, header=True, index=False)
df_merge.to_csv(icd_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

In [58]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-02-06 20:00:17

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes