### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
print(today)

2026-08-11

In [4]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-08-11 21:21:18

### Restart & Run All Cells

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\PC1\OneDrive\Downloads\Datasets

In [7]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Datasets path : C:\Users\PC1\OneDrive\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [9]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [11]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
#df_S100[colu].sort_values(['%Change'],ascending=[False])
df_S100[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.05,-,-,1.05,1.06,1.04,25086677,26344.59
1,ADVANC,374.00,3,0.81,373.00,375.00,372.00,5249169,1962462.51
2,AEONTS,102.50,-3,-2.84,105.00,105.00,102.50,634201,65496.28
3,AMATA,28.50,-0.25,-0.87,28.25,28.75,28.25,6631190,189012.76
4,AOT,63.00,-0.25,-0.40,63.00,63.25,62.50,16412690,1032862.73

In [12]:
df_S100.query('Symbol == ("ADVANC","BCH","IVL","JMT","PTTGC","RCL","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,ADVANC,-,374.00,3,0.81,373.00,375.00,372.00,-,0.00,5249169,1962462.51,177100,373.00,374.00,41000
12,BCH,-,10.90,-0.10,-0.91,11.10,11.10,10.90,-,0.00,9229872,101431.79,1695200,10.90,11.00,245200
47,IVL,-,22.00,-,-,22.10,22.80,21.90,-,0.00,99107535,2217268.92,963800,22.00,22.10,315500
49,JMT,-,11.90,-0.10,-0.83,12.00,12.10,11.80,-,0.00,9583578,114173.09,651100,11.80,11.90,10700
70,PTTGC,-,38.50,1,2.67,37.75,39.25,37.50,-,0.00,49354686,1906982.94,1591000,38.50,38.75,670200
73,RCL,-,39.25,2.75,7.53,36.50,39.75,36.50,18649590,634086.06,30914593,1108954.82,18900,39.25,39.50,252300
81,STA,-,17.70,-0.60,-3.28,18.30,18.40,17.60,-,0.00,9734337,175798.23,262700,17.60,17.70,196500

In [13]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAI,4.08,-0.04,-0.97,4.12,4.14,4.06,3130079,12802.62
1,ADVICE,7.30,-0.25,-3.31,7.50,7.50,7.25,3731624,27505.85
2,AH,15.70,-,-,16.00,16.00,15.70,264897,4195.60
3,AIT,4.96,-,-,4.96,4.96,4.92,574455,2839.86
4,ASIAN,7.30,-,-,7.35,7.40,7.30,666245,4881.11

In [14]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
2,AH,-,15.70,-,-,16.00,16.00,15.70,-,0,264897,4195.60,37000,15.70,15.80,1000
33,MCS,-,7.90,-,-,7.90,7.90,7.80,-,0,719649,5648.38,30500,7.85,7.90,63000
42,ORI,-,1.99,-,-,1.99,2.02,1.97,-,0,1075893,2136.68,100,1.98,1.99,2500
60,SINGER,-,11.70,0.10,0.86,11.50,11.80,11.20,-,0,6970587,80250.06,151800,11.60,11.70,74100

In [15]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.05,-,-,1.05,1.06,1.04,25086677,26344.59
1,AMATA,28.50,-0.25,-0.87,28.25,28.75,28.25,6631190,189012.76
2,BA,18.80,-0.90,-4.57,19.40,19.80,18.50,21086851,399767.68
3,BANPU,14.60,-0.10,-0.68,14.80,15.00,14.60,24922682,369217.16
4,BBL,191.50,0.50,0.26,191.50,192.50,191.00,5497028,1052465.03

In [16]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,10.90,-0.10,-0.91,11.10,11.10,10.90,-,0.00,9229872,101431.79,1695200,10.90,11.00,245200
24,IVL,-,22.00,-,-,22.10,22.80,21.90,-,0.00,99107535,2217268.92,963800,22.00,22.10,315500
37,PTTGC,-,38.50,1,2.67,37.75,39.25,37.50,-,0.00,49354686,1906982.94,1591000,38.50,38.75,670200
40,RCL,-,39.25,2.75,7.53,36.50,39.75,36.50,18649590,634086.06,30914593,1108954.82,18900,39.25,39.50,252300
54,TOA,-,16.30,0.10,0.62,16.30,16.40,16.10,-,0.00,2222341,36128.82,31700,16.30,16.40,119500

In [17]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AEONTS,102.50,-3,-2.84,105.00,105.00,102.50,634201,65496.28
1,AMATA,28.50,-0.25,-0.87,28.25,28.75,28.25,6631190,189012.76
2,AP,8.15,-0.10,-1.21,8.25,8.25,8.15,5830622,47780.02
3,BA,18.80,-0.90,-4.57,19.40,19.80,18.50,21086851,399767.68
4,BAM,6.75,-0.05,-0.74,6.80,6.80,6.75,2496486,16893.51

In [18]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
7,JMT,-,11.90,-0.10,-0.83,12.00,12.10,11.80,-,0.00,9583578,114173.09,651100,11.80,11.90,10700
20,RCL,-,39.25,2.75,7.53,36.50,39.75,36.50,18649590,634086.06,30914593,1108954.82,18900,39.25,39.50,252300

In [19]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.05,-,-,1.05,1.06,1.04,25086677,26344.59
1,ADVANC,374.00,3,0.81,373.00,375.00,372.00,5249169,1962462.51
2,AEONTS,102.50,-3,-2.84,105.00,105.00,102.50,634201,65496.28
3,AMATA,28.50,-0.25,-0.87,28.25,28.75,28.25,6631190,189012.76
4,AOT,63.00,-0.25,-0.40,63.00,63.25,62.50,16412690,1032862.73

In [20]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMT","NER","ORI","PTTGC","STA","SYNEX","TOA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.92,-0.02,-0.68,2.94,2.98,2.88,-,0.00,56529602,165024.15,1370600,2.90,2.92,574900
14,BCH,-,10.90,-0.10,-0.91,11.10,11.10,10.90,-,0.00,9229872,101431.79,1695200,10.90,11.00,245200
48,IVL,-,22.00,-,-,22.10,22.80,21.90,-,0.00,99107535,2217268.92,963800,22.00,22.10,315500
50,JMT,-,11.90,-0.10,-0.83,12.00,12.10,11.80,-,0.00,9583578,114173.09,651100,11.80,11.90,10700
67,NER,-,4.52,-0.06,-1.31,4.56,4.58,4.50,-,0.00,29438894,133201.65,1044800,4.52,4.54,514900
79,PTTGC,-,38.50,1,2.67,37.75,39.25,37.50,-,0.00,49354686,1906982.94,1591000,38.50,38.75,670200
99,STA,-,17.70,-0.60,-3.28,18.30,18.40,17.60,-,0.00,9734337,175798.23,262700,17.60,17.70,196500
109,TOA,-,16.30,0.10,0.62,16.30,16.40,16.10,-,0.00,2222341,36128.82,31700,16.30,16.40,119500
117,TVO,-,27.00,-0.50,-1.82,27.50,27.50,27.00,-,0.00,558407,15242.40,448100,27.00,27.25,90700

In [21]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].head()

  Symbol  Last Change %Change  Open  High   Low  Total Volume  Total Value (k)
0    AOT 63.00  -0.25   -0.40 63.00 63.25 62.50      16412690       1032862.73
1   AURA 14.40  -0.10   -0.69 14.60 14.70 14.30       1626567         23573.26
2     BA 18.80  -0.90   -4.57 19.40 19.80 18.50      21086851        399767.68
3    BCH 10.90  -0.10   -0.91 11.10 11.10 10.90       9229872        101431.79
4   BDMS 19.70  -0.20   -1.01 19.90 19.90 19.50      93421665       1839549.92

In [22]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,BCH,-,10.90,-0.10,-0.91,11.10,11.10,10.90,-,0.00,9229872,101431.79,1695200,10.90,11.00,245200
14,CPF,-,21.90,0.10,0.46,21.70,22.00,21.70,-,0.00,20881987,456870.47,1079900,21.90,22.00,1227600
25,STA,-,17.70,-0.60,-3.28,18.30,18.40,17.60,-,0.00,9734337,175798.23,262700,17.60,17.70,196500
29,TVO,-,27.00,-0.50,-1.82,27.50,27.50,27.00,-,0.00,558407,15242.40,448100,27.00,27.25,90700

In [23]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].head()

   Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0       A     -      -       -     -     -     -            2            0.00
1      A5  1.79   0.01    0.56  1.79  1.80  1.75       132404          236.48
3   AMATA 28.50  -0.25   -0.87 28.25 28.75 28.25      6631190       189012.76
4  AMATAV  2.16   0.10    4.85  2.22  2.30  2.12      1599791         3501.12
5    ANAN  0.32      -       -  0.32  0.33  0.32      4832553         1546.69

In [24]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.92,-0.02,-0.68,2.94,2.98,2.88,-,0,56529602,165024.15,1370600,2.90,2.92,574900
34,ORI,-,1.99,-,-,1.99,2.02,1.97,-,0,1075893,2136.68,100,1.98,1.99,2500
53,SENA,-,1.78,-,-,1.79,1.79,1.77,-,0,81401,144.62,35300,1.77,1.78,54800

In [25]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].head()

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0    AIMCG  1.74  -0.01   -0.57  1.75  1.76  1.74       306202          535.47
1   AIMIRT 12.60  -0.10   -0.79 12.60 12.70 12.60       143620         1815.26
2     ALLY  5.15      -       -  5.15  5.20  5.10      1785401         9173.33
3   AMATAR  7.55      -       -  7.60  7.60  7.55        45300          342.07
4  AXTRART 13.20  -0.10   -0.75 13.30 13.30 13.10       504105         6651.64

In [26]:
df_PFREIT.query('Symbol == ("AIMIRT","CPNREIT","GVREIT","PROSPECT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,AIMIRT,-,12.60,-0.10,-0.79,12.60,12.70,12.60,-,0,143620,1815.26,400,12.60,12.70,679400
9,CPNREIT,-,13.60,-0.10,-0.73,13.70,13.80,13.50,-,0,1980614,27055.32,655900,13.50,13.60,154300
17,GVREIT,-,8.20,-0.10,-1.20,8.30,8.30,8.20,-,0,323273,2660.23,216500,8.20,8.25,41800
38,PROSPECT,-,10.30,-0.10,-0.96,10.40,10.40,10.30,-,0,1456010,15129.21,1467400,10.30,10.40,1002400
54,WHAIR,-,8.45,0.05,0.60,8.45,8.45,8.40,-,0,309228,2610.16,408800,8.40,8.45,90600
55,WHART,-,11.20,-,-,11.20,11.30,11.10,-,0,1684862,18942.14,58700,11.20,11.30,564900

In [27]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].head()

   Symbol Last Change %Change Open  High   Low Total Volume Total Value (k)
0     AAV 1.05      -       - 1.05  1.06  1.04     25086677        26344.59
1     ANI 3.64      -       - 3.76  3.86  3.62      1957303         7265.63
2     AOT   63  -0.25   -0.40   63 63.25 62.50     16412690      1032862.73
3  ASIMAR 1.45      -       - 1.47  1.48  1.45      1622500         2377.93
4       B 0.04   0.01   33.33 0.04  0.04  0.03      1238885           39.41

In [28]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,39.25,2.75,7.53,36.50,39.75,36.50,18649590,634086.06,30914593,1108954.82,18900,39.25,39.50,252300
23,TFFIF,-,7.20,0.05,0.70,7.15,7.20,7.10,-,0,1217330,8704.78,588600,7.15,7.20,2633600

In [29]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].head()

   Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0   3BBIF 6.55      -       - 6.60 6.60 6.55      4278729        28125.57
1  ADVANC  374      3    0.81  373  375  372      5249169      1962462.51
2     AIT 4.96      -       - 4.96 4.96 4.92       574455         2839.86
3     ALT 1.75  -0.04   -2.23 1.85 1.87 1.74     13396835        24289.61
4     AMR 0.39  -0.01   -2.50 0.40 0.40 0.39        22800            8.90

In [30]:
df_ICT.query('Symbol == ("3BBIF","DIF","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.55,-,-,6.60,6.60,6.55,-,0,4278729,28125.57,5847400,6.55,6.60,7276600
7,DIF,-,10.30,-0.10,-0.96,10.30,10.40,10.30,-,0,16428424,169986.93,10666400,10.30,10.40,11304300
33,SYNEX,-,9.50,-0.20,-2.06,9.75,9.75,9.50,-,0,2888775,27635.30,769200,9.50,9.55,14000

## Add section ENERG for PTG

In [32]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].head()

  Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0    ACC 0.31  -0.03   -8.82 0.33 0.34 0.31      7157107         2280.62
1    ACE 1.29      -       - 1.29 1.30 1.28       866901         1117.34
2     AE 0.09      -       - 0.09 0.10 0.09       318696           28.96
3    AGE 1.38   0.02    1.47 1.36 1.38 1.35      1915909         2623.69
4     AI 3.24   0.28    9.46 2.94 3.28 2.94      4188119        13386.90

In [33]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
34,PTG,-,7.45,-,-,7.45,7.50,7.45,-,0,1276183,9512.71,129700,7.45,7.50,508100
35,PTT,-,39.50,0.75,1.94,39,39.50,39,-,0,114176269,4491076.04,15956900,39.25,39.50,14653700

### ------------ End of Individual Category

In [35]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(668, 16)

In [36]:
df.Symbol.nunique()

362

In [111]:
df.query('Symbol == "IVL"')

,Symbol,Date,Trading-Sign,Last,Change,%Change,Open,High,Low,TR-Volume,TR-Value-(k),Total-Volume,Total-Value-(k),Bid-Size,Bid,Offer,Offer-Size
47,IVL,2026-08-11,0.00,22.00,0.00,0.00,22.10,22.80,21.90,0,0.00,99107535,2217268.92,963800,22.00,22.10,315500

In [113]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(362, 17)

In [115]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Date', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open',
       'High', 'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume',
       'Total-Value-(k)', 'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [40]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(362, 9)

In [41]:
# Clean Symbol column (remove <XD>)
df['Symbol'] = df['Symbol'].str.replace(r'\s*<.*?>', '', regex=True)

# Then proceed with numeric conversion as above
numeric_cols = df.columns.drop('Symbol')
df[numeric_cols] = (
    df[numeric_cols].replace('-', 0)
    .apply(pd.to_numeric, errors='coerce', downcast=None)  # Disable downcasting
)
df[cols].shape

C:\Users\PC1\AppData\Local\Temp\ipykernel_65840\3393296708.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[numeric_cols].replace('-', 0)

(362, 9)

In [42]:
# If run after actual work day
#today = today - timedelta(days=2)
#today

In [43]:
df.insert(1, 'Date', today)

In [44]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2026-08-11,1.05,0.00,0.00,1.05,1.06,1.04,25086677,26344.59
1,ADVANC,2026-08-11,374.00,3.00,0.81,373.00,375.00,372.00,5249169,1962462.51
2,AEONTS,2026-08-11,102.50,-3.00,-2.84,105.00,105.00,102.50,634201,65496.28
3,AMATA,2026-08-11,28.50,-0.25,-0.87,28.25,28.75,28.25,6631190,189012.76
4,AOT,2026-08-11,63.00,-0.25,-0.40,63.00,63.25,62.50,16412690,1032862.73
...,...,...,...,...,...,...,...,...,...,...
51,TCC,2026-08-11,0.29,0.00,0.00,0.29,0.30,0.29,968601,281.30
52,TGE,2026-08-11,1.20,-0.03,-2.44,1.25,1.25,1.20,827212,1006.15
55,TSE,2026-08-11,0.77,-0.03,-3.75,0.80,0.82,0.77,7126713,5636.84
57,UBE,2026-08-11,0.61,0.02,3.39,0.59,0.61,0.59,2308673,1385.65
59,WP,2026-08-11,3.76,0.00,0.00,3.76,3.76,3.74,84096,314.63

In [45]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [46]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(188, 1)

In [47]:
df_out = df[colt]
df_out.shape

(362, 10)

In [48]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(160, 10)

In [49]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [50]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [51]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [52]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price.csv

In [53]:
df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(god_file, header=True, index=False)
df_merge[colp].to_csv(icd_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [55]:
file_name = "Price-Today.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [56]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Today.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Today.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Today.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Today.csv

In [57]:
df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(god_file, header=True, index=False)
df_merge.to_csv(icd_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

In [58]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-08-11 21:21:19

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes