### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
print(today)

2026-05-22

In [4]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-05-22 20:02:58

### Restart & Run All Cells

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\PC1\OneDrive\Downloads\Datasets

In [7]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Datasets path : C:\Users\PC1\OneDrive\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [9]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [11]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
#df_S100[colu].sort_values(['%Change'],ascending=[False])
df_S100[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-0.01,-0.93,1.07,1.08,1.06,36276364,38694.60
1,ADVANC,355.00,-3,-0.84,359.00,361.00,355.00,7266150,2602236.53
2,AEONTS,93.00,0.25,0.27,92.75,93.50,92.50,127196,11834.93
3,AMATA,25.00,-0.25,-0.99,25.25,25.50,24.80,17196466,430314.06
4,AOT,52.75,-,-,53.00,53.00,52.25,15521101,817284.42

In [12]:
df_S100.query('Symbol == ("ADVANC","BCH","IVL","JMT","PTTGC","RCL","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,ADVANC,-,355.00,-3,-0.84,359.00,361.00,355.00,-,0.00,7266150,2602236.53,423300,355.00,356.00,300
12,BCH,-,9.25,0.05,0.54,9.20,9.35,9.20,-,0.00,5033152,46649.60,332100,9.25,9.30,844100
47,IVL,-,24.70,0.40,1.65,24.30,24.90,24.30,-,0.00,23392185,575759.50,330200,24.60,24.70,279400
50,JMT,-,10.70,-0.10,-0.93,10.80,10.80,10.50,-,0.00,6948520,74113.98,657800,10.60,10.70,244500
71,PTTGC,-,37.50,-,-,37.50,38.00,37.25,-,0.00,18818048,708947.71,465400,37.50,37.75,558100
74,RCL,-,30.50,-,-,30.50,30.50,30.25,-,0.00,588452,17891.24,443500,30.25,30.50,102600
84,STA,-,18.90,-0.10,-0.53,19.10,19.10,18.80,-,0.00,6996228,132283.53,431400,18.80,18.90,528000

In [13]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAI,3.46,-0.08,-2.26,3.58,3.58,3.46,3043533,10669.64
1,ADVICE,6.00,0.20,3.45,5.80,6.00,5.75,5208001,30766.80
2,AH,13.60,-0.20,-1.45,13.90,13.90,13.60,225519,3075.49
3,AIT,4.68,-,-,4.68,4.70,4.66,662776,3101.90
4,ASIAN,6.95,-,-,6.95,7.00,6.90,234715,1628.96

In [14]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
2,AH,-,13.60,-0.20,-1.45,13.90,13.90,13.60,-,0,225519,3075.49,2400,13.60,13.70,25000
39,MCS,-,7.40,-,-,7.40,7.40,7.35,-,0,866104,6393.79,92000,7.35,7.40,342700
50,ORI,-,1.71,-,-,1.73,1.73,1.70,-,0,969057,1660.39,249600,1.70,1.71,69800
73,SINGER,-,7.15,0.05,0.70,7.15,7.20,6.95,-,0,6128665,43435.22,193600,7.15,7.20,246800
82,SYNEX,-,9.20,0.05,0.55,9.20,9.25,9.15,-,0,422046,3883.94,217100,9.15,9.20,3800

In [15]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-0.01,-0.93,1.07,1.08,1.06,36276364,38694.60
1,AMATA,25.00,-0.25,-0.99,25.25,25.50,24.80,17196466,430314.06
2,BA,14.40,-,-,14.50,14.50,14.10,4501531,64263.15
3,BANPU,5.95,0.05,0.85,5.90,5.95,5.85,37288636,221097.93
4,BBL,168.50,-0.50,-0.30,169.50,170.50,167.00,7890526,1328497.54

In [16]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,9.25,0.05,0.54,9.20,9.35,9.20,-,0.00,5033152,46649.60,332100,9.25,9.30,844100
24,IVL,-,24.70,0.40,1.65,24.30,24.90,24.30,-,0.00,23392185,575759.50,330200,24.60,24.70,279400
38,PTTGC,-,37.50,-,-,37.50,38.00,37.25,-,0.00,18818048,708947.71,465400,37.50,37.75,558100
41,RCL,-,30.50,-,-,30.50,30.50,30.25,-,0.00,588452,17891.24,443500,30.25,30.50,102600
53,TOA,-,12.50,-,-,12.50,12.70,12.30,-,0.00,3506797,43785.51,123400,12.40,12.50,136900

In [17]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AEONTS,93.00,0.25,0.27,92.75,93.50,92.50,127196,11834.93
1,AMATA,25.00,-0.25,-0.99,25.25,25.50,24.80,17196466,430314.06
2,AP,7.50,0.10,1.35,7.40,7.55,7.40,8485138,63535.37
3,BAM,6.40,0.05,0.79,6.40,6.50,6.40,12580680,80999.40
4,BBL,168.50,-0.50,-0.30,169.50,170.50,167.00,7890526,1328497.54

In [18]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
6,JMT,-,10.70,-0.10,-0.93,10.80,10.80,10.50,-,0.00,6948520,74113.98,657800,10.60,10.70,244500
19,RCL,-,30.50,-,-,30.50,30.50,30.25,-,0.00,588452,17891.24,443500,30.25,30.50,102600

In [19]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-0.01,-0.93,1.07,1.08,1.06,36276364,38694.60
1,ADVANC,355.00,-3,-0.84,359.00,361.00,355.00,7266150,2602236.53
2,AEONTS,93.00,0.25,0.27,92.75,93.50,92.50,127196,11834.93
3,AMATA,25.00,-0.25,-0.99,25.25,25.50,24.80,17196466,430314.06
4,AOT,52.75,-,-,53.00,53.00,52.25,15521101,817284.42

In [20]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMT","NER","ORI","PTTGC","STA","SYNEX","TOA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.18,-,-,2.20,2.20,2.16,-,0.00,40969713,89575.75,446900,2.18,2.20,5087800
13,BCH,-,9.25,0.05,0.54,9.20,9.35,9.20,-,0.00,5033152,46649.60,332100,9.25,9.30,844100
48,IVL,-,24.70,0.40,1.65,24.30,24.90,24.30,-,0.00,23392185,575759.50,330200,24.60,24.70,279400
50,JMT,-,10.70,-0.10,-0.93,10.80,10.80,10.50,-,0.00,6948520,74113.98,657800,10.60,10.70,244500
66,NER,-,4.40,0.02,0.46,4.40,4.42,4.38,-,0.00,3364932,14801.62,1971100,4.38,4.40,34500
68,ORI,-,1.71,-,-,1.73,1.73,1.70,-,0.00,969057,1660.39,249600,1.70,1.71,69800
80,PTTGC,-,37.50,-,-,37.50,38.00,37.25,-,0.00,18818048,708947.71,465400,37.50,37.75,558100
101,STA,-,18.90,-0.10,-0.53,19.10,19.10,18.80,-,0.00,6996228,132283.53,431400,18.80,18.90,528000
104,SYNEX,-,9.20,0.05,0.55,9.20,9.25,9.15,-,0.00,422046,3883.94,217100,9.15,9.20,3800
112,TOA,-,12.50,-,-,12.50,12.70,12.30,-,0.00,3506797,43785.51,123400,12.40,12.50,136900
119,TVO,-,25.25,0.25,1,25.25,25.50,25.00,-,0.00,270087,6822.46,67100,25.25,25.50,391700

In [21]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].head()

  Symbol  Last Change %Change  Open  High   Low  Total Volume  Total Value (k)
0    AOT 52.75      -       - 53.00 53.00 52.25      15521101        817284.42
1   AURA 15.10   0.70    4.86 14.40 15.20 14.20       5721913         83703.52
2     BA 14.40      -       - 14.50 14.50 14.10       4501531         64263.15
3    BCH  9.25   0.05    0.54  9.20  9.35  9.20       5033152         46649.60
4   BDMS 18.10  -0.10   -0.55 18.10 18.20 18.10      32464212        587838.79

In [22]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,BCH,-,9.25,0.05,0.54,9.20,9.35,9.20,-,0.00,5033152,46649.60,332100,9.25,9.30,844100
15,CPF,-,18.90,-0.20,-1.05,19.10,19.20,18.80,92100,1740.69,17875074,338670.07,5136900,18.80,18.90,682200
26,STA,-,18.90,-0.10,-0.53,19.10,19.10,18.80,-,0.00,6996228,132283.53,431400,18.80,18.90,528000
29,TVO,-,25.25,0.25,1,25.25,25.50,25.00,-,0.00,270087,6822.46,67100,25.25,25.50,391700

In [23]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].head()

   Symbol Last Change %Change  Open  High   Low Total Volume Total Value (k)
0       A 4.24   0.04    0.95  4.24  4.24  4.24          200            0.85
1      A5 1.82      -       -  1.82  1.82  1.80        24612           44.47
3   AMATA   25  -0.25   -0.99 25.25 25.50 24.80     17196466       430314.06
4  AMATAV 1.98   0.02    1.02  1.97  1.98  1.97        48018           94.77
5    ANAN 0.35   0.01    2.94  0.35  0.35  0.33      2007601          683.18

In [24]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.18,-,-,2.20,2.20,2.16,-,0,40969713,89575.75,446900,2.18,2.20,5087800
34,ORI,-,1.71,-,-,1.73,1.73,1.70,-,0,969057,1660.39,249600,1.70,1.71,69800
53,SENA,-,1.78,-,-,1.78,1.79,1.77,-,0,231101,410.31,148400,1.77,1.78,11400

In [25]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].head()

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0    AIMCG  1.34  -0.02   -1.47  1.35  1.35  1.33        95472          127.93
1   AIMIRT 11.40  -0.10   -0.87 11.30 11.40 11.30       438587         4959.51
2     ALLY  4.74   0.02    0.42  4.72  4.76  4.70       906699         4288.13
3   AMATAR  7.35   0.10    1.38  7.50  7.50  7.15        92730          676.41
4  AXTRART 12.80      -       - 12.70 12.80 12.60      2391718        30555.88

In [111]:
df_PFREIT.query('Symbol == ("CPNREIT","GVREIT","WHAIR","WHART","AIMIRT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,AIMIRT,XD,11.40,-0.10,-0.87,11.30,11.40,11.30,-,0,438587,4959.51,113400,11.30,11.40,249400
9,CPNREIT,-,12.70,0.20,1.60,12.50,12.70,12.50,-,0,2602824,32999.28,1008500,12.60,12.70,639300
17,GVREIT,-,7,0.05,0.72,6.95,7,6.90,-,0,969400,6748.19,807700,6.95,7.00,827200
54,WHAIR,XD,7.50,-0.05,-0.66,7.45,7.50,7.45,-,0,574211,4285.12,420900,7.45,7.50,475100
55,WHART,-,10.40,-,-,10.40,10.40,10.30,-,0,2376400,24701.91,1366300,10.30,10.40,608000

In [27]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].head()

   Symbol  Last Change %Change Open High   Low Total Volume Total Value (k)
0     AAV  1.06  -0.01   -0.93 1.07 1.08  1.06     36276364        38694.60
1     ANI  2.56   0.02    0.79 2.54 2.56  2.52        11852           30.10
2     AOT 52.75      -       -   53   53 52.25     15521101       817284.42
3  ASIMAR  1.39   0.03    2.21 1.37 1.45  1.37       210950          294.46
4       B  0.04   0.01   33.33 0.04 0.04  0.03      1553026           48.27

In [28]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,30.50,-,-,30.50,30.50,30.25,-,0,588452,17891.24,443500,30.25,30.50,102600
23,TFFIF,-,6.60,-0.05,-0.75,6.60,6.65,6.60,-,0,1470220,9767.04,4614800,6.60,6.65,657900

In [29]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].head()

   Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0   3BBIF 6.45      -       - 6.50 6.50 6.40      5553074        35846.52
1  ADVANC  355     -3   -0.84  359  361  355      7266150      2602236.53
2     AIT 4.68      -       - 4.68 4.70 4.66       662776         3101.90
3     ALT 1.35      -       - 1.36 1.44 1.33      4779326         6609.89
4     AMR 0.36      -       - 0.34 0.36 0.34       277227           95.37

In [30]:
df_ICT.query('Symbol == ("3BBIF","DIF","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.45,-,-,6.50,6.50,6.40,-,0,5553074,35846.52,1923600,6.45,6.50,2877200
7,DIF,-,9.95,-,-,9.90,9.95,9.90,-,0,5702533,56655.29,3586500,9.90,9.95,1508000
33,SYNEX,-,9.20,0.05,0.55,9.20,9.25,9.15,-,0,422046,3883.94,217100,9.15,9.20,3800

## Add section ENERG for PTG

In [32]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].head()

  Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0    ACC 0.40  -0.01   -2.44 0.41 0.41 0.40      4074300         1633.38
1    ACE 1.29      -       - 1.29 1.30 1.28        76603           98.75
2     AE 0.11      -       - 0.10 0.11 0.10      2288030          236.80
3    AGE 1.21      -       - 1.22 1.23 1.20      1463218         1773.21
4     AI 2.86   0.02    0.70 2.86 2.86 2.82       108201          305.98

In [33]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
35,PTG,-,7.25,-0.05,-0.68,7.35,7.35,7.20,-,0,3025631,22009.00,1135800,7.20,7.25,59400
36,PTT,-,36.75,-0.50,-1.34,37.25,37.25,36.75,-,0,37507792,1386434.72,12746000,36.75,37,5122700

### ------------ End of Individual Category

In [35]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(669, 16)

In [36]:
df.Symbol.nunique()

361

In [37]:
df.query('Symbol == "CPNREIT"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,12.70,0.20,1.60,12.50,12.70,12.50,-,0,2602824,32999.28,1008500,12.60,12.70,639300

In [38]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(361, 16)

In [39]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [40]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(361, 9)

In [41]:
# Clean Symbol column (remove <XD>)
df['Symbol'] = df['Symbol'].str.replace(r'\s*<.*?>', '', regex=True)

# Then proceed with numeric conversion as above
numeric_cols = df.columns.drop('Symbol')
df[numeric_cols] = (
    df[numeric_cols].replace('-', 0)
    .apply(pd.to_numeric, errors='coerce', downcast=None)  # Disable downcasting
)
df[cols].shape

C:\Users\PC1\AppData\Local\Temp\ipykernel_9432\3393296708.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[numeric_cols].replace('-', 0)

(361, 9)

In [42]:
# If run after actual work day
#today = today - timedelta(days=2)
#today

In [43]:
df.insert(1, 'Date', today)

In [44]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2026-05-22,1.06,-0.01,-0.93,1.07,1.08,1.06,36276364,38694.60
1,ADVANC,2026-05-22,355.00,-3.00,-0.84,359.00,361.00,355.00,7266150,2602236.53
2,AEONTS,2026-05-22,93.00,0.25,0.27,92.75,93.50,92.50,127196,11834.93
3,AMATA,2026-05-22,25.00,-0.25,-0.99,25.25,25.50,24.80,17196466,430314.06
4,AOT,2026-05-22,52.75,0.00,0.00,53.00,53.00,52.25,15521101,817284.42
...,...,...,...,...,...,...,...,...,...,...
53,TGE,2026-05-22,1.15,0.00,0.00,1.14,1.16,1.14,38947,44.66
55,TPIPP,2026-05-22,1.78,0.00,0.00,1.79,1.80,1.78,953951,1702.32
56,TSE,2026-05-22,0.87,0.04,4.82,0.83,0.89,0.83,42782870,37023.43
58,UBE,2026-05-22,0.57,0.03,5.56,0.55,0.59,0.55,21755866,12363.61
60,WP,2026-05-22,3.54,0.00,0.00,3.52,3.54,3.52,119376,422.18

In [45]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [46]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(190, 1)

In [47]:
df_out = df[colt]
df_out.shape

(361, 10)

In [48]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(161, 10)

In [49]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [50]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [51]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [52]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price.csv

In [53]:
df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(god_file, header=True, index=False)
df_merge[colp].to_csv(icd_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [55]:
file_name = "Price-Today.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [56]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Today.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Today.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Today.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Today.csv

In [57]:
df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(god_file, header=True, index=False)
df_merge.to_csv(icd_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

In [58]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-05-22 20:02:59

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes