### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
print(today)

2026-10-28

In [4]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-10-28 19:20:27

### Restart & Run All Cells

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\PC1\OneDrive\Downloads\Datasets

In [7]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Datasets path : C:\Users\PC1\OneDrive\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A4\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [9]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [11]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
#df_S100[colu].sort_values(['%Change'],ascending=[False])
df_S100[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,0.81,-,-,0.81,0.82,0.80,27893036,22569.19
1,ADVANC,336.00,1,0.30,335.00,339.00,335.00,5654129,1905439.83
2,AEONTS,89.00,-0.25,-0.28,89.25,89.75,89.00,326342,29108.10
3,AMATA,27.00,-1.75,-6.09,28.25,28.50,26.50,28242842,774801.71
4,AOT,60.00,-1.25,-2.04,61.50,61.50,60.00,34827319,2110523.52

In [12]:
df_S100.query('Symbol == ("ADVANC","BCH","IVL","JMT","PTTGC","RCL","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,ADVANC,-,336.00,1,0.30,335.00,339.00,335.00,1182000,398265.11,5654129,1905439.83,88600,336.00,337.00,111600
12,BCH,-,10.90,0.10,0.93,10.80,10.90,10.70,331900,3617.71,8623611,93518.31,647100,10.90,11.00,1202600
48,IVL,-,26.50,-1,-3.64,27.50,27.50,26.25,-,0.00,25411808,675549.76,2682800,26.25,26.50,471300
50,JMT,-,10.40,-,-,10.50,10.60,10.30,-,0.00,1794790,18730.23,317300,10.30,10.40,266500
71,PTTGC,-,51.00,-3.25,-5.99,54.25,54.25,50.50,-,0.00,56641215,2914341.56,1842500,50.75,51.00,257700
74,RCL,-,49.25,-,-,49.00,49.50,48.50,-,0.00,2107804,103302.35,139400,49.00,49.25,73200
82,STA,-,22.90,-0.80,-3.38,23.70,23.80,22.80,-,0.00,7902769,182652.92,248500,22.80,22.90,2800

In [13]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAI,4.24,-0.02,-0.47,4.28,4.28,4.24,600655,2552.43
1,ADVICE,7.05,-,-,7.05,7.15,7.00,385622,2720.27
2,AH,15.00,-,-,14.90,15.10,14.90,190254,2846.76
3,AIT,4.74,-0.02,-0.42,4.76,4.78,4.72,281003,1333.42
4,ASIAN,7.15,-,-,7.20,7.20,7.15,196041,1404.58

In [14]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
2,AH,-,15.00,-,-,14.90,15.10,14.90,-,0,190254,2846.76,4100,14.90,15.00,8000
33,MCS,-,7.75,-0.05,-0.64,7.80,7.80,7.70,-,0,383127,2970.46,138500,7.75,7.80,533300
42,ORI,-,1.75,-0.03,-1.69,1.78,1.78,1.75,-,0,429798,757.41,113200,1.75,1.76,6200
60,SINGER,-,13.60,-0.40,-2.86,14.10,14.20,13.50,-,0,7505665,103233.06,69200,13.60,13.70,89700

In [15]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,0.81,-,-,0.81,0.82,0.80,27893036,22569.19
1,AMATA,27.00,-1.75,-6.09,28.25,28.50,26.50,28242842,774801.71
2,BA,18.10,-0.80,-4.23,19.00,19.00,18.10,16449582,301925.38
3,BANPU,14.40,-0.20,-1.37,14.70,14.70,14.40,10659669,154263.23
4,BBL,187.50,2.50,1.35,185.00,188.00,184.50,12135369,2264910.62

In [16]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,10.90,0.10,0.93,10.80,10.90,10.70,331900,3617.71,8623611,93518.31,647100,10.90,11.00,1202600
24,IVL,-,26.50,-1,-3.64,27.50,27.50,26.25,-,0.00,25411808,675549.76,2682800,26.25,26.50,471300
37,PTTGC,-,51.00,-3.25,-5.99,54.25,54.25,50.50,-,0.00,56641215,2914341.56,1842500,50.75,51.00,257700
40,RCL,-,49.25,-,-,49.00,49.50,48.50,-,0.00,2107804,103302.35,139400,49.00,49.25,73200
54,TOA,-,14.90,0.10,0.68,14.80,14.90,14.70,-,0.00,612009,9054.38,11200,14.80,14.90,143500

In [17]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AEONTS,89.00,-0.25,-0.28,89.25,89.75,89.00,326342,29108.10
1,AMATA,27.00,-1.75,-6.09,28.25,28.50,26.50,28242842,774801.71
2,AP,7.90,-0.10,-1.25,8.05,8.05,7.85,4095884,32440.96
3,BA,18.10,-0.80,-4.23,19.00,19.00,18.10,16449582,301925.38
4,BAM,6.35,-0.05,-0.78,6.40,6.40,6.35,1588892,10109.02

In [18]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
7,JMT,-,10.40,-,-,10.50,10.60,10.30,-,0.00,1794790,18730.23,317300,10.30,10.40,266500
20,RCL,-,49.25,-,-,49.00,49.50,48.50,-,0.00,2107804,103302.35,139400,49.00,49.25,73200

In [19]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,0.81,-,-,0.81,0.82,0.80,27893036,22569.19
1,ADVANC,336.00,1,0.30,335.00,339.00,335.00,5654129,1905439.83
2,AEONTS,89.00,-0.25,-0.28,89.25,89.75,89.00,326342,29108.10
3,AMATA,27.00,-1.75,-6.09,28.25,28.50,26.50,28242842,774801.71
4,AOT,60.00,-1.25,-2.04,61.50,61.50,60.00,34827319,2110523.52

In [20]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMT","NER","ORI","PTTGC","STA","SYNEX","TOA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,3.16,-0.02,-0.63,3.20,3.22,3.12,-,0.00,82403656,260774.20,3055300,3.16,3.18,1586600
14,BCH,-,10.90,0.10,0.93,10.80,10.90,10.70,331900,3617.71,8623611,93518.31,647100,10.90,11.00,1202600
49,IVL,-,26.50,-1,-3.64,27.50,27.50,26.25,-,0.00,25411808,675549.76,2682800,26.25,26.50,471300
51,JMT,-,10.40,-,-,10.50,10.60,10.30,-,0.00,1794790,18730.23,317300,10.30,10.40,266500
68,NER,-,4.70,-0.02,-0.42,4.74,4.76,4.68,-,0.00,7769952,36668.92,219700,4.70,4.72,263500
80,PTTGC,-,51.00,-3.25,-5.99,54.25,54.25,50.50,-,0.00,56641215,2914341.56,1842500,50.75,51.00,257700
100,STA,-,22.90,-0.80,-3.38,23.70,23.80,22.80,-,0.00,7902769,182652.92,248500,22.80,22.90,2800
109,TOA,-,14.90,0.10,0.68,14.80,14.90,14.70,-,0.00,612009,9054.38,11200,14.80,14.90,143500
117,TVO,-,28.50,-0.25,-0.87,28.75,28.75,28.00,-,0.00,1944238,55249.33,334500,28.50,28.75,263200

In [21]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].head()

  Symbol  Last Change %Change  Open  High   Low  Total Volume  Total Value (k)
0    AOT 60.00  -1.25   -2.04 61.50 61.50 60.00      34827319       2110523.52
1   AURA 13.50   0.10    0.75 13.50 13.60 13.30       4086865         54953.41
2     BA 18.10  -0.80   -4.23 19.00 19.00 18.10      16449582        301925.38
3    BCH 10.90   0.10    0.93 10.80 10.90 10.70       8623611         93518.31
4   BDMS 19.90      -       - 19.90 20.00 19.70      65029652       1293398.11

In [22]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,BCH,-,10.90,0.10,0.93,10.80,10.90,10.70,331900,3617.71,8623611,93518.31,647100,10.90,11.00,1202600
14,CPF,-,19.90,-0.10,-0.50,20.00,20.10,19.80,160100,3185.99,25028435,498385.25,2174400,19.90,20.00,1943800
25,STA,-,22.90,-0.80,-3.38,23.70,23.80,22.80,-,0.00,7902769,182652.92,248500,22.80,22.90,2800
29,TVO,-,28.50,-0.25,-0.87,28.75,28.75,28.00,-,0.00,1944238,55249.33,334500,28.50,28.75,263200

In [23]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].head()

   Symbol Last Change %Change  Open  High   Low Total Volume Total Value (k)
1      A5 1.76  -0.02   -1.12  1.79  1.79  1.75        27500           48.33
2   AMATA   27  -1.75   -6.09 28.25 28.50 26.50     28242842       774801.71
3  AMATAV 2.10      -       -  2.12  2.12  2.08        44100           92.70
4    ANAN 0.34  -0.01   -2.86  0.36  0.37  0.34     16635318         5941.93
5      AP 7.90  -0.10   -1.25  8.05  8.05  7.85      4095884        32440.96

In [24]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
7,AWC,-,3.16,-0.02,-0.63,3.20,3.22,3.12,-,0,82403656,260774.20,3055300,3.16,3.18,1586600
32,ORI,-,1.75,-0.03,-1.69,1.78,1.78,1.75,-,0,429798,757.41,113200,1.75,1.76,6200
51,SENA,-,1.56,-,-,1.56,1.58,1.55,-,0,247821,386.22,38400,1.55,1.56,34500

In [25]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].head()

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0    AIMCG  1.43      -       -  1.43  1.44  1.43       107100          153.21
1   AIMIRT 11.70   0.10    0.86 11.60 11.80 11.60       252416         2941.55
2     ALLY  4.62   0.02    0.43  4.60  4.62  4.58       993481         4570.48
3   AMATAR  7.35  -0.05   -0.68  7.35  7.35  7.35         2500           18.38
4  AXTRART 11.90   0.30    2.59 11.60    12 11.60      1161697        13720.45

In [26]:
df_PFREIT.query('Symbol == ("AIMIRT","CPNREIT","GVREIT","PROSPECT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,AIMIRT,-,11.70,0.10,0.86,11.60,11.80,11.60,-,0,252416,2941.55,167600,11.60,11.70,3300
9,CPNREIT,-,13.10,-,-,13.20,13.20,13,-,0,2174555,28495.01,291400,13.00,13.10,495800
17,GVREIT,-,7.10,-0.10,-1.39,7.20,7.20,7.10,-,0,262213,1876.69,146500,7.10,7.15,42500
38,PROSPECT,-,9.05,-0.05,-0.55,9.05,9.10,9,-,0,3280691,29669.01,2744600,9.00,9.05,541800
54,WHAIR,-,8,-,-,8,8.05,7.95,-,0,830758,6640.67,61000,8.00,8.05,18100
55,WHART,-,10.90,-,-,10.90,10.90,10.80,-,0,3208319,34757.03,89200,10.80,10.90,474700

In [27]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].head()

   Symbol Last Change %Change  Open  High  Low Total Volume Total Value (k)
0     AAV 0.81      -       -  0.81  0.82 0.80     27893036        22569.19
1     ANI 3.12   0.04    1.30  3.12  3.12 3.12          300            0.94
2     AOT   60  -1.25   -2.04 61.50 61.50   60     34827319      2110523.52
3  ASIMAR 1.44   0.01    0.70  1.46  1.46 1.43       215600          309.41
4       B 0.03      -       -  0.03  0.03 0.02       310995            7.86

In [28]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,49.25,-,-,49,49.50,48.50,-,0,2107804,103302.35,139400,49.00,49.25,73200
23,TFFIF,-,7,-,-,7,7.05,7,-,0,1587385,11127.00,1092800,6.95,7.00,91900

In [29]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].head()

   Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0   3BBIF 6.30      -       - 6.30 6.35 6.25      2219435        13975.43
1  ADVANC  336      1    0.30  335  339  335      5654129      1905439.83
2     AIT 4.74  -0.02   -0.42 4.76 4.78 4.72       281003         1333.42
3     ALT 1.65   0.01    0.61 1.66 1.68 1.65      1200400         1994.25
4     AMR 0.38   0.01    2.70 0.38 0.39 0.37        62200           23.65

In [30]:
df_ICT.query('Symbol == ("3BBIF","DIF","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.30,-,-,6.30,6.35,6.25,-,0,2219435,13975.43,939400,6.30,6.35,1509500
7,DIF,-,9.55,0.05,0.53,9.60,9.60,9.50,-,0,11051974,105312.20,291600,9.55,9.60,1445300
34,SYNEX,-,9.45,-0.10,-1.05,9.55,9.55,9.40,-,0,576685,5461.20,347300,9.40,9.45,60800

## Add section ENERG for PTG

In [32]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].head()

  Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0    ACC 0.32   0.01    3.23 0.31 0.33 0.31       400000          126.72
1    ACE 1.29      -       - 1.29 1.29 1.28      1155404         1483.97
2     AE 0.14  -0.01   -6.67 0.17 0.17 0.13      5866732          853.35
3    AGE 1.33  -0.02   -1.48 1.36 1.36 1.30      1248090         1648.24
4     AI 3.22      -       - 3.22 3.26 3.20       172349          553.79

In [33]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
34,PTG,-,7.75,-0.25,-3.12,7.95,7.95,7.75,-,0,4868026,38057.27,272200,7.75,7.80,75400
35,PTT,-,42,-,-,42.25,42.25,41.75,-,0,58535290,2460249.30,8953400,42,42.25,13447600

### ------------ End of Individual Category

In [35]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(663, 16)

In [36]:
df.Symbol.nunique()

357

In [37]:
df.query('Symbol == "IVL"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
48,IVL,-,26.50,-1,-3.64,27.50,27.50,26.25,-,0.00,25411808,675549.76,2682800,26.25,26.50,471300
24,IVL,-,26.50,-1,-3.64,27.50,27.50,26.25,-,0.00,25411808,675549.76,2682800,26.25,26.50,471300
49,IVL,-,26.50,-1,-3.64,27.50,27.50,26.25,-,0.00,25411808,675549.76,2682800,26.25,26.50,471300

In [38]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(357, 16)

In [39]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [40]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(357, 9)

In [41]:
# Clean Symbol column (remove <XD>)
df['Symbol'] = df['Symbol'].str.replace(r'\s*<.*?>', '', regex=True)

# Then proceed with numeric conversion as above
numeric_cols = df.columns.drop('Symbol')
df[numeric_cols] = (
    df[numeric_cols].replace('-', 0)
    .apply(pd.to_numeric, errors='coerce', downcast=None)  # Disable downcasting
)
df[cols].shape

C:\Users\PC1\AppData\Local\Temp\ipykernel_35508\3393296708.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[numeric_cols].replace('-', 0)

(357, 9)

In [42]:
# If run after actual work day
#today = today - timedelta(days=2)
#today

In [43]:
df.insert(1, 'Date', today)

In [44]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2026-10-28,0.81,0.00,0.00,0.81,0.82,0.80,27893036,22569.19
1,ADVANC,2026-10-28,336.00,1.00,0.30,335.00,339.00,335.00,5654129,1905439.83
2,AEONTS,2026-10-28,89.00,-0.25,-0.28,89.25,89.75,89.00,326342,29108.10
3,AMATA,2026-10-28,27.00,-1.75,-6.09,28.25,28.50,26.50,28242842,774801.71
4,AOT,2026-10-28,60.00,-1.25,-2.04,61.50,61.50,60.00,34827319,2110523.52
...,...,...,...,...,...,...,...,...,...,...
51,TCC,2026-10-28,0.28,0.01,3.70,0.27,0.28,0.26,242182,65.39
52,TGE,2026-10-28,0.98,0.00,0.00,0.99,0.99,0.98,210026,206.78
55,TSE,2026-10-28,1.22,-0.06,-4.69,1.30,1.31,1.21,44839303,56337.72
57,UBE,2026-10-28,0.57,-0.02,-3.39,0.59,0.59,0.57,5678192,3288.94
59,WP,2026-10-28,3.68,-0.02,-0.54,3.70,3.72,3.68,286143,1058.41

In [45]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [46]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(188, 1)

In [47]:
df_out = df[colt]
df_out.shape

(357, 10)

In [48]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(160, 10)

In [49]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [50]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [51]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = os.path.join(dat_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [52]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price.csv

In [53]:
df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(icd_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [55]:
file_name = "Price-Today.csv"
output_file = os.path.join(dat_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [56]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Today.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Today.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Today.csv

In [57]:
df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(icd_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

In [58]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-10-28 19:20:28

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes