### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
print(today)

2026-05-15

In [4]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-05-15 19:55:12

### Restart & Run All Cells

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\PC1\OneDrive\Downloads\Datasets

In [7]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Datasets path : C:\Users\PC1\OneDrive\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [9]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [11]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
#df_S100[colu].sort_values(['%Change'],ascending=[False])
df_S100[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.05,-0.02,-1.87,1.07,1.07,1.05,36180741,38175.05
1,ADVANC,365.00,2,0.55,361.00,365.00,360.00,4256712,1545829.38
2,AEONTS,92.75,-0.50,-0.54,92.25,93.00,91.75,396675,36648.70
3,AMATA,21.40,0.70,3.38,21.30,21.60,21.10,36111359,770205.91
4,AOT,53.00,-0.25,-0.47,53.25,53.25,52.50,13340049,706386.21

In [12]:
df_S100.query('Symbol == ("ADVANC","BCH","IVL","JMT","PTTGC","RCL","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,ADVANC,-,365.00,2,0.55,361.00,365.00,360.00,-,0.00,4256712,1545829.38,25400,364.00,365.00,286700
12,BCH,-,9.20,-,-,9.20,9.25,9.20,-,0.00,4803294,44247.02,1208700,9.20,9.25,522600
47,IVL,-,24.40,-1.10,-4.31,25.25,26.00,23.90,-,0.00,55040562,1342763.26,61800,24.30,24.40,253400
50,JMT,-,10.50,1.05,11.11,9.35,10.70,9.35,-,0.00,83712718,850855.43,649700,10.50,10.60,163500
71,PTTGC,-,38.00,-1.50,-3.80,39.25,39.75,37.75,-,0.00,22283502,854067.40,379600,38.00,38.25,1354800
74,RCL,-,31.00,-0.50,-1.59,31.50,31.75,30.75,-,0.00,2044794,63714.47,406700,30.75,31.00,37500
84,STA,-,19.70,-0.30,-1.50,19.90,20.00,19.60,-,0.00,7793715,154406.06,74100,19.60,19.70,107300

In [13]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAI,3.44,-0.04,-1.15,3.48,3.48,3.44,895604,3096.07
1,ADVICE,5.80,-0.20,-3.33,6.15,6.35,5.70,18476343,112274.01
2,AH,13.90,0.40,2.96,13.80,14.00,13.80,538331,7482.27
3,AIT,4.70,-,-,4.70,4.72,4.68,660503,3106.47
4,ASIAN,6.90,-,-,6.90,6.95,6.85,1264229,8763.19

In [14]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
2,AH,-,13.90,0.40,2.96,13.80,14.00,13.80,-,0,538331,7482.27,36700,13.80,13.90,16300
39,MCS,-,7.60,-0.05,-0.65,7.70,7.70,7.50,-,0,1302153,9865.75,181600,7.55,7.60,182600
50,ORI,-,1.69,-0.02,-1.17,1.70,1.73,1.69,-,0,3140909,5363.47,257800,1.69,1.70,3000
73,SINGER,-,6.60,0.95,16.81,6.05,6.80,6.00,-,0,29661263,193585.00,102400,6.55,6.60,47100
83,SYNEX,-,9.25,-0.25,-2.63,9.50,9.65,9.15,-,0,4041593,37680.81,785900,9.20,9.25,501900

In [15]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.05,-0.02,-1.87,1.07,1.07,1.05,36180741,38175.05
1,AMATA,21.40,0.70,3.38,21.30,21.60,21.10,36111359,770205.91
2,BA,13.80,-0.20,-1.43,14.10,14.10,13.80,6498188,90591.28
3,BANPU,5.60,-,-,5.60,5.60,5.55,22702392,126648.91
4,BBL,165.00,0.50,0.30,165.00,167.00,164.50,11976880,1982388.48

In [16]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,9.20,-,-,9.20,9.25,9.20,-,0.00,4803294,44247.02,1208700,9.20,9.25,522600
24,IVL,-,24.40,-1.10,-4.31,25.25,26.00,23.90,-,0.00,55040562,1342763.26,61800,24.30,24.40,253400
38,PTTGC,-,38.00,-1.50,-3.80,39.25,39.75,37.75,-,0.00,22283502,854067.40,379600,38.00,38.25,1354800
41,RCL,-,31.00,-0.50,-1.59,31.50,31.75,30.75,-,0.00,2044794,63714.47,406700,30.75,31.00,37500
53,TOA,-,11.70,-0.10,-0.85,11.80,11.90,11.60,-,0.00,2648842,31074.51,431100,11.60,11.70,378000

In [17]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AEONTS,92.75,-0.50,-0.54,92.25,93.00,91.75,396675,36648.70
1,AMATA,21.40,0.70,3.38,21.30,21.60,21.10,36111359,770205.91
2,AP,7.50,-,-,7.55,7.55,7.45,13991442,105239.39
3,BAM,6.55,-0.10,-1.50,6.60,6.65,6.50,11604534,75962.11
4,BBL,165.00,0.50,0.30,165.00,167.00,164.50,11976880,1982388.48

In [18]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
6,JMT,-,10.50,1.05,11.11,9.35,10.70,9.35,-,0.00,83712718,850855.43,649700,10.50,10.60,163500
19,RCL,-,31.00,-0.50,-1.59,31.50,31.75,30.75,-,0.00,2044794,63714.47,406700,30.75,31.00,37500

In [19]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.05,-0.02,-1.87,1.07,1.07,1.05,36180741,38175.05
1,ADVANC,365.00,2,0.55,361.00,365.00,360.00,4256712,1545829.38
2,AEONTS,92.75,-0.50,-0.54,92.25,93.00,91.75,396675,36648.70
3,AMATA,21.40,0.70,3.38,21.30,21.60,21.10,36111359,770205.91
4,AOT,53.00,-0.25,-0.47,53.25,53.25,52.50,13340049,706386.21

In [20]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMT","NER","ORI","PTTGC","STA","SYNEX","TOA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.14,-0.04,-1.83,2.18,2.18,2.12,-,0.00,35720848,76686.88,7123200,2.12,2.14,113000
13,BCH,-,9.20,-,-,9.20,9.25,9.20,-,0.00,4803294,44247.02,1208700,9.20,9.25,522600
48,IVL,-,24.40,-1.10,-4.31,25.25,26.00,23.90,-,0.00,55040562,1342763.26,61800,24.30,24.40,253400
50,JMT,-,10.50,1.05,11.11,9.35,10.70,9.35,-,0.00,83712718,850855.43,649700,10.50,10.60,163500
66,NER,-,4.38,-0.04,-0.90,4.40,4.42,4.36,-,0.00,5872721,25759.78,1222200,4.36,4.38,86300
68,ORI,-,1.69,-0.02,-1.17,1.70,1.73,1.69,-,0.00,3140909,5363.47,257800,1.69,1.70,3000
80,PTTGC,-,38.00,-1.50,-3.80,39.25,39.75,37.75,-,0.00,22283502,854067.40,379600,38.00,38.25,1354800
101,STA,-,19.70,-0.30,-1.50,19.90,20.00,19.60,-,0.00,7793715,154406.06,74100,19.60,19.70,107300
104,SYNEX,-,9.25,-0.25,-2.63,9.50,9.65,9.15,-,0.00,4041593,37680.81,785900,9.20,9.25,501900
112,TOA,-,11.70,-0.10,-0.85,11.80,11.90,11.60,-,0.00,2648842,31074.51,431100,11.60,11.70,378000
119,TVO,-,25.25,0.45,1.81,24.90,25.50,24.80,-,0.00,1503431,37751.25,178400,25.25,25.50,354900

In [21]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].head()

  Symbol  Last Change %Change  Open  High   Low  Total Volume  Total Value (k)
0    AOT 53.00  -0.25   -0.47 53.25 53.25 52.50      13340049        706386.21
1   AURA 14.20   0.60    4.41 13.60 14.40 13.40       5554647         77282.60
2     BA 13.80  -0.20   -1.43 14.10 14.10 13.80       6498188         90591.28
3    BCH  9.20      -       -  9.20  9.25  9.20       4803294         44247.02
4   BDMS 18.30  -0.20   -1.08 18.50 18.50 18.10      62212626       1136016.40

In [22]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,BCH,-,9.20,-,-,9.20,9.25,9.20,-,0.00,4803294,44247.02,1208700,9.20,9.25,522600
15,CPF,-,19.00,-0.20,-1.04,19.10,19.10,18.80,154200,3124.25,34199130,649648.38,1635200,19.00,19.10,743100
26,STA,-,19.70,-0.30,-1.50,19.90,20.00,19.60,-,0.00,7793715,154406.06,74100,19.60,19.70,107300
29,TVO,-,25.25,0.45,1.81,24.90,25.50,24.80,-,0.00,1503431,37751.25,178400,25.25,25.50,354900

In [23]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].head()

   Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
1      A5  1.83      -       -  1.83  1.83  1.83         1105            2.02
3   AMATA 21.40   0.70    3.38 21.30 21.60 21.10     36111359       770205.91
4  AMATAV  1.94   0.01    0.52  1.93  1.94  1.92        49912           96.31
5    ANAN  0.35      -       -  0.35  0.35  0.34       571200          195.16
6      AP  7.50      -       -  7.55  7.55  7.45     13991442       105239.39

In [24]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.14,-0.04,-1.83,2.18,2.18,2.12,-,0,35720848,76686.88,7123200,2.12,2.14,113000
34,ORI,-,1.69,-0.02,-1.17,1.70,1.73,1.69,-,0,3140909,5363.47,257800,1.69,1.70,3000
53,SENA,-,1.80,-0.01,-0.55,1.80,1.81,1.77,-,0,940966,1681.06,1900,1.79,1.80,1600

In [25]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].head()

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0    AIMCG  1.34      -       -  1.35  1.36  1.33       416800          559.83
1   AIMIRT 11.60      -       - 11.50 11.60 11.50       159209         1841.92
2     ALLY  4.70      -       -  4.70  4.72  4.68       202669          950.82
3   AMATAR  7.15   0.05    0.70  7.05  7.20  7.05        19493          139.33
4  AXTRART 12.90  -0.10   -0.77    13 13.20 12.90      2073997        26976.10

In [26]:
df_PFREIT.query('Symbol == ("CPNREIT","GVREIT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,12.40,0.10,0.81,12.30,12.50,12.30,-,0,2289561,28399.73,605100,12.40,12.50,777000
17,GVREIT,-,6.90,-,-,6.90,6.95,6.85,-,0,1228114,8475.57,615900,6.85,6.90,279000
54,WHAIR,-,7.50,-0.05,-0.66,7.50,7.55,7.50,-,0,388092,2924.68,351700,7.50,7.55,213900
55,WHART,-,10.70,0.10,0.94,10.70,10.80,10.60,-,0,4299640,45837.02,1647100,10.60,10.70,371800

In [27]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].head()

   Symbol Last Change %Change  Open  High   Low Total Volume Total Value (k)
0     AAV 1.05  -0.02   -1.87  1.07  1.07  1.05     36180741        38175.05
1     ANI 2.52      -       -  2.54  2.58  2.50        26102           66.64
2     AOT   53  -0.25   -0.47 53.25 53.25 52.50     13340049       706386.21
3  ASIMAR 1.40  -0.03   -2.10  1.44  1.45  1.38       248111          348.03
4       B 0.04      -       -  0.04  0.04  0.03       503435           17.32

In [28]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,31,-0.50,-1.59,31.50,31.75,30.75,-,0,2044794,63714.47,406700,30.75,31.00,37500
23,TFFIF,-,6.70,0.10,1.52,6.65,6.70,6.60,-,0,1980543,13177.30,792800,6.65,6.70,1643500

In [29]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].head()

   Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0   3BBIF 6.65      -       - 6.60 6.65 6.55      7177174        47454.42
1  ADVANC  365      2    0.55  361  365  360      4256712      1545829.38
2     AIT 4.70      -       - 4.70 4.72 4.68       660503         3106.47
3     ALT 1.24      -       - 1.27 1.27 1.22      1600500         1979.54
4     AMR 0.34   0.01    3.03 0.33 0.34 0.33       531121          179.19

In [30]:
df_ICT.query('Symbol == ("3BBIF","DIF","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.65,-,-,6.60,6.65,6.55,-,0,7177174,47454.42,594700,6.60,6.65,2508300
7,DIF,XD,10,-0.10,-0.99,9.90,10.10,9.90,-,0,22751458,226678.85,7536100,9.95,10,3132500
33,SYNEX,-,9.25,-0.25,-2.63,9.50,9.65,9.15,-,0,4041593,37680.81,785900,9.20,9.25,501900

## Add section ENERG for PTG

In [32]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].head()

  Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0    ACC 0.37  -0.01   -2.63 0.38 0.38 0.37      3164406         1174.06
1    ACE 1.28   0.01    0.79 1.27 1.28 1.27       233210          297.56
2     AE 0.09  -0.01     -10 0.10 0.10 0.09       930738           90.88
3    AGE 1.23   0.03    2.50 1.25 1.27 1.21     10223900        12641.77
4     AI 2.90   0.02    0.69 2.88 2.92 2.88        55154          159.20

In [33]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
35,PTG,-,7.35,-0.15,-2,7.50,7.55,7.30,-,0,4813453,35647.44,266900,7.35,7.40,48400
36,PTT,-,36.25,-1,-2.68,37,37,36.25,-,0,74320078,2713497.79,10055800,36.25,36.50,9994500

### ------------ End of Individual Category

In [35]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(671, 16)

In [36]:
df.Symbol.nunique()

363

In [37]:
df.query('Symbol == "CPNREIT"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,12.40,0.10,0.81,12.30,12.50,12.30,-,0,2289561,28399.73,605100,12.40,12.50,777000

In [38]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(363, 16)

In [39]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [40]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(363, 9)

In [41]:
# Clean Symbol column (remove <XD>)
df['Symbol'] = df['Symbol'].str.replace(r'\s*<.*?>', '', regex=True)

# Then proceed with numeric conversion as above
numeric_cols = df.columns.drop('Symbol')
df[numeric_cols] = (
    df[numeric_cols].replace('-', 0)
    .apply(pd.to_numeric, errors='coerce', downcast=None)  # Disable downcasting
)
df[cols].shape

C:\Users\PC1\AppData\Local\Temp\ipykernel_29016\3393296708.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[numeric_cols].replace('-', 0)

(363, 9)

In [42]:
# If run after actual work day
#today = today - timedelta(days=2)
#today

In [43]:
df.insert(1, 'Date', today)

In [44]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2026-05-15,1.05,-0.02,-1.87,1.07,1.07,1.05,36180741,38175.05
1,ADVANC,2026-05-15,365.00,2.00,0.55,361.00,365.00,360.00,4256712,1545829.38
2,AEONTS,2026-05-15,92.75,-0.50,-0.54,92.25,93.00,91.75,396675,36648.70
3,AMATA,2026-05-15,21.40,0.70,3.38,21.30,21.60,21.10,36111359,770205.91
4,AOT,2026-05-15,53.00,-0.25,-0.47,53.25,53.25,52.50,13340049,706386.21
...,...,...,...,...,...,...,...,...,...,...
53,TGE,2026-05-15,1.15,0.02,1.77,1.15,1.15,1.13,93119,106.84
55,TPIPP,2026-05-15,1.79,0.02,1.13,1.77,1.79,1.77,2838435,5059.67
56,TSE,2026-05-15,0.81,-0.02,-2.41,0.82,0.82,0.76,19616333,15542.57
58,UBE,2026-05-15,0.57,-0.01,-1.72,0.59,0.60,0.57,17988817,10453.90
60,WP,2026-05-15,3.52,-0.02,-0.56,3.54,3.56,3.52,64743,228.67

In [45]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [46]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(190, 1)

In [47]:
df_out = df[colt]
df_out.shape

(363, 10)

In [48]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(162, 10)

In [49]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [50]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [51]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [52]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price.csv

In [53]:
df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(god_file, header=True, index=False)
df_merge[colp].to_csv(icd_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [55]:
file_name = "Price-Today.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [56]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Today.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Today.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Today.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Today.csv

In [57]:
df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(god_file, header=True, index=False)
df_merge.to_csv(icd_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

In [58]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-05-15 19:55:13

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes