### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
yesterday = today - timedelta(days=1)
print(today, yesterday)

2026-03-19 2026-03-18

In [4]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-19 20:04:29

### Restart & Run All Cells

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\PC1\OneDrive\Downloads\Datasets

In [7]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Datasets path : C:\Users\PC1\OneDrive\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [9]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [11]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
#df_S100[colu].sort_values(['%Change'],ascending=[False])
df_S100[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-0.04,-3.64,1.09,1.10,1.06,55042525,59311.25
1,ADVANC,376.00,-3,-0.79,377.00,382.00,375.00,6353049,2403030.54
2,AEONTS,88.25,-2.25,-2.49,90.25,90.25,88.25,408955,36469.61
3,AMATA,18.70,-1,-5.08,19.30,19.40,18.70,14603922,277482.76
4,AOT,48.00,-1.50,-3.03,48.75,49.25,48.00,32003089,1557635.80

In [12]:
df_S100.query('Symbol == ("ADVANC","BCH","IVL","JMT","PTTGC","RCL","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,ADVANC,-,376.00,-3,-0.79,377.00,382.00,375.00,-,0.00,6353049,2403030.54,249900,375.00,376.00,68600
12,BCH,-,9.70,-0.40,-3.96,10.00,10.10,9.70,-,0.00,12268131,120595.09,852500,9.70,9.75,551500
47,IVL,-,23.60,0.30,1.29,23.70,24.00,23.10,-,0.00,65051283,1533039.80,394100,23.60,23.70,55800
50,JMT,-,8.10,-0.30,-3.57,8.35,8.45,8.10,-,0.00,12743522,105515.14,719800,8.10,8.15,15800
71,PTTGC,-,32.25,1.50,4.88,31.00,32.75,30.50,-,0.00,56967972,1810540.12,1245000,32.25,32.50,361000
74,RCL,-,31.00,-3.50,-10.14,34.25,34.50,31.00,-,0.00,13203270,426079.82,368100,31.00,31.25,247700
84,STA,-,16.00,-0.60,-3.61,16.40,16.50,15.90,-,0.00,14378474,232703.30,1324800,16.00,16.10,152800

In [13]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAI,3.34,-0.14,-4.02,3.48,3.50,3.34,7914748,27015.13
1,ADVICE,5.45,-0.20,-3.54,5.65,5.65,5.45,1658848,9123.57
2,AH,13.00,-0.30,-2.26,13.30,13.30,13.00,105240,1374.60
3,AIT,4.82,-0.06,-1.23,4.88,4.88,4.82,808471,3922.28
4,ASIAN,6.95,-0.20,-2.80,7.15,7.35,6.95,1188231,8451.12

In [14]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
2,AH,-,13.00,-0.30,-2.26,13.30,13.30,13.00,-,0,105240,1374.60,700,13.00,13.10,1100
39,MCS,-,9.45,-0.10,-1.05,9.55,9.60,9.35,-,0,1342229,12692.93,19300,9.40,9.45,200
50,ORI,-,1.80,-0.03,-1.64,1.84,1.84,1.77,-,0,1924008,3455.93,69700,1.80,1.81,72400
73,SINGER,-,4.96,-0.29,-5.52,5.20,5.20,4.96,-,0,3152894,15961.83,15100,4.96,5.00,53900
83,SYNEX,-,9.30,-0.40,-4.12,9.65,9.70,9.30,-,0,1334998,12577.00,112500,9.25,9.30,9700

In [15]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-0.04,-3.64,1.09,1.10,1.06,55042525,59311.25
1,AMATA,18.70,-1,-5.08,19.30,19.40,18.70,14603922,277482.76
2,BA,13.10,-0.60,-4.38,13.70,13.70,13.10,6997556,93349.39
3,BANPU,6.05,0.30,5.22,5.95,6.05,5.80,144188305,856580.52
4,BBL,164.00,-2,-1.20,165.00,166.00,164.00,12324496,2031016.37

In [16]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,9.70,-0.40,-3.96,10.00,10.10,9.70,-,0.00,12268131,120595.09,852500,9.70,9.75,551500
24,IVL,-,23.60,0.30,1.29,23.70,24.00,23.10,-,0.00,65051283,1533039.80,394100,23.60,23.70,55800
38,PTTGC,-,32.25,1.50,4.88,31.00,32.75,30.50,-,0.00,56967972,1810540.12,1245000,32.25,32.50,361000
41,RCL,-,31.00,-3.50,-10.14,34.25,34.50,31.00,-,0.00,13203270,426079.82,368100,31.00,31.25,247700
53,TOA,-,12.30,-0.30,-2.38,12.50,12.90,12.20,-,0.00,4918430,61366.72,380300,12.20,12.30,7200

In [17]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AEONTS,88.25,-2.25,-2.49,90.25,90.25,88.25,408955,36469.61
1,AMATA,18.70,-1,-5.08,19.30,19.40,18.70,14603922,277482.76
2,AP,8.35,-0.25,-2.91,8.55,8.55,8.35,7533191,63658.80
3,BAM,6.85,-0.20,-2.84,7.05,7.05,6.85,22337782,154797.67
4,BBL,164.00,-2,-1.20,165.00,166.00,164.00,12324496,2031016.37

In [18]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
6,JMT,-,8.10,-0.30,-3.57,8.35,8.45,8.10,-,0,12743522,105515.14,719800,8.10,8.15,15800
19,RCL,-,31.00,-3.50,-10.14,34.25,34.50,31.00,-,0,13203270,426079.82,368100,31.00,31.25,247700

In [19]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-0.04,-3.64,1.09,1.10,1.06,55042525,59311.25
1,ADVANC,376.00,-3,-0.79,377.00,382.00,375.00,6353049,2403030.54
2,AEONTS,88.25,-2.25,-2.49,90.25,90.25,88.25,408955,36469.61
3,AMATA,18.70,-1,-5.08,19.30,19.40,18.70,14603922,277482.76
4,AOT,48.00,-1.50,-3.03,48.75,49.25,48.00,32003089,1557635.80

In [20]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMT","NER","ORI","PTTGC","STA","SYNEX","TOA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,1.99,-0.07,-3.40,2.02,2.04,1.98,-,0.00,80412240,160948.97,10699400,1.98,2.00,786500
13,BCH,-,9.70,-0.40,-3.96,10.00,10.10,9.70,-,0.00,12268131,120595.09,852500,9.70,9.75,551500
48,IVL,-,23.60,0.30,1.29,23.70,24.00,23.10,-,0.00,65051283,1533039.80,394100,23.60,23.70,55800
50,JMT,-,8.10,-0.30,-3.57,8.35,8.45,8.10,-,0.00,12743522,105515.14,719800,8.10,8.15,15800
66,NER,-,4.66,-0.18,-3.72,4.82,4.82,4.66,-,0.00,21820809,103193.37,926600,4.66,4.68,48800
68,ORI,-,1.80,-0.03,-1.64,1.84,1.84,1.77,-,0.00,1924008,3455.93,69700,1.80,1.81,72400
80,PTTGC,-,32.25,1.50,4.88,31.00,32.75,30.50,-,0.00,56967972,1810540.12,1245000,32.25,32.50,361000
101,STA,-,16.00,-0.60,-3.61,16.40,16.50,15.90,-,0.00,14378474,232703.30,1324800,16.00,16.10,152800
104,SYNEX,-,9.30,-0.40,-4.12,9.65,9.70,9.30,-,0.00,1334998,12577.00,112500,9.25,9.30,9700
112,TOA,-,12.30,-0.30,-2.38,12.50,12.90,12.20,-,0.00,4918430,61366.72,380300,12.20,12.30,7200
119,TVO,-,24.20,-0.30,-1.22,24.40,24.70,24.20,-,0.00,951450,23243.57,58800,24.10,24.20,4000

In [21]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AOT,48.00,-1.50,-3.03,48.75,49.25,48.00,32003089,1557635.80
1,AURA,13.30,-0.70,-5.00,13.90,13.90,13.10,3721050,50176.64
2,BA,13.10,-0.60,-4.38,13.70,13.70,13.10,6997556,93349.39
3,BCH,9.70,-0.40,-3.96,10.00,10.10,9.70,12268131,120595.09
4,BDMS,18.40,-0.30,-1.60,18.60,18.80,18.40,91545395,1698115.37

In [22]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,BCH,-,9.70,-0.40,-3.96,10.00,10.10,9.70,-,0.00,12268131,120595.09,852500,9.70,9.75,551500
15,CPF,-,19.50,-0.60,-2.99,19.90,20.10,19.50,-,0.00,38983619,770163.53,2163700,19.50,19.60,146700
26,STA,-,16.00,-0.60,-3.61,16.40,16.50,15.90,-,0.00,14378474,232703.30,1324800,16.00,16.10,152800
29,TVO,-,24.20,-0.30,-1.22,24.40,24.70,24.20,-,0.00,951450,23243.57,58800,24.10,24.20,4000

In [23]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].head()

   Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
1      A5  1.85      -       -  1.84  1.85  1.78         3200            5.80
3   AMATA 18.70     -1   -5.08 19.30 19.40 18.70     14603922       277482.76
4  AMATAV     2  -0.02   -0.99  2.04  2.04     2        48801           97.73
5    ANAN  0.37  -0.01   -2.63  0.37  0.37  0.36      1522149          555.11
6      AP  8.35  -0.25   -2.91  8.55  8.55  8.35      7533191        63658.80

In [24]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,1.99,-0.07,-3.40,2.02,2.04,1.98,-,0,80412240,160948.97,10699400,1.98,2,786500
34,ORI,-,1.80,-0.03,-1.64,1.84,1.84,1.77,-,0,1924008,3455.93,69700,1.80,1.81,72400
53,SENA,-,1.88,-0.01,-0.53,1.88,1.89,1.86,-,0,118773,222.56,1000,1.87,1.88,57200

In [25]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].head()

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0    AIMCG  1.27  -0.03   -2.31  1.30  1.30  1.25       265725          335.21
1   AIMIRT 10.90      -       - 10.90 10.90 10.80        40901          444.06
2     ALLY  4.28  -0.04   -0.93  4.32  4.32  4.28       344306         1481.52
3   AMATAR  6.65      -       -  6.65  6.65  6.60        17300          115.04
4  AXTRART 12.40      -       - 12.40 12.50 12.30       850585        10575.14

In [26]:
df_PFREIT.query('Symbol == ("CPNREIT","GVREIT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,11.50,-0.20,-1.71,11.60,11.70,11.50,-,0,2299579,26538.67,91900,11.50,11.60,216400
17,GVREIT,-,6.40,-,-,6.35,6.40,6.35,-,0,191051,1222.23,4300,6.40,6.45,54000
54,WHAIR,-,6.90,-0.05,-0.72,6.95,6.95,6.85,-,0,349751,2408.64,14700,6.85,6.90,219300
55,WHART,-,10.20,-0.10,-0.97,10.20,10.30,10.10,-,0,1531508,15619.19,1066300,10.10,10.20,18800

In [27]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].head()

   Symbol Last Change %Change  Open  High  Low Total Volume Total Value (k)
0     AAV 1.06  -0.04   -3.64  1.09  1.10 1.06     55042525        59311.25
1     ANI 2.62  -0.06   -2.24  2.66  2.68 2.60        23715           61.98
2     AOT   48  -1.50   -3.03 48.75 49.25   48     32003089      1557635.80
3  ASIMAR 1.47  -0.03      -2  1.50  1.53 1.47       209401          313.01
4       B 0.04      -       -  0.04  0.04 0.03      1591043           62.01

In [28]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,31,-3.50,-10.14,34.25,34.50,31,-,0,13203270,426079.82,368100,31.00,31.25,247700
23,TFFIF,-,6.55,-0.10,-1.50,6.65,6.65,6.55,-,0,1517273,9990.30,589000,6.55,6.60,407900

In [29]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].head()

   Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0   3BBIF 6.55  -0.05   -0.76 6.55 6.60 6.50      8893609        58379.14
1  ADVANC  376     -3   -0.79  377  382  375      6353049      2403030.54
2     AIT 4.82  -0.06   -1.23 4.88 4.88 4.82       808471         3922.28
3     ALT 1.03  -0.06   -5.50 1.08 1.09 1.03       261100          280.83
4     AMR 0.32  -0.03   -8.57 0.35 0.35 0.32       854502          281.64

In [30]:
df_ICT.query('Symbol == ("3BBIF","DIF","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.55,-0.05,-0.76,6.55,6.60,6.50,-,0,8893609,58379.14,100800,6.55,6.60,3497200
7,DIF,-,9.50,0.05,0.53,9.45,9.50,9.40,-,0,7961274,75240.81,4200,9.45,9.50,8905300
33,SYNEX,-,9.30,-0.40,-4.12,9.65,9.70,9.30,-,0,1334998,12577.00,112500,9.25,9.30,9700

## Add section ENERG for PTG

In [32]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].head()

  Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0    ACC 0.38  -0.01   -2.56 0.39 0.39 0.38      1012194          388.22
1    ACE 1.28  -0.01   -0.78 1.29 1.29 1.28       330371          424.53
2     AE 0.08  -0.02     -20 0.10 0.11 0.07     62754254         5073.47
3    AGE 1.32      -       - 1.39 1.44 1.32      9603728        13252.11
4     AI 2.94  -0.04   -1.34    3 3.12 2.94      2054885         6269.82

In [33]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
35,PTG,-,7.90,-0.15,-1.86,8.05,8.10,7.90,-,0,8933757,71212.34,374100,7.90,7.95,91600
36,PTT,-,34.25,0.75,2.24,33.50,34.25,33.50,-,0,126796644,4312285.69,7167500,34,34.25,11765000

### ------------ End of Individual Category

In [35]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(669, 16)

In [36]:
df.Symbol.nunique()

361

In [37]:
df.query('Symbol == "CPNREIT"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,11.50,-0.20,-1.71,11.60,11.70,11.50,-,0,2299579,26538.67,91900,11.50,11.60,216400

In [38]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(361, 16)

In [39]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [40]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(361, 9)

In [41]:
# Clean Symbol column (remove <XD>)
df['Symbol'] = df['Symbol'].str.replace(r'\s*<.*?>', '', regex=True)

# Then proceed with numeric conversion as above
numeric_cols = df.columns.drop('Symbol')
df[numeric_cols] = (
    df[numeric_cols].replace('-', 0)
    .apply(pd.to_numeric, errors='coerce', downcast=None)  # Disable downcasting
)
df[cols].shape

C:\Users\PC1\AppData\Local\Temp\ipykernel_65408\3393296708.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[numeric_cols].replace('-', 0)

(361, 9)

In [42]:
# If run after actual work day
#today = today - timedelta(days=2)
#today

In [43]:
df.insert(1, 'Date', today)

In [44]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2026-03-19,1.06,-0.04,-3.64,1.09,1.10,1.06,55042525,59311.25
1,ADVANC,2026-03-19,376.00,-3.00,-0.79,377.00,382.00,375.00,6353049,2403030.54
2,AEONTS,2026-03-19,88.25,-2.25,-2.49,90.25,90.25,88.25,408955,36469.61
3,AMATA,2026-03-19,18.70,-1.00,-5.08,19.30,19.40,18.70,14603922,277482.76
4,AOT,2026-03-19,48.00,-1.50,-3.03,48.75,49.25,48.00,32003089,1557635.80
...,...,...,...,...,...,...,...,...,...,...
53,TGE,2026-03-19,1.17,-0.09,-7.14,1.29,1.30,1.16,254603,306.09
55,TPIPP,2026-03-19,1.80,-0.03,-1.64,1.83,1.83,1.80,2312808,4194.40
56,TSE,2026-03-19,0.52,0.00,0.00,0.51,0.57,0.50,19015718,10234.76
58,UBE,2026-03-19,0.71,0.11,18.33,0.61,0.77,0.61,236103565,167544.53
60,WP,2026-03-19,3.76,0.00,0.00,3.76,3.76,3.72,335482,1256.00

In [45]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [46]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(192, 1)

In [47]:
df_out = df[colt]
df_out.shape

(361, 10)

In [48]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(164, 10)

In [49]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [50]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [51]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [52]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price.csv

In [53]:
df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(god_file, header=True, index=False)
df_merge[colp].to_csv(icd_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [55]:
file_name = "Price-Today.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [56]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Today.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Today.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Today.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Today.csv

In [57]:
df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(god_file, header=True, index=False)
df_merge.to_csv(icd_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

In [58]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-19 20:04:30

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes