### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
print(today)

2026-08-06

In [4]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-08-06 20:04:43

### Restart & Run All Cells

In [6]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\PC1\OneDrive\Downloads\Datasets

In [7]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Datasets path : C:\Users\PC1\OneDrive\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [8]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [9]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [11]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
#df_S100[colu].sort_values(['%Change'],ascending=[False])
df_S100[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-,-,1.06,1.06,1.05,11942889,12628.76
1,ADVANC,375.00,6,1.63,371.00,378.00,371.00,15126781,5669450.30
2,AEONTS,104.50,-0.50,-0.48,105.50,106.00,104.50,267378,28093.44
3,AMATA,28.75,0.50,1.77,28.25,28.75,27.50,7933255,224085.09
4,AOT,63.25,0.25,0.40,63.50,64.00,63.25,13974955,888576.42

In [12]:
df_S100.query('Symbol == ("ADVANC","BCH","IVL","JMT","PTTGC","RCL","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,ADVANC,-,375.00,6,1.63,371.00,378.00,371.00,268000,100880.50,15126781,5669450.30,385400,375.00,376.00,50700
12,BCH,-,11.30,0.40,3.67,11.00,11.30,10.90,-,0.00,23492548,261536.88,392000,11.20,11.30,196500
47,IVL,-,21.90,-,-,21.90,22.10,21.70,-,0.00,15260251,334317.86,1921500,21.80,21.90,285100
49,JMT,-,12.10,-0.20,-1.63,12.30,12.40,12.10,-,0.00,4805382,58814.21,594500,12.10,12.20,129100
70,PTTGC,-,36.75,-0.25,-0.68,37.00,37.25,36.50,-,0.00,41611305,1534591.92,1100800,36.75,37.00,3082500
73,RCL,-,34.50,-1,-2.82,35.50,35.50,34.50,-,0.00,4404669,153187.19,287200,34.50,34.75,75600
81,STA,-,18.30,-0.10,-0.54,18.50,18.50,18.30,-,0.00,3788294,69652.29,320200,18.20,18.30,120100

In [13]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAI,4.00,0.02,0.50,4.00,4.02,3.96,1043093,4158.63
1,ADVICE,7.45,0.20,2.76,7.25,7.45,7.20,1533230,11303.59
2,AH,16.30,-0.40,-2.40,16.70,16.70,16.20,286756,4684.63
3,AIT,4.90,-0.06,-1.21,4.94,4.96,4.90,537123,2644.28
4,ASIAN,7.65,0.05,0.66,7.60,7.65,7.60,258522,1967.41

In [14]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
2,AH,-,16.30,-0.40,-2.40,16.70,16.70,16.20,-,0,286756,4684.63,52600,16.30,16.40,1000
33,MCS,-,8.05,-,-,8.05,8.10,8.00,-,0,245561,1977.19,26900,8.05,8.10,249100
42,ORI,-,2.00,-0.02,-0.99,2.02,2.04,2.00,-,0,1575135,3180.09,165000,2.00,2.02,25000
60,SINGER,-,12.00,-,-,11.90,12.20,11.90,-,0,2414626,29039.04,495000,11.90,12.00,26300

In [15]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-,-,1.06,1.06,1.05,11942889,12628.76
1,AMATA,28.75,0.50,1.77,28.25,28.75,27.50,7933255,224085.09
2,BA,19.70,0.10,0.51,19.70,19.70,19.40,4289858,83972.17
3,BANPU,15.00,-0.10,-0.66,15.00,15.10,14.90,26339845,395875.01
4,BBL,195.00,2.50,1.30,192.50,196.50,192.00,17758723,3463582.06

In [16]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,11.30,0.40,3.67,11.00,11.30,10.90,-,0.00,23492548,261536.88,392000,11.20,11.30,196500
24,IVL,-,21.90,-,-,21.90,22.10,21.70,-,0.00,15260251,334317.86,1921500,21.80,21.90,285100
37,PTTGC,-,36.75,-0.25,-0.68,37.00,37.25,36.50,-,0.00,41611305,1534591.92,1100800,36.75,37.00,3082500
40,RCL,-,34.50,-1,-2.82,35.50,35.50,34.50,-,0.00,4404669,153187.19,287200,34.50,34.75,75600
54,TOA,-,16.30,0.10,0.62,16.10,16.60,16.10,-,0.00,2904777,47601.70,156400,16.20,16.30,49000

In [17]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AEONTS,104.50,-0.50,-0.48,105.50,106.00,104.50,267378,28093.44
1,AMATA,28.75,0.50,1.77,28.25,28.75,27.50,7933255,224085.09
2,AP,8.25,-,-,8.20,8.25,8.10,12995216,106221.45
3,BA,19.70,0.10,0.51,19.70,19.70,19.40,4289858,83972.17
4,BAM,6.85,0.05,0.74,6.80,6.90,6.75,12932173,88496.85

In [18]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
7,JMT,-,12.10,-0.20,-1.63,12.30,12.40,12.10,-,0.00,4805382,58814.21,594500,12.10,12.20,129100
20,RCL,-,34.50,-1,-2.82,35.50,35.50,34.50,-,0.00,4404669,153187.19,287200,34.50,34.75,75600

In [19]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-,-,1.06,1.06,1.05,11942889,12628.76
1,ADVANC,375.00,6,1.63,371.00,378.00,371.00,15126781,5669450.30
2,AEONTS,104.50,-0.50,-0.48,105.50,106.00,104.50,267378,28093.44
3,AMATA,28.75,0.50,1.77,28.25,28.75,27.50,7933255,224085.09
4,AOT,63.25,0.25,0.40,63.50,64.00,63.25,13974955,888576.42

In [20]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMT","NER","ORI","PTTGC","STA","SYNEX","TOA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.98,-0.02,-0.67,3.00,3.02,2.98,-,0.00,38784487,116122.97,6750700,2.96,2.98,1268700
14,BCH,-,11.30,0.40,3.67,11.00,11.30,10.90,-,0.00,23492548,261536.88,392000,11.20,11.30,196500
48,IVL,-,21.90,-,-,21.90,22.10,21.70,-,0.00,15260251,334317.86,1921500,21.80,21.90,285100
50,JMT,-,12.10,-0.20,-1.63,12.30,12.40,12.10,-,0.00,4805382,58814.21,594500,12.10,12.20,129100
67,NER,-,4.56,0.06,1.33,4.52,4.56,4.50,-,0.00,10972165,49707.97,105900,4.54,4.56,1360500
79,PTTGC,-,36.75,-0.25,-0.68,37.00,37.25,36.50,-,0.00,41611305,1534591.92,1100800,36.75,37.00,3082500
99,STA,-,18.30,-0.10,-0.54,18.50,18.50,18.30,-,0.00,3788294,69652.29,320200,18.20,18.30,120100
109,TOA,-,16.30,0.10,0.62,16.10,16.60,16.10,-,0.00,2904777,47601.70,156400,16.20,16.30,49000
117,TVO,-,27.50,0.25,0.92,27.50,27.50,27.25,-,0.00,367096,10092.34,460300,27.25,27.50,73800

In [21]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].head()

  Symbol  Last Change %Change  Open  High   Low  Total Volume  Total Value (k)
0    AOT 63.25   0.25    0.40 63.50 64.00 63.25      13974955        888576.42
1   AURA 14.40   0.30    2.13 14.20 14.60 14.20       5213121         75227.83
2     BA 19.70   0.10    0.51 19.70 19.70 19.40       4289858         83972.17
3    BCH 11.30   0.40    3.67 11.00 11.30 10.90      23492548        261536.88
4   BDMS 19.90   0.30    1.53 19.60 20.10 19.50     146810658       2922498.43

In [22]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,BCH,-,11.30,0.40,3.67,11.00,11.30,10.90,-,0.00,23492548,261536.88,392000,11.20,11.30,196500
14,CPF,-,21.90,0.20,0.92,21.70,21.90,21.60,-,0.00,16856273,366106.19,600,21.80,21.90,360200
25,STA,-,18.30,-0.10,-0.54,18.50,18.50,18.30,-,0.00,3788294,69652.29,320200,18.20,18.30,120100
29,TVO,-,27.50,0.25,0.92,27.50,27.50,27.25,-,0.00,367096,10092.34,460300,27.25,27.50,73800

In [23]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].head()

   Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0       A     -      -       -     -     -     -            9            0.02
1      A5  1.81  -0.01   -0.55  1.81  1.81  1.79         4300            7.78
3   AMATA 28.75   0.50    1.77 28.25 28.75 27.50      7933255       224085.09
4  AMATAV  2.08   0.02    0.97  2.08  2.10  2.06        63501          131.37
5    ANAN  0.34      -       -  0.34  0.34  0.33      4035211         1340.49

In [24]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2.98,-0.02,-0.67,3,3.02,2.98,-,0,38784487,116122.97,6750700,2.96,2.98,1268700
34,ORI,-,2,-0.02,-0.99,2.02,2.04,2,-,0,1575135,3180.09,165000,2,2.02,25000
53,SENA,-,1.80,0.01,0.56,1.79,1.80,1.78,-,0,109006,195.16,25700,1.79,1.80,50400

In [25]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].head()

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0    AIMCG  1.75      -       -  1.74  1.75  1.74        11201           19.58
1   AIMIRT 12.70   0.10    0.79 12.50 12.70 12.50       471104         5934.95
2     ALLY  5.15  -0.05   -0.96  5.15  5.20  5.10       522629         2691.55
3   AMATAR  7.60      -       -  7.50  7.65  7.50        39637          298.29
4  AXTRART    13  -0.10   -0.76 13.10 13.20    13       980040        12819.68

In [26]:
df_PFREIT.query('Symbol == ("AIMIRT","CPNREIT","GVREIT","PROSPECT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,AIMIRT,-,12.70,0.10,0.79,12.50,12.70,12.50,-,0,471104,5934.95,280900,12.50,12.70,550500
9,CPNREIT,-,13.50,-0.10,-0.74,13.50,13.60,13.40,-,0,2170947,29272.88,365800,13.40,13.50,8200
17,GVREIT,-,8.20,-0.05,-0.61,8.20,8.25,8.15,-,0,163409,1337.23,1169800,8.15,8.20,35100
38,PROSPECT,XA,10.30,-,-,10.40,10.40,10.30,-,0,884878,9134.41,633100,10.30,10.40,777700
54,WHAIR,-,8.45,0.05,0.60,8.35,8.45,8.35,-,0,1084649,9128.43,25500,8.40,8.45,92800
55,WHART,-,11.40,-0.10,-0.87,11.40,11.50,11.40,-,0,2136072,24387.84,41100,11.40,11.50,1981200

In [27]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.06,-,-,1.06,1.06,1.05,11942889,12628.76
1,ANI,3.52,-0.02,-0.56,3.64,3.64,3.52,327300,1156.07
2,AOT,63.25,0.25,0.40,63.50,64.00,63.25,13974955,888576.42
3,ASIMAR,1.47,0.02,1.38,1.45,1.50,1.45,958311,1408.05
4,B,0.03,-0.01,-25,0.03,0.04,0.03,574669,18.86

In [28]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,34.50,-1,-2.82,35.50,35.50,34.50,-,0.00,4404669,153187.19,287200,34.50,34.75,75600
23,TFFIF,-,7.15,0.05,0.70,7.10,7.20,7.10,-,0.00,2700773,19319.46,1646100,7.15,7.20,2334100

In [29]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].head()

   Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0   3BBIF 6.55      -       - 6.60 6.60 6.50      9803464        64226.96
1  ADVANC  375      6    1.63  371  378  371     15126781      5669450.30
2     AIT 4.90  -0.06   -1.21 4.94 4.96 4.90       537123         2644.28
3     ALT 1.72  -0.03   -1.71 1.75 1.79 1.72      2135676         3749.61
4     AMR 0.40   0.01    2.56 0.39 0.40 0.39        41040           16.24

In [30]:
df_ICT.query('Symbol == ("3BBIF","DIF","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.55,-,-,6.60,6.60,6.50,-,0,9803464,64226.96,2306500,6.55,6.60,5187400
7,DIF,-,10.30,-0.10,-0.96,10.30,10.40,10.30,-,0,8344464,86266.55,18090800,10.30,10.40,15998200
33,SYNEX,-,9.95,-0.15,-1.49,10.20,10.20,9.95,-,0,3506327,35457.15,229600,9.95,10,3300

## Add section ENERG for PTG

In [32]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].head()

  Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0    ACC 0.30  -0.01   -3.23 0.31 0.32 0.30      4639501         1409.34
1    ACE 1.31      -       - 1.31 1.31 1.30       691611          900.44
2     AE 0.10      -       - 0.10 0.10 0.09       153694           14.19
3    AGE 1.35  -0.01   -0.74 1.36 1.37 1.35      1008897         1367.99
4     AI 2.94   0.04    1.38 2.92 2.96 2.90       222789          653.20

In [33]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
34,PTG,-,7.30,-0.10,-1.35,7.35,7.35,7.25,-,0,7309253,53355.97,1898400,7.25,7.30,15500
35,PTT,-,38.75,0.50,1.31,38.25,39,38,-,0,161334241,6222581.79,30044500,38.50,38.75,4218400

### ------------ End of Individual Category

In [35]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(668, 16)

In [36]:
df.Symbol.nunique()

362

In [37]:
df.query('Symbol == "CPNREIT"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,13.50,-0.10,-0.74,13.50,13.60,13.40,-,0,2170947,29272.88,365800,13.40,13.50,8200

In [38]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(362, 16)

In [39]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [40]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(362, 9)

In [41]:
# Clean Symbol column (remove <XD>)
df['Symbol'] = df['Symbol'].str.replace(r'\s*<.*?>', '', regex=True)

# Then proceed with numeric conversion as above
numeric_cols = df.columns.drop('Symbol')
df[numeric_cols] = (
    df[numeric_cols].replace('-', 0)
    .apply(pd.to_numeric, errors='coerce', downcast=None)  # Disable downcasting
)
df[cols].shape

C:\Users\PC1\AppData\Local\Temp\ipykernel_26396\3393296708.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[numeric_cols].replace('-', 0)

(362, 9)

In [42]:
# If run after actual work day
#today = today - timedelta(days=2)
#today

In [43]:
df.insert(1, 'Date', today)

In [44]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2026-08-06,1.06,0.00,0.00,1.06,1.06,1.05,11942889,12628.76
1,ADVANC,2026-08-06,375.00,6.00,1.63,371.00,378.00,371.00,15126781,5669450.30
2,AEONTS,2026-08-06,104.50,-0.50,-0.48,105.50,106.00,104.50,267378,28093.44
3,AMATA,2026-08-06,28.75,0.50,1.77,28.25,28.75,27.50,7933255,224085.09
4,AOT,2026-08-06,63.25,0.25,0.40,63.50,64.00,63.25,13974955,888576.42
...,...,...,...,...,...,...,...,...,...,...
51,TCC,2026-08-06,0.30,0.00,0.00,0.31,0.31,0.30,185929,55.88
52,TGE,2026-08-06,1.28,0.00,0.00,1.29,1.31,1.26,445042,570.99
55,TSE,2026-08-06,0.77,-0.01,-1.28,0.78,0.79,0.77,2296815,1785.76
57,UBE,2026-08-06,0.59,0.01,1.72,0.59,0.60,0.58,2149500,1267.85
59,WP,2026-08-06,3.72,-0.02,-0.53,3.72,3.76,3.72,52605,196.62

In [45]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [46]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(188, 1)

In [47]:
df_out = df[colt]
df_out.shape

(362, 10)

In [48]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(160, 10)

In [49]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [50]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [51]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [52]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price.csv

In [53]:
df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(god_file, header=True, index=False)
df_merge[colp].to_csv(icd_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [55]:
file_name = "Price-Today.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [56]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Today.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Today.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Today.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Today.csv

In [57]:
df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(god_file, header=True, index=False)
df_merge.to_csv(icd_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

In [58]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-08-06 20:04:44

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes