### Start and Run All

In [2]:
import os
import pandas as pd
from urllib import request
from bs4 import BeautifulSoup
# from datetime import date, timedelta
from datetime import datetime
from time import sleep, strftime

# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-19 20:23:51

In [3]:
url = "https://www.set.or.th/en/market/product/stock/quote/"
percent_span = ''

In [4]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [5]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [6]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file : {input_file}")

Input file : C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [7]:
file_name = "price-hilo.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [8]:
print(f"Output file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\price-hilo.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\price-hilo.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\price-hilo.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\price-hilo.csv

In [9]:
def cvt_str_to_flt(input_str):
    # Check for the special pattern and return 0
    if input_str == '(-)':
        return 0
    
    # Remove parentheses and percent sign
    cleaned_str = input_str.replace('(', '').replace(')', '').replace('%', '')

    # Convert to float
    try:
        return float(cleaned_str)
    except ValueError:
        # Handle the case where the conversion fails
        return None

In [10]:
def get_stock_data(in_df):

    in_df.columns = ['name']
    
    output_columns = ['name', 'price', 'today_low', 'today_high', 'year_low', 'year_high', 'percent', 'updated_at']
    # Initialize an empty DataFrame with specified columns
    out_df = pd.DataFrame(columns=output_columns)
    
    for index, row in in_df.iterrows():
        name = str(row['name']).upper()
        response = request.urlopen(url + name + '/price')
        html_page = BeautifulSoup(response, 'html.parser')
        
  #      price = html_page.find('div', class_='value text-white mb-0 me-2 lh-1 stock-info').text.strip()        
  #      if (price == '-'):
  #          price = '0.00'        

        price_div = html_page.find('div', class_='value text-white mb-0 me-2 lh-1 stock-info')
        if price_div:
            price = price_div.text.strip()
        else:
            print(f"Price div not found for {name}")
            price = '0.00'     
            
        # Try to find the <h3> tag with the class 'theme-success'
        h3_tag = html_page.find('h3', class_='theme-success')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)
                
        # Try to find the <h3> tag with the class 'theme-danger'
        h3_tag = html_page.find('h3', class_='theme-danger')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)    
                
        # Try to find the <h3> tag with the class 'theme-danger'
        h3_tag = html_page.find('h3', class_='theme-normal')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)   
                
        percent = cvt_str_to_flt(percent_span)
                
        values_low = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder me-auto lh-1')
        today_low = values_low[0].text
        if (today_low == '-'):
            today_low = '0.00'
        
        values_high = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder lh-1')
        today_high = values_high[0].text
        if (today_high == '-'):
            today_high = '0.00'         
        
        year_low = values_low[1].text        
        year_high = values_high[1].text     
        
        # Find the div with the specific class, then find the span within it
        div = html_page.find('div', class_='price-detail-date d-flex align-items-center text-nowrap fs-12px')
        if div:
            span = div.find('span')
            if span:
                text = span.get_text()
#                 print(text)
            else:
                print("Span not found")
        else:
            print("Div not found")
            
        # Extract the date part from the string
        # Assuming the date is always in the format 'dd Mon yyyy'
        date_str = ' '.join(text.split()[2:5])

        # Parse the date string into a datetime object
        date_obj = datetime.strptime(date_str, '%d %b %Y')

        # Format the datetime object to 'yyyy-mm-dd'
        updated_at = date_obj.strftime('%Y-%m-%d')

#         print(updated_at)
        
        # Append row to the DataFrame and print the row
        out_df.loc[len(out_df)] = [name, price, today_low, today_high, year_low, year_high, percent, updated_at]
#       print(out_df.iloc[-1].to_string(header=False, index=False)) 
        print(','.join(map(str, out_df.iloc[-1])))
        sleep(4)
        
    return out_df  # return the final dataframe with all values populated

In [11]:
start_time = strftime("%I:%M %p")
print('Start at: ', start_time)

Start at:  08:23 PM

In [12]:
df = pd.read_csv(input_file, header=None)
out_df = get_stock_data(df)

ACE,1.28,1.28,1.29,1.24,1.38,-0.78,2026-03-19
ADVANC,376.00,375.00,382.00,261.00,410.00,-0.79,2026-03-19
AEONTS,88.25,88.25,90.25,86.50,122.50,-2.49,2026-03-19
AH,13.00,13.00,13.30,10.00,15.80,-2.26,2026-03-19
AIE,1.31,1.24,1.37,0.90,1.61,6.5,2026-03-19
AIMIRT,10.90,10.80,10.90,9.20,11.40,0.0,2026-03-19
AIT,4.82,4.82,4.88,4.08,5.30,-1.23,2026-03-19
AMATA,18.70,18.70,19.40,11.20,22.50,-5.08,2026-03-19
ANAN,0.37,0.36,0.37,0.35,0.79,-2.63,2026-03-19
AOT,48.00,48.00,49.25,26.75,59.00,-3.03,2026-03-19
AP,8.35,8.35,8.55,5.60,9.70,-2.91,2026-03-19
ASIAN,6.95,6.95,7.35,6.50,8.35,-2.8,2026-03-19
ASK,8.30,8.25,8.45,6.20,10.30,-2.92,2026-03-19
ASP,2.04,2.04,2.06,1.81,2.80,-0.97,2026-03-19
ASW,7.30,7.30,7.65,4.90,8.20,-4.58,2026-03-19
AWC,1.99,1.98,2.04,1.55,2.88,-3.4,2026-03-19
BA,13.10,13.10,13.70,10.60,19.80,-4.38,2026-03-19
BAM,6.85,6.85,7.05,5.70,8.60,-2.84,2026-03-19
BANPU,6.05,5.80,6.05,4.00,6.35,5.22,2026-03-19
BBL,164.00,164.00,166.00,131.00,181.00,-1.2,2026-03-19
BCH,9.70,9.70,10.10,9.20,16.00,-3.96,2026-03-19
BCP,40.00,39.00,40.25,24.20,41.00,2.56,2026-03-19
BCPG,6.15,6.15,6.40,5.25,9.60,-3.15,2026-03-19
BDMS,18.40,18.40,18.80,17.40,24.90,-1.6,2026-03-19
BEAUTY,0.34,0.33,0.36,0.19,0.68,-2.86,2026-03-19
BEC,1.97,1.97,2.02,1.79,4.04,-3.43,2026-03-19
BEM,5.15,5.15,5.25,4.56,6.30,-2.83,2026-03-19
BGC,4.48,4.32,4.50,3.30,5.80,-0.44,2026-03-19
BGRIM,10.60,10.60,11.30,8.90,16.60,-7.83,2026-03-19
BH,160.50,160.50,166.00,130.00,214.00,-3.6,2026-03-19
BJC,13.90,13.70,14.10,12.80,24.60,-2.11,2026-03-19
BKIH,311.00,308.00,311.00,271.00,315.00,0.65,2026-03-19
BLA,19.10,19.00,19.60,14.00,24.00,-2.55,2026-03-19
BLAND,0.42,0.41,0.42,0.38,0.54,0.0,2026-03-19
BPP,12.30,12.10,12.40,6.20,13.00,0.82,2026-03-19
BTS,2.00,2.00,2.04,1.98,5.90,-2.91,2026-03-19
BTSGIF,2.56,2.54,2.58,2.46,2.86,0.0,2026-03-19
CBG,35.25,35.00,36.50,32.75,64.50,-4.08,2026-03-19
CENTEL,31.50,31.25,32.75,19.40,40.50,-4.55,2026-03-19
CHG,1.43,1.43,1.47,1.39,1.94,-2.72,2026-03-19
CK,15.10,15.10,15.70,10.20,18.40,-5.03,2026-03-19
CKP,2.20,2.20,2.24,2.10,3.04,-1.79,2026-03-19
COM7,21.90,21.80,23.20,16.70,28.00,-6.41,2026-03-19
CPALL,44.25,44.25,45.75,40.50,54.50,-3.8,2026-03-19
CPAXT,14.90,14.90,15.20,13.90,28.00,-1.97,2026-03-19
CPF,19.50,19.50,20.10,18.10,26.50,-2.99,2026-03-19
CPN,63.00,62.50,64.00,41.00,70.50,-2.33,2026-03-19
CPNCG,6.15,6.15,6.15,5.75,6.50,0.0,2026-03-19
CPNREIT,11.50,11.50,11.70,10.20,12.50,-1.71,2026-03-19
CRC,17.90,17.90,18.80,15.80,28.50,-5.79,2026-03-19
DCC,1.21,1.20,1.22,1.13,1.65,-0.82,2026-03-19
DCON,0.21,0.20,0.21,0.21,0.30,0.0,2026-03-19
DELTA,268.00,267.00,278.00,51.25,292.00,-2.9,2026-03-19
DIF,9.50,9.40,9.50,7.35,9.60,0.53,2026-03-19
DOHOME,3.10,3.08,3.22,2.17,6.49,-3.73,2026-03-19
EA,2.52,2.52,2.66,1.73,3.88,-3.08,2026-03-19
EGATIF,6.15,6.10,6.15,5.75,6.30,0.0,2026-03-19
EGCO,107.50,107.50,109.00,85.00,143.00,-1.83,2026-03-19
EPG,3.08,3.06,3.16,2.12,4.10,-1.91,2026-03-19
FORTH,6.50,6.40,6.80,5.45,10.30,-4.41,2026-03-19
FPT,6.10,6.10,6.10,5.50,8.75,-1.61,2026-03-19
FSMART,6.15,6.15,6.45,5.35,9.85,-3.91,2026-03-19
GC,4.42,4.40,4.44,3.40,5.00,0.0,2026-03-19
GFPT,9.10,9.10,9.60,8.00,11.00,-5.21,2026-03-19
GLOBAL,5.90,5.90,6.40,4.01,8.44,-8.53,2026-03-19
GPSC,31.50,31.25,33.25,22.40,45.00,-5.97,2026-03-19
GULF,55.25,55.25,57.00,37.75,64.25,-2.64,2026-03-19
GUNKUL,2.08,2.06,2.14,1.31,2.58,-2.8,2026-03-19
GVREIT,6.40,6.35,6.40,6.15,6.95,0.0,2026-03-19
HANA,24.10,23.70,25.75,14.00,26.75,-6.41,2026-03-19
HFT,4.20,4.20,4.28,3.32,4.48,-3.23,2026-03-19
HMPRO,6.05,6.00,6.20,5.70,9.20,-3.2,2026-03-19
HTC,15.60,15.50,15.80,14.50,17.10,-1.89,2026-03-19
ICHI,12.70,12.60,13.40,9.40,15.20,-5.22,2026-03-19
III,3.96,3.92,4.00,3.72,5.25,-1.0,2026-03-19
ILM,13.30,13.10,13.40,11.50,16.20,-1.48,2026-03-19
IMH,3.00,2.98,3.04,2.84,4.48,-1.32,2026-03-19
IMPACT,10.80,10.80,11.00,9.25,11.50,-0.92,2026-03-19
IP,4.16,4.12,4.30,2.96,4.70,-2.35,2026-03-19
IRPC,1.48,1.44,1.52,0.70,1.51,1.37,2026-03-19
IVL,23.60,23.10,24.00,14.60,24.50,1.29,2026-03-19
3BBIF,6.55,6.50,6.60,5.25,6.85,-0.76,2026-03-19
JMART,6.55,6.55,6.85,5.20,10.90,-4.38,2026-03-19
JMT,8.10,8.10,8.45,7.35,14.90,-3.57,2026-03-19
KBANK,187.00,187.00,189.00,145.00,208.00,-1.32,2026-03-19
KCE,22.70,22.70,24.20,13.70,28.25,-6.2,2026-03-19
KGI,4.30,4.26,4.30,3.40,4.54,0.0,2026-03-19
KKP,71.25,71.25,72.50,43.50,78.00,-2.06,2026-03-19
KTB,34.25,34.00,34.75,19.70,35.50,0.0,2026-03-19
KTC,29.00,28.75,29.75,21.80,47.75,-3.33,2026-03-19
LALIN,4.58,4.58,4.64,4.62,5.40,-1.29,2026-03-19
LANNA,15.10,14.90,15.20,14.10,16.90,-2.58,2026-03-19
LH,3.64,3.62,3.68,3.18,4.74,-1.62,2026-03-19
LIT,0.62,0.60,0.62,0.39,1.01,3.33,2026-03-19
LPN,1.57,1.56,1.59,1.46,2.20,-1.26,2026-03-19
M,18.80,18.80,19.40,13.80,35.25,-2.59,2026-03-19
MAJOR,7.60,7.40,7.60,6.25,11.30,0.0,2026-03-19
MBAX,2.04,2.04,2.60,1.17,2.22,-8.11,2026-03-19
MC,10.90,10.80,11.00,9.15,12.50,-0.91,2026-03-19
MCS,9.45,9.35,9.60,7.10,9.75,-1.05,2026-03-19
MEGA,32.75,32.50,33.50,24.30,40.00,-2.96,2026-03-19
MINT,20.90,20.90,21.80,19.60,28.25,-5.0,2026-03-19
MST,6.80,6.80,6.80,5.50,8.10,-1.45,2026-03-19
MTC,28.25,28.25,29.25,27.00,46.50,-5.04,2026-03-19
NER,4.66,4.66,4.82,3.88,5.40,-3.72,2026-03-19
NOBLE,2.04,2.04,2.08,1.60,2.72,-0.97,2026-03-19
ONEE,2.58,2.58,2.72,1.94,3.06,-4.44,2026-03-19
OR,11.10,11.10,11.50,10.10,15.60,-1.77,2026-03-19
ORI,1.80,1.77,1.84,1.50,3.12,-1.64,2026-03-19
OSP,14.00,13.90,14.40,12.90,19.50,-3.45,2026-03-19
PCSGH,3.08,3.00,3.12,2.46,3.64,0.0,2026-03-19
PDG,2.96,2.94,2.96,2.46,3.20,-6.92,2026-03-19
PLANB,3.76,3.74,3.90,3.00,5.90,-3.09,2026-03-19
POPF,6.80,6.80,6.90,5.40,7.00,-1.45,2026-03-19
PREB,3.88,3.84,3.90,3.30,4.10,0.0,2026-03-19
PRM,7.60,7.60,7.80,5.10,8.25,-1.94,2026-03-19
PSH,3.52,3.50,3.62,3.48,5.55,-1.68,2026-03-19
PSL,6.75,6.70,7.15,4.96,8.45,-5.59,2026-03-19
PTG,7.90,7.90,8.10,5.45,10.20,-1.86,2026-03-19
PTL,9.95,9.65,10.20,7.50,14.50,1.02,2026-03-19
PTT,34.25,33.50,34.25,29.25,38.00,2.24,2026-03-19
PTTEP,155.00,149.00,155.00,93.00,149.50,5.44,2026-03-19
PTTGC,32.25,30.50,32.75,14.20,32.00,4.88,2026-03-19
QH,1.35,1.35,1.37,1.15,1.63,-1.46,2026-03-19
RATCH,28.25,28.00,28.75,22.50,32.50,-1.74,2026-03-19
RBF,3.52,3.46,3.62,2.90,5.30,-1.68,2026-03-19
RCL,31.00,31.00,34.50,18.20,34.50,-10.14,2026-03-19
RJH,12.30,12.20,12.60,11.10,15.70,-3.15,2026-03-19
ROJNA,4.96,4.94,5.05,4.14,5.95,-1.78,2026-03-19
SAPPE,29.50,29.50,30.25,27.50,41.75,-1.67,2026-03-19
SAT,14.10,14.10,14.40,9.95,16.70,-2.08,2026-03-19
SAWAD,22.50,22.50,23.40,14.80,32.00,-4.66,2026-03-19
SC,1.94,1.93,1.98,1.40,2.62,-2.51,2026-03-19
SCB,144.00,144.00,145.00,111.00,149.50,-0.69,2026-03-19
SCC,181.50,178.50,184.50,128.00,231.00,-1.89,2026-03-19
SCCC,139.00,138.50,139.00,138.00,160.50,0.0,2026-03-19
SCGP,17.60,17.60,18.50,10.70,21.70,-4.86,2026-03-19
SENA,1.88,1.86,1.89,1.54,2.18,-0.53,2026-03-19
SGP,7.80,7.45,7.90,5.00,8.05,3.31,2026-03-19
SINGER,4.96,4.96,5.20,3.92,8.15,-5.52,2026-03-19
SIRI,1.39,1.39,1.44,1.11,1.66,-3.47,2026-03-19
SIS,19.70,19.60,20.70,17.60,24.60,-4.83,2026-03-19
SJWD,7.15,7.10,7.45,5.75,10.80,-4.03,2026-03-19
SMPC,9.20,9.15,9.20,7.80,9.45,0.55,2026-03-19
SNC,5.70,5.70,5.75,5.10,7.35,0.0,2026-03-19
SPALI,16.80,16.70,17.00,13.20,19.00,-1.18,2026-03-19
SPCG,9.05,8.95,9.10,6.60,10.30,0.0,2026-03-19
SPRC,7.30,7.20,7.50,4.26,8.20,2.1,2026-03-19
SPRIME,3.44,3.42,3.44,3.00,4.14,0.0,2026-03-19
SSP,3.40,3.38,3.44,3.00,5.35,0.0,2026-03-19
STA,16.00,15.90,16.50,10.30,16.60,-3.61,2026-03-19
STGT,9.90,9.75,10.90,5.10,10.70,-6.6,2026-03-19
SUPER,0.11,0.10,0.11,0.09,0.22,0.0,2026-03-19
SUPEREIF,5.65,5.65,5.80,4.72,6.35,-1.74,2026-03-19
SVI,7.40,7.35,7.40,5.55,8.35,0.68,2026-03-19
SYNEX,9.30,9.30,9.70,8.90,12.80,-4.12,2026-03-19
TASCO,13.10,12.90,13.30,12.40,15.90,0.0,2026-03-19
TCAP,55.25,55.25,56.25,44.25,63.00,-1.34,2026-03-19
TFFIF,6.55,6.55,6.65,5.25,6.95,-1.5,2026-03-19
TFG,7.15,7.15,7.60,4.10,7.65,-5.3,2026-03-19
THANI,1.64,1.62,1.66,1.39,2.06,-1.2,2026-03-19
THG,8.20,8.20,8.40,6.15,10.32,-2.96,2026-03-19
TIPH,20.00,20.00,20.50,16.70,23.30,-2.44,2026-03-19
TISCO,113.50,113.00,114.50,95.00,116.50,0.44,2026-03-19
TKN,3.92,3.90,4.02,3.86,8.50,-2.0,2026-03-19
TKS,6.25,6.20,6.35,4.90,7.10,0.0,2026-03-19
TMT,3.26,2.96,3.26,2.68,3.54,8.67,2026-03-19
TOA,12.30,12.20,12.90,9.35,16.40,-2.38,2026-03-19
TOP,46.00,46.00,47.75,21.00,56.75,-2.13,2026-03-19
TPIPL,0.69,0.69,0.71,0.65,1.06,-2.82,2026-03-19
TPIPP,1.80,1.80,1.83,1.66,2.44,-1.64,2026-03-19
TQM,12.80,12.70,13.00,10.60,16.60,-1.54,2026-03-19
TRUE,13.80,13.60,14.20,10.10,14.90,-0.72,2026-03-19
TSE,0.52,0.50,0.57,0.29,0.68,0.0,2026-03-19
TSTH,0.73,0.72,0.74,0.47,0.93,-1.35,2026-03-19
TTA,4.70,4.68,4.84,3.22,5.55,-6.0,2026-03-19
TTB,2.24,2.22,2.26,1.74,2.38,-0.88,2026-03-19
TTLPF,9.70,9.65,9.75,8.80,12.30,-0.51,2026-03-19
TTW,9.05,9.05,9.15,8.45,9.50,-0.55,2026-03-19
TU,10.80,10.80,11.00,8.60,14.10,-2.7,2026-03-19
TVO,24.20,24.20,24.70,19.70,26.00,-1.22,2026-03-19
TYCN,1.71,1.67,1.71,1.54,1.88,0.0,2026-03-19
UTP,7.40,7.40,7.50,7.20,8.00,-0.67,2026-03-19
VGI,0.84,0.84,0.88,0.77,3.26,-4.55,2026-03-19
VIBHA,1.38,1.38,1.41,1.32,1.66,-1.43,2026-03-19
VNG,1.95,1.93,1.97,1.64,2.54,0.52,2026-03-19
WHA,4.06,4.06,4.18,2.26,4.60,-3.79,2026-03-19
WHAIR,6.90,6.85,6.95,4.12,7.00,-0.72,2026-03-19
WHART,10.20,10.10,10.30,8.55,11.20,-0.97,2026-03-19
WHAUP,4.24,4.24,4.40,2.76,5.25,-3.64,2026-03-19
WICE,2.42,2.36,2.60,2.20,3.94,-3.2,2026-03-19
WORK,3.44,3.44,3.52,3.48,5.60,-2.82,2026-03-19

In [13]:
end_time = strftime("%I:%M %p")
print('End at: ', end_time)

End at:  08:38 PM

In [14]:
out_df.query('price == "-"')

Empty DataFrame
Columns: [name, price, today_low, today_high, year_low, year_high, percent, updated_at]
Index: []

In [15]:
out_df.shape

(192, 8)

In [16]:
out_df = out_df[out_df['name'] != 'TYCN']

In [17]:
out_df = out_df[out_df['name'] != 'MST']

In [18]:
out_df = out_df[out_df['name'] != 'SPRIME']

In [19]:
out_df = out_df[out_df['name'] != 'FPT']

In [20]:
out_df = out_df[out_df['name'] != 'PDG']

In [21]:
out_df = out_df[out_df['name'] != 'PREB']

In [22]:
out_df = out_df[out_df['name'] != 'MBAX']

In [24]:
out_df.shape

(185, 8)

In [25]:
out_df['price'] = out_df['price'].astype('float')
out_df['today_low'] = out_df['today_low'].astype('float')
out_df['today_high'] = out_df['today_high'].astype('float')
out_df['year_low'] = out_df['year_low'].astype('float')
out_df['year_high'] = out_df['year_high'].astype('float')
out_df['percent'] = out_df['percent'].astype('float')

In [26]:
sorted_out_df = out_df.sort_values('percent')

In [27]:
sorted_out_df.query('today_low < year_low')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
191,WORK,3.44,3.44,3.52,3.48,5.6,-2.82,2026-03-19
90,LALIN,4.58,4.58,4.64,4.62,5.4,-1.29,2026-03-19
51,DCON,0.21,0.20,0.21,0.21,0.3,0.00,2026-03-19

In [28]:
sorted_out_df.query('today_high > year_high')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
151,STGT,9.90,9.75,10.90,5.1,10.70,-6.60,2026-03-19
79,IRPC,1.48,1.44,1.52,0.7,1.51,1.37,2026-03-19
122,PTTGC,32.25,30.50,32.75,14.2,32.00,4.88,2026-03-19
121,PTTEP,155.00,149.00,155.00,93.0,149.50,5.44,2026-03-19

In [29]:
out_df.query('today_high > year_high')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
79,IRPC,1.48,1.44,1.52,0.7,1.51,1.37,2026-03-19
121,PTTEP,155.00,149.00,155.00,93.0,149.50,5.44,2026-03-19
122,PTTGC,32.25,30.50,32.75,14.2,32.00,4.88,2026-03-19
151,STGT,9.90,9.75,10.90,5.1,10.70,-6.60,2026-03-19

In [30]:
file_name = "Price-Hilo.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [31]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Hilo.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Hilo.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Hilo.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Hilo.csv

In [32]:
out_df.to_csv(output_file, index=False)  
out_df.to_csv(god_file, index=False) 
out_df.to_csv(icd_file, index=False)  
out_df.to_csv(osd_file, index=False)

In [33]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-19 20:38:09