In [1]:
import os
import pandas as pd
from urllib import request
from bs4 import BeautifulSoup
# from datetime import date, timedelta
from datetime import datetime
from time import sleep, strftime

# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-10-28 19:25:07

In [2]:
url = "https://www.set.or.th/en/market/product/stock/quote/"
percent_span = ''

In [3]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [4]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path : {dat_path}") 
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Data path : C:\Users\PC1\OneDrive\A4\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [5]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file : {input_file}")

Input file : C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [6]:
file_name = "price-hilo.csv"
output_file = os.path.join(dat_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [7]:
print(f"Output file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"osd_file : {osd_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\price-hilo.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\price-hilo.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\price-hilo.csv

In [8]:
def cvt_str_to_flt(input_str):
    # Check for the special pattern and return 0
    if input_str == '(-)':
        return 0
    
    # Remove parentheses and percent sign
    cleaned_str = input_str.replace('(', '').replace(')', '').replace('%', '')

    # Convert to float
    try:
        return float(cleaned_str)
    except ValueError:
        # Handle the case where the conversion fails
        return None

In [9]:
def get_stock_data(in_df):

    in_df.columns = ['name']
    
    output_columns = ['name', 'price', 'today_low', 'today_high', 'year_low', 'year_high', 'percent', 'updated_at']
    # Initialize an empty DataFrame with specified columns
    out_df = pd.DataFrame(columns=output_columns)
    
    for index, row in in_df.iterrows():
        name = str(row['name']).upper()
        response = request.urlopen(url + name + '/price')
        html_page = BeautifulSoup(response, 'html.parser')
        
  #      price = html_page.find('div', class_='value text-white mb-0 me-2 lh-1 stock-info').text.strip()        
  #      if (price == '-'):
  #          price = '0.00'        

        price_div = html_page.find('div', class_='value text-white mb-0 me-2 lh-1 stock-info')
        if price_div:
            price = price_div.text.strip()
        else:
            print(f"Price div not found for {name}")
            price = '0.00'     
            
        # Try to find the <h3> tag with the class 'theme-success'
        h3_tag = html_page.find('h3', class_='theme-success')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)
                
        # Try to find the <h3> tag with the class 'theme-danger'
        h3_tag = html_page.find('h3', class_='theme-danger')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)    
                
        # Try to find the <h3> tag with the class 'theme-danger'
        h3_tag = html_page.find('h3', class_='theme-normal')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)   
                
        percent = cvt_str_to_flt(percent_span)
                
        values_low = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder me-auto lh-1')
        today_low = values_low[0].text
        if (today_low == '-'):
            today_low = '0.00'
        
        values_high = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder lh-1')
        today_high = values_high[0].text
        if (today_high == '-'):
            today_high = '0.00'         
        
        year_low = values_low[1].text        
        year_high = values_high[1].text     
        
        # Find the div with the specific class, then find the span within it
        div = html_page.find('div', class_='price-detail-date d-flex align-items-center text-nowrap fs-12px')
        if div:
            span = div.find('span')
            if span:
                text = span.get_text()
#                 print(text)
            else:
                print("Span not found")
        else:
            print("Div not found")
            
        # Extract the date part from the string
        # Assuming the date is always in the format 'dd Mon yyyy'
        date_str = ' '.join(text.split()[2:5])

        # Parse the date string into a datetime object
        date_obj = datetime.strptime(date_str, '%d %b %Y')

        # Format the datetime object to 'yyyy-mm-dd'
        updated_at = date_obj.strftime('%Y-%m-%d')

#         print(updated_at)
        
        # Append row to the DataFrame and print the row
        out_df.loc[len(out_df)] = [name, price, today_low, today_high, year_low, year_high, percent, updated_at]
#       print(out_df.iloc[-1].to_string(header=False, index=False)) 
        print(','.join(map(str, out_df.iloc[-1])))
        sleep(4)
        
    return out_df  # return the final dataframe with all values populated

In [10]:
start_time = strftime("%I:%M %p")
print('Start at: ', start_time)

Start at:  07:25 PM

In [11]:
df = pd.read_csv(input_file, header=None)
out_df = get_stock_data(df)

ACE,1.29,1.28,1.29,1.26,1.52,0.0,2026-10-28
ADVANC,336.00,335.00,339.00,298.00,410.00,0.3,2026-10-28
AEONTS,89.00,89.00,89.75,86.50,112.00,-0.28,2026-10-28
AH,15.00,14.90,15.10,11.70,16.80,0.0,2026-10-28
AIE,1.45,1.43,1.48,0.90,1.87,-2.68,2026-10-28
AIMIRT,11.70,11.60,11.80,10.10,12.70,0.86,2026-10-28
AIT,4.74,4.72,4.78,4.64,5.30,-0.42,2026-10-28
AMATA,27.00,26.50,28.50,14.00,34.50,-6.09,2026-10-28
ANAN,0.34,0.34,0.37,0.29,0.48,-2.86,2026-10-28
AOT,60.00,60.00,61.50,39.25,67.25,-2.04,2026-10-28
AP,7.90,7.85,8.05,6.85,9.70,-1.25,2026-10-28
ASIAN,7.15,7.15,7.20,6.75,8.25,0.0,2026-10-28
ASK,9.70,9.60,9.75,7.00,12.70,-0.51,2026-10-28
ASP,2.30,2.30,2.32,1.97,2.60,-0.86,2026-10-28
ASW,7.55,7.50,7.55,5.90,8.20,-0.66,2026-10-28
AWC,3.16,3.12,3.22,1.90,3.34,-0.63,2026-10-28
BA,18.10,18.10,19.00,12.00,20.00,-4.23,2026-10-28
BAM,6.35,6.35,6.40,6.15,8.30,-0.78,2026-10-28
BBL,187.50,184.50,188.00,154.50,204.00,1.35,2026-10-28
BCH,10.90,10.70,10.90,9.10,12.10,0.93,2026-10-28
BCP,49.50,49.50,51.50,24.20,60.75,-3.88,2026-10-28
BCPG,6.75,6.65,6.80,5.30,8.70,-0.74,2026-10-28
BDMS,19.90,19.70,20.00,17.40,22.40,0.0,2026-10-28
BEAUTY,0.28,0.28,0.29,0.27,0.59,0.0,2026-10-28
BEC,1.80,1.78,1.80,1.72,2.26,0.0,2026-10-28
BEM,6.35,6.30,6.40,4.84,7.35,0.0,2026-10-28
BGC,5.90,5.80,5.95,3.30,7.15,0.0,2026-10-28
BGRIM,19.30,19.20,19.90,10.30,21.40,-0.52,2026-10-28
BH,201.00,200.00,202.00,136.00,214.00,0.0,2026-10-28
BJC,20.10,19.70,20.20,12.80,20.10,1.01,2026-10-28
BKIH,399.00,399.00,400.00,297.00,400.00,0.0,2026-10-28
BLA,22.70,22.70,23.00,17.30,27.50,0.0,2026-10-28
BLAND,0.51,0.50,0.51,0.40,0.78,2.0,2026-10-28
BTS,1.91,1.90,1.94,1.82,3.08,-1.04,2026-10-28
BTSGIF,2.14,2.10,2.14,2.08,2.72,0.0,2026-10-28
CBG,52.00,51.50,52.25,32.75,59.25,0.0,2026-10-28
CENTEL,44.75,44.50,47.50,29.25,47.50,-5.79,2026-10-28
CHG,1.53,1.52,1.57,1.33,1.78,-2.55,2026-10-28
CK,17.10,17.00,17.40,11.10,20.70,-0.58,2026-10-28
CKP,2.32,2.32,2.36,2.12,2.76,-0.85,2026-10-28
COM7,32.75,32.50,33.25,18.20,34.00,-1.5,2026-10-28
CPALL,44.25,44.00,44.25,40.50,54.50,0.57,2026-10-28
CPAXT,14.20,14.10,14.20,13.90,20.50,0.0,2026-10-28
CPF,19.90,19.80,20.10,18.10,24.00,-0.5,2026-10-28
CPN,65.00,65.00,65.75,49.00,70.50,0.0,2026-10-28
CPNCG,5.15,5.05,5.15,4.90,6.50,0.0,2026-10-28
CPNREIT,13.10,13.00,13.20,10.60,13.80,0.0,2026-10-28
CRC,32.75,32.50,33.75,16.50,33.75,-1.5,2026-10-28
DCC,1.31,1.30,1.32,1.13,1.51,-0.76,2026-10-28
DCON,0.16,0.15,0.16,0.13,0.25,6.67,2026-10-28
DELTA,232.00,228.00,237.00,155.50,372.00,-1.28,2026-10-28
DIF,9.55,9.50,9.60,8.95,10.40,0.53,2026-10-28
DOHOME,3.48,3.48,3.56,3.02,4.29,-1.14,2026-10-28
EA,2.46,2.46,2.50,2.40,3.64,0.0,2026-10-28
EGATIF,6.05,6.05,6.10,5.95,6.40,0.0,2026-10-28
EGCO,131.50,131.00,133.00,107.00,137.00,-1.13,2026-10-28
EPG,6.65,6.65,6.75,2.76,6.85,-0.75,2026-10-28
FORTH,14.00,13.90,14.30,5.45,18.90,-1.41,2026-10-28
FSMART,6.45,6.40,6.55,5.50,8.45,-0.77,2026-10-28
GC,5.40,5.35,5.50,3.90,5.90,0.0,2026-10-28
GFPT,9.95,9.90,10.00,8.50,11.50,0.0,2026-10-28
GLOBAL,6.95,6.90,7.10,5.25,8.29,0.0,2026-10-28
GPSC,50.75,50.50,51.50,30.00,55.75,-0.98,2026-10-28
GULF,61.50,61.25,62.00,39.75,68.50,0.0,2026-10-28
GUNKUL,4.92,4.92,4.98,1.76,5.55,0.82,2026-10-28
GVREIT,7.10,7.10,7.20,6.30,8.50,-1.39,2026-10-28
HANA,49.25,48.50,50.00,15.10,54.25,2.07,2026-10-28
HFT,4.06,4.06,4.08,3.48,4.60,0.0,2026-10-28
HMPRO,6.35,6.30,6.50,5.75,7.55,-2.31,2026-10-28
HTC,15.30,15.20,15.40,14.60,16.90,0.0,2026-10-28
ICHI,14.20,14.10,14.40,11.80,15.20,-0.7,2026-10-28
III,4.46,4.42,4.54,3.72,5.50,-1.33,2026-10-28
ILM,13.60,13.30,14.00,12.10,14.90,0.74,2026-10-28
IMH,3.22,3.20,3.30,2.70,4.28,0.0,2026-10-28
IMPACT,13.00,12.70,13.00,9.85,14.20,0.0,2026-10-28
IP,4.90,4.86,4.90,3.68,5.65,-0.41,2026-10-28
IRPC,2.80,2.80,2.92,0.96,3.22,-4.11,2026-10-28
IVL,26.50,26.25,27.50,14.60,30.50,-3.64,2026-10-28
3BBIF,6.30,6.25,6.35,6.00,6.95,0.0,2026-10-28
JMART,10.30,10.30,10.60,5.80,12.80,-1.9,2026-10-28
JMT,10.40,10.30,10.60,7.65,13.00,0.0,2026-10-28
KBANK,250.00,246.00,252.00,178.00,261.00,2.04,2026-10-28
KCE,73.50,70.25,73.75,16.00,81.50,5.38,2026-10-28
KGI,4.82,4.80,4.84,3.74,5.30,-0.41,2026-10-28
KKP,119.50,119.00,120.00,62.75,121.50,0.0,2026-10-28
KTB,44.50,44.00,44.75,26.00,46.00,0.56,2026-10-28
KTC,35.50,35.00,35.50,24.40,41.25,1.43,2026-10-28
LALIN,4.18,4.16,4.20,4.14,5.15,0.0,2026-10-28
LANNA,14.70,14.70,14.80,14.00,16.50,0.0,2026-10-28
LH,3.56,3.54,3.64,3.40,4.50,-1.11,2026-10-28
LIT,0.70,0.70,0.72,0.58,1.00,0.0,2026-10-28
LPN,1.57,1.55,1.57,1.46,1.68,0.0,2026-10-28
M,20.60,20.30,20.80,17.00,33.25,-0.48,2026-10-28
MAJOR,7.50,7.45,7.60,6.25,8.30,1.35,2026-10-28
MBAX,2.02,2.00,2.02,1.31,2.60,0.0,2026-10-28
MC,11.20,11.10,11.30,10.50,12.50,0.0,2026-10-28
MCS,7.75,7.70,7.80,7.20,9.75,-0.64,2026-10-28
MEGA,34.00,33.75,34.25,28.50,40.00,0.0,2026-10-28
MINT,20.50,20.30,20.90,19.60,27.00,-1.44,2026-10-28
MST,7.50,7.50,7.75,6.50,8.55,-1.96,2026-10-28
MTC,28.75,28.75,29.25,26.75,41.50,0.0,2026-10-28
NER,4.70,4.68,4.76,4.10,5.40,-0.42,2026-10-28
NOBLE,1.42,1.41,1.44,1.40,2.72,-1.39,2026-10-28
ONEE,2.88,2.88,2.94,1.94,3.40,-1.37,2026-10-28
OR,12.80,12.70,12.90,10.40,15.60,0.0,2026-10-28
ORI,1.75,1.75,1.78,1.63,2.32,-1.69,2026-10-28
OSP,18.20,18.00,18.40,13.70,18.90,-0.55,2026-10-28
PCSGH,2.86,2.86,2.92,2.86,3.28,-2.05,2026-10-28
PDG,3.28,3.28,3.28,2.72,3.50,0.0,2026-10-28
PLANB,8.50,8.35,8.70,3.00,9.20,-1.73,2026-10-28
POPF,8.45,8.45,8.55,6.35,9.00,-0.59,2026-10-28
PREB,3.42,3.40,3.42,3.30,4.10,0.59,2026-10-28
PRM,8.65,8.65,8.80,6.10,10.50,-1.14,2026-10-28
PROSPECT,9.05,9.00,9.10,6.60,10.80,-0.55,2026-10-28
PSH,3.74,3.74,3.80,3.30,4.14,-2.09,2026-10-28
PSL,9.65,9.65,10.00,5.70,11.40,-4.46,2026-10-28
PTG,7.75,7.75,7.95,6.75,10.20,-3.13,2026-10-28
PTL,13.70,13.70,13.90,7.50,15.10,-1.44,2026-10-28
PTT,42.00,41.75,42.25,30.00,43.75,0.0,2026-10-28
PTTEP,162.50,161.00,166.00,104.00,167.00,-2.4,2026-10-28
PTTGC,51.00,50.50,54.25,19.00,54.75,-5.99,2026-10-28
QH,1.37,1.36,1.39,1.21,1.53,0.0,2026-10-28
RATCH,38.25,38.25,39.00,26.50,39.75,-1.29,2026-10-28
RBF,4.86,4.80,4.92,2.90,5.55,-0.82,2026-10-28
RCL,49.25,48.50,49.50,24.70,52.25,0.0,2026-10-28
RJH,16.60,16.40,16.70,11.10,17.40,-0.6,2026-10-28
ROJNA,5.75,5.70,5.80,4.28,6.45,0.88,2026-10-28
SAPPE,30.00,29.75,30.75,28.50,38.25,0.0,2026-10-28
SAT,15.90,15.90,16.00,13.00,16.80,-0.63,2026-10-28
SAWAD,22.40,22.30,22.70,19.90,30.75,0.45,2026-10-28
SC,1.88,1.86,1.92,1.54,2.22,-2.59,2026-10-28
SCB,154.50,153.50,155.50,127.00,160.00,0.65,2026-10-28
SCC,278.00,274.00,278.00,163.00,278.00,0.0,2026-10-28
SCCC,151.50,151.00,152.50,138.00,156.50,-0.66,2026-10-28
SCGP,28.25,28.25,29.50,14.90,32.25,-3.42,2026-10-28
SENA,1.56,1.55,1.58,1.55,2.10,0.0,2026-10-28
SGP,8.75,8.70,8.85,6.30,9.65,-0.57,2026-10-28
SINGER,13.60,13.50,14.20,4.10,14.90,-2.86,2026-10-28
SIRI,1.42,1.42,1.43,1.29,1.60,-0.7,2026-10-28
SIS,24.30,24.20,24.70,18.30,27.50,-1.22,2026-10-28
SJWD,9.95,9.85,10.00,6.40,10.60,-0.5,2026-10-28
SMPC,9.60,9.50,9.70,8.70,10.40,0.0,2026-10-28
SNC,6.75,6.70,6.85,5.50,8.85,0.0,2026-10-28
SPALI,15.80,15.70,15.90,14.80,19.00,-0.63,2026-10-28
SPCG,10.40,10.30,11.60,8.15,13.00,-8.77,2026-10-28
SPRC,14.20,14.00,14.60,4.60,16.50,-4.05,2026-10-28
SSP,7.75,7.65,7.80,3.00,8.50,1.31,2026-10-28
STA,22.90,22.80,23.80,11.20,24.20,-3.38,2026-10-28
STGT,9.50,9.45,10.10,6.50,12.20,-6.86,2026-10-28
SUPER,0.12,0.12,0.13,0.09,0.14,0.0,2026-10-28
SUPEREIF,6.30,6.25,6.30,5.00,7.05,0.0,2026-10-28
SYNEX,9.45,9.40,9.55,8.55,11.30,-1.05,2026-10-28
TASCO,17.20,17.00,17.40,12.40,17.90,-0.58,2026-10-28
TCAP,80.25,80.00,81.00,50.50,91.75,0.0,2026-10-28
TFFIF,7.00,7.00,7.05,6.00,7.20,0.0,2026-10-28
TFG,9.50,9.40,9.65,4.24,11.60,-0.52,2026-10-28
THANI,2.30,2.26,2.32,1.55,2.44,0.0,2026-10-28
THG,6.50,6.40,6.55,6.35,9.90,0.78,2026-10-28
TIPH,24.50,24.50,24.70,19.20,27.00,-0.81,2026-10-28
TISCO,126.00,125.50,126.50,105.50,133.00,0.4,2026-10-28
TKN,4.50,4.48,4.50,3.66,5.00,0.0,2026-10-28
TKS,7.85,7.85,7.95,5.35,8.45,-1.26,2026-10-28
TMT,4.40,4.36,4.40,2.68,4.54,0.0,2026-10-28
TOA,14.90,14.70,14.90,11.50,16.80,0.68,2026-10-28
TOP,65.25,64.25,67.25,33.00,79.00,-3.33,2026-10-28
TPIPL,0.88,0.87,0.89,0.65,1.04,-1.12,2026-10-28
TPIPP,1.59,1.58,1.60,1.57,2.10,0.0,2026-10-28
TQM,14.40,14.40,14.50,10.60,18.10,-0.69,2026-10-28
TRUE,12.80,12.70,13.00,10.20,15.00,0.0,2026-10-28
TSE,1.22,1.21,1.31,0.34,1.41,-4.69,2026-10-28
TSTH,0.87,0.86,0.91,0.62,1.12,-3.33,2026-10-28
TTA,5.05,5.05,5.15,3.94,6.10,-1.94,2026-10-28
TTB,2.76,2.72,2.80,1.82,3.18,0.73,2026-10-28
TTLPF,7.50,7.45,7.55,6.90,10.70,0.0,2026-10-28
TTW,10.00,10.00,10.10,8.90,10.70,-0.99,2026-10-28
TU,12.90,12.80,13.10,10.40,14.10,-1.53,2026-10-28
TVO,28.50,28.00,28.75,21.00,30.25,-0.87,2026-10-28
TYCN,1.68,1.65,1.68,1.50,1.86,1.82,2026-10-28
UTP,8.95,8.95,9.05,7.10,9.65,-0.56,2026-10-28
VGI,0.97,0.96,1.06,0.77,1.42,-3.96,2026-10-28
VIBHA,1.33,1.32,1.33,1.31,1.47,0.0,2026-10-28
VNG,1.91,1.88,1.91,1.64,2.28,1.6,2026-10-28
WHA,4.88,4.88,4.96,3.08,5.60,0.0,2026-10-28
WHAIR,8.00,7.95,8.05,5.95,8.75,0.0,2026-10-28
WHART,10.90,10.80,10.90,9.60,11.60,0.0,2026-10-28
WHAUP,7.05,6.70,7.30,3.86,8.50,6.02,2026-10-28
WICE,3.04,2.98,3.10,2.20,3.90,-2.56,2026-10-28
WORK,3.18,3.16,3.20,3.18,4.22,-0.63,2026-10-28

In [12]:
end_time = strftime("%I:%M %p")
print('End at: ', end_time)

End at:  07:39 PM

In [13]:
out_df.query('price == "-"')

Empty DataFrame
Columns: [name, price, today_low, today_high, year_low, year_high, percent, updated_at]
Index: []

In [14]:
out_df.shape

(188, 8)

In [15]:
out_df = out_df[out_df['name'] != 'TYCN']

In [16]:
out_df = out_df[out_df['name'] != 'MST']

In [17]:
out_df = out_df[out_df['name'] != 'PDG']

In [18]:
out_df = out_df[out_df['name'] != 'PREB']

In [19]:
out_df = out_df[out_df['name'] != 'MBAX']

In [20]:
out_df.shape

(183, 8)

In [21]:
out_df['price'] = out_df['price'].astype('float')
out_df['today_low'] = out_df['today_low'].astype('float')
out_df['today_high'] = out_df['today_high'].astype('float')
out_df['year_low'] = out_df['year_low'].astype('float')
out_df['year_high'] = out_df['year_high'].astype('float')
out_df['percent'] = out_df['percent'].astype('float')

In [22]:
sorted_out_df = out_df.sort_values('percent')

In [23]:
sorted_out_df.query('today_low < year_low')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
187,WORK,3.18,3.16,3.2,3.18,4.22,-0.63,2026-10-28

In [24]:
sorted_out_df.query('today_high > year_high')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
29,BJC,20.1,19.7,20.2,12.8,20.1,1.01,2026-10-28

In [25]:
out_df.query('today_high > year_high')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
29,BJC,20.1,19.7,20.2,12.8,20.1,1.01,2026-10-28

In [26]:
file_name = "Price-Hilo.csv"
output_file = os.path.join(dat_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [27]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Hilo.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Hilo.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Hilo.csv

In [28]:
out_df.to_csv(output_file, index=False)  
out_df.to_csv(icd_file, index=False)  
out_df.to_csv(osd_file, index=False)

In [29]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-10-28 19:39:10