### Start and Run All

In [2]:
import os
import pandas as pd
from urllib import request
from bs4 import BeautifulSoup
# from datetime import date, timedelta
from datetime import datetime
from time import sleep, strftime

# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-05 20:27:12

In [3]:
url = "https://www.set.or.th/en/market/product/stock/quote/"
percent_span = ''

In [4]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [5]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A4\Daily
Base path: C:\Users\PC1\OneDrive\A4
Data path : C:\Users\PC1\OneDrive\A4\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [6]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file : {input_file}")

Input file : C:\Users\PC1\OneDrive\A4\Data\name-ttl.csv

In [7]:
file_name = "price-hilo.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [8]:
print(f"Output file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

Output file : C:\Users\PC1\OneDrive\A4\Data\price-hilo.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\price-hilo.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\price-hilo.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\price-hilo.csv

In [9]:
def cvt_str_to_flt(input_str):
    # Check for the special pattern and return 0
    if input_str == '(-)':
        return 0
    
    # Remove parentheses and percent sign
    cleaned_str = input_str.replace('(', '').replace(')', '').replace('%', '')

    # Convert to float
    try:
        return float(cleaned_str)
    except ValueError:
        # Handle the case where the conversion fails
        return None

In [10]:
def get_stock_data(in_df):

    in_df.columns = ['name']
    
    output_columns = ['name', 'price', 'today_low', 'today_high', 'year_low', 'year_high', 'percent', 'updated_at']
    # Initialize an empty DataFrame with specified columns
    out_df = pd.DataFrame(columns=output_columns)
    
    for index, row in in_df.iterrows():
        name = str(row['name']).upper()
        response = request.urlopen(url + name + '/price')
        html_page = BeautifulSoup(response, 'html.parser')
        
  #      price = html_page.find('div', class_='value text-white mb-0 me-2 lh-1 stock-info').text.strip()        
  #      if (price == '-'):
  #          price = '0.00'        

        price_div = html_page.find('div', class_='value text-white mb-0 me-2 lh-1 stock-info')
        if price_div:
            price = price_div.text.strip()
        else:
            print(f"Price div not found for {name}")
            price = '0.00'     
            
        # Try to find the <h3> tag with the class 'theme-success'
        h3_tag = html_page.find('h3', class_='theme-success')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)
                
        # Try to find the <h3> tag with the class 'theme-danger'
        h3_tag = html_page.find('h3', class_='theme-danger')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)    
                
        # Try to find the <h3> tag with the class 'theme-danger'
        h3_tag = html_page.find('h3', class_='theme-normal')
        if h3_tag:
        # Find all <span> tags within the found <h3> tag
            span_tags = h3_tag.find_all('span')
    
            if len(span_tags) > 1:
                # Extract the text from the second <span> tag
                percent_span = span_tags[1].text
                # print(percent_span)   
                
        percent = cvt_str_to_flt(percent_span)
                
        values_low = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder me-auto lh-1')
        today_low = values_low[0].text
        if (today_low == '-'):
            today_low = '0.00'
        
        values_high = html_page.find_all('span', class_='title-font-family fs-16px fw-bolder lh-1')
        today_high = values_high[0].text
        if (today_high == '-'):
            today_high = '0.00'         
        
        year_low = values_low[1].text        
        year_high = values_high[1].text     
        
        # Find the div with the specific class, then find the span within it
        div = html_page.find('div', class_='price-detail-date d-flex align-items-center text-nowrap fs-12px')
        if div:
            span = div.find('span')
            if span:
                text = span.get_text()
#                 print(text)
            else:
                print("Span not found")
        else:
            print("Div not found")
            
        # Extract the date part from the string
        # Assuming the date is always in the format 'dd Mon yyyy'
        date_str = ' '.join(text.split()[2:5])

        # Parse the date string into a datetime object
        date_obj = datetime.strptime(date_str, '%d %b %Y')

        # Format the datetime object to 'yyyy-mm-dd'
        updated_at = date_obj.strftime('%Y-%m-%d')

#         print(updated_at)
        
        # Append row to the DataFrame and print the row
        out_df.loc[len(out_df)] = [name, price, today_low, today_high, year_low, year_high, percent, updated_at]
#       print(out_df.iloc[-1].to_string(header=False, index=False)) 
        print(','.join(map(str, out_df.iloc[-1])))
        sleep(2)
        
    return out_df  # return the final dataframe with all values populated

In [11]:
start_time = strftime("%I:%M %p")
print('Start at: ', start_time)

Start at:  08:27 PM

In [12]:
df = pd.read_csv(input_file, header=None)
out_df = get_stock_data(df)

ACE,1.27,1.27,1.29,1.24,1.38,0.0,2026-03-05
ADVANC,360.00,352.00,367.00,259.00,410.00,0.0,2026-03-05
AEONTS,90.00,88.75,92.00,87.00,122.50,0.28,2026-03-05
AH,14.30,14.00,14.80,10.00,15.80,0.7,2026-03-05
AIE,1.00,0.97,1.02,0.90,1.64,3.09,2026-03-05
AIMIRT,10.90,10.80,11.00,9.20,11.40,-1.8,2026-03-05
AIT,4.88,4.82,4.90,4.08,5.30,0.83,2026-03-05
AJ,1.58,1.57,1.63,1.51,4.06,0.0,2026-03-05
AMATA,18.50,18.10,18.90,11.20,22.90,1.65,2026-03-05
ANAN,0.38,0.37,0.39,0.36,0.79,0.0,2026-03-05
AOT,51.00,49.50,51.00,26.75,59.00,5.15,2026-03-05
AP,8.60,8.15,8.65,5.60,9.70,4.88,2026-03-05
ASIAN,7.10,7.00,7.15,6.50,8.35,-2.07,2026-03-05
ASK,8.85,8.55,9.00,6.20,10.30,1.72,2026-03-05
ASP,2.14,2.04,2.18,1.81,2.80,0.0,2026-03-05
ASW,7.75,7.65,8.00,4.90,8.20,0.0,2026-03-05
AWC,2.08,2.02,2.16,1.55,3.02,0.0,2026-03-05
BA,14.50,14.10,15.40,10.60,21.60,0.0,2026-03-05
BAM,7.05,6.90,7.20,5.70,8.60,0.71,2026-03-05
BANPU,6.20,5.85,6.35,4.00,6.20,8.77,2026-03-05
BAY,25.25,24.50,25.25,20.70,28.00,2.23,2026-03-05
BBL,168.00,167.50,171.50,131.00,181.00,-0.3,2026-03-05
BCH,9.75,9.65,10.00,9.20,16.10,-0.51,2026-03-05
BCP,36.00,34.00,36.00,24.20,41.00,3.6,2026-03-05
BCPG,7.10,6.90,7.30,5.25,9.60,0.0,2026-03-05
BCT,46.25,45.50,46.25,42.00,68.75,6.32,2026-03-05
BDMS,19.40,19.10,20.00,17.40,24.90,-0.51,2026-03-05
BE8,5.50,5.25,5.75,4.10,12.50,5.77,2026-03-05
BEAUTY,0.33,0.31,0.33,0.19,0.68,6.45,2026-03-05
BEC,1.95,1.92,1.97,1.79,4.04,2.63,2026-03-05
BEM,5.70,5.45,5.70,4.56,6.30,2.7,2026-03-05
BGC,4.44,4.20,4.46,3.30,5.95,0.91,2026-03-05
BGRIM,11.70,11.40,12.50,8.90,16.60,1.74,2026-03-05
BH,176.50,172.50,183.00,130.00,214.00,1.73,2026-03-05
BJC,13.90,13.40,14.20,13.10,24.60,0.72,2026-03-05
BKIH,315.00,312.00,315.00,271.00,315.00,0.32,2026-03-05
BLA,19.70,19.40,20.00,14.00,24.00,0.0,2026-03-05
BLAND,0.43,0.42,0.44,0.38,0.54,0.0,2026-03-05
BPP,12.50,11.90,12.50,6.20,13.00,6.84,2026-03-05
BTS,2.10,2.04,2.16,2.00,6.15,0.96,2026-03-05
BTSGIF,2.52,2.50,2.54,2.46,2.86,0.8,2026-03-05
CBG,37.00,36.25,39.75,36.75,66.50,-3.9,2026-03-05
CENTEL,35.50,34.00,35.75,19.40,40.50,7.58,2026-03-05
CHG,1.50,1.46,1.53,1.39,2.14,2.04,2026-03-05
CK,16.50,15.80,16.50,10.20,18.40,6.45,2026-03-05
CKP,2.30,2.28,2.36,2.10,3.04,0.88,2026-03-05
COM7,22.90,22.40,23.00,16.70,28.00,4.09,2026-03-05
CPALL,49.00,48.00,50.25,40.50,54.50,1.55,2026-03-05
CPF,19.00,18.80,19.60,18.60,26.50,-1.55,2026-03-05
CPN,65.00,63.25,66.75,41.00,70.50,1.17,2026-03-05
CPNCG,6.20,6.10,6.25,5.75,6.50,1.64,2026-03-05
CPNREIT,11.50,11.50,11.70,10.20,12.50,0.0,2026-03-05
CRC,18.50,17.80,19.00,15.80,32.00,1.09,2026-03-05
DCC,1.19,1.15,1.19,1.13,1.65,2.59,2026-03-05
DCON,0.23,0.22,0.24,0.23,0.30,-4.17,2026-03-05
DELTA,258.00,248.00,265.00,51.25,292.00,7.95,2026-03-05
DIF,9.35,9.35,9.40,7.35,9.60,0.0,2026-03-05
DOHOME,3.40,3.26,3.44,2.17,6.63,0.0,2026-03-05
DRT,4.78,4.76,4.86,4.42,7.35,0.84,2026-03-05
EA,2.66,2.56,2.72,1.73,3.88,6.4,2026-03-05
EASTW,2.44,2.40,2.58,1.57,3.30,0.83,2026-03-05
EGATIF,6.10,6.05,6.10,5.75,6.30,0.0,2026-03-05
EGCO,113.50,111.00,114.00,85.00,143.00,2.25,2026-03-05
EPG,3.34,3.26,3.46,2.12,4.10,0.0,2026-03-05
FORTH,7.50,7.05,7.50,5.45,10.30,7.14,2026-03-05
FPT,6.30,6.10,6.40,5.50,8.75,5.0,2026-03-05
FSMART,6.50,6.35,6.75,5.35,9.85,3.17,2026-03-05
FTREIT,11.00,10.80,11.10,8.60,12.30,1.85,2026-03-05
GC,4.30,4.26,4.40,3.40,5.05,0.94,2026-03-05
GFPT,9.05,8.85,9.05,8.00,11.00,2.26,2026-03-05
GGC,2.80,2.80,2.88,2.76,5.45,0.72,2026-03-05
GLOBAL,6.85,6.65,7.15,4.01,8.44,-2.84,2026-03-05
GPSC,34.25,32.75,36.75,22.40,45.00,0.0,2026-03-05
GRAMMY,3.84,3.80,4.10,3.90,6.40,-4.0,2026-03-05
GUNKUL,2.20,2.14,2.32,1.31,2.58,0.92,2026-03-05
GVREIT,6.40,6.35,6.50,6.15,6.95,0.79,2026-03-05
HANA,19.10,17.50,19.10,14.00,26.75,10.4,2026-03-05
HFT,4.14,4.10,4.18,3.32,4.48,-0.48,2026-03-05
HMPRO,6.65,6.35,6.80,5.70,9.20,0.76,2026-03-05
HTC,15.40,15.40,15.60,14.50,17.10,1.32,2026-03-05
ICHI,13.90,13.80,14.20,9.40,15.20,0.0,2026-03-05
III,3.98,3.76,3.98,3.72,5.25,4.74,2026-03-05
ILM,13.60,13.40,14.00,11.50,16.20,0.0,2026-03-05
IMH,2.96,2.86,2.96,2.84,4.48,4.23,2026-03-05
IMPACT,10.50,10.50,10.80,9.25,11.40,-2.78,2026-03-05
INOX,0.39,0.38,0.39,0.34,0.50,2.63,2026-03-05
IP,3.92,3.88,4.00,2.40,4.70,1.03,2026-03-05
IRPC,1.18,1.15,1.22,0.70,1.44,0.0,2026-03-05
IVL,19.20,18.00,19.90,14.60,24.50,2.13,2026-03-05
3BBIF,6.50,6.45,6.55,5.25,6.85,1.56,2026-03-05
JMART,6.55,6.15,6.60,5.20,10.90,3.97,2026-03-05
JMT,8.85,8.55,9.30,7.35,14.90,-0.56,2026-03-05
KBANK,190.00,188.50,194.00,145.00,208.00,0.0,2026-03-05
KCE,17.70,16.70,17.70,13.70,28.25,7.27,2026-03-05
KGI,4.32,4.26,4.34,3.40,4.54,2.37,2026-03-05
KKP,73.50,72.25,74.25,43.50,78.00,1.38,2026-03-05
KSL,1.24,1.20,1.24,1.19,1.61,0.0,2026-03-05
KTB,33.75,33.00,33.75,19.70,35.50,3.05,2026-03-05
KTC,29.75,29.25,30.75,21.80,50.75,0.85,2026-03-05
KYE,285.00,283.00,287.00,272.00,324.00,1.06,2026-03-05
LALIN,4.72,4.72,4.76,4.68,5.45,0.0,2026-03-05
LANNA,15.00,14.80,15.20,14.10,17.10,2.04,2026-03-05
LH,3.78,3.66,3.82,3.18,4.74,1.07,2026-03-05
LHFG,0.98,0.97,0.99,0.72,1.04,2.08,2026-03-05
LHK,3.40,3.34,3.42,3.02,3.70,1.19,2026-03-05
LIT,0.66,0.64,0.70,0.39,1.01,-1.49,2026-03-05
LPH,3.74,3.72,3.76,3.20,4.44,0.54,2026-03-05
LPN,1.58,1.54,1.58,1.46,2.22,3.27,2026-03-05
M,19.10,18.80,19.70,13.80,35.25,0.53,2026-03-05
MAJOR,7.85,7.75,8.00,6.25,11.90,0.0,2026-03-05
MBAX,1.69,1.61,1.70,1.17,2.20,1.81,2026-03-05
MC,11.20,10.90,11.30,9.15,12.50,1.82,2026-03-05
MCS,9.30,9.15,9.30,7.10,9.75,1.64,2026-03-05
MEGA,35.00,33.50,35.00,24.30,40.00,4.48,2026-03-05
MINT,21.70,20.80,22.20,19.60,29.50,2.84,2026-03-05
MST,6.85,6.80,6.90,5.50,8.55,0.74,2026-03-05
MTC,32.50,31.50,33.50,27.00,48.25,0.78,2026-03-05
NER,4.66,4.58,4.68,3.88,5.40,1.75,2026-03-05
NOBLE,2.24,2.24,2.34,1.60,2.72,-0.88,2026-03-05
ONEE,2.72,2.64,2.74,1.94,3.06,4.62,2026-03-05
OR,11.40,11.10,12.10,10.10,15.60,-3.39,2026-03-05
ORI,1.83,1.76,1.85,1.50,3.12,3.98,2026-03-05
OSP,14.80,14.50,15.70,12.90,19.50,-1.33,2026-03-05
PAP,1.94,1.94,1.95,1.31,2.18,2.65,2026-03-05
PCSGH,3.06,2.98,3.06,2.46,3.78,2.68,2026-03-05
PDG,3.04,3.00,3.04,2.46,3.12,2.01,2026-03-05
PLANB,4.44,4.26,4.46,3.00,6.40,3.74,2026-03-05
POPF,6.85,6.80,6.85,5.40,7.00,0.0,2026-03-05
PREB,3.88,3.72,3.94,3.30,4.10,1.57,2026-03-05
PRM,7.60,7.40,7.80,5.10,8.25,0.66,2026-03-05
PSH,3.56,3.54,3.70,3.50,5.65,0.56,2026-03-05
PSL,7.90,7.70,8.00,4.96,8.45,0.0,2026-03-05
PTG,8.60,8.40,8.95,5.45,10.20,-1.15,2026-03-05
PTL,7.85,7.70,8.00,7.50,14.50,0.64,2026-03-05
PTT,34.00,33.25,34.75,27.00,38.00,-3.55,2026-03-05
PTTEP,140.00,137.50,141.00,93.00,146.50,1.82,2026-03-05
PTTGC,24.70,23.50,25.25,14.20,29.25,0.0,2026-03-05
QH,1.39,1.35,1.39,1.15,1.63,3.73,2026-03-05
RATCH,29.75,28.75,30.00,22.50,32.50,2.59,2026-03-05
RBF,3.62,3.54,3.66,2.90,5.30,2.84,2026-03-05
RCL,31.50,30.75,31.50,18.20,33.75,1.61,2026-03-05
RJH,13.50,13.20,13.60,11.10,16.20,3.05,2026-03-05
ROJNA,5.00,4.96,5.05,4.14,5.95,0.81,2026-03-05
RS,0.15,0.14,0.15,0.13,0.90,0.0,2026-03-05
S11,4.06,4.06,4.08,2.40,4.24,-0.49,2026-03-05
SAPPE,30.50,29.50,31.25,27.50,45.50,1.67,2026-03-05
SAT,14.60,14.50,14.90,9.95,16.70,-8.18,2026-03-05
SAWAD,25.50,24.80,26.25,14.80,32.05,2.82,2026-03-05
SC,1.94,1.88,1.95,1.40,2.62,4.3,2026-03-05
SCB,145.00,143.00,146.00,111.00,149.50,1.75,2026-03-05
SCC,187.50,182.50,198.00,128.00,231.00,-1.83,2026-03-05
SCCC,140.50,139.50,141.00,138.50,166.50,-5.07,2026-03-05
SCGP,17.80,17.50,18.10,10.70,21.70,2.3,2026-03-05
SENA,1.82,1.78,1.85,1.54,2.18,1.11,2026-03-05
SGP,7.65,7.50,7.65,5.00,8.05,0.66,2026-03-05
SINGER,5.20,5.05,5.45,3.92,8.15,2.97,2026-03-05
SIRI,1.48,1.46,1.49,1.11,1.71,3.5,2026-03-05
SIS,22.10,21.80,22.80,17.60,25.00,0.0,2026-03-05
SJWD,7.90,7.75,8.00,5.75,10.80,1.94,2026-03-05
SKN,6.65,6.65,7.00,5.15,7.15,-1.48,2026-03-05
SKR,6.75,6.60,6.85,6.20,8.30,0.0,2026-03-05
SMPC,9.15,9.05,9.35,7.80,9.45,1.67,2026-03-05
SNC,5.70,5.60,5.75,5.10,7.35,3.64,2026-03-05
SPALI,17.80,16.70,17.80,13.20,19.00,4.09,2026-03-05
SPC,57.00,56.50,57.00,53.00,59.75,0.88,2026-03-05
SPCG,9.10,8.95,9.10,6.60,10.30,1.11,2026-03-05
SPRC,7.15,6.70,7.15,4.26,7.90,0.0,2026-03-05
SPRIME,3.44,3.40,3.44,3.00,4.20,-0.58,2026-03-05
SSP,3.26,3.24,3.30,3.00,5.60,2.52,2026-03-05
STA,13.10,12.50,13.10,10.30,15.80,5.65,2026-03-05
STANLY,197.00,195.50,198.00,176.00,225.00,1.29,2026-03-05
STGT,9.00,8.35,9.00,5.10,10.20,8.43,2026-03-05
SUPER,0.10,0.09,0.11,0.09,0.22,0.0,2026-03-05
SUPEREIF,5.60,5.55,5.70,4.72,6.35,0.0,2026-03-05
SVI,7.40,7.35,7.40,5.55,8.35,1.37,2026-03-05
SYNEX,9.10,8.90,9.45,9.15,12.80,-0.55,2026-03-05
TASCO,12.80,12.60,12.90,12.40,15.90,2.4,2026-03-05
TCAP,56.75,56.25,57.75,44.25,63.00,0.89,2026-03-05
TFFIF,6.50,6.50,6.55,5.25,6.95,0.78,2026-03-05
TFG,6.00,5.65,6.30,3.92,6.60,-1.64,2026-03-05
THANI,1.70,1.67,1.74,1.39,2.06,0.0,2026-03-05
THG,8.40,8.25,8.50,6.15,10.32,1.2,2026-03-05
TIPH,20.90,20.40,20.90,16.70,23.30,2.45,2026-03-05
TIPCO,7.10,7.05,7.25,6.90,9.90,0.0,2026-03-05
TISCO,112.50,112.00,113.00,95.00,116.50,0.45,2026-03-05
TK,4.18,4.06,4.22,3.28,4.90,0.97,2026-03-05
TKN,4.10,3.98,4.14,3.86,8.75,1.49,2026-03-05
TKS,6.40,6.35,6.50,4.90,7.10,1.59,2026-03-05
TMT,2.80,2.72,2.86,2.60,3.54,0.72,2026-03-05
TMW,57.25,57.00,60.00,47.00,62.50,-1.72,2026-03-05
TOA,14.40,14.10,15.00,9.35,16.40,0.0,2026-03-05
TOP,49.75,48.00,50.00,21.00,56.75,2.05,2026-03-05
TPIPL,0.73,0.72,0.75,0.65,1.06,1.39,2026-03-05
TPIPP,1.85,1.84,1.87,1.66,2.50,0.54,2026-03-05
TQM,12.90,12.80,13.20,10.60,16.60,1.57,2026-03-05
TRUE,13.60,13.10,14.00,10.10,14.90,2.26,2026-03-05
TSE,0.39,0.38,0.40,0.29,0.68,5.41,2026-03-05
TSTH,0.71,0.70,0.72,0.47,0.93,0.0,2026-03-05
TTA,4.88,4.80,5.00,3.22,5.55,-1.21,2026-03-05
TTB,2.22,2.18,2.26,1.74,2.38,0.91,2026-03-05
TTLPF,9.65,9.60,9.70,8.80,12.30,0.52,2026-03-05
TTW,9.40,9.35,9.45,8.45,9.50,1.08,2026-03-05
TU,10.80,10.60,11.40,8.60,14.10,-1.82,2026-03-05
TVO,24.10,23.70,24.30,19.70,26.00,1.26,2026-03-05
TYCN,1.72,1.66,1.72,1.54,1.88,-0.58,2026-03-05
UTP,7.55,7.55,7.75,7.20,8.30,-1.31,2026-03-05
VGI,1.02,0.96,1.02,0.77,3.38,6.25,2026-03-05
VIBHA,1.41,1.38,1.41,1.32,1.85,1.44,2026-03-05
VNG,1.89,1.86,1.97,1.64,2.72,0.0,2026-03-05
WHA,4.04,3.98,4.16,2.26,4.60,0.0,2026-03-05
WHAIR,6.60,6.50,6.60,4.12,7.00,-0.75,2026-03-05
WHART,10.30,10.20,10.50,8.55,11.20,-1.9,2026-03-05
WHAUP,4.42,4.26,4.58,2.76,5.25,2.79,2026-03-05
WICE,2.54,2.48,2.54,2.20,3.94,3.25,2026-03-05
WORK,3.66,3.56,3.68,3.48,5.85,2.23,2026-03-05

In [13]:
end_time = strftime("%I:%M %p")
print('End at: ', end_time)

End at:  08:36 PM

In [14]:
out_df.query('price == "-"')

Empty DataFrame
Columns: [name, price, today_low, today_high, year_low, year_high, percent, updated_at]
Index: []

In [15]:
out_df.shape

(215, 8)

In [16]:
out_df = out_df[out_df['name'] != 'BCT']

In [17]:
out_df = out_df[out_df['name'] != 'LPF']

In [18]:
out_df = out_df[out_df['name'] != 'TYCN']

In [19]:
out_df = out_df[out_df['name'] != 'GRAMMY']

In [20]:
out_df = out_df[out_df['name'] != 'MST']

In [21]:
out_df = out_df[out_df['name'] != 'SPC']

In [22]:
out_df = out_df[out_df['name'] != 'SPRIME']

In [23]:
out_df = out_df[out_df['name'] != 'FPT']

In [24]:
out_df = out_df[out_df['name'] != 'GGC']

In [25]:
out_df = out_df[out_df['name'] != 'SKN']

In [26]:
out_df = out_df[out_df['name'] != 'KYE']

In [27]:
out_df = out_df[out_df['name'] != 'PDG']

In [28]:
out_df = out_df[out_df['name'] != 'PREB']

In [29]:
out_df = out_df[out_df['name'] != 'MBAX']

In [30]:
out_df = out_df[out_df['name'] != 'TYCN']

In [31]:
out_df.shape

(202, 8)

In [32]:
out_df['price'] = out_df['price'].astype('float')
out_df['today_low'] = out_df['today_low'].astype('float')
out_df['today_high'] = out_df['today_high'].astype('float')
out_df['year_low'] = out_df['year_low'].astype('float')
out_df['year_high'] = out_df['year_high'].astype('float')
out_df['percent'] = out_df['percent'].astype('float')

In [33]:
sorted_out_df = out_df.sort_values('percent')

In [34]:
sorted_out_df.query('today_low < year_low')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
54,DCON,0.23,0.22,0.24,0.23,0.3,-4.17,2026-03-05
41,CBG,37.00,36.25,39.75,36.75,66.5,-3.90,2026-03-05
175,SYNEX,9.10,8.90,9.45,9.15,12.8,-0.55,2026-03-05

In [35]:
sorted_out_df.query('today_high > year_high')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
19,BANPU,6.2,5.85,6.35,4.0,6.2,8.77,2026-03-05

In [36]:
out_df.query('today_high > year_high')

,name,price,today_low,today_high,year_low,year_high,percent,updated_at
19,BANPU,6.2,5.85,6.35,4.0,6.2,8.77,2026-03-05

In [37]:
file_name = "Price-Hilo.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [38]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A4\Data\Price-Hilo.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Hilo.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Hilo.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Hilo.csv

In [39]:
out_df.to_csv(output_file, index=False)  
out_df.to_csv(god_file, index=False) 
out_df.to_csv(icd_file, index=False)  
out_df.to_csv(osd_file, index=False)

In [40]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-03-05 20:36:11