##### SQLite port_lite database: stocks table
##### PostgreSQL portpg database: stocks table
##### MySQL stock database: setindex, price, buy tables
##### Output files: 5-day-average, extremes

In [2]:
import calendar
import os
import pandas as pd
from datetime import date, timedelta
from sqlalchemy import create_engine, text
from pandas.tseries.offsets import BDay

engine = create_engine("mysql+pymysql://root:@localhost:3306/stock")
const = engine.connect()

pd.options.display.float_format = '{:.2f}'.format

today = date.today()
print(today)

2026-03-06

In [3]:
sql = """SELECT * FROM setindex ORDER BY date DESC LIMIT 1"""
df_tmp1 = pd.read_sql(sql, const)
df_tmp1

         date  setindex
0  2026-02-27   1528.26

In [4]:
sql = """SELECT * FROM setindex WHERE year(date) = 2026 ORDER BY date ASC LIMIT 1"""
df_tmp2 = pd.read_sql(sql, const)
df_tmp2

         date  setindex
0  2026-01-05   1280.05

In [5]:
diff = (df_tmp1.iloc[0] - df_tmp2.iloc[0])
print(diff)

date        53 days, 0:00:00
setindex              248.21
Name: 0, dtype: object

In [25]:
sql = '''
SELECT period, name, volbuy AS shares
FROM buy
WHERE active = 1
ORDER BY period, name'''
df_buy = pd.read_sql(sql, const)
df_buy['shares'] = buy['shares'].astype('int64')
df_buy

   period     name  shares
0       1    PTTGC    6000
1       1      SCC     600
2       1   SINGER    6000
3       1      STA   10000
4       2    3BBIF  120000
5       2  CPNREIT   55000
6       2      DIF   45000
7       2   GVREIT   69000
8       2      MCS   75000
9       2      NER   27000
10      2      PTT    7500
11      2     SENA  105000
12      2    TFFIF   20000
13      2    WHAIR   50000
14      2    WHART   20000
15      3   ADVANC     100
16      3       AH    1200
17      3      AWC    9000
18      3      BCH    4000
19      3      CPF   10000
20      3      PTG    3600
21      3      RCL   27000
22      3    SYNEX   17500
23      3      TOA    1000
24      3      TVO    4000
25      4   AIMIRT   17500
26      4      IVL    7200
27      4    JMART    6800
28      4      JMT    7000
29      4      ORI   50000

In [19]:
sql = """SELECT * FROM price LIMIT 1"""
df_price = pd.read_sql(sql, const)
df_price.dtypes

name      object
date      object
price    float64
maxp     float64
minp     float64
qty        int64
opnp     float64
dtype: object