### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [75]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()
engine = create_engine("sqlite:///c:\\ruby\\portlt\\db\\development.sqlite3")
conlt = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
print(today)

2026-05-22

In [77]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-05-22 09:46:09

### Restart & Run All Cells

In [80]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "OneDrive", "Downloads", "Datasets")
print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
#icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

Datasets path: C:\Users\User\OneDrive\Downloads\Datasets

In [82]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\User
Current path: C:\Users\User\OneDrive\A4\Daily
Base path: C:\Users\User\OneDrive\A4
Datasets path : C:\Users\User\OneDrive\Downloads\Datasets
Data path : C:\Users\User\OneDrive\A4\Data
Google Drive path : C:\Users\User\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\User\iCloudDrive\Data
Obsidian path : C:\Users\User\OneDrive\Documents\obsidian-git-sync\Data

In [84]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [86]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [89]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].head()

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0    AIMCG  1.36   0.01    0.74  1.35  1.37  1.35        54200           73.42
1   AIMIRT 11.50   0.20    1.77 11.40 11.50 11.40        74587          856.07
2     ALLY  4.72   0.02    0.43  4.72  4.72  4.70       642483         3020.79
3   AMATAR  7.25  -0.05   -0.68  7.20  7.30  7.20        52600          380.76
4  AXTRART 12.80   0.10    0.79 12.70 12.80 12.70      1438679        18281.14

In [91]:
df_PFREIT.query('Symbol == ("CPNREIT","GVREIT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,12.50,-,-,12.50,12.60,12.50,-,0,3907560,48895.39,667500,12.50,12.60,344800
17,GVREIT,-,6.95,-,-,6.95,6.95,6.90,-,0,627207,4356.09,887600,6.90,6.95,399200
54,WHAIR,-,7.55,0.10,1.34,7.45,7.55,7.45,-,0,682610,5130.81,123700,7.50,7.55,244600
55,WHART,-,10.40,-,-,10.30,10.50,10.30,-,0,1063390,11048.44,1817400,10.30,10.40,50000

### ------------ End of Individual Category

In [94]:
df = pd.concat([df_PFREIT])
df.shape

(52, 16)

In [96]:
df.Symbol.nunique()

52

In [98]:
df.query('Symbol == "AIMIRT"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,AIMIRT,-,11.50,0.20,1.77,11.40,11.50,11.40,-,0,74587,856.07,34800,11.40,11.50,22600

In [100]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(52, 16)

In [102]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [104]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(52, 9)

In [108]:
# Clean Symbol column (remove <XD>)
df['Symbol'] = df['Symbol'].str.replace(r'\s*<.*?>', '', regex=True)

# Then proceed with numeric conversion
numeric_cols = df.columns.drop('Symbol')

# Option A: Use inplace=False and then infer_objects
df[numeric_cols] = (
    df[numeric_cols].replace('-', 0)
    .infer_objects(copy=False)  # Explicitly handle downcasting
    .apply(pd.to_numeric, errors='coerce')
)

df[cols].shape

(52, 9)

In [34]:
# If run after actual work day
#today = today - timedelta(days=2)
#today

In [110]:
df.insert(1, 'Date', today)

In [112]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AIMCG,2026-05-22,1.36,0.01,0.74,1.35,1.37,1.35,54200,73.42
1,AIMIRT,2026-05-22,11.50,0.20,1.77,11.40,11.50,11.40,74587,856.07
2,ALLY,2026-05-22,4.72,0.02,0.43,4.72,4.72,4.70,642483,3020.79
3,AMATAR,2026-05-22,7.25,-0.05,-0.68,7.20,7.30,7.20,52600,380.76
4,AXTRART,2026-05-22,12.80,0.10,0.79,12.70,12.80,12.70,1438679,18281.14
5,B-WORK,2026-05-22,6.15,0.00,0.00,6.10,6.30,6.10,385102,2371.13
6,BAREIT,2026-05-22,10.50,0.00,0.00,10.50,10.60,10.40,768890,8027.18
7,BOFFICE,2026-05-22,5.35,0.00,0.00,5.35,5.40,5.35,810813,4345.04
8,CPNCG,2026-05-22,6.05,0.00,0.00,6.05,6.05,6.00,224028,1353.72
9,CPNREIT,2026-05-22,12.50,0.00,0.00,12.50,12.60,12.50,3907560,48895.39
10,CPTREIT,2026-05-22,6.25,0.00,0.00,6.25,6.25,6.20,49800,309.38
11,CTARAF,2026-05-22,4.66,-0.02,-0.43,4.66,4.66,4.66,10700,49.86
12,DREIT,2026-05-22,4.74,0.00,0.00,4.76,4.78,4.74,51401,245.09
13,FTREIT,2026-05-22,11.30,0.10,0.89,11.20,11.40,11.20,1604855,18098.86
14,FUTURERT,2026-05-22,9.05,0.00,0.00,9.05,9.05,9.00,264935,2387.14
15,GAHREIT,2026-05-22,4.14,-0.02,-0.48,4.16,4.16,4.14,73734,306.11
16,GROREIT,2026-05-22,7.90,-0.05,-0.63,7.95,8.00,7.85,70200,555.19
17,GVREIT,2026-05-22,6.95,0.00,0.00,6.95,6.95,6.90,627207,4356.09
18,HPF,2026-05-22,5.85,0.00,0.00,5.85,5.85,5.85,46210,270.33
19,HYDROGEN,2026-05-22,8.25,-0.05,-0.60,8.25,8.25,8.25,400,3.30
20,IMPACT,2026-05-22,11.70,0.30,2.63,11.40,11.70,11.30,468291,5433.69
21,INETREIT,2026-05-22,12.50,0.00,0.00,12.50,12.50,12.40,1137820,14212.97
22,ISSARA,2026-05-22,6.65,0.05,0.76,6.60,6.65,6.60,3200,21.22
24,KTBSTMR,2026-05-22,5.85,0.05,0.86,5.80,5.85,5.80,142894,829.17
25,LHHOTEL,2026-05-22,13.30,0.10,0.76,13.20,13.30,13.20,1418202,18806.88
26,LHRREIT,2026-05-22,4.40,0.00,0.00,4.50,4.50,4.40,23602,105.12
27,LHSC,2026-05-22,14.40,-0.10,-0.69,14.50,14.50,14.40,512945,7433.83
28,LUXF,2026-05-22,9.05,0.05,0.56,9.05,9.05,9.05,100,0.91
29,M-PAT,2026-05-22,0.00,0.00,0.00,0.00,0.00,0.00,2,0.00
30,M-STOR,2026-05-22,0.00,0.00,0.00,0.00,0.00,0.00,1,0.01
31,MII,2026-05-22,5.45,0.05,0.93,5.40,5.45,5.40,10201,55.58
32,MIPF,2026-05-22,0.00,0.00,0.00,0.00,0.00,0.00,1,0.01
33,MJLF,2026-05-22,5.30,0.05,0.95,5.25,5.30,5.20,49652,260.84
34,MNIT,2026-05-22,1.90,0.00,0.00,1.91,1.91,1.90,6000,11.45
36,MNRF,2026-05-22,2.04,0.00,0.00,2.06,2.06,2.02,97801,198.76
37,POPF,2026-05-22,7.65,0.05,0.66,7.55,7.70,7.55,137979,1055.36
38,PROSPECT,2026-05-22,9.05,0.10,1.12,8.95,9.05,8.90,3541092,31783.70
39,QHBREIT,2026-05-22,3.76,0.02,0.53,3.74,3.76,3.70,523816,1954.76
40,QHHRREIT,2026-05-22,7.80,0.00,0.00,7.75,7.80,7.75,69096,537.27
41,QHOP,2026-05-22,0.00,0.00,0.00,0.00,0.00,0.00,1,0.00
42,SIRIPRT,2026-05-22,7.20,0.10,1.41,7.20,7.20,7.20,1100,7.92
43,SPRIME,2026-05-22,3.66,-0.08,-2.14,3.66,3.66,3.64,173602,633.99
44,SRIPANWA,2026-05-22,5.05,0.00,0.00,5.05,5.05,5.00,29800,149.89
45,SSPF,2026-05-22,3.20,-0.10,-3.03,3.20,3.20,3.20,100,0.32
46,SSTRT,2026-05-22,4.36,0.00,0.00,4.38,4.38,4.34,209110,907.76
47,TIF1,2026-05-22,7.80,0.05,0.65,7.75,7.80,7.70,37400,289.89
50,TPRIME,2026-05-22,0.00,0.00,0.00,0.00,0.00,0.00,2,0.02
51,TTLPF,2026-05-22,9.90,-0.05,-0.50,9.90,9.90,9.85,249197,2466.45
52,TU-PF,2026-05-22,1.19,-0.18,-13.14,1.28,1.28,1.00,8999,10.09
53,WHABT,2026-05-22,5.80,0.00,0.00,5.75,5.80,5.75,447004,2574.65
54,WHAIR,2026-05-22,7.55,0.10,1.34,7.45,7.55,7.45,682610,5130.81
55,WHART,2026-05-22,10.40,0.00,0.00,10.30,10.50,10.30,1063390,11048.44

In [114]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\User\OneDrive\A4\Data\name-ttl.csv

In [116]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(190, 1)

In [118]:
df_out = df[colt]
df_out.shape

(52, 10)

In [140]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(9, 10)

In [142]:
df_merge.columns = df_merge.columns.str.lower()
df_merge

,symbol,date,last,change,%change,open,high,low,total-volume,total-value-(k)
0,AIMIRT,2026-05-22,11.50,0.20,1.77,11.40,11.50,11.40,74587,856.07
1,CPNCG,2026-05-22,6.05,0.00,0.00,6.05,6.05,6.00,224028,1353.72
2,CPNREIT,2026-05-22,12.50,0.00,0.00,12.50,12.60,12.50,3907560,48895.39
3,GVREIT,2026-05-22,6.95,0.00,0.00,6.95,6.95,6.90,627207,4356.09
4,IMPACT,2026-05-22,11.70,0.30,2.63,11.40,11.70,11.30,468291,5433.69
5,POPF,2026-05-22,7.65,0.05,0.66,7.55,7.70,7.55,137979,1055.36
6,TTLPF,2026-05-22,9.90,-0.05,-0.50,9.90,9.90,9.85,249197,2466.45
7,WHAIR,2026-05-22,7.55,0.10,1.34,7.45,7.55,7.45,682610,5130.81
8,WHART,2026-05-22,10.40,0.00,0.00,10.30,10.50,10.30,1063390,11048.44

In [124]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [126]:
stock_list = df_merge['name'].unique().tolist()
stock_list_str = ("','").join(stock_list)
print(stock_list_str)

AIMIRT','CPNCG','CPNREIT','GVREIT','IMPACT','POPF','TTLPF','WHAIR','WHART

In [128]:
select_date = '2026-04-01'

In [130]:
sql = f"""
SELECT *
FROM epss
WHERE name IN ('{stock_list_str}')
AND publish_date >= '2026-01-01'
ORDER BY name, year DESC, quarter DESC"""
df_tmp = pd.read_sql(sql, conlt)
df_tmp.columns

Index(['id', 'name', 'year', 'quarter', 'q_amt', 'y_amt', 'aq_amt', 'ay_amt',
       'q_eps', 'y_eps', 'aq_eps', 'ay_eps', 'ticker_id', 'publish_date'],
      dtype='object')

In [132]:
df_merge2 = pd.merge(df_merge, df_tmp, on = 'name', how='inner')
df_merge2.shape

(9, 23)

In [134]:
colp = 'name date price high low volume open q_amt y_amt aq_amt ay_amt'.split()

file_name = "Price-REIT.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [136]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\User\OneDrive\A4\Data\Price-REIT.csv
icd_file : C:\Users\User\iCloudDrive\Data\Price-REIT.csv
god_file : C:\Users\User\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-REIT.csv
osd_file : C:\Users\User\OneDrive\Documents\obsidian-git-sync\Data\Price-REIT.csv

In [138]:
df_merge2[colp]

,name,date,price,high,low,volume,open,q_amt,y_amt,aq_amt,ay_amt
0,AIMIRT,2026-05-22,11.50,11.50,11.40,74587,11.40,195932,342254,684130,948697
1,CPNCG,2026-05-22,6.05,6.05,6.00,224028,6.05,47692,96874,108134,342309
2,CPNREIT,2026-05-22,12.50,12.60,12.50,3907560,12.50,1484839,357438,3460976,1696069
3,GVREIT,2026-05-22,6.95,6.95,6.90,627207,6.95,170078,203852,170078,203852
4,IMPACT,2026-05-22,11.70,11.70,11.30,468291,11.40,394738,277552,949916,837143
5,POPF,2026-05-22,7.65,7.70,7.55,137979,7.55,89411,79653,400983,387072
6,TTLPF,2026-05-22,9.90,9.90,9.85,249197,9.90,38648,50872,279111,213524
7,WHAIR,2026-05-22,7.55,7.55,7.45,682610,7.45,-176793,-116575,413649,316443
8,WHART,2026-05-22,10.40,10.50,10.30,1063390,10.30,390358,204671,2349806,1920947

In [146]:
df_merge2[colp].to_csv(output_file, header=True, index=False)
df_merge2[colp].to_csv(god_file, header=True, index=False)
#df_merge2[colp].to_csv(icd_file, header=True, index=False)
df_merge2[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [149]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2026-05-22 09:55:40

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes